/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CompensatoryData service. Represents a row in the &quot;ax_CompensatoryData&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.ax.hrms.model.impl.CompensatoryDataModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.ax.hrms.model.impl.CompensatoryDataImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CompensatoryData
 * @generated
 */
@ProviderType
public interface CompensatoryDataModel
	extends BaseModel<CompensatoryData>, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a compensatory data model instance should use the {@link CompensatoryData} interface instead.
	 */

	/**
	 * Returns the primary key of this compensatory data.
	 *
	 * @return the primary key of this compensatory data
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this compensatory data.
	 *
	 * @param primaryKey the primary key of this compensatory data
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this compensatory data.
	 *
	 * @return the uuid of this compensatory data
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this compensatory data.
	 *
	 * @param uuid the uuid of this compensatory data
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the company ID of this compensatory data.
	 *
	 * @return the company ID of this compensatory data
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this compensatory data.
	 *
	 * @param companyId the company ID of this compensatory data
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the created by of this compensatory data.
	 *
	 * @return the created by of this compensatory data
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this compensatory data.
	 *
	 * @param createdBy the created by of this compensatory data
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified by of this compensatory data.
	 *
	 * @return the modified by of this compensatory data
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this compensatory data.
	 *
	 * @param modifiedBy the modified by of this compensatory data
	 */
	public void setModifiedBy(long modifiedBy);

	/**
	 * Returns the group ID of this compensatory data.
	 *
	 * @return the group ID of this compensatory data
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this compensatory data.
	 *
	 * @param groupId the group ID of this compensatory data
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the create date of this compensatory data.
	 *
	 * @return the create date of this compensatory data
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this compensatory data.
	 *
	 * @param createDate the create date of this compensatory data
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this compensatory data.
	 *
	 * @return the modified date of this compensatory data
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this compensatory data.
	 *
	 * @param modifiedDate the modified date of this compensatory data
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the compensatory data ID of this compensatory data.
	 *
	 * @return the compensatory data ID of this compensatory data
	 */
	public long getCompensatoryDataId();

	/**
	 * Sets the compensatory data ID of this compensatory data.
	 *
	 * @param compensatoryDataId the compensatory data ID of this compensatory data
	 */
	public void setCompensatoryDataId(long compensatoryDataId);

	/**
	 * Returns the employee ID of this compensatory data.
	 *
	 * @return the employee ID of this compensatory data
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this compensatory data.
	 *
	 * @param employeeId the employee ID of this compensatory data
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the date of compensation of this compensatory data.
	 *
	 * @return the date of compensation of this compensatory data
	 */
	public Date getDateOfCompensation();

	/**
	 * Sets the date of compensation of this compensatory data.
	 *
	 * @param dateOfCompensation the date of compensation of this compensatory data
	 */
	public void setDateOfCompensation(Date dateOfCompensation);

	/**
	 * Returns the requested hours of this compensatory data.
	 *
	 * @return the requested hours of this compensatory data
	 */
	public int getRequestedHours();

	/**
	 * Sets the requested hours of this compensatory data.
	 *
	 * @param requestedHours the requested hours of this compensatory data
	 */
	public void setRequestedHours(int requestedHours);

	/**
	 * Returns the approved hours of this compensatory data.
	 *
	 * @return the approved hours of this compensatory data
	 */
	public int getApprovedHours();

	/**
	 * Sets the approved hours of this compensatory data.
	 *
	 * @param approvedHours the approved hours of this compensatory data
	 */
	public void setApprovedHours(int approvedHours);

	/**
	 * Returns the manager ID of this compensatory data.
	 *
	 * @return the manager ID of this compensatory data
	 */
	public long getManagerId();

	/**
	 * Sets the manager ID of this compensatory data.
	 *
	 * @param managerId the manager ID of this compensatory data
	 */
	public void setManagerId(long managerId);

	/**
	 * Returns the leave compensatory status master ID of this compensatory data.
	 *
	 * @return the leave compensatory status master ID of this compensatory data
	 */
	public long getLeaveCompensatoryStatusMasterId();

	/**
	 * Sets the leave compensatory status master ID of this compensatory data.
	 *
	 * @param leaveCompensatoryStatusMasterId the leave compensatory status master ID of this compensatory data
	 */
	public void setLeaveCompensatoryStatusMasterId(
		long leaveCompensatoryStatusMasterId);

	/**
	 * Returns the description of this compensatory data.
	 *
	 * @return the description of this compensatory data
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this compensatory data.
	 *
	 * @param description the description of this compensatory data
	 */
	public void setDescription(String description);

	@Override
	public CompensatoryData cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}