/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the EmployeeUanEsic service. Represents a row in the &quot;ax_EmployeeUanEsic&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.ax.hrms.model.impl.EmployeeUanEsicModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.ax.hrms.model.impl.EmployeeUanEsicImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmployeeUanEsic
 * @generated
 */
@ProviderType
public interface EmployeeUanEsicModel
	extends BaseModel<EmployeeUanEsic>, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a employee uan esic model instance should use the {@link EmployeeUanEsic} interface instead.
	 */

	/**
	 * Returns the primary key of this employee uan esic.
	 *
	 * @return the primary key of this employee uan esic
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this employee uan esic.
	 *
	 * @param primaryKey the primary key of this employee uan esic
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this employee uan esic.
	 *
	 * @return the uuid of this employee uan esic
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this employee uan esic.
	 *
	 * @param uuid the uuid of this employee uan esic
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the company ID of this employee uan esic.
	 *
	 * @return the company ID of this employee uan esic
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this employee uan esic.
	 *
	 * @param companyId the company ID of this employee uan esic
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the created by of this employee uan esic.
	 *
	 * @return the created by of this employee uan esic
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this employee uan esic.
	 *
	 * @param createdBy the created by of this employee uan esic
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified by of this employee uan esic.
	 *
	 * @return the modified by of this employee uan esic
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this employee uan esic.
	 *
	 * @param modifiedBy the modified by of this employee uan esic
	 */
	public void setModifiedBy(long modifiedBy);

	/**
	 * Returns the group ID of this employee uan esic.
	 *
	 * @return the group ID of this employee uan esic
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this employee uan esic.
	 *
	 * @param groupId the group ID of this employee uan esic
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the create date of this employee uan esic.
	 *
	 * @return the create date of this employee uan esic
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this employee uan esic.
	 *
	 * @param createDate the create date of this employee uan esic
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this employee uan esic.
	 *
	 * @return the modified date of this employee uan esic
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this employee uan esic.
	 *
	 * @param modifiedDate the modified date of this employee uan esic
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the uan esic ID of this employee uan esic.
	 *
	 * @return the uan esic ID of this employee uan esic
	 */
	public long getUanEsicId();

	/**
	 * Sets the uan esic ID of this employee uan esic.
	 *
	 * @param uanEsicId the uan esic ID of this employee uan esic
	 */
	public void setUanEsicId(long uanEsicId);

	/**
	 * Returns the uan of this employee uan esic.
	 *
	 * @return the uan of this employee uan esic
	 */
	@AutoEscape
	public String getUan();

	/**
	 * Sets the uan of this employee uan esic.
	 *
	 * @param uan the uan of this employee uan esic
	 */
	public void setUan(String uan);

	/**
	 * Returns the esic no of this employee uan esic.
	 *
	 * @return the esic no of this employee uan esic
	 */
	@AutoEscape
	public String getEsicNo();

	/**
	 * Sets the esic no of this employee uan esic.
	 *
	 * @param esicNo the esic no of this employee uan esic
	 */
	public void setEsicNo(String esicNo);

	/**
	 * Returns the status of this employee uan esic.
	 *
	 * @return the status of this employee uan esic
	 */
	public boolean getStatus();

	/**
	 * Returns <code>true</code> if this employee uan esic is status.
	 *
	 * @return <code>true</code> if this employee uan esic is status; <code>false</code> otherwise
	 */
	public boolean isStatus();

	/**
	 * Sets whether this employee uan esic is status.
	 *
	 * @param status the status of this employee uan esic
	 */
	public void setStatus(boolean status);

	@Override
	public EmployeeUanEsic cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}