/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the EmployeeDocument service. Represents a row in the &quot;ax_EmployeeDocument&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.ax.hrms.model.impl.EmployeeDocumentModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.ax.hrms.model.impl.EmployeeDocumentImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmployeeDocument
 * @generated
 */
@ProviderType
public interface EmployeeDocumentModel
	extends BaseModel<EmployeeDocument>, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a employee document model instance should use the {@link EmployeeDocument} interface instead.
	 */

	/**
	 * Returns the primary key of this employee document.
	 *
	 * @return the primary key of this employee document
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this employee document.
	 *
	 * @param primaryKey the primary key of this employee document
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this employee document.
	 *
	 * @return the uuid of this employee document
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this employee document.
	 *
	 * @param uuid the uuid of this employee document
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the company ID of this employee document.
	 *
	 * @return the company ID of this employee document
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this employee document.
	 *
	 * @param companyId the company ID of this employee document
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the created by of this employee document.
	 *
	 * @return the created by of this employee document
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this employee document.
	 *
	 * @param createdBy the created by of this employee document
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified by of this employee document.
	 *
	 * @return the modified by of this employee document
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this employee document.
	 *
	 * @param modifiedBy the modified by of this employee document
	 */
	public void setModifiedBy(long modifiedBy);

	/**
	 * Returns the group ID of this employee document.
	 *
	 * @return the group ID of this employee document
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this employee document.
	 *
	 * @param groupId the group ID of this employee document
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the create date of this employee document.
	 *
	 * @return the create date of this employee document
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this employee document.
	 *
	 * @param createDate the create date of this employee document
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this employee document.
	 *
	 * @return the modified date of this employee document
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this employee document.
	 *
	 * @param modifiedDate the modified date of this employee document
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the document ID of this employee document.
	 *
	 * @return the document ID of this employee document
	 */
	public long getDocumentId();

	/**
	 * Sets the document ID of this employee document.
	 *
	 * @param documentId the document ID of this employee document
	 */
	public void setDocumentId(long documentId);

	/**
	 * Returns the document type ID of this employee document.
	 *
	 * @return the document type ID of this employee document
	 */
	public long getDocumentTypeId();

	/**
	 * Sets the document type ID of this employee document.
	 *
	 * @param documentTypeId the document type ID of this employee document
	 */
	public void setDocumentTypeId(long documentTypeId);

	/**
	 * Returns the document number of this employee document.
	 *
	 * @return the document number of this employee document
	 */
	@AutoEscape
	public String getDocumentNumber();

	/**
	 * Sets the document number of this employee document.
	 *
	 * @param documentNumber the document number of this employee document
	 */
	public void setDocumentNumber(String documentNumber);

	/**
	 * Returns the document name of this employee document.
	 *
	 * @return the document name of this employee document
	 */
	@AutoEscape
	public String getDocumentName();

	/**
	 * Sets the document name of this employee document.
	 *
	 * @param documentName the document name of this employee document
	 */
	public void setDocumentName(String documentName);

	/**
	 * Returns the document media ID of this employee document.
	 *
	 * @return the document media ID of this employee document
	 */
	public long getDocumentMediaId();

	/**
	 * Sets the document media ID of this employee document.
	 *
	 * @param documentMediaId the document media ID of this employee document
	 */
	public void setDocumentMediaId(long documentMediaId);

	/**
	 * Returns the document status of this employee document.
	 *
	 * @return the document status of this employee document
	 */
	public boolean getDocumentStatus();

	/**
	 * Returns <code>true</code> if this employee document is document status.
	 *
	 * @return <code>true</code> if this employee document is document status; <code>false</code> otherwise
	 */
	public boolean isDocumentStatus();

	/**
	 * Sets whether this employee document is document status.
	 *
	 * @param documentStatus the document status of this employee document
	 */
	public void setDocumentStatus(boolean documentStatus);

	/**
	 * Returns the employee ID of this employee document.
	 *
	 * @return the employee ID of this employee document
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this employee document.
	 *
	 * @param employeeId the employee ID of this employee document
	 */
	public void setEmployeeId(long employeeId);

	@Override
	public EmployeeDocument cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}