/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the EmployeeDetails service. Represents a row in the &quot;ax_EmployeeDetails&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.ax.hrms.model.impl.EmployeeDetailsModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.ax.hrms.model.impl.EmployeeDetailsImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmployeeDetails
 * @generated
 */
@ProviderType
public interface EmployeeDetailsModel
	extends BaseModel<EmployeeDetails>, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a employee details model instance should use the {@link EmployeeDetails} interface instead.
	 */

	/**
	 * Returns the primary key of this employee details.
	 *
	 * @return the primary key of this employee details
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this employee details.
	 *
	 * @param primaryKey the primary key of this employee details
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this employee details.
	 *
	 * @return the uuid of this employee details
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this employee details.
	 *
	 * @param uuid the uuid of this employee details
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the company ID of this employee details.
	 *
	 * @return the company ID of this employee details
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this employee details.
	 *
	 * @param companyId the company ID of this employee details
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the created by of this employee details.
	 *
	 * @return the created by of this employee details
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this employee details.
	 *
	 * @param createdBy the created by of this employee details
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified by of this employee details.
	 *
	 * @return the modified by of this employee details
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this employee details.
	 *
	 * @param modifiedBy the modified by of this employee details
	 */
	public void setModifiedBy(long modifiedBy);

	/**
	 * Returns the group ID of this employee details.
	 *
	 * @return the group ID of this employee details
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this employee details.
	 *
	 * @param groupId the group ID of this employee details
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the create date of this employee details.
	 *
	 * @return the create date of this employee details
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this employee details.
	 *
	 * @param createDate the create date of this employee details
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this employee details.
	 *
	 * @return the modified date of this employee details
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this employee details.
	 *
	 * @param modifiedDate the modified date of this employee details
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the employee ID of this employee details.
	 *
	 * @return the employee ID of this employee details
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this employee details.
	 *
	 * @param employeeId the employee ID of this employee details
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the employee code of this employee details.
	 *
	 * @return the employee code of this employee details
	 */
	@AutoEscape
	public String getEmployeeCode();

	/**
	 * Sets the employee code of this employee details.
	 *
	 * @param employeeCode the employee code of this employee details
	 */
	public void setEmployeeCode(String employeeCode);

	/**
	 * Returns the lr user ID of this employee details.
	 *
	 * @return the lr user ID of this employee details
	 */
	public long getLrUserId();

	/**
	 * Sets the lr user ID of this employee details.
	 *
	 * @param lrUserId the lr user ID of this employee details
	 */
	public void setLrUserId(long lrUserId);

	/**
	 * Returns the lr user uuid of this employee details.
	 *
	 * @return the lr user uuid of this employee details
	 */
	public String getLrUserUuid();

	/**
	 * Sets the lr user uuid of this employee details.
	 *
	 * @param lrUserUuid the lr user uuid of this employee details
	 */
	public void setLrUserUuid(String lrUserUuid);

	/**
	 * Returns the first name of this employee details.
	 *
	 * @return the first name of this employee details
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this employee details.
	 *
	 * @param firstName the first name of this employee details
	 */
	public void setFirstName(String firstName);

	/**
	 * Returns the last name of this employee details.
	 *
	 * @return the last name of this employee details
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this employee details.
	 *
	 * @param lastName the last name of this employee details
	 */
	public void setLastName(String lastName);

	/**
	 * Returns the official email of this employee details.
	 *
	 * @return the official email of this employee details
	 */
	@AutoEscape
	public String getOfficialEmail();

	/**
	 * Sets the official email of this employee details.
	 *
	 * @param officialEmail the official email of this employee details
	 */
	public void setOfficialEmail(String officialEmail);

	/**
	 * Returns the personal email of this employee details.
	 *
	 * @return the personal email of this employee details
	 */
	@AutoEscape
	public String getPersonalEmail();

	/**
	 * Sets the personal email of this employee details.
	 *
	 * @param personalEmail the personal email of this employee details
	 */
	public void setPersonalEmail(String personalEmail);

	/**
	 * Returns the joining date of this employee details.
	 *
	 * @return the joining date of this employee details
	 */
	public Date getJoiningDate();

	/**
	 * Sets the joining date of this employee details.
	 *
	 * @param joiningDate the joining date of this employee details
	 */
	public void setJoiningDate(Date joiningDate);

	/**
	 * Returns the leaving date of this employee details.
	 *
	 * @return the leaving date of this employee details
	 */
	public Date getLeavingDate();

	/**
	 * Sets the leaving date of this employee details.
	 *
	 * @param leavingDate the leaving date of this employee details
	 */
	public void setLeavingDate(Date leavingDate);

	/**
	 * Returns the mobile no of this employee details.
	 *
	 * @return the mobile no of this employee details
	 */
	@AutoEscape
	public String getMobileNo();

	/**
	 * Sets the mobile no of this employee details.
	 *
	 * @param mobileNo the mobile no of this employee details
	 */
	public void setMobileNo(String mobileNo);

	/**
	 * Returns the gender of this employee details.
	 *
	 * @return the gender of this employee details
	 */
	@AutoEscape
	public String getGender();

	/**
	 * Sets the gender of this employee details.
	 *
	 * @param gender the gender of this employee details
	 */
	public void setGender(String gender);

	/**
	 * Returns the father name of this employee details.
	 *
	 * @return the father name of this employee details
	 */
	@AutoEscape
	public String getFatherName();

	/**
	 * Sets the father name of this employee details.
	 *
	 * @param fatherName the father name of this employee details
	 */
	public void setFatherName(String fatherName);

	/**
	 * Returns the date of birth of this employee details.
	 *
	 * @return the date of birth of this employee details
	 */
	public Date getDateOfBirth();

	/**
	 * Sets the date of birth of this employee details.
	 *
	 * @param dateOfBirth the date of birth of this employee details
	 */
	public void setDateOfBirth(Date dateOfBirth);

	/**
	 * Returns the marital status of this employee details.
	 *
	 * @return the marital status of this employee details
	 */
	public boolean getMaritalStatus();

	/**
	 * Returns <code>true</code> if this employee details is marital status.
	 *
	 * @return <code>true</code> if this employee details is marital status; <code>false</code> otherwise
	 */
	public boolean isMaritalStatus();

	/**
	 * Sets whether this employee details is marital status.
	 *
	 * @param maritalStatus the marital status of this employee details
	 */
	public void setMaritalStatus(boolean maritalStatus);

	/**
	 * Returns the marriage date of this employee details.
	 *
	 * @return the marriage date of this employee details
	 */
	public Date getMarriageDate();

	/**
	 * Sets the marriage date of this employee details.
	 *
	 * @param marriageDate the marriage date of this employee details
	 */
	public void setMarriageDate(Date marriageDate);

	/**
	 * Returns the spouse name of this employee details.
	 *
	 * @return the spouse name of this employee details
	 */
	@AutoEscape
	public String getSpouseName();

	/**
	 * Sets the spouse name of this employee details.
	 *
	 * @param spouseName the spouse name of this employee details
	 */
	public void setSpouseName(String spouseName);

	/**
	 * Returns the employee address ID of this employee details.
	 *
	 * @return the employee address ID of this employee details
	 */
	public long getEmployeeAddressId();

	/**
	 * Sets the employee address ID of this employee details.
	 *
	 * @param employeeAddressId the employee address ID of this employee details
	 */
	public void setEmployeeAddressId(long employeeAddressId);

	/**
	 * Returns the skype ID of this employee details.
	 *
	 * @return the skype ID of this employee details
	 */
	@AutoEscape
	public String getSkypeId();

	/**
	 * Sets the skype ID of this employee details.
	 *
	 * @param skypeId the skype ID of this employee details
	 */
	public void setSkypeId(String skypeId);

	/**
	 * Returns the nominnee ID of this employee details.
	 *
	 * @return the nominnee ID of this employee details
	 */
	public long getNominneeId();

	/**
	 * Sets the nominnee ID of this employee details.
	 *
	 * @param nominneeId the nominnee ID of this employee details
	 */
	public void setNominneeId(long nominneeId);

	/**
	 * Returns the bank account ID of this employee details.
	 *
	 * @return the bank account ID of this employee details
	 */
	public long getBankAccountId();

	/**
	 * Sets the bank account ID of this employee details.
	 *
	 * @param bankAccountId the bank account ID of this employee details
	 */
	public void setBankAccountId(long bankAccountId);

	/**
	 * Returns the uan esic ID of this employee details.
	 *
	 * @return the uan esic ID of this employee details
	 */
	public long getUanEsicId();

	/**
	 * Sets the uan esic ID of this employee details.
	 *
	 * @param uanEsicId the uan esic ID of this employee details
	 */
	public void setUanEsicId(long uanEsicId);

	/**
	 * Returns the probation status ID of this employee details.
	 *
	 * @return the probation status ID of this employee details
	 */
	public long getProbationStatusId();

	/**
	 * Sets the probation status ID of this employee details.
	 *
	 * @param probationStatusId the probation status ID of this employee details
	 */
	public void setProbationStatusId(long probationStatusId);

	/**
	 * Returns the is employee onboarded of this employee details.
	 *
	 * @return the is employee onboarded of this employee details
	 */
	public boolean getIsEmployeeOnboarded();

	/**
	 * Returns <code>true</code> if this employee details is is employee onboarded.
	 *
	 * @return <code>true</code> if this employee details is is employee onboarded; <code>false</code> otherwise
	 */
	public boolean isIsEmployeeOnboarded();

	/**
	 * Sets whether this employee details is is employee onboarded.
	 *
	 * @param isEmployeeOnboarded the is employee onboarded of this employee details
	 */
	public void setIsEmployeeOnboarded(boolean isEmployeeOnboarded);

	/**
	 * Returns the is experienced of this employee details.
	 *
	 * @return the is experienced of this employee details
	 */
	public boolean getIsExperienced();

	/**
	 * Returns <code>true</code> if this employee details is is experienced.
	 *
	 * @return <code>true</code> if this employee details is is experienced; <code>false</code> otherwise
	 */
	public boolean isIsExperienced();

	/**
	 * Sets whether this employee details is is experienced.
	 *
	 * @param isExperienced the is experienced of this employee details
	 */
	public void setIsExperienced(boolean isExperienced);

	/**
	 * Returns the is probation enabled of this employee details.
	 *
	 * @return the is probation enabled of this employee details
	 */
	public boolean getIsProbationEnabled();

	/**
	 * Returns <code>true</code> if this employee details is is probation enabled.
	 *
	 * @return <code>true</code> if this employee details is is probation enabled; <code>false</code> otherwise
	 */
	public boolean isIsProbationEnabled();

	/**
	 * Sets whether this employee details is is probation enabled.
	 *
	 * @param isProbationEnabled the is probation enabled of this employee details
	 */
	public void setIsProbationEnabled(boolean isProbationEnabled);

	/**
	 * Returns the profile pic ID of this employee details.
	 *
	 * @return the profile pic ID of this employee details
	 */
	public long getProfilePicId();

	/**
	 * Sets the profile pic ID of this employee details.
	 *
	 * @param profilePicId the profile pic ID of this employee details
	 */
	public void setProfilePicId(long profilePicId);

	/**
	 * Returns the insurance link of this employee details.
	 *
	 * @return the insurance link of this employee details
	 */
	@AutoEscape
	public String getInsuranceLink();

	/**
	 * Sets the insurance link of this employee details.
	 *
	 * @param insuranceLink the insurance link of this employee details
	 */
	public void setInsuranceLink(String insuranceLink);

	/**
	 * Returns the is terminated of this employee details.
	 *
	 * @return the is terminated of this employee details
	 */
	public boolean getIsTerminated();

	/**
	 * Returns <code>true</code> if this employee details is is terminated.
	 *
	 * @return <code>true</code> if this employee details is is terminated; <code>false</code> otherwise
	 */
	public boolean isIsTerminated();

	/**
	 * Sets whether this employee details is is terminated.
	 *
	 * @param isTerminated the is terminated of this employee details
	 */
	public void setIsTerminated(boolean isTerminated);

	/**
	 * Returns the appraisal date of this employee details.
	 *
	 * @return the appraisal date of this employee details
	 */
	public Date getAppraisalDate();

	/**
	 * Sets the appraisal date of this employee details.
	 *
	 * @param appraisalDate the appraisal date of this employee details
	 */
	public void setAppraisalDate(Date appraisalDate);

	/**
	 * Returns the employee type of this employee details.
	 *
	 * @return the employee type of this employee details
	 */
	@AutoEscape
	public String getEmployeeType();

	/**
	 * Sets the employee type of this employee details.
	 *
	 * @param employeeType the employee type of this employee details
	 */
	public void setEmployeeType(String employeeType);

	/**
	 * Returns the stipend of this employee details.
	 *
	 * @return the stipend of this employee details
	 */
	public double getStipend();

	/**
	 * Sets the stipend of this employee details.
	 *
	 * @param stipend the stipend of this employee details
	 */
	public void setStipend(double stipend);

	@Override
	public EmployeeDetails cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}