/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the EmployeeProbationDetails service. Represents a row in the &quot;ax_EmployeeProbationDetails&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.ax.hrms.model.impl.EmployeeProbationDetailsModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.ax.hrms.model.impl.EmployeeProbationDetailsImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmployeeProbationDetails
 * @generated
 */
@ProviderType
public interface EmployeeProbationDetailsModel
	extends BaseModel<EmployeeProbationDetails>, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a employee probation details model instance should use the {@link EmployeeProbationDetails} interface instead.
	 */

	/**
	 * Returns the primary key of this employee probation details.
	 *
	 * @return the primary key of this employee probation details
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this employee probation details.
	 *
	 * @param primaryKey the primary key of this employee probation details
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this employee probation details.
	 *
	 * @return the uuid of this employee probation details
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this employee probation details.
	 *
	 * @param uuid the uuid of this employee probation details
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the company ID of this employee probation details.
	 *
	 * @return the company ID of this employee probation details
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this employee probation details.
	 *
	 * @param companyId the company ID of this employee probation details
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the created by of this employee probation details.
	 *
	 * @return the created by of this employee probation details
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this employee probation details.
	 *
	 * @param createdBy the created by of this employee probation details
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified by of this employee probation details.
	 *
	 * @return the modified by of this employee probation details
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this employee probation details.
	 *
	 * @param modifiedBy the modified by of this employee probation details
	 */
	public void setModifiedBy(long modifiedBy);

	/**
	 * Returns the group ID of this employee probation details.
	 *
	 * @return the group ID of this employee probation details
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this employee probation details.
	 *
	 * @param groupId the group ID of this employee probation details
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the create date of this employee probation details.
	 *
	 * @return the create date of this employee probation details
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this employee probation details.
	 *
	 * @param createDate the create date of this employee probation details
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this employee probation details.
	 *
	 * @return the modified date of this employee probation details
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this employee probation details.
	 *
	 * @param modifiedDate the modified date of this employee probation details
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the probation detail ID of this employee probation details.
	 *
	 * @return the probation detail ID of this employee probation details
	 */
	public long getProbationDetailId();

	/**
	 * Sets the probation detail ID of this employee probation details.
	 *
	 * @param probationDetailId the probation detail ID of this employee probation details
	 */
	public void setProbationDetailId(long probationDetailId);

	/**
	 * Returns the probation period of this employee probation details.
	 *
	 * @return the probation period of this employee probation details
	 */
	public int getProbationPeriod();

	/**
	 * Sets the probation period of this employee probation details.
	 *
	 * @param probationPeriod the probation period of this employee probation details
	 */
	public void setProbationPeriod(int probationPeriod);

	/**
	 * Returns the probation end date of this employee probation details.
	 *
	 * @return the probation end date of this employee probation details
	 */
	public Date getProbationEndDate();

	/**
	 * Sets the probation end date of this employee probation details.
	 *
	 * @param probationEndDate the probation end date of this employee probation details
	 */
	public void setProbationEndDate(Date probationEndDate);

	/**
	 * Returns the probation status ID of this employee probation details.
	 *
	 * @return the probation status ID of this employee probation details
	 */
	public long getProbationStatusId();

	/**
	 * Sets the probation status ID of this employee probation details.
	 *
	 * @param probationStatusId the probation status ID of this employee probation details
	 */
	public void setProbationStatusId(long probationStatusId);

	/**
	 * Returns the is extended of this employee probation details.
	 *
	 * @return the is extended of this employee probation details
	 */
	public Boolean getIsExtended();

	/**
	 * Sets the is extended of this employee probation details.
	 *
	 * @param isExtended the is extended of this employee probation details
	 */
	public void setIsExtended(Boolean isExtended);

	/**
	 * Returns the employee ID of this employee probation details.
	 *
	 * @return the employee ID of this employee probation details
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this employee probation details.
	 *
	 * @param employeeId the employee ID of this employee probation details
	 */
	public void setEmployeeId(long employeeId);

	@Override
	public EmployeeProbationDetails cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}