/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the LeaveRequest service. Represents a row in the &quot;ax_LeaveRequest&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.ax.hrms.model.impl.LeaveRequestModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.ax.hrms.model.impl.LeaveRequestImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LeaveRequest
 * @generated
 */
@ProviderType
public interface LeaveRequestModel
	extends BaseModel<LeaveRequest>, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a leave request model instance should use the {@link LeaveRequest} interface instead.
	 */

	/**
	 * Returns the primary key of this leave request.
	 *
	 * @return the primary key of this leave request
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this leave request.
	 *
	 * @param primaryKey the primary key of this leave request
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this leave request.
	 *
	 * @return the uuid of this leave request
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this leave request.
	 *
	 * @param uuid the uuid of this leave request
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the company ID of this leave request.
	 *
	 * @return the company ID of this leave request
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this leave request.
	 *
	 * @param companyId the company ID of this leave request
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the created by of this leave request.
	 *
	 * @return the created by of this leave request
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this leave request.
	 *
	 * @param createdBy the created by of this leave request
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified by of this leave request.
	 *
	 * @return the modified by of this leave request
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this leave request.
	 *
	 * @param modifiedBy the modified by of this leave request
	 */
	public void setModifiedBy(long modifiedBy);

	/**
	 * Returns the group ID of this leave request.
	 *
	 * @return the group ID of this leave request
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this leave request.
	 *
	 * @param groupId the group ID of this leave request
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the create date of this leave request.
	 *
	 * @return the create date of this leave request
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this leave request.
	 *
	 * @param createDate the create date of this leave request
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this leave request.
	 *
	 * @return the modified date of this leave request
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this leave request.
	 *
	 * @param modifiedDate the modified date of this leave request
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the leave request ID of this leave request.
	 *
	 * @return the leave request ID of this leave request
	 */
	public long getLeaveRequestId();

	/**
	 * Sets the leave request ID of this leave request.
	 *
	 * @param leaveRequestId the leave request ID of this leave request
	 */
	public void setLeaveRequestId(long leaveRequestId);

	/**
	 * Returns the employee ID of this leave request.
	 *
	 * @return the employee ID of this leave request
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this leave request.
	 *
	 * @param employeeId the employee ID of this leave request
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the leave type master ID of this leave request.
	 *
	 * @return the leave type master ID of this leave request
	 */
	public long getLeaveTypeMasterId();

	/**
	 * Sets the leave type master ID of this leave request.
	 *
	 * @param leaveTypeMasterId the leave type master ID of this leave request
	 */
	public void setLeaveTypeMasterId(long leaveTypeMasterId);

	/**
	 * Returns the start date time of this leave request.
	 *
	 * @return the start date time of this leave request
	 */
	public Date getStartDateTime();

	/**
	 * Sets the start date time of this leave request.
	 *
	 * @param startDateTime the start date time of this leave request
	 */
	public void setStartDateTime(Date startDateTime);

	/**
	 * Returns the end date time of this leave request.
	 *
	 * @return the end date time of this leave request
	 */
	public Date getEndDateTime();

	/**
	 * Sets the end date time of this leave request.
	 *
	 * @param endDateTime the end date time of this leave request
	 */
	public void setEndDateTime(Date endDateTime);

	/**
	 * Returns the reason of this leave request.
	 *
	 * @return the reason of this leave request
	 */
	@AutoEscape
	public String getReason();

	/**
	 * Sets the reason of this leave request.
	 *
	 * @param reason the reason of this leave request
	 */
	public void setReason(String reason);

	/**
	 * Returns the leave compensatory status master ID of this leave request.
	 *
	 * @return the leave compensatory status master ID of this leave request
	 */
	public long getLeaveCompensatoryStatusMasterId();

	/**
	 * Sets the leave compensatory status master ID of this leave request.
	 *
	 * @param leaveCompensatoryStatusMasterId the leave compensatory status master ID of this leave request
	 */
	public void setLeaveCompensatoryStatusMasterId(
		long leaveCompensatoryStatusMasterId);

	/**
	 * Returns the hr approval ID of this leave request.
	 *
	 * @return the hr approval ID of this leave request
	 */
	public long getHrApprovalId();

	/**
	 * Sets the hr approval ID of this leave request.
	 *
	 * @param hrApprovalId the hr approval ID of this leave request
	 */
	public void setHrApprovalId(long hrApprovalId);

	/**
	 * Returns the manager approval ID of this leave request.
	 *
	 * @return the manager approval ID of this leave request
	 */
	public long getManagerApprovalId();

	/**
	 * Sets the manager approval ID of this leave request.
	 *
	 * @param managerApprovalId the manager approval ID of this leave request
	 */
	public void setManagerApprovalId(long managerApprovalId);

	/**
	 * Returns the date of request of this leave request.
	 *
	 * @return the date of request of this leave request
	 */
	public Date getDateOfRequest();

	/**
	 * Sets the date of request of this leave request.
	 *
	 * @param dateOfRequest the date of request of this leave request
	 */
	public void setDateOfRequest(Date dateOfRequest);

	@Override
	public LeaveRequest cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}