/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the LeaveTypeViewPermit service. Represents a row in the &quot;ax_LeaveTypeViewPermit&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.ax.hrms.model.impl.LeaveTypeViewPermitModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.ax.hrms.model.impl.LeaveTypeViewPermitImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LeaveTypeViewPermit
 * @generated
 */
@ProviderType
public interface LeaveTypeViewPermitModel
	extends BaseModel<LeaveTypeViewPermit>, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a leave type view permit model instance should use the {@link LeaveTypeViewPermit} interface instead.
	 */

	/**
	 * Returns the primary key of this leave type view permit.
	 *
	 * @return the primary key of this leave type view permit
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this leave type view permit.
	 *
	 * @param primaryKey the primary key of this leave type view permit
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this leave type view permit.
	 *
	 * @return the uuid of this leave type view permit
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this leave type view permit.
	 *
	 * @param uuid the uuid of this leave type view permit
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the company ID of this leave type view permit.
	 *
	 * @return the company ID of this leave type view permit
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this leave type view permit.
	 *
	 * @param companyId the company ID of this leave type view permit
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the created by of this leave type view permit.
	 *
	 * @return the created by of this leave type view permit
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this leave type view permit.
	 *
	 * @param createdBy the created by of this leave type view permit
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified by of this leave type view permit.
	 *
	 * @return the modified by of this leave type view permit
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this leave type view permit.
	 *
	 * @param modifiedBy the modified by of this leave type view permit
	 */
	public void setModifiedBy(long modifiedBy);

	/**
	 * Returns the group ID of this leave type view permit.
	 *
	 * @return the group ID of this leave type view permit
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this leave type view permit.
	 *
	 * @param groupId the group ID of this leave type view permit
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the create date of this leave type view permit.
	 *
	 * @return the create date of this leave type view permit
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this leave type view permit.
	 *
	 * @param createDate the create date of this leave type view permit
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this leave type view permit.
	 *
	 * @return the modified date of this leave type view permit
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this leave type view permit.
	 *
	 * @param modifiedDate the modified date of this leave type view permit
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the leave type view permit ID of this leave type view permit.
	 *
	 * @return the leave type view permit ID of this leave type view permit
	 */
	public long getLeaveTypeViewPermitId();

	/**
	 * Sets the leave type view permit ID of this leave type view permit.
	 *
	 * @param leaveTypeViewPermitId the leave type view permit ID of this leave type view permit
	 */
	public void setLeaveTypeViewPermitId(long leaveTypeViewPermitId);

	/**
	 * Returns the leave type master ID of this leave type view permit.
	 *
	 * @return the leave type master ID of this leave type view permit
	 */
	public long getLeaveTypeMasterId();

	/**
	 * Sets the leave type master ID of this leave type view permit.
	 *
	 * @param leaveTypeMasterId the leave type master ID of this leave type view permit
	 */
	public void setLeaveTypeMasterId(long leaveTypeMasterId);

	/**
	 * Returns the employee ID of this leave type view permit.
	 *
	 * @return the employee ID of this leave type view permit
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this leave type view permit.
	 *
	 * @param employeeId the employee ID of this leave type view permit
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the year of leave type view permit of this leave type view permit.
	 *
	 * @return the year of leave type view permit of this leave type view permit
	 */
	public int getYearOfLeaveTypeViewPermit();

	/**
	 * Sets the year of leave type view permit of this leave type view permit.
	 *
	 * @param yearOfLeaveTypeViewPermit the year of leave type view permit of this leave type view permit
	 */
	public void setYearOfLeaveTypeViewPermit(int yearOfLeaveTypeViewPermit);

	@Override
	public LeaveTypeViewPermit cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}