/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the RolePolicies service. Represents a row in the &quot;ax_RolePolicies&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.ax.hrms.model.impl.RolePoliciesModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.ax.hrms.model.impl.RolePoliciesImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RolePolicies
 * @generated
 */
@ProviderType
public interface RolePoliciesModel
	extends BaseModel<RolePolicies>, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a role policies model instance should use the {@link RolePolicies} interface instead.
	 */

	/**
	 * Returns the primary key of this role policies.
	 *
	 * @return the primary key of this role policies
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this role policies.
	 *
	 * @param primaryKey the primary key of this role policies
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this role policies.
	 *
	 * @return the uuid of this role policies
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this role policies.
	 *
	 * @param uuid the uuid of this role policies
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the company ID of this role policies.
	 *
	 * @return the company ID of this role policies
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this role policies.
	 *
	 * @param companyId the company ID of this role policies
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the created by of this role policies.
	 *
	 * @return the created by of this role policies
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this role policies.
	 *
	 * @param createdBy the created by of this role policies
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified by of this role policies.
	 *
	 * @return the modified by of this role policies
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this role policies.
	 *
	 * @param modifiedBy the modified by of this role policies
	 */
	public void setModifiedBy(long modifiedBy);

	/**
	 * Returns the group ID of this role policies.
	 *
	 * @return the group ID of this role policies
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this role policies.
	 *
	 * @param groupId the group ID of this role policies
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the create date of this role policies.
	 *
	 * @return the create date of this role policies
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this role policies.
	 *
	 * @param createDate the create date of this role policies
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this role policies.
	 *
	 * @return the modified date of this role policies
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this role policies.
	 *
	 * @param modifiedDate the modified date of this role policies
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the role policies ID of this role policies.
	 *
	 * @return the role policies ID of this role policies
	 */
	public long getRolePoliciesId();

	/**
	 * Sets the role policies ID of this role policies.
	 *
	 * @param rolePoliciesId the role policies ID of this role policies
	 */
	public void setRolePoliciesId(long rolePoliciesId);

	/**
	 * Returns the role ID of this role policies.
	 *
	 * @return the role ID of this role policies
	 */
	public long getRoleId();

	/**
	 * Sets the role ID of this role policies.
	 *
	 * @param roleId the role ID of this role policies
	 */
	public void setRoleId(long roleId);

	/**
	 * Returns the policy ID of this role policies.
	 *
	 * @return the policy ID of this role policies
	 */
	public long getPolicyId();

	/**
	 * Sets the policy ID of this role policies.
	 *
	 * @param policyId the policy ID of this role policies
	 */
	public void setPolicyId(long policyId);

	@Override
	public RolePolicies cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}