/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the TimeTracker service. Represents a row in the &quot;ax_TimeTracker&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.ax.hrms.model.impl.TimeTrackerModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.ax.hrms.model.impl.TimeTrackerImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TimeTracker
 * @generated
 */
@ProviderType
public interface TimeTrackerModel
	extends BaseModel<TimeTracker>, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a time tracker model instance should use the {@link TimeTracker} interface instead.
	 */

	/**
	 * Returns the primary key of this time tracker.
	 *
	 * @return the primary key of this time tracker
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this time tracker.
	 *
	 * @param primaryKey the primary key of this time tracker
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this time tracker.
	 *
	 * @return the uuid of this time tracker
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this time tracker.
	 *
	 * @param uuid the uuid of this time tracker
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the company ID of this time tracker.
	 *
	 * @return the company ID of this time tracker
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this time tracker.
	 *
	 * @param companyId the company ID of this time tracker
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the created by of this time tracker.
	 *
	 * @return the created by of this time tracker
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this time tracker.
	 *
	 * @param createdBy the created by of this time tracker
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified by of this time tracker.
	 *
	 * @return the modified by of this time tracker
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this time tracker.
	 *
	 * @param modifiedBy the modified by of this time tracker
	 */
	public void setModifiedBy(long modifiedBy);

	/**
	 * Returns the group ID of this time tracker.
	 *
	 * @return the group ID of this time tracker
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this time tracker.
	 *
	 * @param groupId the group ID of this time tracker
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the create date of this time tracker.
	 *
	 * @return the create date of this time tracker
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this time tracker.
	 *
	 * @param createDate the create date of this time tracker
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this time tracker.
	 *
	 * @return the modified date of this time tracker
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this time tracker.
	 *
	 * @param modifiedDate the modified date of this time tracker
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the time tracker ID of this time tracker.
	 *
	 * @return the time tracker ID of this time tracker
	 */
	public long getTimeTrackerId();

	/**
	 * Sets the time tracker ID of this time tracker.
	 *
	 * @param timeTrackerId the time tracker ID of this time tracker
	 */
	public void setTimeTrackerId(long timeTrackerId);

	/**
	 * Returns the task ID of this time tracker.
	 *
	 * @return the task ID of this time tracker
	 */
	public long getTaskId();

	/**
	 * Sets the task ID of this time tracker.
	 *
	 * @param taskId the task ID of this time tracker
	 */
	public void setTaskId(long taskId);

	/**
	 * Returns the employee ID of this time tracker.
	 *
	 * @return the employee ID of this time tracker
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this time tracker.
	 *
	 * @param employeeId the employee ID of this time tracker
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the start time of this time tracker.
	 *
	 * @return the start time of this time tracker
	 */
	public Date getStartTime();

	/**
	 * Sets the start time of this time tracker.
	 *
	 * @param startTime the start time of this time tracker
	 */
	public void setStartTime(Date startTime);

	/**
	 * Returns the end time of this time tracker.
	 *
	 * @return the end time of this time tracker
	 */
	public Date getEndTime();

	/**
	 * Sets the end time of this time tracker.
	 *
	 * @param endTime the end time of this time tracker
	 */
	public void setEndTime(Date endTime);

	/**
	 * Returns the duration of this time tracker.
	 *
	 * @return the duration of this time tracker
	 */
	public double getDuration();

	/**
	 * Sets the duration of this time tracker.
	 *
	 * @param duration the duration of this time tracker
	 */
	public void setDuration(double duration);

	/**
	 * Returns the description of this time tracker.
	 *
	 * @return the description of this time tracker
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this time tracker.
	 *
	 * @param description the description of this time tracker
	 */
	public void setDescription(String description);

	/**
	 * Returns the manager approve status of this time tracker.
	 *
	 * @return the manager approve status of this time tracker
	 */
	@AutoEscape
	public String getManagerApproveStatus();

	/**
	 * Sets the manager approve status of this time tracker.
	 *
	 * @param managerApproveStatus the manager approve status of this time tracker
	 */
	public void setManagerApproveStatus(String managerApproveStatus);

	@Override
	public TimeTracker cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}