/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the UpcomingProbationEmployee service. Represents a row in the &quot;ax_UpcomingProbationEmployee&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.ax.hrms.model.impl.UpcomingProbationEmployeeModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.ax.hrms.model.impl.UpcomingProbationEmployeeImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UpcomingProbationEmployee
 * @generated
 */
@ProviderType
public interface UpcomingProbationEmployeeModel
	extends BaseModel<UpcomingProbationEmployee>, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a upcoming probation employee model instance should use the {@link UpcomingProbationEmployee} interface instead.
	 */

	/**
	 * Returns the primary key of this upcoming probation employee.
	 *
	 * @return the primary key of this upcoming probation employee
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this upcoming probation employee.
	 *
	 * @param primaryKey the primary key of this upcoming probation employee
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this upcoming probation employee.
	 *
	 * @return the uuid of this upcoming probation employee
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this upcoming probation employee.
	 *
	 * @param uuid the uuid of this upcoming probation employee
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the company ID of this upcoming probation employee.
	 *
	 * @return the company ID of this upcoming probation employee
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this upcoming probation employee.
	 *
	 * @param companyId the company ID of this upcoming probation employee
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the created by of this upcoming probation employee.
	 *
	 * @return the created by of this upcoming probation employee
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this upcoming probation employee.
	 *
	 * @param createdBy the created by of this upcoming probation employee
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified by of this upcoming probation employee.
	 *
	 * @return the modified by of this upcoming probation employee
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this upcoming probation employee.
	 *
	 * @param modifiedBy the modified by of this upcoming probation employee
	 */
	public void setModifiedBy(long modifiedBy);

	/**
	 * Returns the group ID of this upcoming probation employee.
	 *
	 * @return the group ID of this upcoming probation employee
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this upcoming probation employee.
	 *
	 * @param groupId the group ID of this upcoming probation employee
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the create date of this upcoming probation employee.
	 *
	 * @return the create date of this upcoming probation employee
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this upcoming probation employee.
	 *
	 * @param createDate the create date of this upcoming probation employee
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this upcoming probation employee.
	 *
	 * @return the modified date of this upcoming probation employee
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this upcoming probation employee.
	 *
	 * @param modifiedDate the modified date of this upcoming probation employee
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the upcoming probation employee ID of this upcoming probation employee.
	 *
	 * @return the upcoming probation employee ID of this upcoming probation employee
	 */
	public long getUpcomingProbationEmployeeId();

	/**
	 * Sets the upcoming probation employee ID of this upcoming probation employee.
	 *
	 * @param upcomingProbationEmployeeId the upcoming probation employee ID of this upcoming probation employee
	 */
	public void setUpcomingProbationEmployeeId(
		long upcomingProbationEmployeeId);

	/**
	 * Returns the probation detail ID of this upcoming probation employee.
	 *
	 * @return the probation detail ID of this upcoming probation employee
	 */
	public long getProbationDetailId();

	/**
	 * Sets the probation detail ID of this upcoming probation employee.
	 *
	 * @param probationDetailId the probation detail ID of this upcoming probation employee
	 */
	public void setProbationDetailId(long probationDetailId);

	/**
	 * Returns the month of this upcoming probation employee.
	 *
	 * @return the month of this upcoming probation employee
	 */
	public int getMonth();

	/**
	 * Sets the month of this upcoming probation employee.
	 *
	 * @param month the month of this upcoming probation employee
	 */
	public void setMonth(int month);

	/**
	 * Returns the year of this upcoming probation employee.
	 *
	 * @return the year of this upcoming probation employee
	 */
	public int getYear();

	/**
	 * Sets the year of this upcoming probation employee.
	 *
	 * @param year the year of this upcoming probation employee
	 */
	public void setYear(int year);

	@Override
	public UpcomingProbationEmployee cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}