/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.master.model.impl;

import com.ax.hrms.master.model.AppraisalStatusMaster;
import com.ax.hrms.master.model.AppraisalStatusMasterModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the AppraisalStatusMaster service. Represents a row in the &quot;ax_master_AppraisalStatusMaster&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AppraisalStatusMasterModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AppraisalStatusMasterImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AppraisalStatusMasterImpl
 * @generated
 */
@JSON(strict = true)
public class AppraisalStatusMasterModelImpl
	extends BaseModelImpl<AppraisalStatusMaster>
	implements AppraisalStatusMasterModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a appraisal status master model instance should use the <code>AppraisalStatusMaster</code> interface instead.
	 */
	public static final String TABLE_NAME = "ax_master_AppraisalStatusMaster";

	public static final Object[][] TABLE_COLUMNS = {
		{"appraisalStatusMasterId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"createdBy", Types.BIGINT}, {"modifiedBy", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"status", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("appraisalStatusMasterId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ax_master_AppraisalStatusMaster (appraisalStatusMasterId LONG not null primary key,companyId LONG,createdBy LONG,modifiedBy LONG,groupId LONG,createDate DATE null,modifiedDate DATE null,status VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table ax_master_AppraisalStatusMaster";

	public static final String ORDER_BY_JPQL =
		" ORDER BY appraisalStatusMaster.appraisalStatusMasterId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ax_master_AppraisalStatusMaster.appraisalStatusMasterId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STATUS_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long APPRAISALSTATUSMASTERID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public AppraisalStatusMasterModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _appraisalStatusMasterId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAppraisalStatusMasterId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _appraisalStatusMasterId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AppraisalStatusMaster.class;
	}

	@Override
	public String getModelClassName() {
		return AppraisalStatusMaster.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<AppraisalStatusMaster, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<AppraisalStatusMaster, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AppraisalStatusMaster, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((AppraisalStatusMaster)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<AppraisalStatusMaster, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<AppraisalStatusMaster, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(AppraisalStatusMaster)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<AppraisalStatusMaster, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<AppraisalStatusMaster, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map
			<String, Function<AppraisalStatusMaster, Object>>
				_attributeGetterFunctions;

		static {
			Map<String, Function<AppraisalStatusMaster, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<AppraisalStatusMaster, Object>>();

			attributeGetterFunctions.put(
				"appraisalStatusMasterId",
				AppraisalStatusMaster::getAppraisalStatusMasterId);
			attributeGetterFunctions.put(
				"companyId", AppraisalStatusMaster::getCompanyId);
			attributeGetterFunctions.put(
				"createdBy", AppraisalStatusMaster::getCreatedBy);
			attributeGetterFunctions.put(
				"modifiedBy", AppraisalStatusMaster::getModifiedBy);
			attributeGetterFunctions.put(
				"groupId", AppraisalStatusMaster::getGroupId);
			attributeGetterFunctions.put(
				"createDate", AppraisalStatusMaster::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", AppraisalStatusMaster::getModifiedDate);
			attributeGetterFunctions.put(
				"status", AppraisalStatusMaster::getStatus);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<AppraisalStatusMaster, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<AppraisalStatusMaster, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<AppraisalStatusMaster, ?>>();

			attributeSetterBiConsumers.put(
				"appraisalStatusMasterId",
				(BiConsumer<AppraisalStatusMaster, Long>)
					AppraisalStatusMaster::setAppraisalStatusMasterId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<AppraisalStatusMaster, Long>)
					AppraisalStatusMaster::setCompanyId);
			attributeSetterBiConsumers.put(
				"createdBy",
				(BiConsumer<AppraisalStatusMaster, Long>)
					AppraisalStatusMaster::setCreatedBy);
			attributeSetterBiConsumers.put(
				"modifiedBy",
				(BiConsumer<AppraisalStatusMaster, Long>)
					AppraisalStatusMaster::setModifiedBy);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<AppraisalStatusMaster, Long>)
					AppraisalStatusMaster::setGroupId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<AppraisalStatusMaster, Date>)
					AppraisalStatusMaster::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<AppraisalStatusMaster, Date>)
					AppraisalStatusMaster::setModifiedDate);
			attributeSetterBiConsumers.put(
				"status",
				(BiConsumer<AppraisalStatusMaster, String>)
					AppraisalStatusMaster::setStatus);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getAppraisalStatusMasterId() {
		return _appraisalStatusMasterId;
	}

	@Override
	public void setAppraisalStatusMasterId(long appraisalStatusMasterId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_appraisalStatusMasterId = appraisalStatusMasterId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getStatus() {
		if (_status == null) {
			return "";
		}
		else {
			return _status;
		}
	}

	@Override
	public void setStatus(String status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalStatus() {
		return getColumnOriginalValue("status");
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), AppraisalStatusMaster.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AppraisalStatusMaster toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, AppraisalStatusMaster>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AppraisalStatusMasterImpl appraisalStatusMasterImpl =
			new AppraisalStatusMasterImpl();

		appraisalStatusMasterImpl.setAppraisalStatusMasterId(
			getAppraisalStatusMasterId());
		appraisalStatusMasterImpl.setCompanyId(getCompanyId());
		appraisalStatusMasterImpl.setCreatedBy(getCreatedBy());
		appraisalStatusMasterImpl.setModifiedBy(getModifiedBy());
		appraisalStatusMasterImpl.setGroupId(getGroupId());
		appraisalStatusMasterImpl.setCreateDate(getCreateDate());
		appraisalStatusMasterImpl.setModifiedDate(getModifiedDate());
		appraisalStatusMasterImpl.setStatus(getStatus());

		appraisalStatusMasterImpl.resetOriginalValues();

		return appraisalStatusMasterImpl;
	}

	@Override
	public AppraisalStatusMaster cloneWithOriginalValues() {
		AppraisalStatusMasterImpl appraisalStatusMasterImpl =
			new AppraisalStatusMasterImpl();

		appraisalStatusMasterImpl.setAppraisalStatusMasterId(
			this.<Long>getColumnOriginalValue("appraisalStatusMasterId"));
		appraisalStatusMasterImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		appraisalStatusMasterImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("createdBy"));
		appraisalStatusMasterImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modifiedBy"));
		appraisalStatusMasterImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		appraisalStatusMasterImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		appraisalStatusMasterImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		appraisalStatusMasterImpl.setStatus(
			this.<String>getColumnOriginalValue("status"));

		return appraisalStatusMasterImpl;
	}

	@Override
	public int compareTo(AppraisalStatusMaster appraisalStatusMaster) {
		long primaryKey = appraisalStatusMaster.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof AppraisalStatusMaster)) {
			return false;
		}

		AppraisalStatusMaster appraisalStatusMaster =
			(AppraisalStatusMaster)object;

		long primaryKey = appraisalStatusMaster.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<AppraisalStatusMaster> toCacheModel() {
		AppraisalStatusMasterCacheModel appraisalStatusMasterCacheModel =
			new AppraisalStatusMasterCacheModel();

		appraisalStatusMasterCacheModel.appraisalStatusMasterId =
			getAppraisalStatusMasterId();

		appraisalStatusMasterCacheModel.companyId = getCompanyId();

		appraisalStatusMasterCacheModel.createdBy = getCreatedBy();

		appraisalStatusMasterCacheModel.modifiedBy = getModifiedBy();

		appraisalStatusMasterCacheModel.groupId = getGroupId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			appraisalStatusMasterCacheModel.createDate = createDate.getTime();
		}
		else {
			appraisalStatusMasterCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			appraisalStatusMasterCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			appraisalStatusMasterCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		appraisalStatusMasterCacheModel.status = getStatus();

		String status = appraisalStatusMasterCacheModel.status;

		if ((status != null) && (status.length() == 0)) {
			appraisalStatusMasterCacheModel.status = null;
		}

		return appraisalStatusMasterCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<AppraisalStatusMaster, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<AppraisalStatusMaster, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AppraisalStatusMaster, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(AppraisalStatusMaster)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, AppraisalStatusMaster>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					AppraisalStatusMaster.class, ModelWrapper.class);

	}

	private long _appraisalStatusMasterId;
	private long _companyId;
	private long _createdBy;
	private long _modifiedBy;
	private long _groupId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _status;

	public <T> T getColumnValue(String columnName) {
		Function<AppraisalStatusMaster, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((AppraisalStatusMaster)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put(
			"appraisalStatusMasterId", _appraisalStatusMasterId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createdBy", _createdBy);
		_columnOriginalValues.put("modifiedBy", _modifiedBy);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("status", _status);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("appraisalStatusMasterId", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("createdBy", 4L);

		columnBitmasks.put("modifiedBy", 8L);

		columnBitmasks.put("groupId", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("status", 128L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private AppraisalStatusMaster _escapedModel;

}