/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.master.model.impl;

import com.ax.hrms.master.model.BranchMaster;
import com.ax.hrms.master.model.BranchMasterModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the BranchMaster service. Represents a row in the &quot;ax_master_BranchMaster&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>BranchMasterModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BranchMasterImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BranchMasterImpl
 * @generated
 */
@JSON(strict = true)
public class BranchMasterModelImpl
	extends BaseModelImpl<BranchMaster> implements BranchMasterModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a branch master model instance should use the <code>BranchMaster</code> interface instead.
	 */
	public static final String TABLE_NAME = "ax_master_BranchMaster";

	public static final Object[][] TABLE_COLUMNS = {
		{"branchMasterId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"createdBy", Types.BIGINT}, {"modifiedBy", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"branchName", Types.VARCHAR},
		{"addressId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("branchMasterId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("branchName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("addressId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ax_master_BranchMaster (branchMasterId LONG not null primary key,companyId LONG,createdBy LONG,modifiedBy LONG,groupId LONG,createDate DATE null,modifiedDate DATE null,branchName VARCHAR(75) null,addressId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table ax_master_BranchMaster";

	public static final String ORDER_BY_JPQL =
		" ORDER BY branchMaster.branchName ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ax_master_BranchMaster.branchName ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long BRANCHNAME_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public BranchMasterModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _branchMasterId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setBranchMasterId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _branchMasterId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return BranchMaster.class;
	}

	@Override
	public String getModelClassName() {
		return BranchMaster.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<BranchMaster, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<BranchMaster, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<BranchMaster, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((BranchMaster)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<BranchMaster, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<BranchMaster, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(BranchMaster)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<BranchMaster, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<BranchMaster, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<BranchMaster, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<BranchMaster, Object>>
				attributeGetterFunctions =
					new LinkedHashMap<String, Function<BranchMaster, Object>>();

			attributeGetterFunctions.put(
				"branchMasterId", BranchMaster::getBranchMasterId);
			attributeGetterFunctions.put(
				"companyId", BranchMaster::getCompanyId);
			attributeGetterFunctions.put(
				"createdBy", BranchMaster::getCreatedBy);
			attributeGetterFunctions.put(
				"modifiedBy", BranchMaster::getModifiedBy);
			attributeGetterFunctions.put("groupId", BranchMaster::getGroupId);
			attributeGetterFunctions.put(
				"createDate", BranchMaster::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", BranchMaster::getModifiedDate);
			attributeGetterFunctions.put(
				"branchName", BranchMaster::getBranchName);
			attributeGetterFunctions.put(
				"addressId", BranchMaster::getAddressId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<BranchMaster, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<BranchMaster, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<BranchMaster, ?>>();

			attributeSetterBiConsumers.put(
				"branchMasterId",
				(BiConsumer<BranchMaster, Long>)
					BranchMaster::setBranchMasterId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<BranchMaster, Long>)BranchMaster::setCompanyId);
			attributeSetterBiConsumers.put(
				"createdBy",
				(BiConsumer<BranchMaster, Long>)BranchMaster::setCreatedBy);
			attributeSetterBiConsumers.put(
				"modifiedBy",
				(BiConsumer<BranchMaster, Long>)BranchMaster::setModifiedBy);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<BranchMaster, Long>)BranchMaster::setGroupId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<BranchMaster, Date>)BranchMaster::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<BranchMaster, Date>)BranchMaster::setModifiedDate);
			attributeSetterBiConsumers.put(
				"branchName",
				(BiConsumer<BranchMaster, String>)BranchMaster::setBranchName);
			attributeSetterBiConsumers.put(
				"addressId",
				(BiConsumer<BranchMaster, Long>)BranchMaster::setAddressId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getBranchMasterId() {
		return _branchMasterId;
	}

	@Override
	public void setBranchMasterId(long branchMasterId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_branchMasterId = branchMasterId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getBranchName() {
		if (_branchName == null) {
			return "";
		}
		else {
			return _branchName;
		}
	}

	@Override
	public void setBranchName(String branchName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_branchName = branchName;
	}

	@JSON
	@Override
	public long getAddressId() {
		return _addressId;
	}

	@Override
	public void setAddressId(long addressId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_addressId = addressId;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), BranchMaster.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public BranchMaster toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, BranchMaster>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		BranchMasterImpl branchMasterImpl = new BranchMasterImpl();

		branchMasterImpl.setBranchMasterId(getBranchMasterId());
		branchMasterImpl.setCompanyId(getCompanyId());
		branchMasterImpl.setCreatedBy(getCreatedBy());
		branchMasterImpl.setModifiedBy(getModifiedBy());
		branchMasterImpl.setGroupId(getGroupId());
		branchMasterImpl.setCreateDate(getCreateDate());
		branchMasterImpl.setModifiedDate(getModifiedDate());
		branchMasterImpl.setBranchName(getBranchName());
		branchMasterImpl.setAddressId(getAddressId());

		branchMasterImpl.resetOriginalValues();

		return branchMasterImpl;
	}

	@Override
	public BranchMaster cloneWithOriginalValues() {
		BranchMasterImpl branchMasterImpl = new BranchMasterImpl();

		branchMasterImpl.setBranchMasterId(
			this.<Long>getColumnOriginalValue("branchMasterId"));
		branchMasterImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		branchMasterImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("createdBy"));
		branchMasterImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modifiedBy"));
		branchMasterImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		branchMasterImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		branchMasterImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		branchMasterImpl.setBranchName(
			this.<String>getColumnOriginalValue("branchName"));
		branchMasterImpl.setAddressId(
			this.<Long>getColumnOriginalValue("addressId"));

		return branchMasterImpl;
	}

	@Override
	public int compareTo(BranchMaster branchMaster) {
		int value = 0;

		value = getBranchName().compareTo(branchMaster.getBranchName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof BranchMaster)) {
			return false;
		}

		BranchMaster branchMaster = (BranchMaster)object;

		long primaryKey = branchMaster.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<BranchMaster> toCacheModel() {
		BranchMasterCacheModel branchMasterCacheModel =
			new BranchMasterCacheModel();

		branchMasterCacheModel.branchMasterId = getBranchMasterId();

		branchMasterCacheModel.companyId = getCompanyId();

		branchMasterCacheModel.createdBy = getCreatedBy();

		branchMasterCacheModel.modifiedBy = getModifiedBy();

		branchMasterCacheModel.groupId = getGroupId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			branchMasterCacheModel.createDate = createDate.getTime();
		}
		else {
			branchMasterCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			branchMasterCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			branchMasterCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		branchMasterCacheModel.branchName = getBranchName();

		String branchName = branchMasterCacheModel.branchName;

		if ((branchName != null) && (branchName.length() == 0)) {
			branchMasterCacheModel.branchName = null;
		}

		branchMasterCacheModel.addressId = getAddressId();

		return branchMasterCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<BranchMaster, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<BranchMaster, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<BranchMaster, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((BranchMaster)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, BranchMaster>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					BranchMaster.class, ModelWrapper.class);

	}

	private long _branchMasterId;
	private long _companyId;
	private long _createdBy;
	private long _modifiedBy;
	private long _groupId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _branchName;
	private long _addressId;

	public <T> T getColumnValue(String columnName) {
		Function<BranchMaster, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((BranchMaster)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("branchMasterId", _branchMasterId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createdBy", _createdBy);
		_columnOriginalValues.put("modifiedBy", _modifiedBy);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("branchName", _branchName);
		_columnOriginalValues.put("addressId", _addressId);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("branchMasterId", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("createdBy", 4L);

		columnBitmasks.put("modifiedBy", 8L);

		columnBitmasks.put("groupId", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("branchName", 128L);

		columnBitmasks.put("addressId", 256L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private BranchMaster _escapedModel;

}