/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.master.model.impl;

import com.ax.hrms.master.model.DepartmentMaster;
import com.ax.hrms.master.service.DepartmentMasterLocalServiceUtil;

/**
 * The extended model base implementation for the DepartmentMaster service. Represents a row in the &quot;ax_master_DepartmentMaster&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DepartmentMasterImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DepartmentMasterImpl
 * @see DepartmentMaster
 * @generated
 */
public abstract class DepartmentMasterBaseImpl
	extends DepartmentMasterModelImpl implements DepartmentMaster {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a department master model instance should use the <code>DepartmentMaster</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			DepartmentMasterLocalServiceUtil.addDepartmentMaster(this);
		}
		else {
			DepartmentMasterLocalServiceUtil.updateDepartmentMaster(this);
		}
	}

}