/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.master.model.impl;

import com.ax.hrms.master.model.DepartmentMaster;
import com.ax.hrms.master.model.DepartmentMasterModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the DepartmentMaster service. Represents a row in the &quot;ax_master_DepartmentMaster&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>DepartmentMasterModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DepartmentMasterImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DepartmentMasterImpl
 * @generated
 */
@JSON(strict = true)
public class DepartmentMasterModelImpl
	extends BaseModelImpl<DepartmentMaster> implements DepartmentMasterModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a department master model instance should use the <code>DepartmentMaster</code> interface instead.
	 */
	public static final String TABLE_NAME = "ax_master_DepartmentMaster";

	public static final Object[][] TABLE_COLUMNS = {
		{"departmentMasterId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"createdBy", Types.BIGINT}, {"modifiedBy", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"departmentName", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("departmentMasterId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("departmentName", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ax_master_DepartmentMaster (departmentMasterId LONG not null primary key,companyId LONG,createdBy LONG,modifiedBy LONG,groupId LONG,createDate DATE null,modifiedDate DATE null,departmentName VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table ax_master_DepartmentMaster";

	public static final String ORDER_BY_JPQL =
		" ORDER BY departmentMaster.departmentMasterId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ax_master_DepartmentMaster.departmentMasterId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DEPARTMENTMASTERID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DEPARTMENTNAME_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public DepartmentMasterModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _departmentMasterId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setDepartmentMasterId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _departmentMasterId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return DepartmentMaster.class;
	}

	@Override
	public String getModelClassName() {
		return DepartmentMaster.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<DepartmentMaster, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<DepartmentMaster, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DepartmentMaster, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((DepartmentMaster)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<DepartmentMaster, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<DepartmentMaster, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(DepartmentMaster)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<DepartmentMaster, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<DepartmentMaster, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<DepartmentMaster, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<DepartmentMaster, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<DepartmentMaster, Object>>();

			attributeGetterFunctions.put(
				"departmentMasterId", DepartmentMaster::getDepartmentMasterId);
			attributeGetterFunctions.put(
				"companyId", DepartmentMaster::getCompanyId);
			attributeGetterFunctions.put(
				"createdBy", DepartmentMaster::getCreatedBy);
			attributeGetterFunctions.put(
				"modifiedBy", DepartmentMaster::getModifiedBy);
			attributeGetterFunctions.put(
				"groupId", DepartmentMaster::getGroupId);
			attributeGetterFunctions.put(
				"createDate", DepartmentMaster::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", DepartmentMaster::getModifiedDate);
			attributeGetterFunctions.put(
				"departmentName", DepartmentMaster::getDepartmentName);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<DepartmentMaster, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<DepartmentMaster, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<DepartmentMaster, ?>>();

			attributeSetterBiConsumers.put(
				"departmentMasterId",
				(BiConsumer<DepartmentMaster, Long>)
					DepartmentMaster::setDepartmentMasterId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<DepartmentMaster, Long>)
					DepartmentMaster::setCompanyId);
			attributeSetterBiConsumers.put(
				"createdBy",
				(BiConsumer<DepartmentMaster, Long>)
					DepartmentMaster::setCreatedBy);
			attributeSetterBiConsumers.put(
				"modifiedBy",
				(BiConsumer<DepartmentMaster, Long>)
					DepartmentMaster::setModifiedBy);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<DepartmentMaster, Long>)
					DepartmentMaster::setGroupId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<DepartmentMaster, Date>)
					DepartmentMaster::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<DepartmentMaster, Date>)
					DepartmentMaster::setModifiedDate);
			attributeSetterBiConsumers.put(
				"departmentName",
				(BiConsumer<DepartmentMaster, String>)
					DepartmentMaster::setDepartmentName);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getDepartmentMasterId() {
		return _departmentMasterId;
	}

	@Override
	public void setDepartmentMasterId(long departmentMasterId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_departmentMasterId = departmentMasterId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalDepartmentMasterId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("departmentMasterId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getDepartmentName() {
		if (_departmentName == null) {
			return "";
		}
		else {
			return _departmentName;
		}
	}

	@Override
	public void setDepartmentName(String departmentName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_departmentName = departmentName;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalDepartmentName() {
		return getColumnOriginalValue("departmentName");
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), DepartmentMaster.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public DepartmentMaster toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, DepartmentMaster>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DepartmentMasterImpl departmentMasterImpl = new DepartmentMasterImpl();

		departmentMasterImpl.setDepartmentMasterId(getDepartmentMasterId());
		departmentMasterImpl.setCompanyId(getCompanyId());
		departmentMasterImpl.setCreatedBy(getCreatedBy());
		departmentMasterImpl.setModifiedBy(getModifiedBy());
		departmentMasterImpl.setGroupId(getGroupId());
		departmentMasterImpl.setCreateDate(getCreateDate());
		departmentMasterImpl.setModifiedDate(getModifiedDate());
		departmentMasterImpl.setDepartmentName(getDepartmentName());

		departmentMasterImpl.resetOriginalValues();

		return departmentMasterImpl;
	}

	@Override
	public DepartmentMaster cloneWithOriginalValues() {
		DepartmentMasterImpl departmentMasterImpl = new DepartmentMasterImpl();

		departmentMasterImpl.setDepartmentMasterId(
			this.<Long>getColumnOriginalValue("departmentMasterId"));
		departmentMasterImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		departmentMasterImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("createdBy"));
		departmentMasterImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modifiedBy"));
		departmentMasterImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		departmentMasterImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		departmentMasterImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		departmentMasterImpl.setDepartmentName(
			this.<String>getColumnOriginalValue("departmentName"));

		return departmentMasterImpl;
	}

	@Override
	public int compareTo(DepartmentMaster departmentMaster) {
		long primaryKey = departmentMaster.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof DepartmentMaster)) {
			return false;
		}

		DepartmentMaster departmentMaster = (DepartmentMaster)object;

		long primaryKey = departmentMaster.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<DepartmentMaster> toCacheModel() {
		DepartmentMasterCacheModel departmentMasterCacheModel =
			new DepartmentMasterCacheModel();

		departmentMasterCacheModel.departmentMasterId = getDepartmentMasterId();

		departmentMasterCacheModel.companyId = getCompanyId();

		departmentMasterCacheModel.createdBy = getCreatedBy();

		departmentMasterCacheModel.modifiedBy = getModifiedBy();

		departmentMasterCacheModel.groupId = getGroupId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			departmentMasterCacheModel.createDate = createDate.getTime();
		}
		else {
			departmentMasterCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			departmentMasterCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			departmentMasterCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		departmentMasterCacheModel.departmentName = getDepartmentName();

		String departmentName = departmentMasterCacheModel.departmentName;

		if ((departmentName != null) && (departmentName.length() == 0)) {
			departmentMasterCacheModel.departmentName = null;
		}

		return departmentMasterCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<DepartmentMaster, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<DepartmentMaster, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DepartmentMaster, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(DepartmentMaster)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, DepartmentMaster>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					DepartmentMaster.class, ModelWrapper.class);

	}

	private long _departmentMasterId;
	private long _companyId;
	private long _createdBy;
	private long _modifiedBy;
	private long _groupId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _departmentName;

	public <T> T getColumnValue(String columnName) {
		Function<DepartmentMaster, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((DepartmentMaster)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("departmentMasterId", _departmentMasterId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createdBy", _createdBy);
		_columnOriginalValues.put("modifiedBy", _modifiedBy);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("departmentName", _departmentName);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("departmentMasterId", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("createdBy", 4L);

		columnBitmasks.put("modifiedBy", 8L);

		columnBitmasks.put("groupId", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("departmentName", 128L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private DepartmentMaster _escapedModel;

}