/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.master.model.impl;

import com.ax.hrms.master.model.DesignationMaster;
import com.ax.hrms.master.model.DesignationMasterModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the DesignationMaster service. Represents a row in the &quot;ax_master_DesignationMaster&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>DesignationMasterModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DesignationMasterImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DesignationMasterImpl
 * @generated
 */
@JSON(strict = true)
public class DesignationMasterModelImpl
	extends BaseModelImpl<DesignationMaster> implements DesignationMasterModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a designation master model instance should use the <code>DesignationMaster</code> interface instead.
	 */
	public static final String TABLE_NAME = "ax_master_DesignationMaster";

	public static final Object[][] TABLE_COLUMNS = {
		{"designationMasterId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"createdBy", Types.BIGINT}, {"modifiedBy", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"designationName", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("designationMasterId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("designationName", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ax_master_DesignationMaster (designationMasterId LONG not null primary key,companyId LONG,createdBy LONG,modifiedBy LONG,groupId LONG,createDate DATE null,modifiedDate DATE null,designationName VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table ax_master_DesignationMaster";

	public static final String ORDER_BY_JPQL =
		" ORDER BY designationMaster.designationMasterId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ax_master_DesignationMaster.designationMasterId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DESIGNATIONMASTERID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DESIGNATIONNAME_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public DesignationMasterModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _designationMasterId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setDesignationMasterId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _designationMasterId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return DesignationMaster.class;
	}

	@Override
	public String getModelClassName() {
		return DesignationMaster.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<DesignationMaster, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<DesignationMaster, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DesignationMaster, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((DesignationMaster)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<DesignationMaster, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<DesignationMaster, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(DesignationMaster)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<DesignationMaster, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<DesignationMaster, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<DesignationMaster, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<DesignationMaster, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<DesignationMaster, Object>>();

			attributeGetterFunctions.put(
				"designationMasterId",
				DesignationMaster::getDesignationMasterId);
			attributeGetterFunctions.put(
				"companyId", DesignationMaster::getCompanyId);
			attributeGetterFunctions.put(
				"createdBy", DesignationMaster::getCreatedBy);
			attributeGetterFunctions.put(
				"modifiedBy", DesignationMaster::getModifiedBy);
			attributeGetterFunctions.put(
				"groupId", DesignationMaster::getGroupId);
			attributeGetterFunctions.put(
				"createDate", DesignationMaster::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", DesignationMaster::getModifiedDate);
			attributeGetterFunctions.put(
				"designationName", DesignationMaster::getDesignationName);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<DesignationMaster, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<DesignationMaster, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<DesignationMaster, ?>>();

			attributeSetterBiConsumers.put(
				"designationMasterId",
				(BiConsumer<DesignationMaster, Long>)
					DesignationMaster::setDesignationMasterId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<DesignationMaster, Long>)
					DesignationMaster::setCompanyId);
			attributeSetterBiConsumers.put(
				"createdBy",
				(BiConsumer<DesignationMaster, Long>)
					DesignationMaster::setCreatedBy);
			attributeSetterBiConsumers.put(
				"modifiedBy",
				(BiConsumer<DesignationMaster, Long>)
					DesignationMaster::setModifiedBy);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<DesignationMaster, Long>)
					DesignationMaster::setGroupId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<DesignationMaster, Date>)
					DesignationMaster::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<DesignationMaster, Date>)
					DesignationMaster::setModifiedDate);
			attributeSetterBiConsumers.put(
				"designationName",
				(BiConsumer<DesignationMaster, String>)
					DesignationMaster::setDesignationName);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getDesignationMasterId() {
		return _designationMasterId;
	}

	@Override
	public void setDesignationMasterId(long designationMasterId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_designationMasterId = designationMasterId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalDesignationMasterId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("designationMasterId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getDesignationName() {
		if (_designationName == null) {
			return "";
		}
		else {
			return _designationName;
		}
	}

	@Override
	public void setDesignationName(String designationName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_designationName = designationName;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalDesignationName() {
		return getColumnOriginalValue("designationName");
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), DesignationMaster.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public DesignationMaster toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, DesignationMaster>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DesignationMasterImpl designationMasterImpl =
			new DesignationMasterImpl();

		designationMasterImpl.setDesignationMasterId(getDesignationMasterId());
		designationMasterImpl.setCompanyId(getCompanyId());
		designationMasterImpl.setCreatedBy(getCreatedBy());
		designationMasterImpl.setModifiedBy(getModifiedBy());
		designationMasterImpl.setGroupId(getGroupId());
		designationMasterImpl.setCreateDate(getCreateDate());
		designationMasterImpl.setModifiedDate(getModifiedDate());
		designationMasterImpl.setDesignationName(getDesignationName());

		designationMasterImpl.resetOriginalValues();

		return designationMasterImpl;
	}

	@Override
	public DesignationMaster cloneWithOriginalValues() {
		DesignationMasterImpl designationMasterImpl =
			new DesignationMasterImpl();

		designationMasterImpl.setDesignationMasterId(
			this.<Long>getColumnOriginalValue("designationMasterId"));
		designationMasterImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		designationMasterImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("createdBy"));
		designationMasterImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modifiedBy"));
		designationMasterImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		designationMasterImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		designationMasterImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		designationMasterImpl.setDesignationName(
			this.<String>getColumnOriginalValue("designationName"));

		return designationMasterImpl;
	}

	@Override
	public int compareTo(DesignationMaster designationMaster) {
		long primaryKey = designationMaster.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof DesignationMaster)) {
			return false;
		}

		DesignationMaster designationMaster = (DesignationMaster)object;

		long primaryKey = designationMaster.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<DesignationMaster> toCacheModel() {
		DesignationMasterCacheModel designationMasterCacheModel =
			new DesignationMasterCacheModel();

		designationMasterCacheModel.designationMasterId =
			getDesignationMasterId();

		designationMasterCacheModel.companyId = getCompanyId();

		designationMasterCacheModel.createdBy = getCreatedBy();

		designationMasterCacheModel.modifiedBy = getModifiedBy();

		designationMasterCacheModel.groupId = getGroupId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			designationMasterCacheModel.createDate = createDate.getTime();
		}
		else {
			designationMasterCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			designationMasterCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			designationMasterCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		designationMasterCacheModel.designationName = getDesignationName();

		String designationName = designationMasterCacheModel.designationName;

		if ((designationName != null) && (designationName.length() == 0)) {
			designationMasterCacheModel.designationName = null;
		}

		return designationMasterCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<DesignationMaster, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<DesignationMaster, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DesignationMaster, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(DesignationMaster)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, DesignationMaster>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					DesignationMaster.class, ModelWrapper.class);

	}

	private long _designationMasterId;
	private long _companyId;
	private long _createdBy;
	private long _modifiedBy;
	private long _groupId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _designationName;

	public <T> T getColumnValue(String columnName) {
		Function<DesignationMaster, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((DesignationMaster)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("designationMasterId", _designationMasterId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createdBy", _createdBy);
		_columnOriginalValues.put("modifiedBy", _modifiedBy);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("designationName", _designationName);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("designationMasterId", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("createdBy", 4L);

		columnBitmasks.put("modifiedBy", 8L);

		columnBitmasks.put("groupId", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("designationName", 128L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private DesignationMaster _escapedModel;

}