/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.master.model.impl;

import com.ax.hrms.master.model.DesignationMaster;
import com.ax.hrms.master.service.DesignationMasterLocalServiceUtil;

/**
 * The extended model base implementation for the DesignationMaster service. Represents a row in the &quot;ax_master_DesignationMaster&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DesignationMasterImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DesignationMasterImpl
 * @see DesignationMaster
 * @generated
 */
public abstract class DesignationMasterBaseImpl
	extends DesignationMasterModelImpl implements DesignationMaster {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a designation master model instance should use the <code>DesignationMaster</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			DesignationMasterLocalServiceUtil.addDesignationMaster(this);
		}
		else {
			DesignationMasterLocalServiceUtil.updateDesignationMaster(this);
		}
	}

}