/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.master.model.impl;

import com.ax.hrms.master.model.DocumentTypeMaster;
import com.ax.hrms.master.model.DocumentTypeMasterModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the DocumentTypeMaster service. Represents a row in the &quot;ax_master_DocumentTypeMaster&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>DocumentTypeMasterModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DocumentTypeMasterImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DocumentTypeMasterImpl
 * @generated
 */
@JSON(strict = true)
public class DocumentTypeMasterModelImpl
	extends BaseModelImpl<DocumentTypeMaster>
	implements DocumentTypeMasterModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a document type master model instance should use the <code>DocumentTypeMaster</code> interface instead.
	 */
	public static final String TABLE_NAME = "ax_master_DocumentTypeMaster";

	public static final Object[][] TABLE_COLUMNS = {
		{"documentTypeMasterId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"createdBy", Types.BIGINT}, {"modifiedBy", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"documentTypeName", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("documentTypeMasterId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("documentTypeName", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ax_master_DocumentTypeMaster (documentTypeMasterId LONG not null primary key,companyId LONG,createdBy LONG,modifiedBy LONG,groupId LONG,createDate DATE null,modifiedDate DATE null,documentTypeName VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table ax_master_DocumentTypeMaster";

	public static final String ORDER_BY_JPQL =
		" ORDER BY documentTypeMaster.documentTypeMasterId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ax_master_DocumentTypeMaster.documentTypeMasterId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DOCUMENTTYPENAME_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DOCUMENTTYPEMASTERID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public DocumentTypeMasterModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _documentTypeMasterId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setDocumentTypeMasterId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _documentTypeMasterId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return DocumentTypeMaster.class;
	}

	@Override
	public String getModelClassName() {
		return DocumentTypeMaster.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<DocumentTypeMaster, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<DocumentTypeMaster, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DocumentTypeMaster, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((DocumentTypeMaster)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<DocumentTypeMaster, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<DocumentTypeMaster, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(DocumentTypeMaster)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<DocumentTypeMaster, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<DocumentTypeMaster, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<DocumentTypeMaster, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<DocumentTypeMaster, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<DocumentTypeMaster, Object>>();

			attributeGetterFunctions.put(
				"documentTypeMasterId",
				DocumentTypeMaster::getDocumentTypeMasterId);
			attributeGetterFunctions.put(
				"companyId", DocumentTypeMaster::getCompanyId);
			attributeGetterFunctions.put(
				"createdBy", DocumentTypeMaster::getCreatedBy);
			attributeGetterFunctions.put(
				"modifiedBy", DocumentTypeMaster::getModifiedBy);
			attributeGetterFunctions.put(
				"groupId", DocumentTypeMaster::getGroupId);
			attributeGetterFunctions.put(
				"createDate", DocumentTypeMaster::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", DocumentTypeMaster::getModifiedDate);
			attributeGetterFunctions.put(
				"documentTypeName", DocumentTypeMaster::getDocumentTypeName);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<DocumentTypeMaster, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<DocumentTypeMaster, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<DocumentTypeMaster, ?>>();

			attributeSetterBiConsumers.put(
				"documentTypeMasterId",
				(BiConsumer<DocumentTypeMaster, Long>)
					DocumentTypeMaster::setDocumentTypeMasterId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<DocumentTypeMaster, Long>)
					DocumentTypeMaster::setCompanyId);
			attributeSetterBiConsumers.put(
				"createdBy",
				(BiConsumer<DocumentTypeMaster, Long>)
					DocumentTypeMaster::setCreatedBy);
			attributeSetterBiConsumers.put(
				"modifiedBy",
				(BiConsumer<DocumentTypeMaster, Long>)
					DocumentTypeMaster::setModifiedBy);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<DocumentTypeMaster, Long>)
					DocumentTypeMaster::setGroupId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<DocumentTypeMaster, Date>)
					DocumentTypeMaster::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<DocumentTypeMaster, Date>)
					DocumentTypeMaster::setModifiedDate);
			attributeSetterBiConsumers.put(
				"documentTypeName",
				(BiConsumer<DocumentTypeMaster, String>)
					DocumentTypeMaster::setDocumentTypeName);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getDocumentTypeMasterId() {
		return _documentTypeMasterId;
	}

	@Override
	public void setDocumentTypeMasterId(long documentTypeMasterId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_documentTypeMasterId = documentTypeMasterId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getDocumentTypeName() {
		if (_documentTypeName == null) {
			return "";
		}
		else {
			return _documentTypeName;
		}
	}

	@Override
	public void setDocumentTypeName(String documentTypeName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_documentTypeName = documentTypeName;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalDocumentTypeName() {
		return getColumnOriginalValue("documentTypeName");
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), DocumentTypeMaster.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public DocumentTypeMaster toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, DocumentTypeMaster>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DocumentTypeMasterImpl documentTypeMasterImpl =
			new DocumentTypeMasterImpl();

		documentTypeMasterImpl.setDocumentTypeMasterId(
			getDocumentTypeMasterId());
		documentTypeMasterImpl.setCompanyId(getCompanyId());
		documentTypeMasterImpl.setCreatedBy(getCreatedBy());
		documentTypeMasterImpl.setModifiedBy(getModifiedBy());
		documentTypeMasterImpl.setGroupId(getGroupId());
		documentTypeMasterImpl.setCreateDate(getCreateDate());
		documentTypeMasterImpl.setModifiedDate(getModifiedDate());
		documentTypeMasterImpl.setDocumentTypeName(getDocumentTypeName());

		documentTypeMasterImpl.resetOriginalValues();

		return documentTypeMasterImpl;
	}

	@Override
	public DocumentTypeMaster cloneWithOriginalValues() {
		DocumentTypeMasterImpl documentTypeMasterImpl =
			new DocumentTypeMasterImpl();

		documentTypeMasterImpl.setDocumentTypeMasterId(
			this.<Long>getColumnOriginalValue("documentTypeMasterId"));
		documentTypeMasterImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		documentTypeMasterImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("createdBy"));
		documentTypeMasterImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modifiedBy"));
		documentTypeMasterImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		documentTypeMasterImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		documentTypeMasterImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		documentTypeMasterImpl.setDocumentTypeName(
			this.<String>getColumnOriginalValue("documentTypeName"));

		return documentTypeMasterImpl;
	}

	@Override
	public int compareTo(DocumentTypeMaster documentTypeMaster) {
		long primaryKey = documentTypeMaster.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof DocumentTypeMaster)) {
			return false;
		}

		DocumentTypeMaster documentTypeMaster = (DocumentTypeMaster)object;

		long primaryKey = documentTypeMaster.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<DocumentTypeMaster> toCacheModel() {
		DocumentTypeMasterCacheModel documentTypeMasterCacheModel =
			new DocumentTypeMasterCacheModel();

		documentTypeMasterCacheModel.documentTypeMasterId =
			getDocumentTypeMasterId();

		documentTypeMasterCacheModel.companyId = getCompanyId();

		documentTypeMasterCacheModel.createdBy = getCreatedBy();

		documentTypeMasterCacheModel.modifiedBy = getModifiedBy();

		documentTypeMasterCacheModel.groupId = getGroupId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			documentTypeMasterCacheModel.createDate = createDate.getTime();
		}
		else {
			documentTypeMasterCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			documentTypeMasterCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			documentTypeMasterCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		documentTypeMasterCacheModel.documentTypeName = getDocumentTypeName();

		String documentTypeName = documentTypeMasterCacheModel.documentTypeName;

		if ((documentTypeName != null) && (documentTypeName.length() == 0)) {
			documentTypeMasterCacheModel.documentTypeName = null;
		}

		return documentTypeMasterCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<DocumentTypeMaster, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<DocumentTypeMaster, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DocumentTypeMaster, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(DocumentTypeMaster)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, DocumentTypeMaster>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					DocumentTypeMaster.class, ModelWrapper.class);

	}

	private long _documentTypeMasterId;
	private long _companyId;
	private long _createdBy;
	private long _modifiedBy;
	private long _groupId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _documentTypeName;

	public <T> T getColumnValue(String columnName) {
		Function<DocumentTypeMaster, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((DocumentTypeMaster)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put(
			"documentTypeMasterId", _documentTypeMasterId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createdBy", _createdBy);
		_columnOriginalValues.put("modifiedBy", _modifiedBy);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("documentTypeName", _documentTypeName);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("documentTypeMasterId", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("createdBy", 4L);

		columnBitmasks.put("modifiedBy", 8L);

		columnBitmasks.put("groupId", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("documentTypeName", 128L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private DocumentTypeMaster _escapedModel;

}