/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.master.model.impl;

import com.ax.hrms.master.model.EducationLevelMaster;
import com.ax.hrms.master.model.EducationLevelMasterModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the EducationLevelMaster service. Represents a row in the &quot;ax_master_EducationLevelMaster&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>EducationLevelMasterModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EducationLevelMasterImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EducationLevelMasterImpl
 * @generated
 */
@JSON(strict = true)
public class EducationLevelMasterModelImpl
	extends BaseModelImpl<EducationLevelMaster>
	implements EducationLevelMasterModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a education level master model instance should use the <code>EducationLevelMaster</code> interface instead.
	 */
	public static final String TABLE_NAME = "ax_master_EducationLevelMaster";

	public static final Object[][] TABLE_COLUMNS = {
		{"educationLevelMasterId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"createdBy", Types.BIGINT}, {"modifiedBy", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"levelName", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("educationLevelMasterId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("levelName", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ax_master_EducationLevelMaster (educationLevelMasterId LONG not null primary key,companyId LONG,createdBy LONG,modifiedBy LONG,groupId LONG,createDate DATE null,modifiedDate DATE null,levelName VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table ax_master_EducationLevelMaster";

	public static final String ORDER_BY_JPQL =
		" ORDER BY educationLevelMaster.educationLevelMasterId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ax_master_EducationLevelMaster.educationLevelMasterId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LEVELNAME_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EDUCATIONLEVELMASTERID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public EducationLevelMasterModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _educationLevelMasterId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEducationLevelMasterId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _educationLevelMasterId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return EducationLevelMaster.class;
	}

	@Override
	public String getModelClassName() {
		return EducationLevelMaster.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<EducationLevelMaster, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<EducationLevelMaster, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EducationLevelMaster, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((EducationLevelMaster)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<EducationLevelMaster, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<EducationLevelMaster, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(EducationLevelMaster)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<EducationLevelMaster, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<EducationLevelMaster, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<EducationLevelMaster, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<EducationLevelMaster, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<EducationLevelMaster, Object>>();

			attributeGetterFunctions.put(
				"educationLevelMasterId",
				EducationLevelMaster::getEducationLevelMasterId);
			attributeGetterFunctions.put(
				"companyId", EducationLevelMaster::getCompanyId);
			attributeGetterFunctions.put(
				"createdBy", EducationLevelMaster::getCreatedBy);
			attributeGetterFunctions.put(
				"modifiedBy", EducationLevelMaster::getModifiedBy);
			attributeGetterFunctions.put(
				"groupId", EducationLevelMaster::getGroupId);
			attributeGetterFunctions.put(
				"createDate", EducationLevelMaster::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", EducationLevelMaster::getModifiedDate);
			attributeGetterFunctions.put(
				"levelName", EducationLevelMaster::getLevelName);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<EducationLevelMaster, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<EducationLevelMaster, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<EducationLevelMaster, ?>>();

			attributeSetterBiConsumers.put(
				"educationLevelMasterId",
				(BiConsumer<EducationLevelMaster, Long>)
					EducationLevelMaster::setEducationLevelMasterId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<EducationLevelMaster, Long>)
					EducationLevelMaster::setCompanyId);
			attributeSetterBiConsumers.put(
				"createdBy",
				(BiConsumer<EducationLevelMaster, Long>)
					EducationLevelMaster::setCreatedBy);
			attributeSetterBiConsumers.put(
				"modifiedBy",
				(BiConsumer<EducationLevelMaster, Long>)
					EducationLevelMaster::setModifiedBy);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<EducationLevelMaster, Long>)
					EducationLevelMaster::setGroupId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<EducationLevelMaster, Date>)
					EducationLevelMaster::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<EducationLevelMaster, Date>)
					EducationLevelMaster::setModifiedDate);
			attributeSetterBiConsumers.put(
				"levelName",
				(BiConsumer<EducationLevelMaster, String>)
					EducationLevelMaster::setLevelName);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getEducationLevelMasterId() {
		return _educationLevelMasterId;
	}

	@Override
	public void setEducationLevelMasterId(long educationLevelMasterId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_educationLevelMasterId = educationLevelMasterId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getLevelName() {
		if (_levelName == null) {
			return "";
		}
		else {
			return _levelName;
		}
	}

	@Override
	public void setLevelName(String levelName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_levelName = levelName;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalLevelName() {
		return getColumnOriginalValue("levelName");
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), EducationLevelMaster.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public EducationLevelMaster toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, EducationLevelMaster>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EducationLevelMasterImpl educationLevelMasterImpl =
			new EducationLevelMasterImpl();

		educationLevelMasterImpl.setEducationLevelMasterId(
			getEducationLevelMasterId());
		educationLevelMasterImpl.setCompanyId(getCompanyId());
		educationLevelMasterImpl.setCreatedBy(getCreatedBy());
		educationLevelMasterImpl.setModifiedBy(getModifiedBy());
		educationLevelMasterImpl.setGroupId(getGroupId());
		educationLevelMasterImpl.setCreateDate(getCreateDate());
		educationLevelMasterImpl.setModifiedDate(getModifiedDate());
		educationLevelMasterImpl.setLevelName(getLevelName());

		educationLevelMasterImpl.resetOriginalValues();

		return educationLevelMasterImpl;
	}

	@Override
	public EducationLevelMaster cloneWithOriginalValues() {
		EducationLevelMasterImpl educationLevelMasterImpl =
			new EducationLevelMasterImpl();

		educationLevelMasterImpl.setEducationLevelMasterId(
			this.<Long>getColumnOriginalValue("educationLevelMasterId"));
		educationLevelMasterImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		educationLevelMasterImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("createdBy"));
		educationLevelMasterImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modifiedBy"));
		educationLevelMasterImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		educationLevelMasterImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		educationLevelMasterImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		educationLevelMasterImpl.setLevelName(
			this.<String>getColumnOriginalValue("levelName"));

		return educationLevelMasterImpl;
	}

	@Override
	public int compareTo(EducationLevelMaster educationLevelMaster) {
		long primaryKey = educationLevelMaster.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof EducationLevelMaster)) {
			return false;
		}

		EducationLevelMaster educationLevelMaster =
			(EducationLevelMaster)object;

		long primaryKey = educationLevelMaster.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<EducationLevelMaster> toCacheModel() {
		EducationLevelMasterCacheModel educationLevelMasterCacheModel =
			new EducationLevelMasterCacheModel();

		educationLevelMasterCacheModel.educationLevelMasterId =
			getEducationLevelMasterId();

		educationLevelMasterCacheModel.companyId = getCompanyId();

		educationLevelMasterCacheModel.createdBy = getCreatedBy();

		educationLevelMasterCacheModel.modifiedBy = getModifiedBy();

		educationLevelMasterCacheModel.groupId = getGroupId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			educationLevelMasterCacheModel.createDate = createDate.getTime();
		}
		else {
			educationLevelMasterCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			educationLevelMasterCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			educationLevelMasterCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		educationLevelMasterCacheModel.levelName = getLevelName();

		String levelName = educationLevelMasterCacheModel.levelName;

		if ((levelName != null) && (levelName.length() == 0)) {
			educationLevelMasterCacheModel.levelName = null;
		}

		return educationLevelMasterCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<EducationLevelMaster, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<EducationLevelMaster, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EducationLevelMaster, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(EducationLevelMaster)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, EducationLevelMaster>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					EducationLevelMaster.class, ModelWrapper.class);

	}

	private long _educationLevelMasterId;
	private long _companyId;
	private long _createdBy;
	private long _modifiedBy;
	private long _groupId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _levelName;

	public <T> T getColumnValue(String columnName) {
		Function<EducationLevelMaster, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((EducationLevelMaster)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put(
			"educationLevelMasterId", _educationLevelMasterId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createdBy", _createdBy);
		_columnOriginalValues.put("modifiedBy", _modifiedBy);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("levelName", _levelName);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("educationLevelMasterId", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("createdBy", 4L);

		columnBitmasks.put("modifiedBy", 8L);

		columnBitmasks.put("groupId", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("levelName", 128L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private EducationLevelMaster _escapedModel;

}