/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.master.model.impl;

import com.ax.hrms.master.model.LeavePolicyMaster;
import com.ax.hrms.master.model.LeavePolicyMasterModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the LeavePolicyMaster service. Represents a row in the &quot;ax_master_LeavePolicyMaster&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>LeavePolicyMasterModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LeavePolicyMasterImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LeavePolicyMasterImpl
 * @generated
 */
@JSON(strict = true)
public class LeavePolicyMasterModelImpl
	extends BaseModelImpl<LeavePolicyMaster> implements LeavePolicyMasterModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a leave policy master model instance should use the <code>LeavePolicyMaster</code> interface instead.
	 */
	public static final String TABLE_NAME = "ax_master_LeavePolicyMaster";

	public static final Object[][] TABLE_COLUMNS = {
		{"leavePolicyMasterId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"createdBy", Types.BIGINT}, {"modifiedBy", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"description", Types.VARCHAR},
		{"accrualRate", Types.DOUBLE}, {"maximumBalance", Types.DOUBLE},
		{"leaveTypeMasterId", Types.BIGINT}, {"isCheckMax", Types.BOOLEAN},
		{"yearOfPolicy", Types.INTEGER}, {"isCarryForward", Types.BOOLEAN},
		{"isContinuous", Types.BOOLEAN}, {"eligibleAfterMonths", Types.INTEGER},
		{"isApplicableFloater", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("leavePolicyMasterId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("accrualRate", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("maximumBalance", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("leaveTypeMasterId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("isCheckMax", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("yearOfPolicy", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("isCarryForward", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("isContinuous", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("eligibleAfterMonths", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("isApplicableFloater", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ax_master_LeavePolicyMaster (leavePolicyMasterId LONG not null primary key,companyId LONG,createdBy LONG,modifiedBy LONG,groupId LONG,createDate DATE null,modifiedDate DATE null,description VARCHAR(75) null,accrualRate DOUBLE,maximumBalance DOUBLE,leaveTypeMasterId LONG,isCheckMax BOOLEAN,yearOfPolicy INTEGER,isCarryForward BOOLEAN,isContinuous BOOLEAN,eligibleAfterMonths INTEGER,isApplicableFloater BOOLEAN)";

	public static final String TABLE_SQL_DROP =
		"drop table ax_master_LeavePolicyMaster";

	public static final String ORDER_BY_JPQL =
		" ORDER BY leavePolicyMaster.leavePolicyMasterId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ax_master_LeavePolicyMaster.leavePolicyMasterId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ELIGIBLEAFTERMONTHS_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LEAVETYPEMASTERID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long YEAROFPOLICY_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LEAVEPOLICYMASTERID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public LeavePolicyMasterModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _leavePolicyMasterId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLeavePolicyMasterId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _leavePolicyMasterId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return LeavePolicyMaster.class;
	}

	@Override
	public String getModelClassName() {
		return LeavePolicyMaster.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<LeavePolicyMaster, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<LeavePolicyMaster, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LeavePolicyMaster, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((LeavePolicyMaster)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<LeavePolicyMaster, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<LeavePolicyMaster, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(LeavePolicyMaster)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<LeavePolicyMaster, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<LeavePolicyMaster, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<LeavePolicyMaster, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<LeavePolicyMaster, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<LeavePolicyMaster, Object>>();

			attributeGetterFunctions.put(
				"leavePolicyMasterId",
				LeavePolicyMaster::getLeavePolicyMasterId);
			attributeGetterFunctions.put(
				"companyId", LeavePolicyMaster::getCompanyId);
			attributeGetterFunctions.put(
				"createdBy", LeavePolicyMaster::getCreatedBy);
			attributeGetterFunctions.put(
				"modifiedBy", LeavePolicyMaster::getModifiedBy);
			attributeGetterFunctions.put(
				"groupId", LeavePolicyMaster::getGroupId);
			attributeGetterFunctions.put(
				"createDate", LeavePolicyMaster::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", LeavePolicyMaster::getModifiedDate);
			attributeGetterFunctions.put(
				"description", LeavePolicyMaster::getDescription);
			attributeGetterFunctions.put(
				"accrualRate", LeavePolicyMaster::getAccrualRate);
			attributeGetterFunctions.put(
				"maximumBalance", LeavePolicyMaster::getMaximumBalance);
			attributeGetterFunctions.put(
				"leaveTypeMasterId", LeavePolicyMaster::getLeaveTypeMasterId);
			attributeGetterFunctions.put(
				"isCheckMax", LeavePolicyMaster::getIsCheckMax);
			attributeGetterFunctions.put(
				"yearOfPolicy", LeavePolicyMaster::getYearOfPolicy);
			attributeGetterFunctions.put(
				"isCarryForward", LeavePolicyMaster::getIsCarryForward);
			attributeGetterFunctions.put(
				"isContinuous", LeavePolicyMaster::getIsContinuous);
			attributeGetterFunctions.put(
				"eligibleAfterMonths",
				LeavePolicyMaster::getEligibleAfterMonths);
			attributeGetterFunctions.put(
				"isApplicableFloater",
				LeavePolicyMaster::getIsApplicableFloater);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<LeavePolicyMaster, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<LeavePolicyMaster, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<LeavePolicyMaster, ?>>();

			attributeSetterBiConsumers.put(
				"leavePolicyMasterId",
				(BiConsumer<LeavePolicyMaster, Long>)
					LeavePolicyMaster::setLeavePolicyMasterId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<LeavePolicyMaster, Long>)
					LeavePolicyMaster::setCompanyId);
			attributeSetterBiConsumers.put(
				"createdBy",
				(BiConsumer<LeavePolicyMaster, Long>)
					LeavePolicyMaster::setCreatedBy);
			attributeSetterBiConsumers.put(
				"modifiedBy",
				(BiConsumer<LeavePolicyMaster, Long>)
					LeavePolicyMaster::setModifiedBy);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<LeavePolicyMaster, Long>)
					LeavePolicyMaster::setGroupId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<LeavePolicyMaster, Date>)
					LeavePolicyMaster::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<LeavePolicyMaster, Date>)
					LeavePolicyMaster::setModifiedDate);
			attributeSetterBiConsumers.put(
				"description",
				(BiConsumer<LeavePolicyMaster, String>)
					LeavePolicyMaster::setDescription);
			attributeSetterBiConsumers.put(
				"accrualRate",
				(BiConsumer<LeavePolicyMaster, Double>)
					LeavePolicyMaster::setAccrualRate);
			attributeSetterBiConsumers.put(
				"maximumBalance",
				(BiConsumer<LeavePolicyMaster, Double>)
					LeavePolicyMaster::setMaximumBalance);
			attributeSetterBiConsumers.put(
				"leaveTypeMasterId",
				(BiConsumer<LeavePolicyMaster, Long>)
					LeavePolicyMaster::setLeaveTypeMasterId);
			attributeSetterBiConsumers.put(
				"isCheckMax",
				(BiConsumer<LeavePolicyMaster, Boolean>)
					LeavePolicyMaster::setIsCheckMax);
			attributeSetterBiConsumers.put(
				"yearOfPolicy",
				(BiConsumer<LeavePolicyMaster, Integer>)
					LeavePolicyMaster::setYearOfPolicy);
			attributeSetterBiConsumers.put(
				"isCarryForward",
				(BiConsumer<LeavePolicyMaster, Boolean>)
					LeavePolicyMaster::setIsCarryForward);
			attributeSetterBiConsumers.put(
				"isContinuous",
				(BiConsumer<LeavePolicyMaster, Boolean>)
					LeavePolicyMaster::setIsContinuous);
			attributeSetterBiConsumers.put(
				"eligibleAfterMonths",
				(BiConsumer<LeavePolicyMaster, Integer>)
					LeavePolicyMaster::setEligibleAfterMonths);
			attributeSetterBiConsumers.put(
				"isApplicableFloater",
				(BiConsumer<LeavePolicyMaster, Boolean>)
					LeavePolicyMaster::setIsApplicableFloater);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getLeavePolicyMasterId() {
		return _leavePolicyMasterId;
	}

	@Override
	public void setLeavePolicyMasterId(long leavePolicyMasterId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_leavePolicyMasterId = leavePolicyMasterId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_description = description;
	}

	@JSON
	@Override
	public double getAccrualRate() {
		return _accrualRate;
	}

	@Override
	public void setAccrualRate(double accrualRate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_accrualRate = accrualRate;
	}

	@JSON
	@Override
	public double getMaximumBalance() {
		return _maximumBalance;
	}

	@Override
	public void setMaximumBalance(double maximumBalance) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_maximumBalance = maximumBalance;
	}

	@JSON
	@Override
	public long getLeaveTypeMasterId() {
		return _leaveTypeMasterId;
	}

	@Override
	public void setLeaveTypeMasterId(long leaveTypeMasterId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_leaveTypeMasterId = leaveTypeMasterId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalLeaveTypeMasterId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("leaveTypeMasterId"));
	}

	@JSON
	@Override
	public boolean getIsCheckMax() {
		return _isCheckMax;
	}

	@JSON
	@Override
	public boolean isIsCheckMax() {
		return _isCheckMax;
	}

	@Override
	public void setIsCheckMax(boolean isCheckMax) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_isCheckMax = isCheckMax;
	}

	@JSON
	@Override
	public int getYearOfPolicy() {
		return _yearOfPolicy;
	}

	@Override
	public void setYearOfPolicy(int yearOfPolicy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_yearOfPolicy = yearOfPolicy;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalYearOfPolicy() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("yearOfPolicy"));
	}

	@JSON
	@Override
	public boolean getIsCarryForward() {
		return _isCarryForward;
	}

	@JSON
	@Override
	public boolean isIsCarryForward() {
		return _isCarryForward;
	}

	@Override
	public void setIsCarryForward(boolean isCarryForward) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_isCarryForward = isCarryForward;
	}

	@JSON
	@Override
	public boolean getIsContinuous() {
		return _isContinuous;
	}

	@JSON
	@Override
	public boolean isIsContinuous() {
		return _isContinuous;
	}

	@Override
	public void setIsContinuous(boolean isContinuous) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_isContinuous = isContinuous;
	}

	@JSON
	@Override
	public int getEligibleAfterMonths() {
		return _eligibleAfterMonths;
	}

	@Override
	public void setEligibleAfterMonths(int eligibleAfterMonths) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_eligibleAfterMonths = eligibleAfterMonths;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalEligibleAfterMonths() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("eligibleAfterMonths"));
	}

	@JSON
	@Override
	public boolean getIsApplicableFloater() {
		return _isApplicableFloater;
	}

	@JSON
	@Override
	public boolean isIsApplicableFloater() {
		return _isApplicableFloater;
	}

	@Override
	public void setIsApplicableFloater(boolean isApplicableFloater) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_isApplicableFloater = isApplicableFloater;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), LeavePolicyMaster.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public LeavePolicyMaster toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, LeavePolicyMaster>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LeavePolicyMasterImpl leavePolicyMasterImpl =
			new LeavePolicyMasterImpl();

		leavePolicyMasterImpl.setLeavePolicyMasterId(getLeavePolicyMasterId());
		leavePolicyMasterImpl.setCompanyId(getCompanyId());
		leavePolicyMasterImpl.setCreatedBy(getCreatedBy());
		leavePolicyMasterImpl.setModifiedBy(getModifiedBy());
		leavePolicyMasterImpl.setGroupId(getGroupId());
		leavePolicyMasterImpl.setCreateDate(getCreateDate());
		leavePolicyMasterImpl.setModifiedDate(getModifiedDate());
		leavePolicyMasterImpl.setDescription(getDescription());
		leavePolicyMasterImpl.setAccrualRate(getAccrualRate());
		leavePolicyMasterImpl.setMaximumBalance(getMaximumBalance());
		leavePolicyMasterImpl.setLeaveTypeMasterId(getLeaveTypeMasterId());
		leavePolicyMasterImpl.setIsCheckMax(isIsCheckMax());
		leavePolicyMasterImpl.setYearOfPolicy(getYearOfPolicy());
		leavePolicyMasterImpl.setIsCarryForward(isIsCarryForward());
		leavePolicyMasterImpl.setIsContinuous(isIsContinuous());
		leavePolicyMasterImpl.setEligibleAfterMonths(getEligibleAfterMonths());
		leavePolicyMasterImpl.setIsApplicableFloater(isIsApplicableFloater());

		leavePolicyMasterImpl.resetOriginalValues();

		return leavePolicyMasterImpl;
	}

	@Override
	public LeavePolicyMaster cloneWithOriginalValues() {
		LeavePolicyMasterImpl leavePolicyMasterImpl =
			new LeavePolicyMasterImpl();

		leavePolicyMasterImpl.setLeavePolicyMasterId(
			this.<Long>getColumnOriginalValue("leavePolicyMasterId"));
		leavePolicyMasterImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		leavePolicyMasterImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("createdBy"));
		leavePolicyMasterImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modifiedBy"));
		leavePolicyMasterImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		leavePolicyMasterImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		leavePolicyMasterImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		leavePolicyMasterImpl.setDescription(
			this.<String>getColumnOriginalValue("description"));
		leavePolicyMasterImpl.setAccrualRate(
			this.<Double>getColumnOriginalValue("accrualRate"));
		leavePolicyMasterImpl.setMaximumBalance(
			this.<Double>getColumnOriginalValue("maximumBalance"));
		leavePolicyMasterImpl.setLeaveTypeMasterId(
			this.<Long>getColumnOriginalValue("leaveTypeMasterId"));
		leavePolicyMasterImpl.setIsCheckMax(
			this.<Boolean>getColumnOriginalValue("isCheckMax"));
		leavePolicyMasterImpl.setYearOfPolicy(
			this.<Integer>getColumnOriginalValue("yearOfPolicy"));
		leavePolicyMasterImpl.setIsCarryForward(
			this.<Boolean>getColumnOriginalValue("isCarryForward"));
		leavePolicyMasterImpl.setIsContinuous(
			this.<Boolean>getColumnOriginalValue("isContinuous"));
		leavePolicyMasterImpl.setEligibleAfterMonths(
			this.<Integer>getColumnOriginalValue("eligibleAfterMonths"));
		leavePolicyMasterImpl.setIsApplicableFloater(
			this.<Boolean>getColumnOriginalValue("isApplicableFloater"));

		return leavePolicyMasterImpl;
	}

	@Override
	public int compareTo(LeavePolicyMaster leavePolicyMaster) {
		long primaryKey = leavePolicyMaster.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof LeavePolicyMaster)) {
			return false;
		}

		LeavePolicyMaster leavePolicyMaster = (LeavePolicyMaster)object;

		long primaryKey = leavePolicyMaster.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<LeavePolicyMaster> toCacheModel() {
		LeavePolicyMasterCacheModel leavePolicyMasterCacheModel =
			new LeavePolicyMasterCacheModel();

		leavePolicyMasterCacheModel.leavePolicyMasterId =
			getLeavePolicyMasterId();

		leavePolicyMasterCacheModel.companyId = getCompanyId();

		leavePolicyMasterCacheModel.createdBy = getCreatedBy();

		leavePolicyMasterCacheModel.modifiedBy = getModifiedBy();

		leavePolicyMasterCacheModel.groupId = getGroupId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			leavePolicyMasterCacheModel.createDate = createDate.getTime();
		}
		else {
			leavePolicyMasterCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			leavePolicyMasterCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			leavePolicyMasterCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		leavePolicyMasterCacheModel.description = getDescription();

		String description = leavePolicyMasterCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			leavePolicyMasterCacheModel.description = null;
		}

		leavePolicyMasterCacheModel.accrualRate = getAccrualRate();

		leavePolicyMasterCacheModel.maximumBalance = getMaximumBalance();

		leavePolicyMasterCacheModel.leaveTypeMasterId = getLeaveTypeMasterId();

		leavePolicyMasterCacheModel.isCheckMax = isIsCheckMax();

		leavePolicyMasterCacheModel.yearOfPolicy = getYearOfPolicy();

		leavePolicyMasterCacheModel.isCarryForward = isIsCarryForward();

		leavePolicyMasterCacheModel.isContinuous = isIsContinuous();

		leavePolicyMasterCacheModel.eligibleAfterMonths =
			getEligibleAfterMonths();

		leavePolicyMasterCacheModel.isApplicableFloater =
			isIsApplicableFloater();

		return leavePolicyMasterCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<LeavePolicyMaster, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<LeavePolicyMaster, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LeavePolicyMaster, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(LeavePolicyMaster)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, LeavePolicyMaster>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					LeavePolicyMaster.class, ModelWrapper.class);

	}

	private long _leavePolicyMasterId;
	private long _companyId;
	private long _createdBy;
	private long _modifiedBy;
	private long _groupId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _description;
	private double _accrualRate;
	private double _maximumBalance;
	private long _leaveTypeMasterId;
	private boolean _isCheckMax;
	private int _yearOfPolicy;
	private boolean _isCarryForward;
	private boolean _isContinuous;
	private int _eligibleAfterMonths;
	private boolean _isApplicableFloater;

	public <T> T getColumnValue(String columnName) {
		Function<LeavePolicyMaster, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((LeavePolicyMaster)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("leavePolicyMasterId", _leavePolicyMasterId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createdBy", _createdBy);
		_columnOriginalValues.put("modifiedBy", _modifiedBy);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("description", _description);
		_columnOriginalValues.put("accrualRate", _accrualRate);
		_columnOriginalValues.put("maximumBalance", _maximumBalance);
		_columnOriginalValues.put("leaveTypeMasterId", _leaveTypeMasterId);
		_columnOriginalValues.put("isCheckMax", _isCheckMax);
		_columnOriginalValues.put("yearOfPolicy", _yearOfPolicy);
		_columnOriginalValues.put("isCarryForward", _isCarryForward);
		_columnOriginalValues.put("isContinuous", _isContinuous);
		_columnOriginalValues.put("eligibleAfterMonths", _eligibleAfterMonths);
		_columnOriginalValues.put("isApplicableFloater", _isApplicableFloater);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("leavePolicyMasterId", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("createdBy", 4L);

		columnBitmasks.put("modifiedBy", 8L);

		columnBitmasks.put("groupId", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("description", 128L);

		columnBitmasks.put("accrualRate", 256L);

		columnBitmasks.put("maximumBalance", 512L);

		columnBitmasks.put("leaveTypeMasterId", 1024L);

		columnBitmasks.put("isCheckMax", 2048L);

		columnBitmasks.put("yearOfPolicy", 4096L);

		columnBitmasks.put("isCarryForward", 8192L);

		columnBitmasks.put("isContinuous", 16384L);

		columnBitmasks.put("eligibleAfterMonths", 32768L);

		columnBitmasks.put("isApplicableFloater", 65536L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private LeavePolicyMaster _escapedModel;

}