/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.master.model.impl;

import com.ax.hrms.master.model.LeaveCompensatoryStatusMaster;
import com.ax.hrms.master.model.LeaveCompensatoryStatusMasterModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the LeaveCompensatoryStatusMaster service. Represents a row in the &quot;ax_master_LeaveCompensatoryStatusMaster&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>LeaveCompensatoryStatusMasterModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LeaveCompensatoryStatusMasterImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LeaveCompensatoryStatusMasterImpl
 * @generated
 */
@JSON(strict = true)
public class LeaveCompensatoryStatusMasterModelImpl
	extends BaseModelImpl<LeaveCompensatoryStatusMaster>
	implements LeaveCompensatoryStatusMasterModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a leave compensatory status master model instance should use the <code>LeaveCompensatoryStatusMaster</code> interface instead.
	 */
	public static final String TABLE_NAME =
		"ax_master_LeaveCompensatoryStatusMaster";

	public static final Object[][] TABLE_COLUMNS = {
		{"leaveCompensatoryStatusMasterId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"createdBy", Types.BIGINT},
		{"modifiedBy", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"leaveCompensatoryStatus", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("leaveCompensatoryStatusMasterId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("leaveCompensatoryStatus", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ax_master_LeaveCompensatoryStatusMaster (leaveCompensatoryStatusMasterId LONG not null primary key,companyId LONG,createdBy LONG,modifiedBy LONG,groupId LONG,createDate DATE null,modifiedDate DATE null,leaveCompensatoryStatus VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table ax_master_LeaveCompensatoryStatusMaster";

	public static final String ORDER_BY_JPQL =
		" ORDER BY leaveCompensatoryStatusMaster.leaveCompensatoryStatusMasterId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ax_master_LeaveCompensatoryStatusMaster.leaveCompensatoryStatusMasterId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LEAVECOMPENSATORYSTATUS_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LEAVECOMPENSATORYSTATUSMASTERID_COLUMN_BITMASK =
		2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public LeaveCompensatoryStatusMasterModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _leaveCompensatoryStatusMasterId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLeaveCompensatoryStatusMasterId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _leaveCompensatoryStatusMasterId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return LeaveCompensatoryStatusMaster.class;
	}

	@Override
	public String getModelClassName() {
		return LeaveCompensatoryStatusMaster.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<LeaveCompensatoryStatusMaster, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<LeaveCompensatoryStatusMaster, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LeaveCompensatoryStatusMaster, Object>
				attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply(
					(LeaveCompensatoryStatusMaster)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<LeaveCompensatoryStatusMaster, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<LeaveCompensatoryStatusMaster, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(LeaveCompensatoryStatusMaster)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<LeaveCompensatoryStatusMaster, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<LeaveCompensatoryStatusMaster, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map
			<String, Function<LeaveCompensatoryStatusMaster, Object>>
				_attributeGetterFunctions;

		static {
			Map<String, Function<LeaveCompensatoryStatusMaster, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String,
						 Function<LeaveCompensatoryStatusMaster, Object>>();

			attributeGetterFunctions.put(
				"leaveCompensatoryStatusMasterId",
				LeaveCompensatoryStatusMaster::
					getLeaveCompensatoryStatusMasterId);
			attributeGetterFunctions.put(
				"companyId", LeaveCompensatoryStatusMaster::getCompanyId);
			attributeGetterFunctions.put(
				"createdBy", LeaveCompensatoryStatusMaster::getCreatedBy);
			attributeGetterFunctions.put(
				"modifiedBy", LeaveCompensatoryStatusMaster::getModifiedBy);
			attributeGetterFunctions.put(
				"groupId", LeaveCompensatoryStatusMaster::getGroupId);
			attributeGetterFunctions.put(
				"createDate", LeaveCompensatoryStatusMaster::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", LeaveCompensatoryStatusMaster::getModifiedDate);
			attributeGetterFunctions.put(
				"leaveCompensatoryStatus",
				LeaveCompensatoryStatusMaster::getLeaveCompensatoryStatus);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<LeaveCompensatoryStatusMaster, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<LeaveCompensatoryStatusMaster, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String,
						 BiConsumer<LeaveCompensatoryStatusMaster, ?>>();

			attributeSetterBiConsumers.put(
				"leaveCompensatoryStatusMasterId",
				(BiConsumer<LeaveCompensatoryStatusMaster, Long>)
					LeaveCompensatoryStatusMaster::
						setLeaveCompensatoryStatusMasterId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<LeaveCompensatoryStatusMaster, Long>)
					LeaveCompensatoryStatusMaster::setCompanyId);
			attributeSetterBiConsumers.put(
				"createdBy",
				(BiConsumer<LeaveCompensatoryStatusMaster, Long>)
					LeaveCompensatoryStatusMaster::setCreatedBy);
			attributeSetterBiConsumers.put(
				"modifiedBy",
				(BiConsumer<LeaveCompensatoryStatusMaster, Long>)
					LeaveCompensatoryStatusMaster::setModifiedBy);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<LeaveCompensatoryStatusMaster, Long>)
					LeaveCompensatoryStatusMaster::setGroupId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<LeaveCompensatoryStatusMaster, Date>)
					LeaveCompensatoryStatusMaster::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<LeaveCompensatoryStatusMaster, Date>)
					LeaveCompensatoryStatusMaster::setModifiedDate);
			attributeSetterBiConsumers.put(
				"leaveCompensatoryStatus",
				(BiConsumer<LeaveCompensatoryStatusMaster, String>)
					LeaveCompensatoryStatusMaster::setLeaveCompensatoryStatus);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getLeaveCompensatoryStatusMasterId() {
		return _leaveCompensatoryStatusMasterId;
	}

	@Override
	public void setLeaveCompensatoryStatusMasterId(
		long leaveCompensatoryStatusMasterId) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_leaveCompensatoryStatusMasterId = leaveCompensatoryStatusMasterId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalLeaveCompensatoryStatusMasterId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue(
				"leaveCompensatoryStatusMasterId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getLeaveCompensatoryStatus() {
		if (_leaveCompensatoryStatus == null) {
			return "";
		}
		else {
			return _leaveCompensatoryStatus;
		}
	}

	@Override
	public void setLeaveCompensatoryStatus(String leaveCompensatoryStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_leaveCompensatoryStatus = leaveCompensatoryStatus;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalLeaveCompensatoryStatus() {
		return getColumnOriginalValue("leaveCompensatoryStatus");
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), LeaveCompensatoryStatusMaster.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public LeaveCompensatoryStatusMaster toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, LeaveCompensatoryStatusMaster>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LeaveCompensatoryStatusMasterImpl leaveCompensatoryStatusMasterImpl =
			new LeaveCompensatoryStatusMasterImpl();

		leaveCompensatoryStatusMasterImpl.setLeaveCompensatoryStatusMasterId(
			getLeaveCompensatoryStatusMasterId());
		leaveCompensatoryStatusMasterImpl.setCompanyId(getCompanyId());
		leaveCompensatoryStatusMasterImpl.setCreatedBy(getCreatedBy());
		leaveCompensatoryStatusMasterImpl.setModifiedBy(getModifiedBy());
		leaveCompensatoryStatusMasterImpl.setGroupId(getGroupId());
		leaveCompensatoryStatusMasterImpl.setCreateDate(getCreateDate());
		leaveCompensatoryStatusMasterImpl.setModifiedDate(getModifiedDate());
		leaveCompensatoryStatusMasterImpl.setLeaveCompensatoryStatus(
			getLeaveCompensatoryStatus());

		leaveCompensatoryStatusMasterImpl.resetOriginalValues();

		return leaveCompensatoryStatusMasterImpl;
	}

	@Override
	public LeaveCompensatoryStatusMaster cloneWithOriginalValues() {
		LeaveCompensatoryStatusMasterImpl leaveCompensatoryStatusMasterImpl =
			new LeaveCompensatoryStatusMasterImpl();

		leaveCompensatoryStatusMasterImpl.setLeaveCompensatoryStatusMasterId(
			this.<Long>getColumnOriginalValue(
				"leaveCompensatoryStatusMasterId"));
		leaveCompensatoryStatusMasterImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		leaveCompensatoryStatusMasterImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("createdBy"));
		leaveCompensatoryStatusMasterImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modifiedBy"));
		leaveCompensatoryStatusMasterImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		leaveCompensatoryStatusMasterImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		leaveCompensatoryStatusMasterImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		leaveCompensatoryStatusMasterImpl.setLeaveCompensatoryStatus(
			this.<String>getColumnOriginalValue("leaveCompensatoryStatus"));

		return leaveCompensatoryStatusMasterImpl;
	}

	@Override
	public int compareTo(
		LeaveCompensatoryStatusMaster leaveCompensatoryStatusMaster) {

		long primaryKey = leaveCompensatoryStatusMaster.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof LeaveCompensatoryStatusMaster)) {
			return false;
		}

		LeaveCompensatoryStatusMaster leaveCompensatoryStatusMaster =
			(LeaveCompensatoryStatusMaster)object;

		long primaryKey = leaveCompensatoryStatusMaster.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<LeaveCompensatoryStatusMaster> toCacheModel() {
		LeaveCompensatoryStatusMasterCacheModel
			leaveCompensatoryStatusMasterCacheModel =
				new LeaveCompensatoryStatusMasterCacheModel();

		leaveCompensatoryStatusMasterCacheModel.
			leaveCompensatoryStatusMasterId =
				getLeaveCompensatoryStatusMasterId();

		leaveCompensatoryStatusMasterCacheModel.companyId = getCompanyId();

		leaveCompensatoryStatusMasterCacheModel.createdBy = getCreatedBy();

		leaveCompensatoryStatusMasterCacheModel.modifiedBy = getModifiedBy();

		leaveCompensatoryStatusMasterCacheModel.groupId = getGroupId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			leaveCompensatoryStatusMasterCacheModel.createDate =
				createDate.getTime();
		}
		else {
			leaveCompensatoryStatusMasterCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			leaveCompensatoryStatusMasterCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			leaveCompensatoryStatusMasterCacheModel.modifiedDate =
				Long.MIN_VALUE;
		}

		leaveCompensatoryStatusMasterCacheModel.leaveCompensatoryStatus =
			getLeaveCompensatoryStatus();

		String leaveCompensatoryStatus =
			leaveCompensatoryStatusMasterCacheModel.leaveCompensatoryStatus;

		if ((leaveCompensatoryStatus != null) &&
			(leaveCompensatoryStatus.length() == 0)) {

			leaveCompensatoryStatusMasterCacheModel.leaveCompensatoryStatus =
				null;
		}

		return leaveCompensatoryStatusMasterCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<LeaveCompensatoryStatusMaster, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<LeaveCompensatoryStatusMaster, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LeaveCompensatoryStatusMaster, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(LeaveCompensatoryStatusMaster)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, LeaveCompensatoryStatusMaster>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						LeaveCompensatoryStatusMaster.class,
						ModelWrapper.class);

	}

	private long _leaveCompensatoryStatusMasterId;
	private long _companyId;
	private long _createdBy;
	private long _modifiedBy;
	private long _groupId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _leaveCompensatoryStatus;

	public <T> T getColumnValue(String columnName) {
		Function<LeaveCompensatoryStatusMaster, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((LeaveCompensatoryStatusMaster)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put(
			"leaveCompensatoryStatusMasterId",
			_leaveCompensatoryStatusMasterId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createdBy", _createdBy);
		_columnOriginalValues.put("modifiedBy", _modifiedBy);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put(
			"leaveCompensatoryStatus", _leaveCompensatoryStatus);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("leaveCompensatoryStatusMasterId", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("createdBy", 4L);

		columnBitmasks.put("modifiedBy", 8L);

		columnBitmasks.put("groupId", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("leaveCompensatoryStatus", 128L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private LeaveCompensatoryStatusMaster _escapedModel;

}