/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.master.model.impl;

import com.ax.hrms.master.model.LeaveTypeMaster;
import com.ax.hrms.master.model.LeaveTypeMasterModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the LeaveTypeMaster service. Represents a row in the &quot;ax_master_LeaveTypeMaster&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>LeaveTypeMasterModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LeaveTypeMasterImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LeaveTypeMasterImpl
 * @generated
 */
@JSON(strict = true)
public class LeaveTypeMasterModelImpl
	extends BaseModelImpl<LeaveTypeMaster> implements LeaveTypeMasterModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a leave type master model instance should use the <code>LeaveTypeMaster</code> interface instead.
	 */
	public static final String TABLE_NAME = "ax_master_LeaveTypeMaster";

	public static final Object[][] TABLE_COLUMNS = {
		{"leaveTypeMasterId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"createdBy", Types.BIGINT}, {"modifiedBy", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"leaveTypeName", Types.VARCHAR},
		{"description", Types.VARCHAR}, {"isActive", Types.BOOLEAN},
		{"isAppearForAll", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("leaveTypeMasterId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("leaveTypeName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("isActive", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("isAppearForAll", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ax_master_LeaveTypeMaster (leaveTypeMasterId LONG not null primary key,companyId LONG,createdBy LONG,modifiedBy LONG,groupId LONG,createDate DATE null,modifiedDate DATE null,leaveTypeName VARCHAR(75) null,description VARCHAR(250) null,isActive BOOLEAN,isAppearForAll BOOLEAN)";

	public static final String TABLE_SQL_DROP =
		"drop table ax_master_LeaveTypeMaster";

	public static final String ORDER_BY_JPQL =
		" ORDER BY leaveTypeMaster.leaveTypeMasterId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ax_master_LeaveTypeMaster.leaveTypeMasterId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ISACTIVE_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ISAPPEARFORALL_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LEAVETYPEMASTERID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LEAVETYPENAME_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public LeaveTypeMasterModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _leaveTypeMasterId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLeaveTypeMasterId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _leaveTypeMasterId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return LeaveTypeMaster.class;
	}

	@Override
	public String getModelClassName() {
		return LeaveTypeMaster.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<LeaveTypeMaster, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<LeaveTypeMaster, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LeaveTypeMaster, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((LeaveTypeMaster)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<LeaveTypeMaster, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<LeaveTypeMaster, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(LeaveTypeMaster)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<LeaveTypeMaster, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<LeaveTypeMaster, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<LeaveTypeMaster, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<LeaveTypeMaster, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<LeaveTypeMaster, Object>>();

			attributeGetterFunctions.put(
				"leaveTypeMasterId", LeaveTypeMaster::getLeaveTypeMasterId);
			attributeGetterFunctions.put(
				"companyId", LeaveTypeMaster::getCompanyId);
			attributeGetterFunctions.put(
				"createdBy", LeaveTypeMaster::getCreatedBy);
			attributeGetterFunctions.put(
				"modifiedBy", LeaveTypeMaster::getModifiedBy);
			attributeGetterFunctions.put(
				"groupId", LeaveTypeMaster::getGroupId);
			attributeGetterFunctions.put(
				"createDate", LeaveTypeMaster::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", LeaveTypeMaster::getModifiedDate);
			attributeGetterFunctions.put(
				"leaveTypeName", LeaveTypeMaster::getLeaveTypeName);
			attributeGetterFunctions.put(
				"description", LeaveTypeMaster::getDescription);
			attributeGetterFunctions.put(
				"isActive", LeaveTypeMaster::getIsActive);
			attributeGetterFunctions.put(
				"isAppearForAll", LeaveTypeMaster::getIsAppearForAll);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<LeaveTypeMaster, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<LeaveTypeMaster, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<LeaveTypeMaster, ?>>();

			attributeSetterBiConsumers.put(
				"leaveTypeMasterId",
				(BiConsumer<LeaveTypeMaster, Long>)
					LeaveTypeMaster::setLeaveTypeMasterId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<LeaveTypeMaster, Long>)
					LeaveTypeMaster::setCompanyId);
			attributeSetterBiConsumers.put(
				"createdBy",
				(BiConsumer<LeaveTypeMaster, Long>)
					LeaveTypeMaster::setCreatedBy);
			attributeSetterBiConsumers.put(
				"modifiedBy",
				(BiConsumer<LeaveTypeMaster, Long>)
					LeaveTypeMaster::setModifiedBy);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<LeaveTypeMaster, Long>)LeaveTypeMaster::setGroupId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<LeaveTypeMaster, Date>)
					LeaveTypeMaster::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<LeaveTypeMaster, Date>)
					LeaveTypeMaster::setModifiedDate);
			attributeSetterBiConsumers.put(
				"leaveTypeName",
				(BiConsumer<LeaveTypeMaster, String>)
					LeaveTypeMaster::setLeaveTypeName);
			attributeSetterBiConsumers.put(
				"description",
				(BiConsumer<LeaveTypeMaster, String>)
					LeaveTypeMaster::setDescription);
			attributeSetterBiConsumers.put(
				"isActive",
				(BiConsumer<LeaveTypeMaster, Boolean>)
					LeaveTypeMaster::setIsActive);
			attributeSetterBiConsumers.put(
				"isAppearForAll",
				(BiConsumer<LeaveTypeMaster, Boolean>)
					LeaveTypeMaster::setIsAppearForAll);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getLeaveTypeMasterId() {
		return _leaveTypeMasterId;
	}

	@Override
	public void setLeaveTypeMasterId(long leaveTypeMasterId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_leaveTypeMasterId = leaveTypeMasterId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalLeaveTypeMasterId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("leaveTypeMasterId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getLeaveTypeName() {
		if (_leaveTypeName == null) {
			return "";
		}
		else {
			return _leaveTypeName;
		}
	}

	@Override
	public void setLeaveTypeName(String leaveTypeName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_leaveTypeName = leaveTypeName;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalLeaveTypeName() {
		return getColumnOriginalValue("leaveTypeName");
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_description = description;
	}

	@JSON
	@Override
	public boolean getIsActive() {
		return _isActive;
	}

	@JSON
	@Override
	public boolean isIsActive() {
		return _isActive;
	}

	@Override
	public void setIsActive(boolean isActive) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_isActive = isActive;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public boolean getOriginalIsActive() {
		return GetterUtil.getBoolean(
			this.<Boolean>getColumnOriginalValue("isActive"));
	}

	@JSON
	@Override
	public boolean getIsAppearForAll() {
		return _isAppearForAll;
	}

	@JSON
	@Override
	public boolean isIsAppearForAll() {
		return _isAppearForAll;
	}

	@Override
	public void setIsAppearForAll(boolean isAppearForAll) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_isAppearForAll = isAppearForAll;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public boolean getOriginalIsAppearForAll() {
		return GetterUtil.getBoolean(
			this.<Boolean>getColumnOriginalValue("isAppearForAll"));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), LeaveTypeMaster.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public LeaveTypeMaster toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, LeaveTypeMaster>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LeaveTypeMasterImpl leaveTypeMasterImpl = new LeaveTypeMasterImpl();

		leaveTypeMasterImpl.setLeaveTypeMasterId(getLeaveTypeMasterId());
		leaveTypeMasterImpl.setCompanyId(getCompanyId());
		leaveTypeMasterImpl.setCreatedBy(getCreatedBy());
		leaveTypeMasterImpl.setModifiedBy(getModifiedBy());
		leaveTypeMasterImpl.setGroupId(getGroupId());
		leaveTypeMasterImpl.setCreateDate(getCreateDate());
		leaveTypeMasterImpl.setModifiedDate(getModifiedDate());
		leaveTypeMasterImpl.setLeaveTypeName(getLeaveTypeName());
		leaveTypeMasterImpl.setDescription(getDescription());
		leaveTypeMasterImpl.setIsActive(isIsActive());
		leaveTypeMasterImpl.setIsAppearForAll(isIsAppearForAll());

		leaveTypeMasterImpl.resetOriginalValues();

		return leaveTypeMasterImpl;
	}

	@Override
	public LeaveTypeMaster cloneWithOriginalValues() {
		LeaveTypeMasterImpl leaveTypeMasterImpl = new LeaveTypeMasterImpl();

		leaveTypeMasterImpl.setLeaveTypeMasterId(
			this.<Long>getColumnOriginalValue("leaveTypeMasterId"));
		leaveTypeMasterImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		leaveTypeMasterImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("createdBy"));
		leaveTypeMasterImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modifiedBy"));
		leaveTypeMasterImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		leaveTypeMasterImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		leaveTypeMasterImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		leaveTypeMasterImpl.setLeaveTypeName(
			this.<String>getColumnOriginalValue("leaveTypeName"));
		leaveTypeMasterImpl.setDescription(
			this.<String>getColumnOriginalValue("description"));
		leaveTypeMasterImpl.setIsActive(
			this.<Boolean>getColumnOriginalValue("isActive"));
		leaveTypeMasterImpl.setIsAppearForAll(
			this.<Boolean>getColumnOriginalValue("isAppearForAll"));

		return leaveTypeMasterImpl;
	}

	@Override
	public int compareTo(LeaveTypeMaster leaveTypeMaster) {
		long primaryKey = leaveTypeMaster.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof LeaveTypeMaster)) {
			return false;
		}

		LeaveTypeMaster leaveTypeMaster = (LeaveTypeMaster)object;

		long primaryKey = leaveTypeMaster.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<LeaveTypeMaster> toCacheModel() {
		LeaveTypeMasterCacheModel leaveTypeMasterCacheModel =
			new LeaveTypeMasterCacheModel();

		leaveTypeMasterCacheModel.leaveTypeMasterId = getLeaveTypeMasterId();

		leaveTypeMasterCacheModel.companyId = getCompanyId();

		leaveTypeMasterCacheModel.createdBy = getCreatedBy();

		leaveTypeMasterCacheModel.modifiedBy = getModifiedBy();

		leaveTypeMasterCacheModel.groupId = getGroupId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			leaveTypeMasterCacheModel.createDate = createDate.getTime();
		}
		else {
			leaveTypeMasterCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			leaveTypeMasterCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			leaveTypeMasterCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		leaveTypeMasterCacheModel.leaveTypeName = getLeaveTypeName();

		String leaveTypeName = leaveTypeMasterCacheModel.leaveTypeName;

		if ((leaveTypeName != null) && (leaveTypeName.length() == 0)) {
			leaveTypeMasterCacheModel.leaveTypeName = null;
		}

		leaveTypeMasterCacheModel.description = getDescription();

		String description = leaveTypeMasterCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			leaveTypeMasterCacheModel.description = null;
		}

		leaveTypeMasterCacheModel.isActive = isIsActive();

		leaveTypeMasterCacheModel.isAppearForAll = isIsAppearForAll();

		return leaveTypeMasterCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<LeaveTypeMaster, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<LeaveTypeMaster, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LeaveTypeMaster, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((LeaveTypeMaster)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, LeaveTypeMaster>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					LeaveTypeMaster.class, ModelWrapper.class);

	}

	private long _leaveTypeMasterId;
	private long _companyId;
	private long _createdBy;
	private long _modifiedBy;
	private long _groupId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _leaveTypeName;
	private String _description;
	private boolean _isActive;
	private boolean _isAppearForAll;

	public <T> T getColumnValue(String columnName) {
		Function<LeaveTypeMaster, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((LeaveTypeMaster)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("leaveTypeMasterId", _leaveTypeMasterId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createdBy", _createdBy);
		_columnOriginalValues.put("modifiedBy", _modifiedBy);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("leaveTypeName", _leaveTypeName);
		_columnOriginalValues.put("description", _description);
		_columnOriginalValues.put("isActive", _isActive);
		_columnOriginalValues.put("isAppearForAll", _isAppearForAll);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("leaveTypeMasterId", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("createdBy", 4L);

		columnBitmasks.put("modifiedBy", 8L);

		columnBitmasks.put("groupId", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("leaveTypeName", 128L);

		columnBitmasks.put("description", 256L);

		columnBitmasks.put("isActive", 512L);

		columnBitmasks.put("isAppearForAll", 1024L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private LeaveTypeMaster _escapedModel;

}