/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.master.model.impl;

import com.ax.hrms.master.model.PolicyTypeMaster;
import com.ax.hrms.master.model.PolicyTypeMasterModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the PolicyTypeMaster service. Represents a row in the &quot;ax_master_PolicyTypeMaster&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>PolicyTypeMasterModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PolicyTypeMasterImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PolicyTypeMasterImpl
 * @generated
 */
@JSON(strict = true)
public class PolicyTypeMasterModelImpl
	extends BaseModelImpl<PolicyTypeMaster> implements PolicyTypeMasterModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a policy type master model instance should use the <code>PolicyTypeMaster</code> interface instead.
	 */
	public static final String TABLE_NAME = "ax_master_PolicyTypeMaster";

	public static final Object[][] TABLE_COLUMNS = {
		{"policyTypeMasterID", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"createdBy", Types.BIGINT}, {"modifiedBy", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"policyType", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("policyTypeMasterID", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("policyType", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ax_master_PolicyTypeMaster (policyTypeMasterID LONG not null primary key,companyId LONG,createdBy LONG,modifiedBy LONG,groupId LONG,createDate DATE null,modifiedDate DATE null,policyType VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table ax_master_PolicyTypeMaster";

	public static final String ORDER_BY_JPQL =
		" ORDER BY policyTypeMaster.policyTypeMasterID ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ax_master_PolicyTypeMaster.policyTypeMasterID ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long POLICYTYPE_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long POLICYTYPEMASTERID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public PolicyTypeMasterModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _policyTypeMasterID;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPolicyTypeMasterID(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _policyTypeMasterID;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return PolicyTypeMaster.class;
	}

	@Override
	public String getModelClassName() {
		return PolicyTypeMaster.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<PolicyTypeMaster, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<PolicyTypeMaster, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PolicyTypeMaster, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((PolicyTypeMaster)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<PolicyTypeMaster, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<PolicyTypeMaster, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(PolicyTypeMaster)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<PolicyTypeMaster, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<PolicyTypeMaster, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<PolicyTypeMaster, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<PolicyTypeMaster, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<PolicyTypeMaster, Object>>();

			attributeGetterFunctions.put(
				"policyTypeMasterID", PolicyTypeMaster::getPolicyTypeMasterID);
			attributeGetterFunctions.put(
				"companyId", PolicyTypeMaster::getCompanyId);
			attributeGetterFunctions.put(
				"createdBy", PolicyTypeMaster::getCreatedBy);
			attributeGetterFunctions.put(
				"modifiedBy", PolicyTypeMaster::getModifiedBy);
			attributeGetterFunctions.put(
				"groupId", PolicyTypeMaster::getGroupId);
			attributeGetterFunctions.put(
				"createDate", PolicyTypeMaster::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", PolicyTypeMaster::getModifiedDate);
			attributeGetterFunctions.put(
				"policyType", PolicyTypeMaster::getPolicyType);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<PolicyTypeMaster, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<PolicyTypeMaster, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<PolicyTypeMaster, ?>>();

			attributeSetterBiConsumers.put(
				"policyTypeMasterID",
				(BiConsumer<PolicyTypeMaster, Long>)
					PolicyTypeMaster::setPolicyTypeMasterID);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<PolicyTypeMaster, Long>)
					PolicyTypeMaster::setCompanyId);
			attributeSetterBiConsumers.put(
				"createdBy",
				(BiConsumer<PolicyTypeMaster, Long>)
					PolicyTypeMaster::setCreatedBy);
			attributeSetterBiConsumers.put(
				"modifiedBy",
				(BiConsumer<PolicyTypeMaster, Long>)
					PolicyTypeMaster::setModifiedBy);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<PolicyTypeMaster, Long>)
					PolicyTypeMaster::setGroupId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<PolicyTypeMaster, Date>)
					PolicyTypeMaster::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<PolicyTypeMaster, Date>)
					PolicyTypeMaster::setModifiedDate);
			attributeSetterBiConsumers.put(
				"policyType",
				(BiConsumer<PolicyTypeMaster, String>)
					PolicyTypeMaster::setPolicyType);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getPolicyTypeMasterID() {
		return _policyTypeMasterID;
	}

	@Override
	public void setPolicyTypeMasterID(long policyTypeMasterID) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_policyTypeMasterID = policyTypeMasterID;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getPolicyType() {
		if (_policyType == null) {
			return "";
		}
		else {
			return _policyType;
		}
	}

	@Override
	public void setPolicyType(String policyType) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_policyType = policyType;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalPolicyType() {
		return getColumnOriginalValue("policyType");
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), PolicyTypeMaster.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public PolicyTypeMaster toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, PolicyTypeMaster>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PolicyTypeMasterImpl policyTypeMasterImpl = new PolicyTypeMasterImpl();

		policyTypeMasterImpl.setPolicyTypeMasterID(getPolicyTypeMasterID());
		policyTypeMasterImpl.setCompanyId(getCompanyId());
		policyTypeMasterImpl.setCreatedBy(getCreatedBy());
		policyTypeMasterImpl.setModifiedBy(getModifiedBy());
		policyTypeMasterImpl.setGroupId(getGroupId());
		policyTypeMasterImpl.setCreateDate(getCreateDate());
		policyTypeMasterImpl.setModifiedDate(getModifiedDate());
		policyTypeMasterImpl.setPolicyType(getPolicyType());

		policyTypeMasterImpl.resetOriginalValues();

		return policyTypeMasterImpl;
	}

	@Override
	public PolicyTypeMaster cloneWithOriginalValues() {
		PolicyTypeMasterImpl policyTypeMasterImpl = new PolicyTypeMasterImpl();

		policyTypeMasterImpl.setPolicyTypeMasterID(
			this.<Long>getColumnOriginalValue("policyTypeMasterID"));
		policyTypeMasterImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		policyTypeMasterImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("createdBy"));
		policyTypeMasterImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modifiedBy"));
		policyTypeMasterImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		policyTypeMasterImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		policyTypeMasterImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		policyTypeMasterImpl.setPolicyType(
			this.<String>getColumnOriginalValue("policyType"));

		return policyTypeMasterImpl;
	}

	@Override
	public int compareTo(PolicyTypeMaster policyTypeMaster) {
		long primaryKey = policyTypeMaster.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof PolicyTypeMaster)) {
			return false;
		}

		PolicyTypeMaster policyTypeMaster = (PolicyTypeMaster)object;

		long primaryKey = policyTypeMaster.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<PolicyTypeMaster> toCacheModel() {
		PolicyTypeMasterCacheModel policyTypeMasterCacheModel =
			new PolicyTypeMasterCacheModel();

		policyTypeMasterCacheModel.policyTypeMasterID = getPolicyTypeMasterID();

		policyTypeMasterCacheModel.companyId = getCompanyId();

		policyTypeMasterCacheModel.createdBy = getCreatedBy();

		policyTypeMasterCacheModel.modifiedBy = getModifiedBy();

		policyTypeMasterCacheModel.groupId = getGroupId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			policyTypeMasterCacheModel.createDate = createDate.getTime();
		}
		else {
			policyTypeMasterCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			policyTypeMasterCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			policyTypeMasterCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		policyTypeMasterCacheModel.policyType = getPolicyType();

		String policyType = policyTypeMasterCacheModel.policyType;

		if ((policyType != null) && (policyType.length() == 0)) {
			policyTypeMasterCacheModel.policyType = null;
		}

		return policyTypeMasterCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<PolicyTypeMaster, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<PolicyTypeMaster, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PolicyTypeMaster, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(PolicyTypeMaster)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, PolicyTypeMaster>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					PolicyTypeMaster.class, ModelWrapper.class);

	}

	private long _policyTypeMasterID;
	private long _companyId;
	private long _createdBy;
	private long _modifiedBy;
	private long _groupId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _policyType;

	public <T> T getColumnValue(String columnName) {
		Function<PolicyTypeMaster, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((PolicyTypeMaster)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("policyTypeMasterID", _policyTypeMasterID);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createdBy", _createdBy);
		_columnOriginalValues.put("modifiedBy", _modifiedBy);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("policyType", _policyType);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("policyTypeMasterID", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("createdBy", 4L);

		columnBitmasks.put("modifiedBy", 8L);

		columnBitmasks.put("groupId", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("policyType", 128L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private PolicyTypeMaster _escapedModel;

}