/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.master.model.impl;

import com.ax.hrms.master.model.PriorityMaster;
import com.ax.hrms.master.model.PriorityMasterModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the PriorityMaster service. Represents a row in the &quot;ax_master_PriorityMaster&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>PriorityMasterModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PriorityMasterImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PriorityMasterImpl
 * @generated
 */
@JSON(strict = true)
public class PriorityMasterModelImpl
	extends BaseModelImpl<PriorityMaster> implements PriorityMasterModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a priority master model instance should use the <code>PriorityMaster</code> interface instead.
	 */
	public static final String TABLE_NAME = "ax_master_PriorityMaster";

	public static final Object[][] TABLE_COLUMNS = {
		{"priorityMasterId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"createdBy", Types.BIGINT}, {"modifiedBy", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"priorityName", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("priorityMasterId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("priorityName", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ax_master_PriorityMaster (priorityMasterId LONG not null primary key,companyId LONG,createdBy LONG,modifiedBy LONG,groupId LONG,createDate DATE null,modifiedDate DATE null,priorityName VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table ax_master_PriorityMaster";

	public static final String ORDER_BY_JPQL =
		" ORDER BY priorityMaster.priorityMasterId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ax_master_PriorityMaster.priorityMasterId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PRIORITYNAME_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PRIORITYMASTERID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public PriorityMasterModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _priorityMasterId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPriorityMasterId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _priorityMasterId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return PriorityMaster.class;
	}

	@Override
	public String getModelClassName() {
		return PriorityMaster.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<PriorityMaster, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<PriorityMaster, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PriorityMaster, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((PriorityMaster)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<PriorityMaster, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<PriorityMaster, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(PriorityMaster)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<PriorityMaster, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<PriorityMaster, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<PriorityMaster, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<PriorityMaster, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<PriorityMaster, Object>>();

			attributeGetterFunctions.put(
				"priorityMasterId", PriorityMaster::getPriorityMasterId);
			attributeGetterFunctions.put(
				"companyId", PriorityMaster::getCompanyId);
			attributeGetterFunctions.put(
				"createdBy", PriorityMaster::getCreatedBy);
			attributeGetterFunctions.put(
				"modifiedBy", PriorityMaster::getModifiedBy);
			attributeGetterFunctions.put("groupId", PriorityMaster::getGroupId);
			attributeGetterFunctions.put(
				"createDate", PriorityMaster::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", PriorityMaster::getModifiedDate);
			attributeGetterFunctions.put(
				"priorityName", PriorityMaster::getPriorityName);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<PriorityMaster, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<PriorityMaster, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<PriorityMaster, ?>>();

			attributeSetterBiConsumers.put(
				"priorityMasterId",
				(BiConsumer<PriorityMaster, Long>)
					PriorityMaster::setPriorityMasterId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<PriorityMaster, Long>)PriorityMaster::setCompanyId);
			attributeSetterBiConsumers.put(
				"createdBy",
				(BiConsumer<PriorityMaster, Long>)PriorityMaster::setCreatedBy);
			attributeSetterBiConsumers.put(
				"modifiedBy",
				(BiConsumer<PriorityMaster, Long>)
					PriorityMaster::setModifiedBy);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<PriorityMaster, Long>)PriorityMaster::setGroupId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<PriorityMaster, Date>)
					PriorityMaster::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<PriorityMaster, Date>)
					PriorityMaster::setModifiedDate);
			attributeSetterBiConsumers.put(
				"priorityName",
				(BiConsumer<PriorityMaster, String>)
					PriorityMaster::setPriorityName);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getPriorityMasterId() {
		return _priorityMasterId;
	}

	@Override
	public void setPriorityMasterId(long priorityMasterId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_priorityMasterId = priorityMasterId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getPriorityName() {
		if (_priorityName == null) {
			return "";
		}
		else {
			return _priorityName;
		}
	}

	@Override
	public void setPriorityName(String priorityName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_priorityName = priorityName;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalPriorityName() {
		return getColumnOriginalValue("priorityName");
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), PriorityMaster.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public PriorityMaster toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, PriorityMaster>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PriorityMasterImpl priorityMasterImpl = new PriorityMasterImpl();

		priorityMasterImpl.setPriorityMasterId(getPriorityMasterId());
		priorityMasterImpl.setCompanyId(getCompanyId());
		priorityMasterImpl.setCreatedBy(getCreatedBy());
		priorityMasterImpl.setModifiedBy(getModifiedBy());
		priorityMasterImpl.setGroupId(getGroupId());
		priorityMasterImpl.setCreateDate(getCreateDate());
		priorityMasterImpl.setModifiedDate(getModifiedDate());
		priorityMasterImpl.setPriorityName(getPriorityName());

		priorityMasterImpl.resetOriginalValues();

		return priorityMasterImpl;
	}

	@Override
	public PriorityMaster cloneWithOriginalValues() {
		PriorityMasterImpl priorityMasterImpl = new PriorityMasterImpl();

		priorityMasterImpl.setPriorityMasterId(
			this.<Long>getColumnOriginalValue("priorityMasterId"));
		priorityMasterImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		priorityMasterImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("createdBy"));
		priorityMasterImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modifiedBy"));
		priorityMasterImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		priorityMasterImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		priorityMasterImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		priorityMasterImpl.setPriorityName(
			this.<String>getColumnOriginalValue("priorityName"));

		return priorityMasterImpl;
	}

	@Override
	public int compareTo(PriorityMaster priorityMaster) {
		long primaryKey = priorityMaster.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof PriorityMaster)) {
			return false;
		}

		PriorityMaster priorityMaster = (PriorityMaster)object;

		long primaryKey = priorityMaster.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<PriorityMaster> toCacheModel() {
		PriorityMasterCacheModel priorityMasterCacheModel =
			new PriorityMasterCacheModel();

		priorityMasterCacheModel.priorityMasterId = getPriorityMasterId();

		priorityMasterCacheModel.companyId = getCompanyId();

		priorityMasterCacheModel.createdBy = getCreatedBy();

		priorityMasterCacheModel.modifiedBy = getModifiedBy();

		priorityMasterCacheModel.groupId = getGroupId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			priorityMasterCacheModel.createDate = createDate.getTime();
		}
		else {
			priorityMasterCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			priorityMasterCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			priorityMasterCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		priorityMasterCacheModel.priorityName = getPriorityName();

		String priorityName = priorityMasterCacheModel.priorityName;

		if ((priorityName != null) && (priorityName.length() == 0)) {
			priorityMasterCacheModel.priorityName = null;
		}

		return priorityMasterCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<PriorityMaster, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<PriorityMaster, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PriorityMaster, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((PriorityMaster)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, PriorityMaster>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					PriorityMaster.class, ModelWrapper.class);

	}

	private long _priorityMasterId;
	private long _companyId;
	private long _createdBy;
	private long _modifiedBy;
	private long _groupId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _priorityName;

	public <T> T getColumnValue(String columnName) {
		Function<PriorityMaster, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((PriorityMaster)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("priorityMasterId", _priorityMasterId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createdBy", _createdBy);
		_columnOriginalValues.put("modifiedBy", _modifiedBy);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("priorityName", _priorityName);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("priorityMasterId", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("createdBy", 4L);

		columnBitmasks.put("modifiedBy", 8L);

		columnBitmasks.put("groupId", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("priorityName", 128L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private PriorityMaster _escapedModel;

}