/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.master.model.impl;

import com.ax.hrms.master.model.ProbationStatusMaster;
import com.ax.hrms.master.service.ProbationStatusMasterLocalServiceUtil;

/**
 * The extended model base implementation for the ProbationStatusMaster service. Represents a row in the &quot;ax_master_ProbationStatusMaster&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ProbationStatusMasterImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProbationStatusMasterImpl
 * @see ProbationStatusMaster
 * @generated
 */
public abstract class ProbationStatusMasterBaseImpl
	extends ProbationStatusMasterModelImpl implements ProbationStatusMaster {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a probation status master model instance should use the <code>ProbationStatusMaster</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ProbationStatusMasterLocalServiceUtil.addProbationStatusMaster(
				this);
		}
		else {
			ProbationStatusMasterLocalServiceUtil.updateProbationStatusMaster(
				this);
		}
	}

}