/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.master.model.impl;

import com.ax.hrms.master.model.ProjectTaskStatusMaster;
import com.ax.hrms.master.model.ProjectTaskStatusMasterModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ProjectTaskStatusMaster service. Represents a row in the &quot;ax_master_ProjectTaskStatusMaster&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ProjectTaskStatusMasterModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ProjectTaskStatusMasterImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProjectTaskStatusMasterImpl
 * @generated
 */
@JSON(strict = true)
public class ProjectTaskStatusMasterModelImpl
	extends BaseModelImpl<ProjectTaskStatusMaster>
	implements ProjectTaskStatusMasterModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a project task status master model instance should use the <code>ProjectTaskStatusMaster</code> interface instead.
	 */
	public static final String TABLE_NAME = "ax_master_ProjectTaskStatusMaster";

	public static final Object[][] TABLE_COLUMNS = {
		{"projectTaskStatusMasterId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"createdBy", Types.BIGINT},
		{"modifiedBy", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"projectTaskStatusName", Types.VARCHAR},
		{"isApplicableForProject", Types.BOOLEAN},
		{"isApplicableForTask", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("projectTaskStatusMasterId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("projectTaskStatusName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("isApplicableForProject", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("isApplicableForTask", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ax_master_ProjectTaskStatusMaster (projectTaskStatusMasterId LONG not null primary key,companyId LONG,createdBy LONG,modifiedBy LONG,groupId LONG,createDate DATE null,modifiedDate DATE null,projectTaskStatusName VARCHAR(75) null,isApplicableForProject BOOLEAN,isApplicableForTask BOOLEAN)";

	public static final String TABLE_SQL_DROP =
		"drop table ax_master_ProjectTaskStatusMaster";

	public static final String ORDER_BY_JPQL =
		" ORDER BY projectTaskStatusMaster.projectTaskStatusMasterId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ax_master_ProjectTaskStatusMaster.projectTaskStatusMasterId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ISAPPLICABLEFORPROJECT_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ISAPPLICABLEFORTASK_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PROJECTTASKSTATUSNAME_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PROJECTTASKSTATUSMASTERID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ProjectTaskStatusMasterModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _projectTaskStatusMasterId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setProjectTaskStatusMasterId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _projectTaskStatusMasterId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ProjectTaskStatusMaster.class;
	}

	@Override
	public String getModelClassName() {
		return ProjectTaskStatusMaster.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ProjectTaskStatusMaster, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ProjectTaskStatusMaster, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ProjectTaskStatusMaster, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ProjectTaskStatusMaster)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ProjectTaskStatusMaster, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ProjectTaskStatusMaster, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ProjectTaskStatusMaster)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ProjectTaskStatusMaster, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ProjectTaskStatusMaster, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map
			<String, Function<ProjectTaskStatusMaster, Object>>
				_attributeGetterFunctions;

		static {
			Map<String, Function<ProjectTaskStatusMaster, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<ProjectTaskStatusMaster, Object>>();

			attributeGetterFunctions.put(
				"projectTaskStatusMasterId",
				ProjectTaskStatusMaster::getProjectTaskStatusMasterId);
			attributeGetterFunctions.put(
				"companyId", ProjectTaskStatusMaster::getCompanyId);
			attributeGetterFunctions.put(
				"createdBy", ProjectTaskStatusMaster::getCreatedBy);
			attributeGetterFunctions.put(
				"modifiedBy", ProjectTaskStatusMaster::getModifiedBy);
			attributeGetterFunctions.put(
				"groupId", ProjectTaskStatusMaster::getGroupId);
			attributeGetterFunctions.put(
				"createDate", ProjectTaskStatusMaster::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", ProjectTaskStatusMaster::getModifiedDate);
			attributeGetterFunctions.put(
				"projectTaskStatusName",
				ProjectTaskStatusMaster::getProjectTaskStatusName);
			attributeGetterFunctions.put(
				"isApplicableForProject",
				ProjectTaskStatusMaster::getIsApplicableForProject);
			attributeGetterFunctions.put(
				"isApplicableForTask",
				ProjectTaskStatusMaster::getIsApplicableForTask);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<ProjectTaskStatusMaster, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<ProjectTaskStatusMaster, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<ProjectTaskStatusMaster, ?>>();

			attributeSetterBiConsumers.put(
				"projectTaskStatusMasterId",
				(BiConsumer<ProjectTaskStatusMaster, Long>)
					ProjectTaskStatusMaster::setProjectTaskStatusMasterId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<ProjectTaskStatusMaster, Long>)
					ProjectTaskStatusMaster::setCompanyId);
			attributeSetterBiConsumers.put(
				"createdBy",
				(BiConsumer<ProjectTaskStatusMaster, Long>)
					ProjectTaskStatusMaster::setCreatedBy);
			attributeSetterBiConsumers.put(
				"modifiedBy",
				(BiConsumer<ProjectTaskStatusMaster, Long>)
					ProjectTaskStatusMaster::setModifiedBy);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<ProjectTaskStatusMaster, Long>)
					ProjectTaskStatusMaster::setGroupId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<ProjectTaskStatusMaster, Date>)
					ProjectTaskStatusMaster::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<ProjectTaskStatusMaster, Date>)
					ProjectTaskStatusMaster::setModifiedDate);
			attributeSetterBiConsumers.put(
				"projectTaskStatusName",
				(BiConsumer<ProjectTaskStatusMaster, String>)
					ProjectTaskStatusMaster::setProjectTaskStatusName);
			attributeSetterBiConsumers.put(
				"isApplicableForProject",
				(BiConsumer<ProjectTaskStatusMaster, Boolean>)
					ProjectTaskStatusMaster::setIsApplicableForProject);
			attributeSetterBiConsumers.put(
				"isApplicableForTask",
				(BiConsumer<ProjectTaskStatusMaster, Boolean>)
					ProjectTaskStatusMaster::setIsApplicableForTask);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getProjectTaskStatusMasterId() {
		return _projectTaskStatusMasterId;
	}

	@Override
	public void setProjectTaskStatusMasterId(long projectTaskStatusMasterId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_projectTaskStatusMasterId = projectTaskStatusMasterId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getProjectTaskStatusName() {
		if (_projectTaskStatusName == null) {
			return "";
		}
		else {
			return _projectTaskStatusName;
		}
	}

	@Override
	public void setProjectTaskStatusName(String projectTaskStatusName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_projectTaskStatusName = projectTaskStatusName;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalProjectTaskStatusName() {
		return getColumnOriginalValue("projectTaskStatusName");
	}

	@JSON
	@Override
	public boolean getIsApplicableForProject() {
		return _isApplicableForProject;
	}

	@JSON
	@Override
	public boolean isIsApplicableForProject() {
		return _isApplicableForProject;
	}

	@Override
	public void setIsApplicableForProject(boolean isApplicableForProject) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_isApplicableForProject = isApplicableForProject;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public boolean getOriginalIsApplicableForProject() {
		return GetterUtil.getBoolean(
			this.<Boolean>getColumnOriginalValue("isApplicableForProject"));
	}

	@JSON
	@Override
	public boolean getIsApplicableForTask() {
		return _isApplicableForTask;
	}

	@JSON
	@Override
	public boolean isIsApplicableForTask() {
		return _isApplicableForTask;
	}

	@Override
	public void setIsApplicableForTask(boolean isApplicableForTask) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_isApplicableForTask = isApplicableForTask;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public boolean getOriginalIsApplicableForTask() {
		return GetterUtil.getBoolean(
			this.<Boolean>getColumnOriginalValue("isApplicableForTask"));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), ProjectTaskStatusMaster.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ProjectTaskStatusMaster toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ProjectTaskStatusMaster>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ProjectTaskStatusMasterImpl projectTaskStatusMasterImpl =
			new ProjectTaskStatusMasterImpl();

		projectTaskStatusMasterImpl.setProjectTaskStatusMasterId(
			getProjectTaskStatusMasterId());
		projectTaskStatusMasterImpl.setCompanyId(getCompanyId());
		projectTaskStatusMasterImpl.setCreatedBy(getCreatedBy());
		projectTaskStatusMasterImpl.setModifiedBy(getModifiedBy());
		projectTaskStatusMasterImpl.setGroupId(getGroupId());
		projectTaskStatusMasterImpl.setCreateDate(getCreateDate());
		projectTaskStatusMasterImpl.setModifiedDate(getModifiedDate());
		projectTaskStatusMasterImpl.setProjectTaskStatusName(
			getProjectTaskStatusName());
		projectTaskStatusMasterImpl.setIsApplicableForProject(
			isIsApplicableForProject());
		projectTaskStatusMasterImpl.setIsApplicableForTask(
			isIsApplicableForTask());

		projectTaskStatusMasterImpl.resetOriginalValues();

		return projectTaskStatusMasterImpl;
	}

	@Override
	public ProjectTaskStatusMaster cloneWithOriginalValues() {
		ProjectTaskStatusMasterImpl projectTaskStatusMasterImpl =
			new ProjectTaskStatusMasterImpl();

		projectTaskStatusMasterImpl.setProjectTaskStatusMasterId(
			this.<Long>getColumnOriginalValue("projectTaskStatusMasterId"));
		projectTaskStatusMasterImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		projectTaskStatusMasterImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("createdBy"));
		projectTaskStatusMasterImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modifiedBy"));
		projectTaskStatusMasterImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		projectTaskStatusMasterImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		projectTaskStatusMasterImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		projectTaskStatusMasterImpl.setProjectTaskStatusName(
			this.<String>getColumnOriginalValue("projectTaskStatusName"));
		projectTaskStatusMasterImpl.setIsApplicableForProject(
			this.<Boolean>getColumnOriginalValue("isApplicableForProject"));
		projectTaskStatusMasterImpl.setIsApplicableForTask(
			this.<Boolean>getColumnOriginalValue("isApplicableForTask"));

		return projectTaskStatusMasterImpl;
	}

	@Override
	public int compareTo(ProjectTaskStatusMaster projectTaskStatusMaster) {
		long primaryKey = projectTaskStatusMaster.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ProjectTaskStatusMaster)) {
			return false;
		}

		ProjectTaskStatusMaster projectTaskStatusMaster =
			(ProjectTaskStatusMaster)object;

		long primaryKey = projectTaskStatusMaster.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ProjectTaskStatusMaster> toCacheModel() {
		ProjectTaskStatusMasterCacheModel projectTaskStatusMasterCacheModel =
			new ProjectTaskStatusMasterCacheModel();

		projectTaskStatusMasterCacheModel.projectTaskStatusMasterId =
			getProjectTaskStatusMasterId();

		projectTaskStatusMasterCacheModel.companyId = getCompanyId();

		projectTaskStatusMasterCacheModel.createdBy = getCreatedBy();

		projectTaskStatusMasterCacheModel.modifiedBy = getModifiedBy();

		projectTaskStatusMasterCacheModel.groupId = getGroupId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			projectTaskStatusMasterCacheModel.createDate = createDate.getTime();
		}
		else {
			projectTaskStatusMasterCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			projectTaskStatusMasterCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			projectTaskStatusMasterCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		projectTaskStatusMasterCacheModel.projectTaskStatusName =
			getProjectTaskStatusName();

		String projectTaskStatusName =
			projectTaskStatusMasterCacheModel.projectTaskStatusName;

		if ((projectTaskStatusName != null) &&
			(projectTaskStatusName.length() == 0)) {

			projectTaskStatusMasterCacheModel.projectTaskStatusName = null;
		}

		projectTaskStatusMasterCacheModel.isApplicableForProject =
			isIsApplicableForProject();

		projectTaskStatusMasterCacheModel.isApplicableForTask =
			isIsApplicableForTask();

		return projectTaskStatusMasterCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ProjectTaskStatusMaster, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ProjectTaskStatusMaster, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ProjectTaskStatusMaster, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(ProjectTaskStatusMaster)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, ProjectTaskStatusMaster>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						ProjectTaskStatusMaster.class, ModelWrapper.class);

	}

	private long _projectTaskStatusMasterId;
	private long _companyId;
	private long _createdBy;
	private long _modifiedBy;
	private long _groupId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _projectTaskStatusName;
	private boolean _isApplicableForProject;
	private boolean _isApplicableForTask;

	public <T> T getColumnValue(String columnName) {
		Function<ProjectTaskStatusMaster, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ProjectTaskStatusMaster)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put(
			"projectTaskStatusMasterId", _projectTaskStatusMasterId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createdBy", _createdBy);
		_columnOriginalValues.put("modifiedBy", _modifiedBy);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put(
			"projectTaskStatusName", _projectTaskStatusName);
		_columnOriginalValues.put(
			"isApplicableForProject", _isApplicableForProject);
		_columnOriginalValues.put("isApplicableForTask", _isApplicableForTask);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("projectTaskStatusMasterId", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("createdBy", 4L);

		columnBitmasks.put("modifiedBy", 8L);

		columnBitmasks.put("groupId", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("projectTaskStatusName", 128L);

		columnBitmasks.put("isApplicableForProject", 256L);

		columnBitmasks.put("isApplicableForTask", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ProjectTaskStatusMaster _escapedModel;

}