/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.master.model.impl;

import com.ax.hrms.master.model.TemplateLevelMaster;
import com.ax.hrms.master.model.TemplateLevelMasterModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the TemplateLevelMaster service. Represents a row in the &quot;ax_master_TemplateLevelMaster&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>TemplateLevelMasterModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TemplateLevelMasterImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TemplateLevelMasterImpl
 * @generated
 */
@JSON(strict = true)
public class TemplateLevelMasterModelImpl
	extends BaseModelImpl<TemplateLevelMaster>
	implements TemplateLevelMasterModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a template level master model instance should use the <code>TemplateLevelMaster</code> interface instead.
	 */
	public static final String TABLE_NAME = "ax_master_TemplateLevelMaster";

	public static final Object[][] TABLE_COLUMNS = {
		{"templateLevelMasterId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"createdBy", Types.BIGINT}, {"modifiedBy", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"levelName", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("templateLevelMasterId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("levelName", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ax_master_TemplateLevelMaster (templateLevelMasterId LONG not null primary key,companyId LONG,createdBy LONG,modifiedBy LONG,groupId LONG,createDate DATE null,modifiedDate DATE null,levelName VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table ax_master_TemplateLevelMaster";

	public static final String ORDER_BY_JPQL =
		" ORDER BY templateLevelMaster.templateLevelMasterId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ax_master_TemplateLevelMaster.templateLevelMasterId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LEVELNAME_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TEMPLATELEVELMASTERID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public TemplateLevelMasterModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _templateLevelMasterId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTemplateLevelMasterId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _templateLevelMasterId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TemplateLevelMaster.class;
	}

	@Override
	public String getModelClassName() {
		return TemplateLevelMaster.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<TemplateLevelMaster, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<TemplateLevelMaster, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TemplateLevelMaster, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((TemplateLevelMaster)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<TemplateLevelMaster, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<TemplateLevelMaster, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(TemplateLevelMaster)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<TemplateLevelMaster, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<TemplateLevelMaster, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<TemplateLevelMaster, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<TemplateLevelMaster, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<TemplateLevelMaster, Object>>();

			attributeGetterFunctions.put(
				"templateLevelMasterId",
				TemplateLevelMaster::getTemplateLevelMasterId);
			attributeGetterFunctions.put(
				"companyId", TemplateLevelMaster::getCompanyId);
			attributeGetterFunctions.put(
				"createdBy", TemplateLevelMaster::getCreatedBy);
			attributeGetterFunctions.put(
				"modifiedBy", TemplateLevelMaster::getModifiedBy);
			attributeGetterFunctions.put(
				"groupId", TemplateLevelMaster::getGroupId);
			attributeGetterFunctions.put(
				"createDate", TemplateLevelMaster::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", TemplateLevelMaster::getModifiedDate);
			attributeGetterFunctions.put(
				"levelName", TemplateLevelMaster::getLevelName);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<TemplateLevelMaster, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<TemplateLevelMaster, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<TemplateLevelMaster, ?>>();

			attributeSetterBiConsumers.put(
				"templateLevelMasterId",
				(BiConsumer<TemplateLevelMaster, Long>)
					TemplateLevelMaster::setTemplateLevelMasterId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<TemplateLevelMaster, Long>)
					TemplateLevelMaster::setCompanyId);
			attributeSetterBiConsumers.put(
				"createdBy",
				(BiConsumer<TemplateLevelMaster, Long>)
					TemplateLevelMaster::setCreatedBy);
			attributeSetterBiConsumers.put(
				"modifiedBy",
				(BiConsumer<TemplateLevelMaster, Long>)
					TemplateLevelMaster::setModifiedBy);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<TemplateLevelMaster, Long>)
					TemplateLevelMaster::setGroupId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<TemplateLevelMaster, Date>)
					TemplateLevelMaster::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<TemplateLevelMaster, Date>)
					TemplateLevelMaster::setModifiedDate);
			attributeSetterBiConsumers.put(
				"levelName",
				(BiConsumer<TemplateLevelMaster, String>)
					TemplateLevelMaster::setLevelName);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getTemplateLevelMasterId() {
		return _templateLevelMasterId;
	}

	@Override
	public void setTemplateLevelMasterId(long templateLevelMasterId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_templateLevelMasterId = templateLevelMasterId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getLevelName() {
		if (_levelName == null) {
			return "";
		}
		else {
			return _levelName;
		}
	}

	@Override
	public void setLevelName(String levelName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_levelName = levelName;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalLevelName() {
		return getColumnOriginalValue("levelName");
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), TemplateLevelMaster.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TemplateLevelMaster toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, TemplateLevelMaster>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TemplateLevelMasterImpl templateLevelMasterImpl =
			new TemplateLevelMasterImpl();

		templateLevelMasterImpl.setTemplateLevelMasterId(
			getTemplateLevelMasterId());
		templateLevelMasterImpl.setCompanyId(getCompanyId());
		templateLevelMasterImpl.setCreatedBy(getCreatedBy());
		templateLevelMasterImpl.setModifiedBy(getModifiedBy());
		templateLevelMasterImpl.setGroupId(getGroupId());
		templateLevelMasterImpl.setCreateDate(getCreateDate());
		templateLevelMasterImpl.setModifiedDate(getModifiedDate());
		templateLevelMasterImpl.setLevelName(getLevelName());

		templateLevelMasterImpl.resetOriginalValues();

		return templateLevelMasterImpl;
	}

	@Override
	public TemplateLevelMaster cloneWithOriginalValues() {
		TemplateLevelMasterImpl templateLevelMasterImpl =
			new TemplateLevelMasterImpl();

		templateLevelMasterImpl.setTemplateLevelMasterId(
			this.<Long>getColumnOriginalValue("templateLevelMasterId"));
		templateLevelMasterImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		templateLevelMasterImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("createdBy"));
		templateLevelMasterImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modifiedBy"));
		templateLevelMasterImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		templateLevelMasterImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		templateLevelMasterImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		templateLevelMasterImpl.setLevelName(
			this.<String>getColumnOriginalValue("levelName"));

		return templateLevelMasterImpl;
	}

	@Override
	public int compareTo(TemplateLevelMaster templateLevelMaster) {
		long primaryKey = templateLevelMaster.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof TemplateLevelMaster)) {
			return false;
		}

		TemplateLevelMaster templateLevelMaster = (TemplateLevelMaster)object;

		long primaryKey = templateLevelMaster.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<TemplateLevelMaster> toCacheModel() {
		TemplateLevelMasterCacheModel templateLevelMasterCacheModel =
			new TemplateLevelMasterCacheModel();

		templateLevelMasterCacheModel.templateLevelMasterId =
			getTemplateLevelMasterId();

		templateLevelMasterCacheModel.companyId = getCompanyId();

		templateLevelMasterCacheModel.createdBy = getCreatedBy();

		templateLevelMasterCacheModel.modifiedBy = getModifiedBy();

		templateLevelMasterCacheModel.groupId = getGroupId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			templateLevelMasterCacheModel.createDate = createDate.getTime();
		}
		else {
			templateLevelMasterCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			templateLevelMasterCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			templateLevelMasterCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		templateLevelMasterCacheModel.levelName = getLevelName();

		String levelName = templateLevelMasterCacheModel.levelName;

		if ((levelName != null) && (levelName.length() == 0)) {
			templateLevelMasterCacheModel.levelName = null;
		}

		return templateLevelMasterCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<TemplateLevelMaster, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<TemplateLevelMaster, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TemplateLevelMaster, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(TemplateLevelMaster)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, TemplateLevelMaster>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					TemplateLevelMaster.class, ModelWrapper.class);

	}

	private long _templateLevelMasterId;
	private long _companyId;
	private long _createdBy;
	private long _modifiedBy;
	private long _groupId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _levelName;

	public <T> T getColumnValue(String columnName) {
		Function<TemplateLevelMaster, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((TemplateLevelMaster)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put(
			"templateLevelMasterId", _templateLevelMasterId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createdBy", _createdBy);
		_columnOriginalValues.put("modifiedBy", _modifiedBy);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("levelName", _levelName);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("templateLevelMasterId", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("createdBy", 4L);

		columnBitmasks.put("modifiedBy", 8L);

		columnBitmasks.put("groupId", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("levelName", 128L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private TemplateLevelMaster _escapedModel;

}