/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.master.model.impl;

import com.ax.hrms.master.model.WishTypeMaster;
import com.ax.hrms.master.model.WishTypeMasterModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the WishTypeMaster service. Represents a row in the &quot;ax_master_WishTypeMaster&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>WishTypeMasterModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link WishTypeMasterImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see WishTypeMasterImpl
 * @generated
 */
@JSON(strict = true)
public class WishTypeMasterModelImpl
	extends BaseModelImpl<WishTypeMaster> implements WishTypeMasterModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a wish type master model instance should use the <code>WishTypeMaster</code> interface instead.
	 */
	public static final String TABLE_NAME = "ax_master_WishTypeMaster";

	public static final Object[][] TABLE_COLUMNS = {
		{"wishTypeMasterId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"createdBy", Types.BIGINT}, {"modifiedBy", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"wishType", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("wishTypeMasterId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("wishType", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ax_master_WishTypeMaster (wishTypeMasterId LONG not null primary key,companyId LONG,createdBy LONG,modifiedBy LONG,groupId LONG,createDate DATE null,modifiedDate DATE null,wishType VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table ax_master_WishTypeMaster";

	public static final String ORDER_BY_JPQL =
		" ORDER BY wishTypeMaster.wishTypeMasterId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ax_master_WishTypeMaster.wishTypeMasterId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long WISHTYPE_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long WISHTYPEMASTERID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public WishTypeMasterModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _wishTypeMasterId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setWishTypeMasterId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _wishTypeMasterId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return WishTypeMaster.class;
	}

	@Override
	public String getModelClassName() {
		return WishTypeMaster.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<WishTypeMaster, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<WishTypeMaster, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<WishTypeMaster, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((WishTypeMaster)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<WishTypeMaster, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<WishTypeMaster, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(WishTypeMaster)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<WishTypeMaster, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<WishTypeMaster, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<WishTypeMaster, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<WishTypeMaster, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<WishTypeMaster, Object>>();

			attributeGetterFunctions.put(
				"wishTypeMasterId", WishTypeMaster::getWishTypeMasterId);
			attributeGetterFunctions.put(
				"companyId", WishTypeMaster::getCompanyId);
			attributeGetterFunctions.put(
				"createdBy", WishTypeMaster::getCreatedBy);
			attributeGetterFunctions.put(
				"modifiedBy", WishTypeMaster::getModifiedBy);
			attributeGetterFunctions.put("groupId", WishTypeMaster::getGroupId);
			attributeGetterFunctions.put(
				"createDate", WishTypeMaster::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", WishTypeMaster::getModifiedDate);
			attributeGetterFunctions.put(
				"wishType", WishTypeMaster::getWishType);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<WishTypeMaster, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<WishTypeMaster, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<WishTypeMaster, ?>>();

			attributeSetterBiConsumers.put(
				"wishTypeMasterId",
				(BiConsumer<WishTypeMaster, Long>)
					WishTypeMaster::setWishTypeMasterId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<WishTypeMaster, Long>)WishTypeMaster::setCompanyId);
			attributeSetterBiConsumers.put(
				"createdBy",
				(BiConsumer<WishTypeMaster, Long>)WishTypeMaster::setCreatedBy);
			attributeSetterBiConsumers.put(
				"modifiedBy",
				(BiConsumer<WishTypeMaster, Long>)
					WishTypeMaster::setModifiedBy);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<WishTypeMaster, Long>)WishTypeMaster::setGroupId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<WishTypeMaster, Date>)
					WishTypeMaster::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<WishTypeMaster, Date>)
					WishTypeMaster::setModifiedDate);
			attributeSetterBiConsumers.put(
				"wishType",
				(BiConsumer<WishTypeMaster, String>)
					WishTypeMaster::setWishType);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getWishTypeMasterId() {
		return _wishTypeMasterId;
	}

	@Override
	public void setWishTypeMasterId(long wishTypeMasterId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_wishTypeMasterId = wishTypeMasterId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getWishType() {
		if (_wishType == null) {
			return "";
		}
		else {
			return _wishType;
		}
	}

	@Override
	public void setWishType(String wishType) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_wishType = wishType;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalWishType() {
		return getColumnOriginalValue("wishType");
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), WishTypeMaster.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public WishTypeMaster toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, WishTypeMaster>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		WishTypeMasterImpl wishTypeMasterImpl = new WishTypeMasterImpl();

		wishTypeMasterImpl.setWishTypeMasterId(getWishTypeMasterId());
		wishTypeMasterImpl.setCompanyId(getCompanyId());
		wishTypeMasterImpl.setCreatedBy(getCreatedBy());
		wishTypeMasterImpl.setModifiedBy(getModifiedBy());
		wishTypeMasterImpl.setGroupId(getGroupId());
		wishTypeMasterImpl.setCreateDate(getCreateDate());
		wishTypeMasterImpl.setModifiedDate(getModifiedDate());
		wishTypeMasterImpl.setWishType(getWishType());

		wishTypeMasterImpl.resetOriginalValues();

		return wishTypeMasterImpl;
	}

	@Override
	public WishTypeMaster cloneWithOriginalValues() {
		WishTypeMasterImpl wishTypeMasterImpl = new WishTypeMasterImpl();

		wishTypeMasterImpl.setWishTypeMasterId(
			this.<Long>getColumnOriginalValue("wishTypeMasterId"));
		wishTypeMasterImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		wishTypeMasterImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("createdBy"));
		wishTypeMasterImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modifiedBy"));
		wishTypeMasterImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		wishTypeMasterImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		wishTypeMasterImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		wishTypeMasterImpl.setWishType(
			this.<String>getColumnOriginalValue("wishType"));

		return wishTypeMasterImpl;
	}

	@Override
	public int compareTo(WishTypeMaster wishTypeMaster) {
		long primaryKey = wishTypeMaster.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof WishTypeMaster)) {
			return false;
		}

		WishTypeMaster wishTypeMaster = (WishTypeMaster)object;

		long primaryKey = wishTypeMaster.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<WishTypeMaster> toCacheModel() {
		WishTypeMasterCacheModel wishTypeMasterCacheModel =
			new WishTypeMasterCacheModel();

		wishTypeMasterCacheModel.wishTypeMasterId = getWishTypeMasterId();

		wishTypeMasterCacheModel.companyId = getCompanyId();

		wishTypeMasterCacheModel.createdBy = getCreatedBy();

		wishTypeMasterCacheModel.modifiedBy = getModifiedBy();

		wishTypeMasterCacheModel.groupId = getGroupId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			wishTypeMasterCacheModel.createDate = createDate.getTime();
		}
		else {
			wishTypeMasterCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			wishTypeMasterCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			wishTypeMasterCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		wishTypeMasterCacheModel.wishType = getWishType();

		String wishType = wishTypeMasterCacheModel.wishType;

		if ((wishType != null) && (wishType.length() == 0)) {
			wishTypeMasterCacheModel.wishType = null;
		}

		return wishTypeMasterCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<WishTypeMaster, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<WishTypeMaster, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<WishTypeMaster, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((WishTypeMaster)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, WishTypeMaster>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					WishTypeMaster.class, ModelWrapper.class);

	}

	private long _wishTypeMasterId;
	private long _companyId;
	private long _createdBy;
	private long _modifiedBy;
	private long _groupId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _wishType;

	public <T> T getColumnValue(String columnName) {
		Function<WishTypeMaster, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((WishTypeMaster)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("wishTypeMasterId", _wishTypeMasterId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createdBy", _createdBy);
		_columnOriginalValues.put("modifiedBy", _modifiedBy);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("wishType", _wishType);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("wishTypeMasterId", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("createdBy", 4L);

		columnBitmasks.put("modifiedBy", 8L);

		columnBitmasks.put("groupId", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("wishType", 128L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private WishTypeMaster _escapedModel;

}