/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.master.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the DocumentTypeMaster service. Represents a row in the &quot;ax_master_DocumentTypeMaster&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.ax.hrms.master.model.impl.DocumentTypeMasterModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.ax.hrms.master.model.impl.DocumentTypeMasterImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DocumentTypeMaster
 * @generated
 */
@ProviderType
public interface DocumentTypeMasterModel
	extends BaseModel<DocumentTypeMaster>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a document type master model instance should use the {@link DocumentTypeMaster} interface instead.
	 */

	/**
	 * Returns the primary key of this document type master.
	 *
	 * @return the primary key of this document type master
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this document type master.
	 *
	 * @param primaryKey the primary key of this document type master
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the document type master ID of this document type master.
	 *
	 * @return the document type master ID of this document type master
	 */
	public long getDocumentTypeMasterId();

	/**
	 * Sets the document type master ID of this document type master.
	 *
	 * @param documentTypeMasterId the document type master ID of this document type master
	 */
	public void setDocumentTypeMasterId(long documentTypeMasterId);

	/**
	 * Returns the company ID of this document type master.
	 *
	 * @return the company ID of this document type master
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this document type master.
	 *
	 * @param companyId the company ID of this document type master
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the created by of this document type master.
	 *
	 * @return the created by of this document type master
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this document type master.
	 *
	 * @param createdBy the created by of this document type master
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified by of this document type master.
	 *
	 * @return the modified by of this document type master
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this document type master.
	 *
	 * @param modifiedBy the modified by of this document type master
	 */
	public void setModifiedBy(long modifiedBy);

	/**
	 * Returns the group ID of this document type master.
	 *
	 * @return the group ID of this document type master
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this document type master.
	 *
	 * @param groupId the group ID of this document type master
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the create date of this document type master.
	 *
	 * @return the create date of this document type master
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this document type master.
	 *
	 * @param createDate the create date of this document type master
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this document type master.
	 *
	 * @return the modified date of this document type master
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this document type master.
	 *
	 * @param modifiedDate the modified date of this document type master
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the document type name of this document type master.
	 *
	 * @return the document type name of this document type master
	 */
	@AutoEscape
	public String getDocumentTypeName();

	/**
	 * Sets the document type name of this document type master.
	 *
	 * @param documentTypeName the document type name of this document type master
	 */
	public void setDocumentTypeName(String documentTypeName);

	@Override
	public DocumentTypeMaster cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}