/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.master.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the PolicyTypeMaster service. Represents a row in the &quot;ax_master_PolicyTypeMaster&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.ax.hrms.master.model.impl.PolicyTypeMasterModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.ax.hrms.master.model.impl.PolicyTypeMasterImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PolicyTypeMaster
 * @generated
 */
@ProviderType
public interface PolicyTypeMasterModel
	extends BaseModel<PolicyTypeMaster>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a policy type master model instance should use the {@link PolicyTypeMaster} interface instead.
	 */

	/**
	 * Returns the primary key of this policy type master.
	 *
	 * @return the primary key of this policy type master
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this policy type master.
	 *
	 * @param primaryKey the primary key of this policy type master
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the policy type master ID of this policy type master.
	 *
	 * @return the policy type master ID of this policy type master
	 */
	public long getPolicyTypeMasterID();

	/**
	 * Sets the policy type master ID of this policy type master.
	 *
	 * @param policyTypeMasterID the policy type master ID of this policy type master
	 */
	public void setPolicyTypeMasterID(long policyTypeMasterID);

	/**
	 * Returns the company ID of this policy type master.
	 *
	 * @return the company ID of this policy type master
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this policy type master.
	 *
	 * @param companyId the company ID of this policy type master
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the created by of this policy type master.
	 *
	 * @return the created by of this policy type master
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this policy type master.
	 *
	 * @param createdBy the created by of this policy type master
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified by of this policy type master.
	 *
	 * @return the modified by of this policy type master
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this policy type master.
	 *
	 * @param modifiedBy the modified by of this policy type master
	 */
	public void setModifiedBy(long modifiedBy);

	/**
	 * Returns the group ID of this policy type master.
	 *
	 * @return the group ID of this policy type master
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this policy type master.
	 *
	 * @param groupId the group ID of this policy type master
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the create date of this policy type master.
	 *
	 * @return the create date of this policy type master
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this policy type master.
	 *
	 * @param createDate the create date of this policy type master
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this policy type master.
	 *
	 * @return the modified date of this policy type master
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this policy type master.
	 *
	 * @param modifiedDate the modified date of this policy type master
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the policy type of this policy type master.
	 *
	 * @return the policy type of this policy type master
	 */
	@AutoEscape
	public String getPolicyType();

	/**
	 * Sets the policy type of this policy type master.
	 *
	 * @param policyType the policy type of this policy type master
	 */
	public void setPolicyType(String policyType);

	@Override
	public PolicyTypeMaster cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}