/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.master.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the TemplateLevelMaster service. Represents a row in the &quot;ax_master_TemplateLevelMaster&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.ax.hrms.master.model.impl.TemplateLevelMasterModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.ax.hrms.master.model.impl.TemplateLevelMasterImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TemplateLevelMaster
 * @generated
 */
@ProviderType
public interface TemplateLevelMasterModel
	extends BaseModel<TemplateLevelMaster>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a template level master model instance should use the {@link TemplateLevelMaster} interface instead.
	 */

	/**
	 * Returns the primary key of this template level master.
	 *
	 * @return the primary key of this template level master
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this template level master.
	 *
	 * @param primaryKey the primary key of this template level master
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the template level master ID of this template level master.
	 *
	 * @return the template level master ID of this template level master
	 */
	public long getTemplateLevelMasterId();

	/**
	 * Sets the template level master ID of this template level master.
	 *
	 * @param templateLevelMasterId the template level master ID of this template level master
	 */
	public void setTemplateLevelMasterId(long templateLevelMasterId);

	/**
	 * Returns the company ID of this template level master.
	 *
	 * @return the company ID of this template level master
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this template level master.
	 *
	 * @param companyId the company ID of this template level master
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the created by of this template level master.
	 *
	 * @return the created by of this template level master
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this template level master.
	 *
	 * @param createdBy the created by of this template level master
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified by of this template level master.
	 *
	 * @return the modified by of this template level master
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this template level master.
	 *
	 * @param modifiedBy the modified by of this template level master
	 */
	public void setModifiedBy(long modifiedBy);

	/**
	 * Returns the group ID of this template level master.
	 *
	 * @return the group ID of this template level master
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this template level master.
	 *
	 * @param groupId the group ID of this template level master
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the create date of this template level master.
	 *
	 * @return the create date of this template level master
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this template level master.
	 *
	 * @param createDate the create date of this template level master
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this template level master.
	 *
	 * @return the modified date of this template level master
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this template level master.
	 *
	 * @param modifiedDate the modified date of this template level master
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the level name of this template level master.
	 *
	 * @return the level name of this template level master
	 */
	@AutoEscape
	public String getLevelName();

	/**
	 * Sets the level name of this template level master.
	 *
	 * @param levelName the level name of this template level master
	 */
	public void setLevelName(String levelName);

	@Override
	public TemplateLevelMaster cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}