/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.master.service.base;

import com.ax.hrms.master.model.ProjectTaskStatusMaster;
import com.ax.hrms.master.service.ProjectTaskStatusMasterLocalService;
import com.ax.hrms.master.service.persistence.AppraisalStatusMasterPersistence;
import com.ax.hrms.master.service.persistence.DepartmentMasterPersistence;
import com.ax.hrms.master.service.persistence.DesignationMasterPersistence;
import com.ax.hrms.master.service.persistence.DocumentTypeMasterPersistence;
import com.ax.hrms.master.service.persistence.EducationLevelMasterPersistence;
import com.ax.hrms.master.service.persistence.LeaveCompensatoryStatusMasterPersistence;
import com.ax.hrms.master.service.persistence.LeavePolicyMasterPersistence;
import com.ax.hrms.master.service.persistence.LeaveTypeMasterPersistence;
import com.ax.hrms.master.service.persistence.PolicyTypeMasterPersistence;
import com.ax.hrms.master.service.persistence.PriorityMasterPersistence;
import com.ax.hrms.master.service.persistence.ProbationStatusMasterPersistence;
import com.ax.hrms.master.service.persistence.ProjectTaskStatusMasterPersistence;
import com.ax.hrms.master.service.persistence.TemplateLevelMasterPersistence;
import com.ax.hrms.master.service.persistence.WishTypeMasterPersistence;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the project task status master local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.ax.hrms.master.service.impl.ProjectTaskStatusMasterLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.ax.hrms.master.service.impl.ProjectTaskStatusMasterLocalServiceImpl
 * @generated
 */
public abstract class ProjectTaskStatusMasterLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService,
			   ProjectTaskStatusMasterLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>ProjectTaskStatusMasterLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.ax.hrms.master.service.ProjectTaskStatusMasterLocalServiceUtil</code>.
	 */

	/**
	 * Adds the project task status master to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ProjectTaskStatusMasterLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param projectTaskStatusMaster the project task status master
	 * @return the project task status master that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public ProjectTaskStatusMaster addProjectTaskStatusMaster(
		ProjectTaskStatusMaster projectTaskStatusMaster) {

		projectTaskStatusMaster.setNew(true);

		return projectTaskStatusMasterPersistence.update(
			projectTaskStatusMaster);
	}

	/**
	 * Creates a new project task status master with the primary key. Does not add the project task status master to the database.
	 *
	 * @param projectTaskStatusMasterId the primary key for the new project task status master
	 * @return the new project task status master
	 */
	@Override
	@Transactional(enabled = false)
	public ProjectTaskStatusMaster createProjectTaskStatusMaster(
		long projectTaskStatusMasterId) {

		return projectTaskStatusMasterPersistence.create(
			projectTaskStatusMasterId);
	}

	/**
	 * Deletes the project task status master with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ProjectTaskStatusMasterLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param projectTaskStatusMasterId the primary key of the project task status master
	 * @return the project task status master that was removed
	 * @throws PortalException if a project task status master with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public ProjectTaskStatusMaster deleteProjectTaskStatusMaster(
			long projectTaskStatusMasterId)
		throws PortalException {

		return projectTaskStatusMasterPersistence.remove(
			projectTaskStatusMasterId);
	}

	/**
	 * Deletes the project task status master from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ProjectTaskStatusMasterLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param projectTaskStatusMaster the project task status master
	 * @return the project task status master that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public ProjectTaskStatusMaster deleteProjectTaskStatusMaster(
		ProjectTaskStatusMaster projectTaskStatusMaster) {

		return projectTaskStatusMasterPersistence.remove(
			projectTaskStatusMaster);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return projectTaskStatusMasterPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			ProjectTaskStatusMaster.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return projectTaskStatusMasterPersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.ax.hrms.master.model.impl.ProjectTaskStatusMasterModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return projectTaskStatusMasterPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.ax.hrms.master.model.impl.ProjectTaskStatusMasterModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return projectTaskStatusMasterPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return projectTaskStatusMasterPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return projectTaskStatusMasterPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public ProjectTaskStatusMaster fetchProjectTaskStatusMaster(
		long projectTaskStatusMasterId) {

		return projectTaskStatusMasterPersistence.fetchByPrimaryKey(
			projectTaskStatusMasterId);
	}

	/**
	 * Returns the project task status master with the primary key.
	 *
	 * @param projectTaskStatusMasterId the primary key of the project task status master
	 * @return the project task status master
	 * @throws PortalException if a project task status master with the primary key could not be found
	 */
	@Override
	public ProjectTaskStatusMaster getProjectTaskStatusMaster(
			long projectTaskStatusMasterId)
		throws PortalException {

		return projectTaskStatusMasterPersistence.findByPrimaryKey(
			projectTaskStatusMasterId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			projectTaskStatusMasterLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(ProjectTaskStatusMaster.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"projectTaskStatusMasterId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			projectTaskStatusMasterLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			ProjectTaskStatusMaster.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"projectTaskStatusMasterId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			projectTaskStatusMasterLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(ProjectTaskStatusMaster.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"projectTaskStatusMasterId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return projectTaskStatusMasterPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement ProjectTaskStatusMasterLocalServiceImpl#deleteProjectTaskStatusMaster(ProjectTaskStatusMaster) to avoid orphaned data");
		}

		return projectTaskStatusMasterLocalService.
			deleteProjectTaskStatusMaster(
				(ProjectTaskStatusMaster)persistedModel);
	}

	@Override
	public BasePersistence<ProjectTaskStatusMaster> getBasePersistence() {
		return projectTaskStatusMasterPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return projectTaskStatusMasterPersistence.findByPrimaryKey(
			primaryKeyObj);
	}

	/**
	 * Returns a range of all the project task status masters.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.ax.hrms.master.model.impl.ProjectTaskStatusMasterModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of project task status masters
	 * @param end the upper bound of the range of project task status masters (not inclusive)
	 * @return the range of project task status masters
	 */
	@Override
	public List<ProjectTaskStatusMaster> getProjectTaskStatusMasters(
		int start, int end) {

		return projectTaskStatusMasterPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of project task status masters.
	 *
	 * @return the number of project task status masters
	 */
	@Override
	public int getProjectTaskStatusMastersCount() {
		return projectTaskStatusMasterPersistence.countAll();
	}

	/**
	 * Updates the project task status master in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ProjectTaskStatusMasterLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param projectTaskStatusMaster the project task status master
	 * @return the project task status master that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public ProjectTaskStatusMaster updateProjectTaskStatusMaster(
		ProjectTaskStatusMaster projectTaskStatusMaster) {

		return projectTaskStatusMasterPersistence.update(
			projectTaskStatusMaster);
	}

	@Deactivate
	protected void deactivate() {
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			ProjectTaskStatusMasterLocalService.class,
			IdentifiableOSGiService.class, PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		projectTaskStatusMasterLocalService =
			(ProjectTaskStatusMasterLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return ProjectTaskStatusMasterLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return ProjectTaskStatusMaster.class;
	}

	protected String getModelClassName() {
		return ProjectTaskStatusMaster.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				projectTaskStatusMasterPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected AppraisalStatusMasterPersistence appraisalStatusMasterPersistence;

	@Reference
	protected DepartmentMasterPersistence departmentMasterPersistence;

	@Reference
	protected DesignationMasterPersistence designationMasterPersistence;

	@Reference
	protected DocumentTypeMasterPersistence documentTypeMasterPersistence;

	@Reference
	protected EducationLevelMasterPersistence educationLevelMasterPersistence;

	@Reference
	protected LeaveCompensatoryStatusMasterPersistence
		leaveCompensatoryStatusMasterPersistence;

	@Reference
	protected LeavePolicyMasterPersistence leavePolicyMasterPersistence;

	@Reference
	protected LeaveTypeMasterPersistence leaveTypeMasterPersistence;

	@Reference
	protected PolicyTypeMasterPersistence policyTypeMasterPersistence;

	@Reference
	protected PriorityMasterPersistence priorityMasterPersistence;

	@Reference
	protected ProbationStatusMasterPersistence probationStatusMasterPersistence;

	protected ProjectTaskStatusMasterLocalService
		projectTaskStatusMasterLocalService;

	@Reference
	protected ProjectTaskStatusMasterPersistence
		projectTaskStatusMasterPersistence;

	@Reference
	protected TemplateLevelMasterPersistence templateLevelMasterPersistence;

	@Reference
	protected WishTypeMasterPersistence wishTypeMasterPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		ProjectTaskStatusMasterLocalServiceBaseImpl.class);

}