/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.model.impl;

import com.ax.hrms.model.AppraisalMeetingInvitees;
import com.ax.hrms.model.AppraisalMeetingInviteesModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the AppraisalMeetingInvitees service. Represents a row in the &quot;ax_AppraisalMeetingInvitees&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AppraisalMeetingInviteesModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AppraisalMeetingInviteesImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AppraisalMeetingInviteesImpl
 * @generated
 */
@JSON(strict = true)
public class AppraisalMeetingInviteesModelImpl
	extends BaseModelImpl<AppraisalMeetingInvitees>
	implements AppraisalMeetingInviteesModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a appraisal meeting invitees model instance should use the <code>AppraisalMeetingInvitees</code> interface instead.
	 */
	public static final String TABLE_NAME = "ax_AppraisalMeetingInvitees";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"companyId", Types.BIGINT},
		{"createdBy", Types.BIGINT}, {"modifiedBy", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP},
		{"appraisalMeetingInviteeId", Types.BIGINT},
		{"employeeId", Types.BIGINT}, {"appraisalMeetingId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("appraisalMeetingInviteeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("employeeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("appraisalMeetingId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ax_AppraisalMeetingInvitees (uuid_ VARCHAR(75) null,companyId LONG,createdBy LONG,modifiedBy LONG,groupId LONG,createDate DATE null,modifiedDate DATE null,appraisalMeetingInviteeId LONG not null primary key,employeeId LONG,appraisalMeetingId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table ax_AppraisalMeetingInvitees";

	public static final String ORDER_BY_JPQL =
		" ORDER BY appraisalMeetingInvitees.appraisalMeetingInviteeId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ax_AppraisalMeetingInvitees.appraisalMeetingInviteeId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long APPRAISALMEETINGID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long APPRAISALMEETINGINVITEEID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public AppraisalMeetingInviteesModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _appraisalMeetingInviteeId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAppraisalMeetingInviteeId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _appraisalMeetingInviteeId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AppraisalMeetingInvitees.class;
	}

	@Override
	public String getModelClassName() {
		return AppraisalMeetingInvitees.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<AppraisalMeetingInvitees, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<AppraisalMeetingInvitees, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AppraisalMeetingInvitees, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((AppraisalMeetingInvitees)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<AppraisalMeetingInvitees, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<AppraisalMeetingInvitees, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(AppraisalMeetingInvitees)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<AppraisalMeetingInvitees, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<AppraisalMeetingInvitees, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map
			<String, Function<AppraisalMeetingInvitees, Object>>
				_attributeGetterFunctions;

		static {
			Map<String, Function<AppraisalMeetingInvitees, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<AppraisalMeetingInvitees, Object>>();

			attributeGetterFunctions.put(
				"uuid", AppraisalMeetingInvitees::getUuid);
			attributeGetterFunctions.put(
				"companyId", AppraisalMeetingInvitees::getCompanyId);
			attributeGetterFunctions.put(
				"createdBy", AppraisalMeetingInvitees::getCreatedBy);
			attributeGetterFunctions.put(
				"modifiedBy", AppraisalMeetingInvitees::getModifiedBy);
			attributeGetterFunctions.put(
				"groupId", AppraisalMeetingInvitees::getGroupId);
			attributeGetterFunctions.put(
				"createDate", AppraisalMeetingInvitees::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", AppraisalMeetingInvitees::getModifiedDate);
			attributeGetterFunctions.put(
				"appraisalMeetingInviteeId",
				AppraisalMeetingInvitees::getAppraisalMeetingInviteeId);
			attributeGetterFunctions.put(
				"employeeId", AppraisalMeetingInvitees::getEmployeeId);
			attributeGetterFunctions.put(
				"appraisalMeetingId",
				AppraisalMeetingInvitees::getAppraisalMeetingId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<AppraisalMeetingInvitees, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<AppraisalMeetingInvitees, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<AppraisalMeetingInvitees, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<AppraisalMeetingInvitees, String>)
					AppraisalMeetingInvitees::setUuid);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<AppraisalMeetingInvitees, Long>)
					AppraisalMeetingInvitees::setCompanyId);
			attributeSetterBiConsumers.put(
				"createdBy",
				(BiConsumer<AppraisalMeetingInvitees, Long>)
					AppraisalMeetingInvitees::setCreatedBy);
			attributeSetterBiConsumers.put(
				"modifiedBy",
				(BiConsumer<AppraisalMeetingInvitees, Long>)
					AppraisalMeetingInvitees::setModifiedBy);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<AppraisalMeetingInvitees, Long>)
					AppraisalMeetingInvitees::setGroupId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<AppraisalMeetingInvitees, Date>)
					AppraisalMeetingInvitees::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<AppraisalMeetingInvitees, Date>)
					AppraisalMeetingInvitees::setModifiedDate);
			attributeSetterBiConsumers.put(
				"appraisalMeetingInviteeId",
				(BiConsumer<AppraisalMeetingInvitees, Long>)
					AppraisalMeetingInvitees::setAppraisalMeetingInviteeId);
			attributeSetterBiConsumers.put(
				"employeeId",
				(BiConsumer<AppraisalMeetingInvitees, Long>)
					AppraisalMeetingInvitees::setEmployeeId);
			attributeSetterBiConsumers.put(
				"appraisalMeetingId",
				(BiConsumer<AppraisalMeetingInvitees, Long>)
					AppraisalMeetingInvitees::setAppraisalMeetingId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getAppraisalMeetingInviteeId() {
		return _appraisalMeetingInviteeId;
	}

	@Override
	public void setAppraisalMeetingInviteeId(long appraisalMeetingInviteeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_appraisalMeetingInviteeId = appraisalMeetingInviteeId;
	}

	@JSON
	@Override
	public long getEmployeeId() {
		return _employeeId;
	}

	@Override
	public void setEmployeeId(long employeeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_employeeId = employeeId;
	}

	@JSON
	@Override
	public long getAppraisalMeetingId() {
		return _appraisalMeetingId;
	}

	@Override
	public void setAppraisalMeetingId(long appraisalMeetingId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_appraisalMeetingId = appraisalMeetingId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalAppraisalMeetingId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("appraisalMeetingId"));
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(
				AppraisalMeetingInvitees.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), AppraisalMeetingInvitees.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AppraisalMeetingInvitees toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, AppraisalMeetingInvitees>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AppraisalMeetingInviteesImpl appraisalMeetingInviteesImpl =
			new AppraisalMeetingInviteesImpl();

		appraisalMeetingInviteesImpl.setUuid(getUuid());
		appraisalMeetingInviteesImpl.setCompanyId(getCompanyId());
		appraisalMeetingInviteesImpl.setCreatedBy(getCreatedBy());
		appraisalMeetingInviteesImpl.setModifiedBy(getModifiedBy());
		appraisalMeetingInviteesImpl.setGroupId(getGroupId());
		appraisalMeetingInviteesImpl.setCreateDate(getCreateDate());
		appraisalMeetingInviteesImpl.setModifiedDate(getModifiedDate());
		appraisalMeetingInviteesImpl.setAppraisalMeetingInviteeId(
			getAppraisalMeetingInviteeId());
		appraisalMeetingInviteesImpl.setEmployeeId(getEmployeeId());
		appraisalMeetingInviteesImpl.setAppraisalMeetingId(
			getAppraisalMeetingId());

		appraisalMeetingInviteesImpl.resetOriginalValues();

		return appraisalMeetingInviteesImpl;
	}

	@Override
	public AppraisalMeetingInvitees cloneWithOriginalValues() {
		AppraisalMeetingInviteesImpl appraisalMeetingInviteesImpl =
			new AppraisalMeetingInviteesImpl();

		appraisalMeetingInviteesImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		appraisalMeetingInviteesImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		appraisalMeetingInviteesImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("createdBy"));
		appraisalMeetingInviteesImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modifiedBy"));
		appraisalMeetingInviteesImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		appraisalMeetingInviteesImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		appraisalMeetingInviteesImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		appraisalMeetingInviteesImpl.setAppraisalMeetingInviteeId(
			this.<Long>getColumnOriginalValue("appraisalMeetingInviteeId"));
		appraisalMeetingInviteesImpl.setEmployeeId(
			this.<Long>getColumnOriginalValue("employeeId"));
		appraisalMeetingInviteesImpl.setAppraisalMeetingId(
			this.<Long>getColumnOriginalValue("appraisalMeetingId"));

		return appraisalMeetingInviteesImpl;
	}

	@Override
	public int compareTo(AppraisalMeetingInvitees appraisalMeetingInvitees) {
		long primaryKey = appraisalMeetingInvitees.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof AppraisalMeetingInvitees)) {
			return false;
		}

		AppraisalMeetingInvitees appraisalMeetingInvitees =
			(AppraisalMeetingInvitees)object;

		long primaryKey = appraisalMeetingInvitees.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<AppraisalMeetingInvitees> toCacheModel() {
		AppraisalMeetingInviteesCacheModel appraisalMeetingInviteesCacheModel =
			new AppraisalMeetingInviteesCacheModel();

		appraisalMeetingInviteesCacheModel.uuid = getUuid();

		String uuid = appraisalMeetingInviteesCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			appraisalMeetingInviteesCacheModel.uuid = null;
		}

		appraisalMeetingInviteesCacheModel.companyId = getCompanyId();

		appraisalMeetingInviteesCacheModel.createdBy = getCreatedBy();

		appraisalMeetingInviteesCacheModel.modifiedBy = getModifiedBy();

		appraisalMeetingInviteesCacheModel.groupId = getGroupId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			appraisalMeetingInviteesCacheModel.createDate =
				createDate.getTime();
		}
		else {
			appraisalMeetingInviteesCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			appraisalMeetingInviteesCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			appraisalMeetingInviteesCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		appraisalMeetingInviteesCacheModel.appraisalMeetingInviteeId =
			getAppraisalMeetingInviteeId();

		appraisalMeetingInviteesCacheModel.employeeId = getEmployeeId();

		appraisalMeetingInviteesCacheModel.appraisalMeetingId =
			getAppraisalMeetingId();

		return appraisalMeetingInviteesCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<AppraisalMeetingInvitees, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<AppraisalMeetingInvitees, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AppraisalMeetingInvitees, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(AppraisalMeetingInvitees)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, AppraisalMeetingInvitees>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						AppraisalMeetingInvitees.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _companyId;
	private long _createdBy;
	private long _modifiedBy;
	private long _groupId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _appraisalMeetingInviteeId;
	private long _employeeId;
	private long _appraisalMeetingId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<AppraisalMeetingInvitees, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((AppraisalMeetingInvitees)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createdBy", _createdBy);
		_columnOriginalValues.put("modifiedBy", _modifiedBy);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put(
			"appraisalMeetingInviteeId", _appraisalMeetingInviteeId);
		_columnOriginalValues.put("employeeId", _employeeId);
		_columnOriginalValues.put("appraisalMeetingId", _appraisalMeetingId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("createdBy", 4L);

		columnBitmasks.put("modifiedBy", 8L);

		columnBitmasks.put("groupId", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("appraisalMeetingInviteeId", 128L);

		columnBitmasks.put("employeeId", 256L);

		columnBitmasks.put("appraisalMeetingId", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private AppraisalMeetingInvitees _escapedModel;

}