/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.model.impl;

import com.ax.hrms.model.AppraisalProcess;
import com.ax.hrms.service.AppraisalProcessLocalServiceUtil;

/**
 * The extended model base implementation for the AppraisalProcess service. Represents a row in the &quot;ax_AppraisalProcess&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AppraisalProcessImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AppraisalProcessImpl
 * @see AppraisalProcess
 * @generated
 */
public abstract class AppraisalProcessBaseImpl
	extends AppraisalProcessModelImpl implements AppraisalProcess {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a appraisal process model instance should use the <code>AppraisalProcess</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			AppraisalProcessLocalServiceUtil.addAppraisalProcess(this);
		}
		else {
			AppraisalProcessLocalServiceUtil.updateAppraisalProcess(this);
		}
	}

}