/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.model.impl;

import com.ax.hrms.model.AppraisalHistory;
import com.ax.hrms.model.AppraisalHistoryModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the AppraisalHistory service. Represents a row in the &quot;ax_AppraisalHistory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AppraisalHistoryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AppraisalHistoryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AppraisalHistoryImpl
 * @generated
 */
@JSON(strict = true)
public class AppraisalHistoryModelImpl
	extends BaseModelImpl<AppraisalHistory> implements AppraisalHistoryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a appraisal history model instance should use the <code>AppraisalHistory</code> interface instead.
	 */
	public static final String TABLE_NAME = "ax_AppraisalHistory";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"companyId", Types.BIGINT},
		{"createdBy", Types.BIGINT}, {"modifiedBy", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"appraisalId", Types.BIGINT},
		{"salaryId", Types.BIGINT}, {"appraisalDate", Types.TIMESTAMP},
		{"appraisalDocumentId", Types.BIGINT}, {"updatedCtcPa", Types.DOUBLE},
		{"updatedCtcPm", Types.DOUBLE}, {"rating", Types.DOUBLE},
		{"comments", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("appraisalId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("salaryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("appraisalDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("appraisalDocumentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("updatedCtcPa", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("updatedCtcPm", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("rating", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("comments", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ax_AppraisalHistory (uuid_ VARCHAR(75) null,companyId LONG,createdBy LONG,modifiedBy LONG,groupId LONG,createDate DATE null,modifiedDate DATE null,appraisalId LONG not null primary key,salaryId LONG,appraisalDate DATE null,appraisalDocumentId LONG,updatedCtcPa DOUBLE,updatedCtcPm DOUBLE,rating DOUBLE,comments VARCHAR(1000) null)";

	public static final String TABLE_SQL_DROP =
		"drop table ax_AppraisalHistory";

	public static final String ORDER_BY_JPQL =
		" ORDER BY appraisalHistory.appraisalId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ax_AppraisalHistory.appraisalId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long APPRAISALID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public AppraisalHistoryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _appraisalId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAppraisalId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _appraisalId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AppraisalHistory.class;
	}

	@Override
	public String getModelClassName() {
		return AppraisalHistory.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<AppraisalHistory, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<AppraisalHistory, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AppraisalHistory, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((AppraisalHistory)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<AppraisalHistory, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<AppraisalHistory, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(AppraisalHistory)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<AppraisalHistory, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<AppraisalHistory, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<AppraisalHistory, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<AppraisalHistory, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<AppraisalHistory, Object>>();

			attributeGetterFunctions.put("uuid", AppraisalHistory::getUuid);
			attributeGetterFunctions.put(
				"companyId", AppraisalHistory::getCompanyId);
			attributeGetterFunctions.put(
				"createdBy", AppraisalHistory::getCreatedBy);
			attributeGetterFunctions.put(
				"modifiedBy", AppraisalHistory::getModifiedBy);
			attributeGetterFunctions.put(
				"groupId", AppraisalHistory::getGroupId);
			attributeGetterFunctions.put(
				"createDate", AppraisalHistory::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", AppraisalHistory::getModifiedDate);
			attributeGetterFunctions.put(
				"appraisalId", AppraisalHistory::getAppraisalId);
			attributeGetterFunctions.put(
				"salaryId", AppraisalHistory::getSalaryId);
			attributeGetterFunctions.put(
				"appraisalDate", AppraisalHistory::getAppraisalDate);
			attributeGetterFunctions.put(
				"appraisalDocumentId",
				AppraisalHistory::getAppraisalDocumentId);
			attributeGetterFunctions.put(
				"updatedCtcPa", AppraisalHistory::getUpdatedCtcPa);
			attributeGetterFunctions.put(
				"updatedCtcPm", AppraisalHistory::getUpdatedCtcPm);
			attributeGetterFunctions.put("rating", AppraisalHistory::getRating);
			attributeGetterFunctions.put(
				"comments", AppraisalHistory::getComments);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<AppraisalHistory, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<AppraisalHistory, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<AppraisalHistory, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<AppraisalHistory, String>)
					AppraisalHistory::setUuid);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<AppraisalHistory, Long>)
					AppraisalHistory::setCompanyId);
			attributeSetterBiConsumers.put(
				"createdBy",
				(BiConsumer<AppraisalHistory, Long>)
					AppraisalHistory::setCreatedBy);
			attributeSetterBiConsumers.put(
				"modifiedBy",
				(BiConsumer<AppraisalHistory, Long>)
					AppraisalHistory::setModifiedBy);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<AppraisalHistory, Long>)
					AppraisalHistory::setGroupId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<AppraisalHistory, Date>)
					AppraisalHistory::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<AppraisalHistory, Date>)
					AppraisalHistory::setModifiedDate);
			attributeSetterBiConsumers.put(
				"appraisalId",
				(BiConsumer<AppraisalHistory, Long>)
					AppraisalHistory::setAppraisalId);
			attributeSetterBiConsumers.put(
				"salaryId",
				(BiConsumer<AppraisalHistory, Long>)
					AppraisalHistory::setSalaryId);
			attributeSetterBiConsumers.put(
				"appraisalDate",
				(BiConsumer<AppraisalHistory, Date>)
					AppraisalHistory::setAppraisalDate);
			attributeSetterBiConsumers.put(
				"appraisalDocumentId",
				(BiConsumer<AppraisalHistory, Long>)
					AppraisalHistory::setAppraisalDocumentId);
			attributeSetterBiConsumers.put(
				"updatedCtcPa",
				(BiConsumer<AppraisalHistory, Double>)
					AppraisalHistory::setUpdatedCtcPa);
			attributeSetterBiConsumers.put(
				"updatedCtcPm",
				(BiConsumer<AppraisalHistory, Double>)
					AppraisalHistory::setUpdatedCtcPm);
			attributeSetterBiConsumers.put(
				"rating",
				(BiConsumer<AppraisalHistory, Double>)
					AppraisalHistory::setRating);
			attributeSetterBiConsumers.put(
				"comments",
				(BiConsumer<AppraisalHistory, String>)
					AppraisalHistory::setComments);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getAppraisalId() {
		return _appraisalId;
	}

	@Override
	public void setAppraisalId(long appraisalId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_appraisalId = appraisalId;
	}

	@JSON
	@Override
	public long getSalaryId() {
		return _salaryId;
	}

	@Override
	public void setSalaryId(long salaryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_salaryId = salaryId;
	}

	@JSON
	@Override
	public Date getAppraisalDate() {
		return _appraisalDate;
	}

	@Override
	public void setAppraisalDate(Date appraisalDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_appraisalDate = appraisalDate;
	}

	@JSON
	@Override
	public long getAppraisalDocumentId() {
		return _appraisalDocumentId;
	}

	@Override
	public void setAppraisalDocumentId(long appraisalDocumentId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_appraisalDocumentId = appraisalDocumentId;
	}

	@JSON
	@Override
	public double getUpdatedCtcPa() {
		return _updatedCtcPa;
	}

	@Override
	public void setUpdatedCtcPa(double updatedCtcPa) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_updatedCtcPa = updatedCtcPa;
	}

	@JSON
	@Override
	public double getUpdatedCtcPm() {
		return _updatedCtcPm;
	}

	@Override
	public void setUpdatedCtcPm(double updatedCtcPm) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_updatedCtcPm = updatedCtcPm;
	}

	@JSON
	@Override
	public double getRating() {
		return _rating;
	}

	@Override
	public void setRating(double rating) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_rating = rating;
	}

	@JSON
	@Override
	public String getComments() {
		if (_comments == null) {
			return "";
		}
		else {
			return _comments;
		}
	}

	@Override
	public void setComments(String comments) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_comments = comments;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(AppraisalHistory.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), AppraisalHistory.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AppraisalHistory toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, AppraisalHistory>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AppraisalHistoryImpl appraisalHistoryImpl = new AppraisalHistoryImpl();

		appraisalHistoryImpl.setUuid(getUuid());
		appraisalHistoryImpl.setCompanyId(getCompanyId());
		appraisalHistoryImpl.setCreatedBy(getCreatedBy());
		appraisalHistoryImpl.setModifiedBy(getModifiedBy());
		appraisalHistoryImpl.setGroupId(getGroupId());
		appraisalHistoryImpl.setCreateDate(getCreateDate());
		appraisalHistoryImpl.setModifiedDate(getModifiedDate());
		appraisalHistoryImpl.setAppraisalId(getAppraisalId());
		appraisalHistoryImpl.setSalaryId(getSalaryId());
		appraisalHistoryImpl.setAppraisalDate(getAppraisalDate());
		appraisalHistoryImpl.setAppraisalDocumentId(getAppraisalDocumentId());
		appraisalHistoryImpl.setUpdatedCtcPa(getUpdatedCtcPa());
		appraisalHistoryImpl.setUpdatedCtcPm(getUpdatedCtcPm());
		appraisalHistoryImpl.setRating(getRating());
		appraisalHistoryImpl.setComments(getComments());

		appraisalHistoryImpl.resetOriginalValues();

		return appraisalHistoryImpl;
	}

	@Override
	public AppraisalHistory cloneWithOriginalValues() {
		AppraisalHistoryImpl appraisalHistoryImpl = new AppraisalHistoryImpl();

		appraisalHistoryImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		appraisalHistoryImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		appraisalHistoryImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("createdBy"));
		appraisalHistoryImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modifiedBy"));
		appraisalHistoryImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		appraisalHistoryImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		appraisalHistoryImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		appraisalHistoryImpl.setAppraisalId(
			this.<Long>getColumnOriginalValue("appraisalId"));
		appraisalHistoryImpl.setSalaryId(
			this.<Long>getColumnOriginalValue("salaryId"));
		appraisalHistoryImpl.setAppraisalDate(
			this.<Date>getColumnOriginalValue("appraisalDate"));
		appraisalHistoryImpl.setAppraisalDocumentId(
			this.<Long>getColumnOriginalValue("appraisalDocumentId"));
		appraisalHistoryImpl.setUpdatedCtcPa(
			this.<Double>getColumnOriginalValue("updatedCtcPa"));
		appraisalHistoryImpl.setUpdatedCtcPm(
			this.<Double>getColumnOriginalValue("updatedCtcPm"));
		appraisalHistoryImpl.setRating(
			this.<Double>getColumnOriginalValue("rating"));
		appraisalHistoryImpl.setComments(
			this.<String>getColumnOriginalValue("comments"));

		return appraisalHistoryImpl;
	}

	@Override
	public int compareTo(AppraisalHistory appraisalHistory) {
		long primaryKey = appraisalHistory.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof AppraisalHistory)) {
			return false;
		}

		AppraisalHistory appraisalHistory = (AppraisalHistory)object;

		long primaryKey = appraisalHistory.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<AppraisalHistory> toCacheModel() {
		AppraisalHistoryCacheModel appraisalHistoryCacheModel =
			new AppraisalHistoryCacheModel();

		appraisalHistoryCacheModel.uuid = getUuid();

		String uuid = appraisalHistoryCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			appraisalHistoryCacheModel.uuid = null;
		}

		appraisalHistoryCacheModel.companyId = getCompanyId();

		appraisalHistoryCacheModel.createdBy = getCreatedBy();

		appraisalHistoryCacheModel.modifiedBy = getModifiedBy();

		appraisalHistoryCacheModel.groupId = getGroupId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			appraisalHistoryCacheModel.createDate = createDate.getTime();
		}
		else {
			appraisalHistoryCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			appraisalHistoryCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			appraisalHistoryCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		appraisalHistoryCacheModel.appraisalId = getAppraisalId();

		appraisalHistoryCacheModel.salaryId = getSalaryId();

		Date appraisalDate = getAppraisalDate();

		if (appraisalDate != null) {
			appraisalHistoryCacheModel.appraisalDate = appraisalDate.getTime();
		}
		else {
			appraisalHistoryCacheModel.appraisalDate = Long.MIN_VALUE;
		}

		appraisalHistoryCacheModel.appraisalDocumentId =
			getAppraisalDocumentId();

		appraisalHistoryCacheModel.updatedCtcPa = getUpdatedCtcPa();

		appraisalHistoryCacheModel.updatedCtcPm = getUpdatedCtcPm();

		appraisalHistoryCacheModel.rating = getRating();

		appraisalHistoryCacheModel.comments = getComments();

		String comments = appraisalHistoryCacheModel.comments;

		if ((comments != null) && (comments.length() == 0)) {
			appraisalHistoryCacheModel.comments = null;
		}

		return appraisalHistoryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<AppraisalHistory, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<AppraisalHistory, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AppraisalHistory, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(AppraisalHistory)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, AppraisalHistory>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					AppraisalHistory.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _companyId;
	private long _createdBy;
	private long _modifiedBy;
	private long _groupId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _appraisalId;
	private long _salaryId;
	private Date _appraisalDate;
	private long _appraisalDocumentId;
	private double _updatedCtcPa;
	private double _updatedCtcPm;
	private double _rating;
	private String _comments;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<AppraisalHistory, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((AppraisalHistory)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createdBy", _createdBy);
		_columnOriginalValues.put("modifiedBy", _modifiedBy);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("appraisalId", _appraisalId);
		_columnOriginalValues.put("salaryId", _salaryId);
		_columnOriginalValues.put("appraisalDate", _appraisalDate);
		_columnOriginalValues.put("appraisalDocumentId", _appraisalDocumentId);
		_columnOriginalValues.put("updatedCtcPa", _updatedCtcPa);
		_columnOriginalValues.put("updatedCtcPm", _updatedCtcPm);
		_columnOriginalValues.put("rating", _rating);
		_columnOriginalValues.put("comments", _comments);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("createdBy", 4L);

		columnBitmasks.put("modifiedBy", 8L);

		columnBitmasks.put("groupId", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("appraisalId", 128L);

		columnBitmasks.put("salaryId", 256L);

		columnBitmasks.put("appraisalDate", 512L);

		columnBitmasks.put("appraisalDocumentId", 1024L);

		columnBitmasks.put("updatedCtcPa", 2048L);

		columnBitmasks.put("updatedCtcPm", 4096L);

		columnBitmasks.put("rating", 8192L);

		columnBitmasks.put("comments", 16384L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private AppraisalHistory _escapedModel;

}