/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.model.impl;

import com.ax.hrms.model.AppraisalReminder;
import com.ax.hrms.model.AppraisalReminderModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the AppraisalReminder service. Represents a row in the &quot;ax_AppraisalReminder&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AppraisalReminderModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AppraisalReminderImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AppraisalReminderImpl
 * @generated
 */
@JSON(strict = true)
public class AppraisalReminderModelImpl
	extends BaseModelImpl<AppraisalReminder> implements AppraisalReminderModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a appraisal reminder model instance should use the <code>AppraisalReminder</code> interface instead.
	 */
	public static final String TABLE_NAME = "ax_AppraisalReminder";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"companyId", Types.BIGINT},
		{"createdBy", Types.BIGINT}, {"modifiedBy", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP},
		{"appraisalRemainderId", Types.BIGINT}, {"employeeId", Types.BIGINT},
		{"appraisalRemainderMonth", Types.VARCHAR},
		{"appraisalRemainderYear", Types.VARCHAR},
		{"appraisalProcessId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("appraisalRemainderId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("employeeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("appraisalRemainderMonth", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("appraisalRemainderYear", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("appraisalProcessId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ax_AppraisalReminder (uuid_ VARCHAR(75) null,companyId LONG,createdBy LONG,modifiedBy LONG,groupId LONG,createDate DATE null,modifiedDate DATE null,appraisalRemainderId LONG not null primary key,employeeId LONG,appraisalRemainderMonth VARCHAR(75) null,appraisalRemainderYear VARCHAR(75) null,appraisalProcessId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table ax_AppraisalReminder";

	public static final String ORDER_BY_JPQL =
		" ORDER BY appraisalReminder.appraisalRemainderId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ax_AppraisalReminder.appraisalRemainderId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long APPRAISALPROCESSID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long APPRAISALREMAINDERID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public AppraisalReminderModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _appraisalRemainderId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAppraisalRemainderId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _appraisalRemainderId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AppraisalReminder.class;
	}

	@Override
	public String getModelClassName() {
		return AppraisalReminder.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<AppraisalReminder, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<AppraisalReminder, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AppraisalReminder, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((AppraisalReminder)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<AppraisalReminder, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<AppraisalReminder, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(AppraisalReminder)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<AppraisalReminder, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<AppraisalReminder, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<AppraisalReminder, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<AppraisalReminder, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<AppraisalReminder, Object>>();

			attributeGetterFunctions.put("uuid", AppraisalReminder::getUuid);
			attributeGetterFunctions.put(
				"companyId", AppraisalReminder::getCompanyId);
			attributeGetterFunctions.put(
				"createdBy", AppraisalReminder::getCreatedBy);
			attributeGetterFunctions.put(
				"modifiedBy", AppraisalReminder::getModifiedBy);
			attributeGetterFunctions.put(
				"groupId", AppraisalReminder::getGroupId);
			attributeGetterFunctions.put(
				"createDate", AppraisalReminder::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", AppraisalReminder::getModifiedDate);
			attributeGetterFunctions.put(
				"appraisalRemainderId",
				AppraisalReminder::getAppraisalRemainderId);
			attributeGetterFunctions.put(
				"employeeId", AppraisalReminder::getEmployeeId);
			attributeGetterFunctions.put(
				"appraisalRemainderMonth",
				AppraisalReminder::getAppraisalRemainderMonth);
			attributeGetterFunctions.put(
				"appraisalRemainderYear",
				AppraisalReminder::getAppraisalRemainderYear);
			attributeGetterFunctions.put(
				"appraisalProcessId", AppraisalReminder::getAppraisalProcessId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<AppraisalReminder, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<AppraisalReminder, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<AppraisalReminder, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<AppraisalReminder, String>)
					AppraisalReminder::setUuid);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<AppraisalReminder, Long>)
					AppraisalReminder::setCompanyId);
			attributeSetterBiConsumers.put(
				"createdBy",
				(BiConsumer<AppraisalReminder, Long>)
					AppraisalReminder::setCreatedBy);
			attributeSetterBiConsumers.put(
				"modifiedBy",
				(BiConsumer<AppraisalReminder, Long>)
					AppraisalReminder::setModifiedBy);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<AppraisalReminder, Long>)
					AppraisalReminder::setGroupId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<AppraisalReminder, Date>)
					AppraisalReminder::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<AppraisalReminder, Date>)
					AppraisalReminder::setModifiedDate);
			attributeSetterBiConsumers.put(
				"appraisalRemainderId",
				(BiConsumer<AppraisalReminder, Long>)
					AppraisalReminder::setAppraisalRemainderId);
			attributeSetterBiConsumers.put(
				"employeeId",
				(BiConsumer<AppraisalReminder, Long>)
					AppraisalReminder::setEmployeeId);
			attributeSetterBiConsumers.put(
				"appraisalRemainderMonth",
				(BiConsumer<AppraisalReminder, String>)
					AppraisalReminder::setAppraisalRemainderMonth);
			attributeSetterBiConsumers.put(
				"appraisalRemainderYear",
				(BiConsumer<AppraisalReminder, String>)
					AppraisalReminder::setAppraisalRemainderYear);
			attributeSetterBiConsumers.put(
				"appraisalProcessId",
				(BiConsumer<AppraisalReminder, Long>)
					AppraisalReminder::setAppraisalProcessId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getAppraisalRemainderId() {
		return _appraisalRemainderId;
	}

	@Override
	public void setAppraisalRemainderId(long appraisalRemainderId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_appraisalRemainderId = appraisalRemainderId;
	}

	@JSON
	@Override
	public long getEmployeeId() {
		return _employeeId;
	}

	@Override
	public void setEmployeeId(long employeeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_employeeId = employeeId;
	}

	@JSON
	@Override
	public String getAppraisalRemainderMonth() {
		if (_appraisalRemainderMonth == null) {
			return "";
		}
		else {
			return _appraisalRemainderMonth;
		}
	}

	@Override
	public void setAppraisalRemainderMonth(String appraisalRemainderMonth) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_appraisalRemainderMonth = appraisalRemainderMonth;
	}

	@JSON
	@Override
	public String getAppraisalRemainderYear() {
		if (_appraisalRemainderYear == null) {
			return "";
		}
		else {
			return _appraisalRemainderYear;
		}
	}

	@Override
	public void setAppraisalRemainderYear(String appraisalRemainderYear) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_appraisalRemainderYear = appraisalRemainderYear;
	}

	@JSON
	@Override
	public long getAppraisalProcessId() {
		return _appraisalProcessId;
	}

	@Override
	public void setAppraisalProcessId(long appraisalProcessId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_appraisalProcessId = appraisalProcessId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalAppraisalProcessId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("appraisalProcessId"));
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(AppraisalReminder.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), AppraisalReminder.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AppraisalReminder toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, AppraisalReminder>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AppraisalReminderImpl appraisalReminderImpl =
			new AppraisalReminderImpl();

		appraisalReminderImpl.setUuid(getUuid());
		appraisalReminderImpl.setCompanyId(getCompanyId());
		appraisalReminderImpl.setCreatedBy(getCreatedBy());
		appraisalReminderImpl.setModifiedBy(getModifiedBy());
		appraisalReminderImpl.setGroupId(getGroupId());
		appraisalReminderImpl.setCreateDate(getCreateDate());
		appraisalReminderImpl.setModifiedDate(getModifiedDate());
		appraisalReminderImpl.setAppraisalRemainderId(
			getAppraisalRemainderId());
		appraisalReminderImpl.setEmployeeId(getEmployeeId());
		appraisalReminderImpl.setAppraisalRemainderMonth(
			getAppraisalRemainderMonth());
		appraisalReminderImpl.setAppraisalRemainderYear(
			getAppraisalRemainderYear());
		appraisalReminderImpl.setAppraisalProcessId(getAppraisalProcessId());

		appraisalReminderImpl.resetOriginalValues();

		return appraisalReminderImpl;
	}

	@Override
	public AppraisalReminder cloneWithOriginalValues() {
		AppraisalReminderImpl appraisalReminderImpl =
			new AppraisalReminderImpl();

		appraisalReminderImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		appraisalReminderImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		appraisalReminderImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("createdBy"));
		appraisalReminderImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modifiedBy"));
		appraisalReminderImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		appraisalReminderImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		appraisalReminderImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		appraisalReminderImpl.setAppraisalRemainderId(
			this.<Long>getColumnOriginalValue("appraisalRemainderId"));
		appraisalReminderImpl.setEmployeeId(
			this.<Long>getColumnOriginalValue("employeeId"));
		appraisalReminderImpl.setAppraisalRemainderMonth(
			this.<String>getColumnOriginalValue("appraisalRemainderMonth"));
		appraisalReminderImpl.setAppraisalRemainderYear(
			this.<String>getColumnOriginalValue("appraisalRemainderYear"));
		appraisalReminderImpl.setAppraisalProcessId(
			this.<Long>getColumnOriginalValue("appraisalProcessId"));

		return appraisalReminderImpl;
	}

	@Override
	public int compareTo(AppraisalReminder appraisalReminder) {
		long primaryKey = appraisalReminder.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof AppraisalReminder)) {
			return false;
		}

		AppraisalReminder appraisalReminder = (AppraisalReminder)object;

		long primaryKey = appraisalReminder.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<AppraisalReminder> toCacheModel() {
		AppraisalReminderCacheModel appraisalReminderCacheModel =
			new AppraisalReminderCacheModel();

		appraisalReminderCacheModel.uuid = getUuid();

		String uuid = appraisalReminderCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			appraisalReminderCacheModel.uuid = null;
		}

		appraisalReminderCacheModel.companyId = getCompanyId();

		appraisalReminderCacheModel.createdBy = getCreatedBy();

		appraisalReminderCacheModel.modifiedBy = getModifiedBy();

		appraisalReminderCacheModel.groupId = getGroupId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			appraisalReminderCacheModel.createDate = createDate.getTime();
		}
		else {
			appraisalReminderCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			appraisalReminderCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			appraisalReminderCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		appraisalReminderCacheModel.appraisalRemainderId =
			getAppraisalRemainderId();

		appraisalReminderCacheModel.employeeId = getEmployeeId();

		appraisalReminderCacheModel.appraisalRemainderMonth =
			getAppraisalRemainderMonth();

		String appraisalRemainderMonth =
			appraisalReminderCacheModel.appraisalRemainderMonth;

		if ((appraisalRemainderMonth != null) &&
			(appraisalRemainderMonth.length() == 0)) {

			appraisalReminderCacheModel.appraisalRemainderMonth = null;
		}

		appraisalReminderCacheModel.appraisalRemainderYear =
			getAppraisalRemainderYear();

		String appraisalRemainderYear =
			appraisalReminderCacheModel.appraisalRemainderYear;

		if ((appraisalRemainderYear != null) &&
			(appraisalRemainderYear.length() == 0)) {

			appraisalReminderCacheModel.appraisalRemainderYear = null;
		}

		appraisalReminderCacheModel.appraisalProcessId =
			getAppraisalProcessId();

		return appraisalReminderCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<AppraisalReminder, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<AppraisalReminder, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AppraisalReminder, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(AppraisalReminder)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, AppraisalReminder>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					AppraisalReminder.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _companyId;
	private long _createdBy;
	private long _modifiedBy;
	private long _groupId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _appraisalRemainderId;
	private long _employeeId;
	private String _appraisalRemainderMonth;
	private String _appraisalRemainderYear;
	private long _appraisalProcessId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<AppraisalReminder, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((AppraisalReminder)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createdBy", _createdBy);
		_columnOriginalValues.put("modifiedBy", _modifiedBy);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put(
			"appraisalRemainderId", _appraisalRemainderId);
		_columnOriginalValues.put("employeeId", _employeeId);
		_columnOriginalValues.put(
			"appraisalRemainderMonth", _appraisalRemainderMonth);
		_columnOriginalValues.put(
			"appraisalRemainderYear", _appraisalRemainderYear);
		_columnOriginalValues.put("appraisalProcessId", _appraisalProcessId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("createdBy", 4L);

		columnBitmasks.put("modifiedBy", 8L);

		columnBitmasks.put("groupId", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("appraisalRemainderId", 128L);

		columnBitmasks.put("employeeId", 256L);

		columnBitmasks.put("appraisalRemainderMonth", 512L);

		columnBitmasks.put("appraisalRemainderYear", 1024L);

		columnBitmasks.put("appraisalProcessId", 2048L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private AppraisalReminder _escapedModel;

}