/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.model.impl;

import com.ax.hrms.model.AppraisalProcess;
import com.ax.hrms.model.AppraisalProcessModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the AppraisalProcess service. Represents a row in the &quot;ax_AppraisalProcess&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AppraisalProcessModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AppraisalProcessImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AppraisalProcessImpl
 * @generated
 */
@JSON(strict = true)
public class AppraisalProcessModelImpl
	extends BaseModelImpl<AppraisalProcess> implements AppraisalProcessModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a appraisal process model instance should use the <code>AppraisalProcess</code> interface instead.
	 */
	public static final String TABLE_NAME = "ax_AppraisalProcess";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"companyId", Types.BIGINT},
		{"createdBy", Types.BIGINT}, {"modifiedBy", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"appraisalProcessId", Types.BIGINT},
		{"isSelfEvalutionFormSent", Types.BOOLEAN},
		{"isSelfEvalutionFormFilled", Types.BOOLEAN},
		{"arePeerEvaluationFormSent", Types.BOOLEAN},
		{"arePeerEvaluationFormFilled", Types.BOOLEAN},
		{"isManagementFormSent", Types.BOOLEAN},
		{"isManagementFormFilled", Types.BOOLEAN},
		{"isMeetingScheduled", Types.BOOLEAN}, {"isMeetingDone", Types.BOOLEAN},
		{"isSalaryUpdated", Types.BOOLEAN}, {"status", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("appraisalProcessId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("isSelfEvalutionFormSent", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("isSelfEvalutionFormFilled", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("arePeerEvaluationFormSent", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("arePeerEvaluationFormFilled", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("isManagementFormSent", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("isManagementFormFilled", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("isMeetingScheduled", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("isMeetingDone", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("isSalaryUpdated", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("status", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ax_AppraisalProcess (uuid_ VARCHAR(75) null,companyId LONG,createdBy LONG,modifiedBy LONG,groupId LONG,createDate DATE null,modifiedDate DATE null,appraisalProcessId LONG not null primary key,isSelfEvalutionFormSent BOOLEAN,isSelfEvalutionFormFilled BOOLEAN,arePeerEvaluationFormSent BOOLEAN,arePeerEvaluationFormFilled BOOLEAN,isManagementFormSent BOOLEAN,isManagementFormFilled BOOLEAN,isMeetingScheduled BOOLEAN,isMeetingDone BOOLEAN,isSalaryUpdated BOOLEAN,status LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table ax_AppraisalProcess";

	public static final String ORDER_BY_JPQL =
		" ORDER BY appraisalProcess.appraisalProcessId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ax_AppraisalProcess.appraisalProcessId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long APPRAISALPROCESSID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public AppraisalProcessModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _appraisalProcessId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAppraisalProcessId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _appraisalProcessId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AppraisalProcess.class;
	}

	@Override
	public String getModelClassName() {
		return AppraisalProcess.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<AppraisalProcess, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<AppraisalProcess, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AppraisalProcess, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((AppraisalProcess)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<AppraisalProcess, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<AppraisalProcess, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(AppraisalProcess)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<AppraisalProcess, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<AppraisalProcess, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<AppraisalProcess, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<AppraisalProcess, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<AppraisalProcess, Object>>();

			attributeGetterFunctions.put("uuid", AppraisalProcess::getUuid);
			attributeGetterFunctions.put(
				"companyId", AppraisalProcess::getCompanyId);
			attributeGetterFunctions.put(
				"createdBy", AppraisalProcess::getCreatedBy);
			attributeGetterFunctions.put(
				"modifiedBy", AppraisalProcess::getModifiedBy);
			attributeGetterFunctions.put(
				"groupId", AppraisalProcess::getGroupId);
			attributeGetterFunctions.put(
				"createDate", AppraisalProcess::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", AppraisalProcess::getModifiedDate);
			attributeGetterFunctions.put(
				"appraisalProcessId", AppraisalProcess::getAppraisalProcessId);
			attributeGetterFunctions.put(
				"isSelfEvalutionFormSent",
				AppraisalProcess::getIsSelfEvalutionFormSent);
			attributeGetterFunctions.put(
				"isSelfEvalutionFormFilled",
				AppraisalProcess::getIsSelfEvalutionFormFilled);
			attributeGetterFunctions.put(
				"arePeerEvaluationFormSent",
				AppraisalProcess::getArePeerEvaluationFormSent);
			attributeGetterFunctions.put(
				"arePeerEvaluationFormFilled",
				AppraisalProcess::getArePeerEvaluationFormFilled);
			attributeGetterFunctions.put(
				"isManagementFormSent",
				AppraisalProcess::getIsManagementFormSent);
			attributeGetterFunctions.put(
				"isManagementFormFilled",
				AppraisalProcess::getIsManagementFormFilled);
			attributeGetterFunctions.put(
				"isMeetingScheduled", AppraisalProcess::getIsMeetingScheduled);
			attributeGetterFunctions.put(
				"isMeetingDone", AppraisalProcess::getIsMeetingDone);
			attributeGetterFunctions.put(
				"isSalaryUpdated", AppraisalProcess::getIsSalaryUpdated);
			attributeGetterFunctions.put("status", AppraisalProcess::getStatus);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<AppraisalProcess, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<AppraisalProcess, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<AppraisalProcess, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<AppraisalProcess, String>)
					AppraisalProcess::setUuid);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<AppraisalProcess, Long>)
					AppraisalProcess::setCompanyId);
			attributeSetterBiConsumers.put(
				"createdBy",
				(BiConsumer<AppraisalProcess, Long>)
					AppraisalProcess::setCreatedBy);
			attributeSetterBiConsumers.put(
				"modifiedBy",
				(BiConsumer<AppraisalProcess, Long>)
					AppraisalProcess::setModifiedBy);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<AppraisalProcess, Long>)
					AppraisalProcess::setGroupId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<AppraisalProcess, Date>)
					AppraisalProcess::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<AppraisalProcess, Date>)
					AppraisalProcess::setModifiedDate);
			attributeSetterBiConsumers.put(
				"appraisalProcessId",
				(BiConsumer<AppraisalProcess, Long>)
					AppraisalProcess::setAppraisalProcessId);
			attributeSetterBiConsumers.put(
				"isSelfEvalutionFormSent",
				(BiConsumer<AppraisalProcess, Boolean>)
					AppraisalProcess::setIsSelfEvalutionFormSent);
			attributeSetterBiConsumers.put(
				"isSelfEvalutionFormFilled",
				(BiConsumer<AppraisalProcess, Boolean>)
					AppraisalProcess::setIsSelfEvalutionFormFilled);
			attributeSetterBiConsumers.put(
				"arePeerEvaluationFormSent",
				(BiConsumer<AppraisalProcess, Boolean>)
					AppraisalProcess::setArePeerEvaluationFormSent);
			attributeSetterBiConsumers.put(
				"arePeerEvaluationFormFilled",
				(BiConsumer<AppraisalProcess, Boolean>)
					AppraisalProcess::setArePeerEvaluationFormFilled);
			attributeSetterBiConsumers.put(
				"isManagementFormSent",
				(BiConsumer<AppraisalProcess, Boolean>)
					AppraisalProcess::setIsManagementFormSent);
			attributeSetterBiConsumers.put(
				"isManagementFormFilled",
				(BiConsumer<AppraisalProcess, Boolean>)
					AppraisalProcess::setIsManagementFormFilled);
			attributeSetterBiConsumers.put(
				"isMeetingScheduled",
				(BiConsumer<AppraisalProcess, Boolean>)
					AppraisalProcess::setIsMeetingScheduled);
			attributeSetterBiConsumers.put(
				"isMeetingDone",
				(BiConsumer<AppraisalProcess, Boolean>)
					AppraisalProcess::setIsMeetingDone);
			attributeSetterBiConsumers.put(
				"isSalaryUpdated",
				(BiConsumer<AppraisalProcess, Boolean>)
					AppraisalProcess::setIsSalaryUpdated);
			attributeSetterBiConsumers.put(
				"status",
				(BiConsumer<AppraisalProcess, Long>)
					AppraisalProcess::setStatus);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getAppraisalProcessId() {
		return _appraisalProcessId;
	}

	@Override
	public void setAppraisalProcessId(long appraisalProcessId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_appraisalProcessId = appraisalProcessId;
	}

	@JSON
	@Override
	public boolean getIsSelfEvalutionFormSent() {
		return _isSelfEvalutionFormSent;
	}

	@JSON
	@Override
	public boolean isIsSelfEvalutionFormSent() {
		return _isSelfEvalutionFormSent;
	}

	@Override
	public void setIsSelfEvalutionFormSent(boolean isSelfEvalutionFormSent) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_isSelfEvalutionFormSent = isSelfEvalutionFormSent;
	}

	@JSON
	@Override
	public boolean getIsSelfEvalutionFormFilled() {
		return _isSelfEvalutionFormFilled;
	}

	@JSON
	@Override
	public boolean isIsSelfEvalutionFormFilled() {
		return _isSelfEvalutionFormFilled;
	}

	@Override
	public void setIsSelfEvalutionFormFilled(
		boolean isSelfEvalutionFormFilled) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_isSelfEvalutionFormFilled = isSelfEvalutionFormFilled;
	}

	@JSON
	@Override
	public boolean getArePeerEvaluationFormSent() {
		return _arePeerEvaluationFormSent;
	}

	@JSON
	@Override
	public boolean isArePeerEvaluationFormSent() {
		return _arePeerEvaluationFormSent;
	}

	@Override
	public void setArePeerEvaluationFormSent(
		boolean arePeerEvaluationFormSent) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_arePeerEvaluationFormSent = arePeerEvaluationFormSent;
	}

	@JSON
	@Override
	public boolean getArePeerEvaluationFormFilled() {
		return _arePeerEvaluationFormFilled;
	}

	@JSON
	@Override
	public boolean isArePeerEvaluationFormFilled() {
		return _arePeerEvaluationFormFilled;
	}

	@Override
	public void setArePeerEvaluationFormFilled(
		boolean arePeerEvaluationFormFilled) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_arePeerEvaluationFormFilled = arePeerEvaluationFormFilled;
	}

	@JSON
	@Override
	public boolean getIsManagementFormSent() {
		return _isManagementFormSent;
	}

	@JSON
	@Override
	public boolean isIsManagementFormSent() {
		return _isManagementFormSent;
	}

	@Override
	public void setIsManagementFormSent(boolean isManagementFormSent) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_isManagementFormSent = isManagementFormSent;
	}

	@JSON
	@Override
	public boolean getIsManagementFormFilled() {
		return _isManagementFormFilled;
	}

	@JSON
	@Override
	public boolean isIsManagementFormFilled() {
		return _isManagementFormFilled;
	}

	@Override
	public void setIsManagementFormFilled(boolean isManagementFormFilled) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_isManagementFormFilled = isManagementFormFilled;
	}

	@JSON
	@Override
	public boolean getIsMeetingScheduled() {
		return _isMeetingScheduled;
	}

	@JSON
	@Override
	public boolean isIsMeetingScheduled() {
		return _isMeetingScheduled;
	}

	@Override
	public void setIsMeetingScheduled(boolean isMeetingScheduled) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_isMeetingScheduled = isMeetingScheduled;
	}

	@JSON
	@Override
	public boolean getIsMeetingDone() {
		return _isMeetingDone;
	}

	@JSON
	@Override
	public boolean isIsMeetingDone() {
		return _isMeetingDone;
	}

	@Override
	public void setIsMeetingDone(boolean isMeetingDone) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_isMeetingDone = isMeetingDone;
	}

	@JSON
	@Override
	public boolean getIsSalaryUpdated() {
		return _isSalaryUpdated;
	}

	@JSON
	@Override
	public boolean isIsSalaryUpdated() {
		return _isSalaryUpdated;
	}

	@Override
	public void setIsSalaryUpdated(boolean isSalaryUpdated) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_isSalaryUpdated = isSalaryUpdated;
	}

	@JSON
	@Override
	public long getStatus() {
		return _status;
	}

	@Override
	public void setStatus(long status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(AppraisalProcess.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), AppraisalProcess.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AppraisalProcess toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, AppraisalProcess>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AppraisalProcessImpl appraisalProcessImpl = new AppraisalProcessImpl();

		appraisalProcessImpl.setUuid(getUuid());
		appraisalProcessImpl.setCompanyId(getCompanyId());
		appraisalProcessImpl.setCreatedBy(getCreatedBy());
		appraisalProcessImpl.setModifiedBy(getModifiedBy());
		appraisalProcessImpl.setGroupId(getGroupId());
		appraisalProcessImpl.setCreateDate(getCreateDate());
		appraisalProcessImpl.setModifiedDate(getModifiedDate());
		appraisalProcessImpl.setAppraisalProcessId(getAppraisalProcessId());
		appraisalProcessImpl.setIsSelfEvalutionFormSent(
			isIsSelfEvalutionFormSent());
		appraisalProcessImpl.setIsSelfEvalutionFormFilled(
			isIsSelfEvalutionFormFilled());
		appraisalProcessImpl.setArePeerEvaluationFormSent(
			isArePeerEvaluationFormSent());
		appraisalProcessImpl.setArePeerEvaluationFormFilled(
			isArePeerEvaluationFormFilled());
		appraisalProcessImpl.setIsManagementFormSent(isIsManagementFormSent());
		appraisalProcessImpl.setIsManagementFormFilled(
			isIsManagementFormFilled());
		appraisalProcessImpl.setIsMeetingScheduled(isIsMeetingScheduled());
		appraisalProcessImpl.setIsMeetingDone(isIsMeetingDone());
		appraisalProcessImpl.setIsSalaryUpdated(isIsSalaryUpdated());
		appraisalProcessImpl.setStatus(getStatus());

		appraisalProcessImpl.resetOriginalValues();

		return appraisalProcessImpl;
	}

	@Override
	public AppraisalProcess cloneWithOriginalValues() {
		AppraisalProcessImpl appraisalProcessImpl = new AppraisalProcessImpl();

		appraisalProcessImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		appraisalProcessImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		appraisalProcessImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("createdBy"));
		appraisalProcessImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modifiedBy"));
		appraisalProcessImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		appraisalProcessImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		appraisalProcessImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		appraisalProcessImpl.setAppraisalProcessId(
			this.<Long>getColumnOriginalValue("appraisalProcessId"));
		appraisalProcessImpl.setIsSelfEvalutionFormSent(
			this.<Boolean>getColumnOriginalValue("isSelfEvalutionFormSent"));
		appraisalProcessImpl.setIsSelfEvalutionFormFilled(
			this.<Boolean>getColumnOriginalValue("isSelfEvalutionFormFilled"));
		appraisalProcessImpl.setArePeerEvaluationFormSent(
			this.<Boolean>getColumnOriginalValue("arePeerEvaluationFormSent"));
		appraisalProcessImpl.setArePeerEvaluationFormFilled(
			this.<Boolean>getColumnOriginalValue(
				"arePeerEvaluationFormFilled"));
		appraisalProcessImpl.setIsManagementFormSent(
			this.<Boolean>getColumnOriginalValue("isManagementFormSent"));
		appraisalProcessImpl.setIsManagementFormFilled(
			this.<Boolean>getColumnOriginalValue("isManagementFormFilled"));
		appraisalProcessImpl.setIsMeetingScheduled(
			this.<Boolean>getColumnOriginalValue("isMeetingScheduled"));
		appraisalProcessImpl.setIsMeetingDone(
			this.<Boolean>getColumnOriginalValue("isMeetingDone"));
		appraisalProcessImpl.setIsSalaryUpdated(
			this.<Boolean>getColumnOriginalValue("isSalaryUpdated"));
		appraisalProcessImpl.setStatus(
			this.<Long>getColumnOriginalValue("status"));

		return appraisalProcessImpl;
	}

	@Override
	public int compareTo(AppraisalProcess appraisalProcess) {
		long primaryKey = appraisalProcess.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof AppraisalProcess)) {
			return false;
		}

		AppraisalProcess appraisalProcess = (AppraisalProcess)object;

		long primaryKey = appraisalProcess.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<AppraisalProcess> toCacheModel() {
		AppraisalProcessCacheModel appraisalProcessCacheModel =
			new AppraisalProcessCacheModel();

		appraisalProcessCacheModel.uuid = getUuid();

		String uuid = appraisalProcessCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			appraisalProcessCacheModel.uuid = null;
		}

		appraisalProcessCacheModel.companyId = getCompanyId();

		appraisalProcessCacheModel.createdBy = getCreatedBy();

		appraisalProcessCacheModel.modifiedBy = getModifiedBy();

		appraisalProcessCacheModel.groupId = getGroupId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			appraisalProcessCacheModel.createDate = createDate.getTime();
		}
		else {
			appraisalProcessCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			appraisalProcessCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			appraisalProcessCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		appraisalProcessCacheModel.appraisalProcessId = getAppraisalProcessId();

		appraisalProcessCacheModel.isSelfEvalutionFormSent =
			isIsSelfEvalutionFormSent();

		appraisalProcessCacheModel.isSelfEvalutionFormFilled =
			isIsSelfEvalutionFormFilled();

		appraisalProcessCacheModel.arePeerEvaluationFormSent =
			isArePeerEvaluationFormSent();

		appraisalProcessCacheModel.arePeerEvaluationFormFilled =
			isArePeerEvaluationFormFilled();

		appraisalProcessCacheModel.isManagementFormSent =
			isIsManagementFormSent();

		appraisalProcessCacheModel.isManagementFormFilled =
			isIsManagementFormFilled();

		appraisalProcessCacheModel.isMeetingScheduled = isIsMeetingScheduled();

		appraisalProcessCacheModel.isMeetingDone = isIsMeetingDone();

		appraisalProcessCacheModel.isSalaryUpdated = isIsSalaryUpdated();

		appraisalProcessCacheModel.status = getStatus();

		return appraisalProcessCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<AppraisalProcess, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<AppraisalProcess, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AppraisalProcess, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(AppraisalProcess)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, AppraisalProcess>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					AppraisalProcess.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _companyId;
	private long _createdBy;
	private long _modifiedBy;
	private long _groupId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _appraisalProcessId;
	private boolean _isSelfEvalutionFormSent;
	private boolean _isSelfEvalutionFormFilled;
	private boolean _arePeerEvaluationFormSent;
	private boolean _arePeerEvaluationFormFilled;
	private boolean _isManagementFormSent;
	private boolean _isManagementFormFilled;
	private boolean _isMeetingScheduled;
	private boolean _isMeetingDone;
	private boolean _isSalaryUpdated;
	private long _status;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<AppraisalProcess, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((AppraisalProcess)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createdBy", _createdBy);
		_columnOriginalValues.put("modifiedBy", _modifiedBy);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("appraisalProcessId", _appraisalProcessId);
		_columnOriginalValues.put(
			"isSelfEvalutionFormSent", _isSelfEvalutionFormSent);
		_columnOriginalValues.put(
			"isSelfEvalutionFormFilled", _isSelfEvalutionFormFilled);
		_columnOriginalValues.put(
			"arePeerEvaluationFormSent", _arePeerEvaluationFormSent);
		_columnOriginalValues.put(
			"arePeerEvaluationFormFilled", _arePeerEvaluationFormFilled);
		_columnOriginalValues.put(
			"isManagementFormSent", _isManagementFormSent);
		_columnOriginalValues.put(
			"isManagementFormFilled", _isManagementFormFilled);
		_columnOriginalValues.put("isMeetingScheduled", _isMeetingScheduled);
		_columnOriginalValues.put("isMeetingDone", _isMeetingDone);
		_columnOriginalValues.put("isSalaryUpdated", _isSalaryUpdated);
		_columnOriginalValues.put("status", _status);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("createdBy", 4L);

		columnBitmasks.put("modifiedBy", 8L);

		columnBitmasks.put("groupId", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("appraisalProcessId", 128L);

		columnBitmasks.put("isSelfEvalutionFormSent", 256L);

		columnBitmasks.put("isSelfEvalutionFormFilled", 512L);

		columnBitmasks.put("arePeerEvaluationFormSent", 1024L);

		columnBitmasks.put("arePeerEvaluationFormFilled", 2048L);

		columnBitmasks.put("isManagementFormSent", 4096L);

		columnBitmasks.put("isManagementFormFilled", 8192L);

		columnBitmasks.put("isMeetingScheduled", 16384L);

		columnBitmasks.put("isMeetingDone", 32768L);

		columnBitmasks.put("isSalaryUpdated", 65536L);

		columnBitmasks.put("status", 131072L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private AppraisalProcess _escapedModel;

}