/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.model.impl;

import com.ax.hrms.model.AppraisalFormTemplates;
import com.ax.hrms.model.AppraisalFormTemplatesModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the AppraisalFormTemplates service. Represents a row in the &quot;ax_AppraisalFormTemplates&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AppraisalFormTemplatesModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AppraisalFormTemplatesImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AppraisalFormTemplatesImpl
 * @generated
 */
@JSON(strict = true)
public class AppraisalFormTemplatesModelImpl
	extends BaseModelImpl<AppraisalFormTemplates>
	implements AppraisalFormTemplatesModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a appraisal form templates model instance should use the <code>AppraisalFormTemplates</code> interface instead.
	 */
	public static final String TABLE_NAME = "ax_AppraisalFormTemplates";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"companyId", Types.BIGINT},
		{"createdBy", Types.BIGINT}, {"modifiedBy", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP},
		{"appraisalFormTemplateId", Types.BIGINT},
		{"templateName", Types.VARCHAR}, {"templateDocumentId", Types.BIGINT},
		{"templateLevelId", Types.BIGINT}, {"templateYear", Types.VARCHAR},
		{"status", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("appraisalFormTemplateId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("templateName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("templateDocumentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("templateLevelId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("templateYear", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("status", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ax_AppraisalFormTemplates (uuid_ VARCHAR(75) null,companyId LONG,createdBy LONG,modifiedBy LONG,groupId LONG,createDate DATE null,modifiedDate DATE null,appraisalFormTemplateId LONG not null primary key,templateName VARCHAR(75) null,templateDocumentId LONG,templateLevelId LONG,templateYear VARCHAR(75) null,status BOOLEAN)";

	public static final String TABLE_SQL_DROP =
		"drop table ax_AppraisalFormTemplates";

	public static final String ORDER_BY_JPQL =
		" ORDER BY appraisalFormTemplates.appraisalFormTemplateId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ax_AppraisalFormTemplates.appraisalFormTemplateId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TEMPLATELEVELID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TEMPLATEYEAR_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long APPRAISALFORMTEMPLATEID_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public AppraisalFormTemplatesModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _appraisalFormTemplateId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAppraisalFormTemplateId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _appraisalFormTemplateId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AppraisalFormTemplates.class;
	}

	@Override
	public String getModelClassName() {
		return AppraisalFormTemplates.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<AppraisalFormTemplates, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<AppraisalFormTemplates, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AppraisalFormTemplates, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((AppraisalFormTemplates)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<AppraisalFormTemplates, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<AppraisalFormTemplates, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(AppraisalFormTemplates)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<AppraisalFormTemplates, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<AppraisalFormTemplates, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map
			<String, Function<AppraisalFormTemplates, Object>>
				_attributeGetterFunctions;

		static {
			Map<String, Function<AppraisalFormTemplates, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<AppraisalFormTemplates, Object>>();

			attributeGetterFunctions.put(
				"uuid", AppraisalFormTemplates::getUuid);
			attributeGetterFunctions.put(
				"companyId", AppraisalFormTemplates::getCompanyId);
			attributeGetterFunctions.put(
				"createdBy", AppraisalFormTemplates::getCreatedBy);
			attributeGetterFunctions.put(
				"modifiedBy", AppraisalFormTemplates::getModifiedBy);
			attributeGetterFunctions.put(
				"groupId", AppraisalFormTemplates::getGroupId);
			attributeGetterFunctions.put(
				"createDate", AppraisalFormTemplates::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", AppraisalFormTemplates::getModifiedDate);
			attributeGetterFunctions.put(
				"appraisalFormTemplateId",
				AppraisalFormTemplates::getAppraisalFormTemplateId);
			attributeGetterFunctions.put(
				"templateName", AppraisalFormTemplates::getTemplateName);
			attributeGetterFunctions.put(
				"templateDocumentId",
				AppraisalFormTemplates::getTemplateDocumentId);
			attributeGetterFunctions.put(
				"templateLevelId", AppraisalFormTemplates::getTemplateLevelId);
			attributeGetterFunctions.put(
				"templateYear", AppraisalFormTemplates::getTemplateYear);
			attributeGetterFunctions.put(
				"status", AppraisalFormTemplates::getStatus);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<AppraisalFormTemplates, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<AppraisalFormTemplates, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<AppraisalFormTemplates, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<AppraisalFormTemplates, String>)
					AppraisalFormTemplates::setUuid);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<AppraisalFormTemplates, Long>)
					AppraisalFormTemplates::setCompanyId);
			attributeSetterBiConsumers.put(
				"createdBy",
				(BiConsumer<AppraisalFormTemplates, Long>)
					AppraisalFormTemplates::setCreatedBy);
			attributeSetterBiConsumers.put(
				"modifiedBy",
				(BiConsumer<AppraisalFormTemplates, Long>)
					AppraisalFormTemplates::setModifiedBy);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<AppraisalFormTemplates, Long>)
					AppraisalFormTemplates::setGroupId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<AppraisalFormTemplates, Date>)
					AppraisalFormTemplates::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<AppraisalFormTemplates, Date>)
					AppraisalFormTemplates::setModifiedDate);
			attributeSetterBiConsumers.put(
				"appraisalFormTemplateId",
				(BiConsumer<AppraisalFormTemplates, Long>)
					AppraisalFormTemplates::setAppraisalFormTemplateId);
			attributeSetterBiConsumers.put(
				"templateName",
				(BiConsumer<AppraisalFormTemplates, String>)
					AppraisalFormTemplates::setTemplateName);
			attributeSetterBiConsumers.put(
				"templateDocumentId",
				(BiConsumer<AppraisalFormTemplates, Long>)
					AppraisalFormTemplates::setTemplateDocumentId);
			attributeSetterBiConsumers.put(
				"templateLevelId",
				(BiConsumer<AppraisalFormTemplates, Long>)
					AppraisalFormTemplates::setTemplateLevelId);
			attributeSetterBiConsumers.put(
				"templateYear",
				(BiConsumer<AppraisalFormTemplates, String>)
					AppraisalFormTemplates::setTemplateYear);
			attributeSetterBiConsumers.put(
				"status",
				(BiConsumer<AppraisalFormTemplates, Boolean>)
					AppraisalFormTemplates::setStatus);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getAppraisalFormTemplateId() {
		return _appraisalFormTemplateId;
	}

	@Override
	public void setAppraisalFormTemplateId(long appraisalFormTemplateId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_appraisalFormTemplateId = appraisalFormTemplateId;
	}

	@JSON
	@Override
	public String getTemplateName() {
		if (_templateName == null) {
			return "";
		}
		else {
			return _templateName;
		}
	}

	@Override
	public void setTemplateName(String templateName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_templateName = templateName;
	}

	@JSON
	@Override
	public long getTemplateDocumentId() {
		return _templateDocumentId;
	}

	@Override
	public void setTemplateDocumentId(long templateDocumentId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_templateDocumentId = templateDocumentId;
	}

	@JSON
	@Override
	public long getTemplateLevelId() {
		return _templateLevelId;
	}

	@Override
	public void setTemplateLevelId(long templateLevelId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_templateLevelId = templateLevelId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalTemplateLevelId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("templateLevelId"));
	}

	@JSON
	@Override
	public String getTemplateYear() {
		if (_templateYear == null) {
			return "";
		}
		else {
			return _templateYear;
		}
	}

	@Override
	public void setTemplateYear(String templateYear) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_templateYear = templateYear;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalTemplateYear() {
		return getColumnOriginalValue("templateYear");
	}

	@JSON
	@Override
	public boolean getStatus() {
		return _status;
	}

	@JSON
	@Override
	public boolean isStatus() {
		return _status;
	}

	@Override
	public void setStatus(boolean status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(AppraisalFormTemplates.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), AppraisalFormTemplates.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AppraisalFormTemplates toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, AppraisalFormTemplates>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AppraisalFormTemplatesImpl appraisalFormTemplatesImpl =
			new AppraisalFormTemplatesImpl();

		appraisalFormTemplatesImpl.setUuid(getUuid());
		appraisalFormTemplatesImpl.setCompanyId(getCompanyId());
		appraisalFormTemplatesImpl.setCreatedBy(getCreatedBy());
		appraisalFormTemplatesImpl.setModifiedBy(getModifiedBy());
		appraisalFormTemplatesImpl.setGroupId(getGroupId());
		appraisalFormTemplatesImpl.setCreateDate(getCreateDate());
		appraisalFormTemplatesImpl.setModifiedDate(getModifiedDate());
		appraisalFormTemplatesImpl.setAppraisalFormTemplateId(
			getAppraisalFormTemplateId());
		appraisalFormTemplatesImpl.setTemplateName(getTemplateName());
		appraisalFormTemplatesImpl.setTemplateDocumentId(
			getTemplateDocumentId());
		appraisalFormTemplatesImpl.setTemplateLevelId(getTemplateLevelId());
		appraisalFormTemplatesImpl.setTemplateYear(getTemplateYear());
		appraisalFormTemplatesImpl.setStatus(isStatus());

		appraisalFormTemplatesImpl.resetOriginalValues();

		return appraisalFormTemplatesImpl;
	}

	@Override
	public AppraisalFormTemplates cloneWithOriginalValues() {
		AppraisalFormTemplatesImpl appraisalFormTemplatesImpl =
			new AppraisalFormTemplatesImpl();

		appraisalFormTemplatesImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		appraisalFormTemplatesImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		appraisalFormTemplatesImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("createdBy"));
		appraisalFormTemplatesImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modifiedBy"));
		appraisalFormTemplatesImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		appraisalFormTemplatesImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		appraisalFormTemplatesImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		appraisalFormTemplatesImpl.setAppraisalFormTemplateId(
			this.<Long>getColumnOriginalValue("appraisalFormTemplateId"));
		appraisalFormTemplatesImpl.setTemplateName(
			this.<String>getColumnOriginalValue("templateName"));
		appraisalFormTemplatesImpl.setTemplateDocumentId(
			this.<Long>getColumnOriginalValue("templateDocumentId"));
		appraisalFormTemplatesImpl.setTemplateLevelId(
			this.<Long>getColumnOriginalValue("templateLevelId"));
		appraisalFormTemplatesImpl.setTemplateYear(
			this.<String>getColumnOriginalValue("templateYear"));
		appraisalFormTemplatesImpl.setStatus(
			this.<Boolean>getColumnOriginalValue("status"));

		return appraisalFormTemplatesImpl;
	}

	@Override
	public int compareTo(AppraisalFormTemplates appraisalFormTemplates) {
		long primaryKey = appraisalFormTemplates.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof AppraisalFormTemplates)) {
			return false;
		}

		AppraisalFormTemplates appraisalFormTemplates =
			(AppraisalFormTemplates)object;

		long primaryKey = appraisalFormTemplates.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<AppraisalFormTemplates> toCacheModel() {
		AppraisalFormTemplatesCacheModel appraisalFormTemplatesCacheModel =
			new AppraisalFormTemplatesCacheModel();

		appraisalFormTemplatesCacheModel.uuid = getUuid();

		String uuid = appraisalFormTemplatesCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			appraisalFormTemplatesCacheModel.uuid = null;
		}

		appraisalFormTemplatesCacheModel.companyId = getCompanyId();

		appraisalFormTemplatesCacheModel.createdBy = getCreatedBy();

		appraisalFormTemplatesCacheModel.modifiedBy = getModifiedBy();

		appraisalFormTemplatesCacheModel.groupId = getGroupId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			appraisalFormTemplatesCacheModel.createDate = createDate.getTime();
		}
		else {
			appraisalFormTemplatesCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			appraisalFormTemplatesCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			appraisalFormTemplatesCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		appraisalFormTemplatesCacheModel.appraisalFormTemplateId =
			getAppraisalFormTemplateId();

		appraisalFormTemplatesCacheModel.templateName = getTemplateName();

		String templateName = appraisalFormTemplatesCacheModel.templateName;

		if ((templateName != null) && (templateName.length() == 0)) {
			appraisalFormTemplatesCacheModel.templateName = null;
		}

		appraisalFormTemplatesCacheModel.templateDocumentId =
			getTemplateDocumentId();

		appraisalFormTemplatesCacheModel.templateLevelId = getTemplateLevelId();

		appraisalFormTemplatesCacheModel.templateYear = getTemplateYear();

		String templateYear = appraisalFormTemplatesCacheModel.templateYear;

		if ((templateYear != null) && (templateYear.length() == 0)) {
			appraisalFormTemplatesCacheModel.templateYear = null;
		}

		appraisalFormTemplatesCacheModel.status = isStatus();

		return appraisalFormTemplatesCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<AppraisalFormTemplates, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<AppraisalFormTemplates, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AppraisalFormTemplates, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(AppraisalFormTemplates)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, AppraisalFormTemplates>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					AppraisalFormTemplates.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _companyId;
	private long _createdBy;
	private long _modifiedBy;
	private long _groupId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _appraisalFormTemplateId;
	private String _templateName;
	private long _templateDocumentId;
	private long _templateLevelId;
	private String _templateYear;
	private boolean _status;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<AppraisalFormTemplates, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((AppraisalFormTemplates)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createdBy", _createdBy);
		_columnOriginalValues.put("modifiedBy", _modifiedBy);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put(
			"appraisalFormTemplateId", _appraisalFormTemplateId);
		_columnOriginalValues.put("templateName", _templateName);
		_columnOriginalValues.put("templateDocumentId", _templateDocumentId);
		_columnOriginalValues.put("templateLevelId", _templateLevelId);
		_columnOriginalValues.put("templateYear", _templateYear);
		_columnOriginalValues.put("status", _status);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("createdBy", 4L);

		columnBitmasks.put("modifiedBy", 8L);

		columnBitmasks.put("groupId", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("appraisalFormTemplateId", 128L);

		columnBitmasks.put("templateName", 256L);

		columnBitmasks.put("templateDocumentId", 512L);

		columnBitmasks.put("templateLevelId", 1024L);

		columnBitmasks.put("templateYear", 2048L);

		columnBitmasks.put("status", 4096L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private AppraisalFormTemplates _escapedModel;

}