/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.model.impl;

import com.ax.hrms.model.AppraisalMeeting;
import com.ax.hrms.model.AppraisalMeetingModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the AppraisalMeeting service. Represents a row in the &quot;ax_AppraisalMeeting&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AppraisalMeetingModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AppraisalMeetingImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AppraisalMeetingImpl
 * @generated
 */
@JSON(strict = true)
public class AppraisalMeetingModelImpl
	extends BaseModelImpl<AppraisalMeeting> implements AppraisalMeetingModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a appraisal meeting model instance should use the <code>AppraisalMeeting</code> interface instead.
	 */
	public static final String TABLE_NAME = "ax_AppraisalMeeting";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"companyId", Types.BIGINT},
		{"createdBy", Types.BIGINT}, {"modifiedBy", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"appraisalMeetingId", Types.BIGINT},
		{"appraisalProcessId", Types.BIGINT}, {"meetingDate", Types.TIMESTAMP},
		{"meetingTime", Types.TIMESTAMP}, {"status", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("appraisalMeetingId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("appraisalProcessId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("meetingDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("meetingTime", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ax_AppraisalMeeting (uuid_ VARCHAR(75) null,companyId LONG,createdBy LONG,modifiedBy LONG,groupId LONG,createDate DATE null,modifiedDate DATE null,appraisalMeetingId LONG not null primary key,appraisalProcessId LONG,meetingDate DATE null,meetingTime DATE null,status BOOLEAN)";

	public static final String TABLE_SQL_DROP =
		"drop table ax_AppraisalMeeting";

	public static final String ORDER_BY_JPQL =
		" ORDER BY appraisalMeeting.appraisalMeetingId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ax_AppraisalMeeting.appraisalMeetingId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long APPRAISALPROCESSID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long APPRAISALMEETINGID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public AppraisalMeetingModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _appraisalMeetingId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAppraisalMeetingId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _appraisalMeetingId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AppraisalMeeting.class;
	}

	@Override
	public String getModelClassName() {
		return AppraisalMeeting.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<AppraisalMeeting, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<AppraisalMeeting, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AppraisalMeeting, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((AppraisalMeeting)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<AppraisalMeeting, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<AppraisalMeeting, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(AppraisalMeeting)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<AppraisalMeeting, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<AppraisalMeeting, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<AppraisalMeeting, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<AppraisalMeeting, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<AppraisalMeeting, Object>>();

			attributeGetterFunctions.put("uuid", AppraisalMeeting::getUuid);
			attributeGetterFunctions.put(
				"companyId", AppraisalMeeting::getCompanyId);
			attributeGetterFunctions.put(
				"createdBy", AppraisalMeeting::getCreatedBy);
			attributeGetterFunctions.put(
				"modifiedBy", AppraisalMeeting::getModifiedBy);
			attributeGetterFunctions.put(
				"groupId", AppraisalMeeting::getGroupId);
			attributeGetterFunctions.put(
				"createDate", AppraisalMeeting::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", AppraisalMeeting::getModifiedDate);
			attributeGetterFunctions.put(
				"appraisalMeetingId", AppraisalMeeting::getAppraisalMeetingId);
			attributeGetterFunctions.put(
				"appraisalProcessId", AppraisalMeeting::getAppraisalProcessId);
			attributeGetterFunctions.put(
				"meetingDate", AppraisalMeeting::getMeetingDate);
			attributeGetterFunctions.put(
				"meetingTime", AppraisalMeeting::getMeetingTime);
			attributeGetterFunctions.put("status", AppraisalMeeting::getStatus);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<AppraisalMeeting, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<AppraisalMeeting, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<AppraisalMeeting, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<AppraisalMeeting, String>)
					AppraisalMeeting::setUuid);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<AppraisalMeeting, Long>)
					AppraisalMeeting::setCompanyId);
			attributeSetterBiConsumers.put(
				"createdBy",
				(BiConsumer<AppraisalMeeting, Long>)
					AppraisalMeeting::setCreatedBy);
			attributeSetterBiConsumers.put(
				"modifiedBy",
				(BiConsumer<AppraisalMeeting, Long>)
					AppraisalMeeting::setModifiedBy);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<AppraisalMeeting, Long>)
					AppraisalMeeting::setGroupId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<AppraisalMeeting, Date>)
					AppraisalMeeting::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<AppraisalMeeting, Date>)
					AppraisalMeeting::setModifiedDate);
			attributeSetterBiConsumers.put(
				"appraisalMeetingId",
				(BiConsumer<AppraisalMeeting, Long>)
					AppraisalMeeting::setAppraisalMeetingId);
			attributeSetterBiConsumers.put(
				"appraisalProcessId",
				(BiConsumer<AppraisalMeeting, Long>)
					AppraisalMeeting::setAppraisalProcessId);
			attributeSetterBiConsumers.put(
				"meetingDate",
				(BiConsumer<AppraisalMeeting, Date>)
					AppraisalMeeting::setMeetingDate);
			attributeSetterBiConsumers.put(
				"meetingTime",
				(BiConsumer<AppraisalMeeting, Date>)
					AppraisalMeeting::setMeetingTime);
			attributeSetterBiConsumers.put(
				"status",
				(BiConsumer<AppraisalMeeting, Boolean>)
					AppraisalMeeting::setStatus);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getAppraisalMeetingId() {
		return _appraisalMeetingId;
	}

	@Override
	public void setAppraisalMeetingId(long appraisalMeetingId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_appraisalMeetingId = appraisalMeetingId;
	}

	@JSON
	@Override
	public long getAppraisalProcessId() {
		return _appraisalProcessId;
	}

	@Override
	public void setAppraisalProcessId(long appraisalProcessId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_appraisalProcessId = appraisalProcessId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalAppraisalProcessId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("appraisalProcessId"));
	}

	@JSON
	@Override
	public Date getMeetingDate() {
		return _meetingDate;
	}

	@Override
	public void setMeetingDate(Date meetingDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_meetingDate = meetingDate;
	}

	@JSON
	@Override
	public Date getMeetingTime() {
		return _meetingTime;
	}

	@Override
	public void setMeetingTime(Date meetingTime) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_meetingTime = meetingTime;
	}

	@JSON
	@Override
	public boolean getStatus() {
		return _status;
	}

	@JSON
	@Override
	public boolean isStatus() {
		return _status;
	}

	@Override
	public void setStatus(boolean status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(AppraisalMeeting.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), AppraisalMeeting.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AppraisalMeeting toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, AppraisalMeeting>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AppraisalMeetingImpl appraisalMeetingImpl = new AppraisalMeetingImpl();

		appraisalMeetingImpl.setUuid(getUuid());
		appraisalMeetingImpl.setCompanyId(getCompanyId());
		appraisalMeetingImpl.setCreatedBy(getCreatedBy());
		appraisalMeetingImpl.setModifiedBy(getModifiedBy());
		appraisalMeetingImpl.setGroupId(getGroupId());
		appraisalMeetingImpl.setCreateDate(getCreateDate());
		appraisalMeetingImpl.setModifiedDate(getModifiedDate());
		appraisalMeetingImpl.setAppraisalMeetingId(getAppraisalMeetingId());
		appraisalMeetingImpl.setAppraisalProcessId(getAppraisalProcessId());
		appraisalMeetingImpl.setMeetingDate(getMeetingDate());
		appraisalMeetingImpl.setMeetingTime(getMeetingTime());
		appraisalMeetingImpl.setStatus(isStatus());

		appraisalMeetingImpl.resetOriginalValues();

		return appraisalMeetingImpl;
	}

	@Override
	public AppraisalMeeting cloneWithOriginalValues() {
		AppraisalMeetingImpl appraisalMeetingImpl = new AppraisalMeetingImpl();

		appraisalMeetingImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		appraisalMeetingImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		appraisalMeetingImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("createdBy"));
		appraisalMeetingImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modifiedBy"));
		appraisalMeetingImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		appraisalMeetingImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		appraisalMeetingImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		appraisalMeetingImpl.setAppraisalMeetingId(
			this.<Long>getColumnOriginalValue("appraisalMeetingId"));
		appraisalMeetingImpl.setAppraisalProcessId(
			this.<Long>getColumnOriginalValue("appraisalProcessId"));
		appraisalMeetingImpl.setMeetingDate(
			this.<Date>getColumnOriginalValue("meetingDate"));
		appraisalMeetingImpl.setMeetingTime(
			this.<Date>getColumnOriginalValue("meetingTime"));
		appraisalMeetingImpl.setStatus(
			this.<Boolean>getColumnOriginalValue("status"));

		return appraisalMeetingImpl;
	}

	@Override
	public int compareTo(AppraisalMeeting appraisalMeeting) {
		long primaryKey = appraisalMeeting.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof AppraisalMeeting)) {
			return false;
		}

		AppraisalMeeting appraisalMeeting = (AppraisalMeeting)object;

		long primaryKey = appraisalMeeting.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<AppraisalMeeting> toCacheModel() {
		AppraisalMeetingCacheModel appraisalMeetingCacheModel =
			new AppraisalMeetingCacheModel();

		appraisalMeetingCacheModel.uuid = getUuid();

		String uuid = appraisalMeetingCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			appraisalMeetingCacheModel.uuid = null;
		}

		appraisalMeetingCacheModel.companyId = getCompanyId();

		appraisalMeetingCacheModel.createdBy = getCreatedBy();

		appraisalMeetingCacheModel.modifiedBy = getModifiedBy();

		appraisalMeetingCacheModel.groupId = getGroupId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			appraisalMeetingCacheModel.createDate = createDate.getTime();
		}
		else {
			appraisalMeetingCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			appraisalMeetingCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			appraisalMeetingCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		appraisalMeetingCacheModel.appraisalMeetingId = getAppraisalMeetingId();

		appraisalMeetingCacheModel.appraisalProcessId = getAppraisalProcessId();

		Date meetingDate = getMeetingDate();

		if (meetingDate != null) {
			appraisalMeetingCacheModel.meetingDate = meetingDate.getTime();
		}
		else {
			appraisalMeetingCacheModel.meetingDate = Long.MIN_VALUE;
		}

		Date meetingTime = getMeetingTime();

		if (meetingTime != null) {
			appraisalMeetingCacheModel.meetingTime = meetingTime.getTime();
		}
		else {
			appraisalMeetingCacheModel.meetingTime = Long.MIN_VALUE;
		}

		appraisalMeetingCacheModel.status = isStatus();

		return appraisalMeetingCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<AppraisalMeeting, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<AppraisalMeeting, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AppraisalMeeting, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(AppraisalMeeting)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, AppraisalMeeting>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					AppraisalMeeting.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _companyId;
	private long _createdBy;
	private long _modifiedBy;
	private long _groupId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _appraisalMeetingId;
	private long _appraisalProcessId;
	private Date _meetingDate;
	private Date _meetingTime;
	private boolean _status;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<AppraisalMeeting, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((AppraisalMeeting)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createdBy", _createdBy);
		_columnOriginalValues.put("modifiedBy", _modifiedBy);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("appraisalMeetingId", _appraisalMeetingId);
		_columnOriginalValues.put("appraisalProcessId", _appraisalProcessId);
		_columnOriginalValues.put("meetingDate", _meetingDate);
		_columnOriginalValues.put("meetingTime", _meetingTime);
		_columnOriginalValues.put("status", _status);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("createdBy", 4L);

		columnBitmasks.put("modifiedBy", 8L);

		columnBitmasks.put("groupId", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("appraisalMeetingId", 128L);

		columnBitmasks.put("appraisalProcessId", 256L);

		columnBitmasks.put("meetingDate", 512L);

		columnBitmasks.put("meetingTime", 1024L);

		columnBitmasks.put("status", 2048L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private AppraisalMeeting _escapedModel;

}