/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.model.impl;

import com.ax.hrms.model.AppraisalHistory;
import com.ax.hrms.service.AppraisalHistoryLocalServiceUtil;

/**
 * The extended model base implementation for the AppraisalHistory service. Represents a row in the &quot;ax_AppraisalHistory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AppraisalHistoryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AppraisalHistoryImpl
 * @see AppraisalHistory
 * @generated
 */
public abstract class AppraisalHistoryBaseImpl
	extends AppraisalHistoryModelImpl implements AppraisalHistory {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a appraisal history model instance should use the <code>AppraisalHistory</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			AppraisalHistoryLocalServiceUtil.addAppraisalHistory(this);
		}
		else {
			AppraisalHistoryLocalServiceUtil.updateAppraisalHistory(this);
		}
	}

}