/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.model.impl;

import com.ax.hrms.model.AppraisalEvaluationFormStatus;
import com.ax.hrms.model.AppraisalEvaluationFormStatusModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the AppraisalEvaluationFormStatus service. Represents a row in the &quot;ax_AppraisalEvaluationFormStatus&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AppraisalEvaluationFormStatusModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AppraisalEvaluationFormStatusImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AppraisalEvaluationFormStatusImpl
 * @generated
 */
@JSON(strict = true)
public class AppraisalEvaluationFormStatusModelImpl
	extends BaseModelImpl<AppraisalEvaluationFormStatus>
	implements AppraisalEvaluationFormStatusModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a appraisal evaluation form status model instance should use the <code>AppraisalEvaluationFormStatus</code> interface instead.
	 */
	public static final String TABLE_NAME = "ax_AppraisalEvaluationFormStatus";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"companyId", Types.BIGINT},
		{"createdBy", Types.BIGINT}, {"modifiedBy", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP},
		{"appraisalEvaluationFormStatusId", Types.BIGINT},
		{"appraisalProcessId", Types.BIGINT},
		{"submissionDate", Types.TIMESTAMP}, {"employeeId", Types.BIGINT},
		{"filledEvaluationDocuemntId", Types.BIGINT},
		{"appraisalFormTemplateId", Types.BIGINT}, {"status", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("appraisalEvaluationFormStatusId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("appraisalProcessId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("submissionDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("employeeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("filledEvaluationDocuemntId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("appraisalFormTemplateId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("status", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ax_AppraisalEvaluationFormStatus (uuid_ VARCHAR(75) null,companyId LONG,createdBy LONG,modifiedBy LONG,groupId LONG,createDate DATE null,modifiedDate DATE null,appraisalEvaluationFormStatusId LONG not null primary key,appraisalProcessId LONG,submissionDate DATE null,employeeId LONG,filledEvaluationDocuemntId LONG,appraisalFormTemplateId LONG,status BOOLEAN)";

	public static final String TABLE_SQL_DROP =
		"drop table ax_AppraisalEvaluationFormStatus";

	public static final String ORDER_BY_JPQL =
		" ORDER BY appraisalEvaluationFormStatus.appraisalEvaluationFormStatusId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ax_AppraisalEvaluationFormStatus.appraisalEvaluationFormStatusId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long APPRAISALFORMTEMPLATEID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long APPRAISALPROCESSID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STATUS_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SUBMISSIONDATE_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 64L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long APPRAISALEVALUATIONFORMSTATUSID_COLUMN_BITMASK =
		128L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public AppraisalEvaluationFormStatusModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _appraisalEvaluationFormStatusId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAppraisalEvaluationFormStatusId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _appraisalEvaluationFormStatusId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AppraisalEvaluationFormStatus.class;
	}

	@Override
	public String getModelClassName() {
		return AppraisalEvaluationFormStatus.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<AppraisalEvaluationFormStatus, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<AppraisalEvaluationFormStatus, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AppraisalEvaluationFormStatus, Object>
				attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply(
					(AppraisalEvaluationFormStatus)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<AppraisalEvaluationFormStatus, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<AppraisalEvaluationFormStatus, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(AppraisalEvaluationFormStatus)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<AppraisalEvaluationFormStatus, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<AppraisalEvaluationFormStatus, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map
			<String, Function<AppraisalEvaluationFormStatus, Object>>
				_attributeGetterFunctions;

		static {
			Map<String, Function<AppraisalEvaluationFormStatus, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String,
						 Function<AppraisalEvaluationFormStatus, Object>>();

			attributeGetterFunctions.put(
				"uuid", AppraisalEvaluationFormStatus::getUuid);
			attributeGetterFunctions.put(
				"companyId", AppraisalEvaluationFormStatus::getCompanyId);
			attributeGetterFunctions.put(
				"createdBy", AppraisalEvaluationFormStatus::getCreatedBy);
			attributeGetterFunctions.put(
				"modifiedBy", AppraisalEvaluationFormStatus::getModifiedBy);
			attributeGetterFunctions.put(
				"groupId", AppraisalEvaluationFormStatus::getGroupId);
			attributeGetterFunctions.put(
				"createDate", AppraisalEvaluationFormStatus::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", AppraisalEvaluationFormStatus::getModifiedDate);
			attributeGetterFunctions.put(
				"appraisalEvaluationFormStatusId",
				AppraisalEvaluationFormStatus::
					getAppraisalEvaluationFormStatusId);
			attributeGetterFunctions.put(
				"appraisalProcessId",
				AppraisalEvaluationFormStatus::getAppraisalProcessId);
			attributeGetterFunctions.put(
				"submissionDate",
				AppraisalEvaluationFormStatus::getSubmissionDate);
			attributeGetterFunctions.put(
				"employeeId", AppraisalEvaluationFormStatus::getEmployeeId);
			attributeGetterFunctions.put(
				"filledEvaluationDocuemntId",
				AppraisalEvaluationFormStatus::getFilledEvaluationDocuemntId);
			attributeGetterFunctions.put(
				"appraisalFormTemplateId",
				AppraisalEvaluationFormStatus::getAppraisalFormTemplateId);
			attributeGetterFunctions.put(
				"status", AppraisalEvaluationFormStatus::getStatus);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<AppraisalEvaluationFormStatus, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<AppraisalEvaluationFormStatus, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String,
						 BiConsumer<AppraisalEvaluationFormStatus, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<AppraisalEvaluationFormStatus, String>)
					AppraisalEvaluationFormStatus::setUuid);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<AppraisalEvaluationFormStatus, Long>)
					AppraisalEvaluationFormStatus::setCompanyId);
			attributeSetterBiConsumers.put(
				"createdBy",
				(BiConsumer<AppraisalEvaluationFormStatus, Long>)
					AppraisalEvaluationFormStatus::setCreatedBy);
			attributeSetterBiConsumers.put(
				"modifiedBy",
				(BiConsumer<AppraisalEvaluationFormStatus, Long>)
					AppraisalEvaluationFormStatus::setModifiedBy);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<AppraisalEvaluationFormStatus, Long>)
					AppraisalEvaluationFormStatus::setGroupId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<AppraisalEvaluationFormStatus, Date>)
					AppraisalEvaluationFormStatus::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<AppraisalEvaluationFormStatus, Date>)
					AppraisalEvaluationFormStatus::setModifiedDate);
			attributeSetterBiConsumers.put(
				"appraisalEvaluationFormStatusId",
				(BiConsumer<AppraisalEvaluationFormStatus, Long>)
					AppraisalEvaluationFormStatus::
						setAppraisalEvaluationFormStatusId);
			attributeSetterBiConsumers.put(
				"appraisalProcessId",
				(BiConsumer<AppraisalEvaluationFormStatus, Long>)
					AppraisalEvaluationFormStatus::setAppraisalProcessId);
			attributeSetterBiConsumers.put(
				"submissionDate",
				(BiConsumer<AppraisalEvaluationFormStatus, Date>)
					AppraisalEvaluationFormStatus::setSubmissionDate);
			attributeSetterBiConsumers.put(
				"employeeId",
				(BiConsumer<AppraisalEvaluationFormStatus, Long>)
					AppraisalEvaluationFormStatus::setEmployeeId);
			attributeSetterBiConsumers.put(
				"filledEvaluationDocuemntId",
				(BiConsumer<AppraisalEvaluationFormStatus, Long>)
					AppraisalEvaluationFormStatus::
						setFilledEvaluationDocuemntId);
			attributeSetterBiConsumers.put(
				"appraisalFormTemplateId",
				(BiConsumer<AppraisalEvaluationFormStatus, Long>)
					AppraisalEvaluationFormStatus::setAppraisalFormTemplateId);
			attributeSetterBiConsumers.put(
				"status",
				(BiConsumer<AppraisalEvaluationFormStatus, Boolean>)
					AppraisalEvaluationFormStatus::setStatus);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getAppraisalEvaluationFormStatusId() {
		return _appraisalEvaluationFormStatusId;
	}

	@Override
	public void setAppraisalEvaluationFormStatusId(
		long appraisalEvaluationFormStatusId) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_appraisalEvaluationFormStatusId = appraisalEvaluationFormStatusId;
	}

	@JSON
	@Override
	public long getAppraisalProcessId() {
		return _appraisalProcessId;
	}

	@Override
	public void setAppraisalProcessId(long appraisalProcessId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_appraisalProcessId = appraisalProcessId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalAppraisalProcessId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("appraisalProcessId"));
	}

	@JSON
	@Override
	public Date getSubmissionDate() {
		return _submissionDate;
	}

	@Override
	public void setSubmissionDate(Date submissionDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_submissionDate = submissionDate;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public Date getOriginalSubmissionDate() {
		return getColumnOriginalValue("submissionDate");
	}

	@JSON
	@Override
	public long getEmployeeId() {
		return _employeeId;
	}

	@Override
	public void setEmployeeId(long employeeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_employeeId = employeeId;
	}

	@JSON
	@Override
	public long getFilledEvaluationDocuemntId() {
		return _filledEvaluationDocuemntId;
	}

	@Override
	public void setFilledEvaluationDocuemntId(long filledEvaluationDocuemntId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_filledEvaluationDocuemntId = filledEvaluationDocuemntId;
	}

	@JSON
	@Override
	public long getAppraisalFormTemplateId() {
		return _appraisalFormTemplateId;
	}

	@Override
	public void setAppraisalFormTemplateId(long appraisalFormTemplateId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_appraisalFormTemplateId = appraisalFormTemplateId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalAppraisalFormTemplateId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("appraisalFormTemplateId"));
	}

	@JSON
	@Override
	public boolean getStatus() {
		return _status;
	}

	@JSON
	@Override
	public boolean isStatus() {
		return _status;
	}

	@Override
	public void setStatus(boolean status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public boolean getOriginalStatus() {
		return GetterUtil.getBoolean(
			this.<Boolean>getColumnOriginalValue("status"));
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(
				AppraisalEvaluationFormStatus.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), AppraisalEvaluationFormStatus.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AppraisalEvaluationFormStatus toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, AppraisalEvaluationFormStatus>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AppraisalEvaluationFormStatusImpl appraisalEvaluationFormStatusImpl =
			new AppraisalEvaluationFormStatusImpl();

		appraisalEvaluationFormStatusImpl.setUuid(getUuid());
		appraisalEvaluationFormStatusImpl.setCompanyId(getCompanyId());
		appraisalEvaluationFormStatusImpl.setCreatedBy(getCreatedBy());
		appraisalEvaluationFormStatusImpl.setModifiedBy(getModifiedBy());
		appraisalEvaluationFormStatusImpl.setGroupId(getGroupId());
		appraisalEvaluationFormStatusImpl.setCreateDate(getCreateDate());
		appraisalEvaluationFormStatusImpl.setModifiedDate(getModifiedDate());
		appraisalEvaluationFormStatusImpl.setAppraisalEvaluationFormStatusId(
			getAppraisalEvaluationFormStatusId());
		appraisalEvaluationFormStatusImpl.setAppraisalProcessId(
			getAppraisalProcessId());
		appraisalEvaluationFormStatusImpl.setSubmissionDate(
			getSubmissionDate());
		appraisalEvaluationFormStatusImpl.setEmployeeId(getEmployeeId());
		appraisalEvaluationFormStatusImpl.setFilledEvaluationDocuemntId(
			getFilledEvaluationDocuemntId());
		appraisalEvaluationFormStatusImpl.setAppraisalFormTemplateId(
			getAppraisalFormTemplateId());
		appraisalEvaluationFormStatusImpl.setStatus(isStatus());

		appraisalEvaluationFormStatusImpl.resetOriginalValues();

		return appraisalEvaluationFormStatusImpl;
	}

	@Override
	public AppraisalEvaluationFormStatus cloneWithOriginalValues() {
		AppraisalEvaluationFormStatusImpl appraisalEvaluationFormStatusImpl =
			new AppraisalEvaluationFormStatusImpl();

		appraisalEvaluationFormStatusImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		appraisalEvaluationFormStatusImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		appraisalEvaluationFormStatusImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("createdBy"));
		appraisalEvaluationFormStatusImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modifiedBy"));
		appraisalEvaluationFormStatusImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		appraisalEvaluationFormStatusImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		appraisalEvaluationFormStatusImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		appraisalEvaluationFormStatusImpl.setAppraisalEvaluationFormStatusId(
			this.<Long>getColumnOriginalValue(
				"appraisalEvaluationFormStatusId"));
		appraisalEvaluationFormStatusImpl.setAppraisalProcessId(
			this.<Long>getColumnOriginalValue("appraisalProcessId"));
		appraisalEvaluationFormStatusImpl.setSubmissionDate(
			this.<Date>getColumnOriginalValue("submissionDate"));
		appraisalEvaluationFormStatusImpl.setEmployeeId(
			this.<Long>getColumnOriginalValue("employeeId"));
		appraisalEvaluationFormStatusImpl.setFilledEvaluationDocuemntId(
			this.<Long>getColumnOriginalValue("filledEvaluationDocuemntId"));
		appraisalEvaluationFormStatusImpl.setAppraisalFormTemplateId(
			this.<Long>getColumnOriginalValue("appraisalFormTemplateId"));
		appraisalEvaluationFormStatusImpl.setStatus(
			this.<Boolean>getColumnOriginalValue("status"));

		return appraisalEvaluationFormStatusImpl;
	}

	@Override
	public int compareTo(
		AppraisalEvaluationFormStatus appraisalEvaluationFormStatus) {

		long primaryKey = appraisalEvaluationFormStatus.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof AppraisalEvaluationFormStatus)) {
			return false;
		}

		AppraisalEvaluationFormStatus appraisalEvaluationFormStatus =
			(AppraisalEvaluationFormStatus)object;

		long primaryKey = appraisalEvaluationFormStatus.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<AppraisalEvaluationFormStatus> toCacheModel() {
		AppraisalEvaluationFormStatusCacheModel
			appraisalEvaluationFormStatusCacheModel =
				new AppraisalEvaluationFormStatusCacheModel();

		appraisalEvaluationFormStatusCacheModel.uuid = getUuid();

		String uuid = appraisalEvaluationFormStatusCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			appraisalEvaluationFormStatusCacheModel.uuid = null;
		}

		appraisalEvaluationFormStatusCacheModel.companyId = getCompanyId();

		appraisalEvaluationFormStatusCacheModel.createdBy = getCreatedBy();

		appraisalEvaluationFormStatusCacheModel.modifiedBy = getModifiedBy();

		appraisalEvaluationFormStatusCacheModel.groupId = getGroupId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			appraisalEvaluationFormStatusCacheModel.createDate =
				createDate.getTime();
		}
		else {
			appraisalEvaluationFormStatusCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			appraisalEvaluationFormStatusCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			appraisalEvaluationFormStatusCacheModel.modifiedDate =
				Long.MIN_VALUE;
		}

		appraisalEvaluationFormStatusCacheModel.
			appraisalEvaluationFormStatusId =
				getAppraisalEvaluationFormStatusId();

		appraisalEvaluationFormStatusCacheModel.appraisalProcessId =
			getAppraisalProcessId();

		Date submissionDate = getSubmissionDate();

		if (submissionDate != null) {
			appraisalEvaluationFormStatusCacheModel.submissionDate =
				submissionDate.getTime();
		}
		else {
			appraisalEvaluationFormStatusCacheModel.submissionDate =
				Long.MIN_VALUE;
		}

		appraisalEvaluationFormStatusCacheModel.employeeId = getEmployeeId();

		appraisalEvaluationFormStatusCacheModel.filledEvaluationDocuemntId =
			getFilledEvaluationDocuemntId();

		appraisalEvaluationFormStatusCacheModel.appraisalFormTemplateId =
			getAppraisalFormTemplateId();

		appraisalEvaluationFormStatusCacheModel.status = isStatus();

		return appraisalEvaluationFormStatusCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<AppraisalEvaluationFormStatus, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<AppraisalEvaluationFormStatus, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AppraisalEvaluationFormStatus, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(AppraisalEvaluationFormStatus)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, AppraisalEvaluationFormStatus>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						AppraisalEvaluationFormStatus.class,
						ModelWrapper.class);

	}

	private String _uuid;
	private long _companyId;
	private long _createdBy;
	private long _modifiedBy;
	private long _groupId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _appraisalEvaluationFormStatusId;
	private long _appraisalProcessId;
	private Date _submissionDate;
	private long _employeeId;
	private long _filledEvaluationDocuemntId;
	private long _appraisalFormTemplateId;
	private boolean _status;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<AppraisalEvaluationFormStatus, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((AppraisalEvaluationFormStatus)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createdBy", _createdBy);
		_columnOriginalValues.put("modifiedBy", _modifiedBy);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put(
			"appraisalEvaluationFormStatusId",
			_appraisalEvaluationFormStatusId);
		_columnOriginalValues.put("appraisalProcessId", _appraisalProcessId);
		_columnOriginalValues.put("submissionDate", _submissionDate);
		_columnOriginalValues.put("employeeId", _employeeId);
		_columnOriginalValues.put(
			"filledEvaluationDocuemntId", _filledEvaluationDocuemntId);
		_columnOriginalValues.put(
			"appraisalFormTemplateId", _appraisalFormTemplateId);
		_columnOriginalValues.put("status", _status);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("createdBy", 4L);

		columnBitmasks.put("modifiedBy", 8L);

		columnBitmasks.put("groupId", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("appraisalEvaluationFormStatusId", 128L);

		columnBitmasks.put("appraisalProcessId", 256L);

		columnBitmasks.put("submissionDate", 512L);

		columnBitmasks.put("employeeId", 1024L);

		columnBitmasks.put("filledEvaluationDocuemntId", 2048L);

		columnBitmasks.put("appraisalFormTemplateId", 4096L);

		columnBitmasks.put("status", 8192L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private AppraisalEvaluationFormStatus _escapedModel;

}