/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.model.impl;

import com.ax.hrms.model.Comment;
import com.ax.hrms.service.CommentLocalServiceUtil;

/**
 * The extended model base implementation for the Comment service. Represents a row in the &quot;ax_Comment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CommentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CommentImpl
 * @see Comment
 * @generated
 */
public abstract class CommentBaseImpl
	extends CommentModelImpl implements Comment {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a comment model instance should use the <code>Comment</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			CommentLocalServiceUtil.addComment(this);
		}
		else {
			CommentLocalServiceUtil.updateComment(this);
		}
	}

}