/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.model.impl;

import com.ax.hrms.model.CompensatoryData;
import com.ax.hrms.service.CompensatoryDataLocalServiceUtil;

/**
 * The extended model base implementation for the CompensatoryData service. Represents a row in the &quot;ax_CompensatoryData&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CompensatoryDataImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CompensatoryDataImpl
 * @see CompensatoryData
 * @generated
 */
public abstract class CompensatoryDataBaseImpl
	extends CompensatoryDataModelImpl implements CompensatoryData {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a compensatory data model instance should use the <code>CompensatoryData</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			CompensatoryDataLocalServiceUtil.addCompensatoryData(this);
		}
		else {
			CompensatoryDataLocalServiceUtil.updateCompensatoryData(this);
		}
	}

}