/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.model.impl;

import com.ax.hrms.model.EmployeeBankAccount;
import com.ax.hrms.service.EmployeeBankAccountLocalServiceUtil;

/**
 * The extended model base implementation for the EmployeeBankAccount service. Represents a row in the &quot;ax_EmployeeBankAccount&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EmployeeBankAccountImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmployeeBankAccountImpl
 * @see EmployeeBankAccount
 * @generated
 */
public abstract class EmployeeBankAccountBaseImpl
	extends EmployeeBankAccountModelImpl implements EmployeeBankAccount {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a employee bank account model instance should use the <code>EmployeeBankAccount</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			EmployeeBankAccountLocalServiceUtil.addEmployeeBankAccount(this);
		}
		else {
			EmployeeBankAccountLocalServiceUtil.updateEmployeeBankAccount(this);
		}
	}

}