/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.model.impl;

import com.ax.hrms.model.EmployeeDepartment;
import com.ax.hrms.model.EmployeeDepartmentModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the EmployeeDepartment service. Represents a row in the &quot;ax_EmployeeDepartment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>EmployeeDepartmentModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EmployeeDepartmentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmployeeDepartmentImpl
 * @generated
 */
@JSON(strict = true)
public class EmployeeDepartmentModelImpl
	extends BaseModelImpl<EmployeeDepartment>
	implements EmployeeDepartmentModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a employee department model instance should use the <code>EmployeeDepartment</code> interface instead.
	 */
	public static final String TABLE_NAME = "ax_EmployeeDepartment";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"companyId", Types.BIGINT},
		{"createdBy", Types.BIGINT}, {"modifiedBy", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP},
		{"employeeDepartmentId", Types.BIGINT},
		{"departmentMasterId", Types.BIGINT}, {"status", Types.BOOLEAN},
		{"dateOfChange", Types.TIMESTAMP}, {"employeeId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("employeeDepartmentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("departmentMasterId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("status", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("dateOfChange", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("employeeId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ax_EmployeeDepartment (uuid_ VARCHAR(75) null,companyId LONG,createdBy LONG,modifiedBy LONG,groupId LONG,createDate DATE null,modifiedDate DATE null,employeeDepartmentId LONG not null primary key,departmentMasterId LONG,status BOOLEAN,dateOfChange DATE null,employeeId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table ax_EmployeeDepartment";

	public static final String ORDER_BY_JPQL =
		" ORDER BY employeeDepartment.employeeDepartmentId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ax_EmployeeDepartment.employeeDepartmentId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DEPARTMENTMASTERID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EMPLOYEEID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STATUS_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EMPLOYEEDEPARTMENTID_COLUMN_BITMASK = 64L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public EmployeeDepartmentModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _employeeDepartmentId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEmployeeDepartmentId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _employeeDepartmentId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return EmployeeDepartment.class;
	}

	@Override
	public String getModelClassName() {
		return EmployeeDepartment.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<EmployeeDepartment, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<EmployeeDepartment, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EmployeeDepartment, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((EmployeeDepartment)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<EmployeeDepartment, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<EmployeeDepartment, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(EmployeeDepartment)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<EmployeeDepartment, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<EmployeeDepartment, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<EmployeeDepartment, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<EmployeeDepartment, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<EmployeeDepartment, Object>>();

			attributeGetterFunctions.put("uuid", EmployeeDepartment::getUuid);
			attributeGetterFunctions.put(
				"companyId", EmployeeDepartment::getCompanyId);
			attributeGetterFunctions.put(
				"createdBy", EmployeeDepartment::getCreatedBy);
			attributeGetterFunctions.put(
				"modifiedBy", EmployeeDepartment::getModifiedBy);
			attributeGetterFunctions.put(
				"groupId", EmployeeDepartment::getGroupId);
			attributeGetterFunctions.put(
				"createDate", EmployeeDepartment::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", EmployeeDepartment::getModifiedDate);
			attributeGetterFunctions.put(
				"employeeDepartmentId",
				EmployeeDepartment::getEmployeeDepartmentId);
			attributeGetterFunctions.put(
				"departmentMasterId",
				EmployeeDepartment::getDepartmentMasterId);
			attributeGetterFunctions.put(
				"status", EmployeeDepartment::getStatus);
			attributeGetterFunctions.put(
				"dateOfChange", EmployeeDepartment::getDateOfChange);
			attributeGetterFunctions.put(
				"employeeId", EmployeeDepartment::getEmployeeId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<EmployeeDepartment, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<EmployeeDepartment, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<EmployeeDepartment, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<EmployeeDepartment, String>)
					EmployeeDepartment::setUuid);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<EmployeeDepartment, Long>)
					EmployeeDepartment::setCompanyId);
			attributeSetterBiConsumers.put(
				"createdBy",
				(BiConsumer<EmployeeDepartment, Long>)
					EmployeeDepartment::setCreatedBy);
			attributeSetterBiConsumers.put(
				"modifiedBy",
				(BiConsumer<EmployeeDepartment, Long>)
					EmployeeDepartment::setModifiedBy);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<EmployeeDepartment, Long>)
					EmployeeDepartment::setGroupId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<EmployeeDepartment, Date>)
					EmployeeDepartment::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<EmployeeDepartment, Date>)
					EmployeeDepartment::setModifiedDate);
			attributeSetterBiConsumers.put(
				"employeeDepartmentId",
				(BiConsumer<EmployeeDepartment, Long>)
					EmployeeDepartment::setEmployeeDepartmentId);
			attributeSetterBiConsumers.put(
				"departmentMasterId",
				(BiConsumer<EmployeeDepartment, Long>)
					EmployeeDepartment::setDepartmentMasterId);
			attributeSetterBiConsumers.put(
				"status",
				(BiConsumer<EmployeeDepartment, Boolean>)
					EmployeeDepartment::setStatus);
			attributeSetterBiConsumers.put(
				"dateOfChange",
				(BiConsumer<EmployeeDepartment, Date>)
					EmployeeDepartment::setDateOfChange);
			attributeSetterBiConsumers.put(
				"employeeId",
				(BiConsumer<EmployeeDepartment, Long>)
					EmployeeDepartment::setEmployeeId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getEmployeeDepartmentId() {
		return _employeeDepartmentId;
	}

	@Override
	public void setEmployeeDepartmentId(long employeeDepartmentId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_employeeDepartmentId = employeeDepartmentId;
	}

	@JSON
	@Override
	public long getDepartmentMasterId() {
		return _departmentMasterId;
	}

	@Override
	public void setDepartmentMasterId(long departmentMasterId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_departmentMasterId = departmentMasterId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalDepartmentMasterId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("departmentMasterId"));
	}

	@JSON
	@Override
	public boolean getStatus() {
		return _status;
	}

	@JSON
	@Override
	public boolean isStatus() {
		return _status;
	}

	@Override
	public void setStatus(boolean status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public boolean getOriginalStatus() {
		return GetterUtil.getBoolean(
			this.<Boolean>getColumnOriginalValue("status"));
	}

	@JSON
	@Override
	public Date getDateOfChange() {
		return _dateOfChange;
	}

	@Override
	public void setDateOfChange(Date dateOfChange) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dateOfChange = dateOfChange;
	}

	@JSON
	@Override
	public long getEmployeeId() {
		return _employeeId;
	}

	@Override
	public void setEmployeeId(long employeeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_employeeId = employeeId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalEmployeeId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("employeeId"));
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(EmployeeDepartment.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), EmployeeDepartment.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public EmployeeDepartment toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, EmployeeDepartment>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EmployeeDepartmentImpl employeeDepartmentImpl =
			new EmployeeDepartmentImpl();

		employeeDepartmentImpl.setUuid(getUuid());
		employeeDepartmentImpl.setCompanyId(getCompanyId());
		employeeDepartmentImpl.setCreatedBy(getCreatedBy());
		employeeDepartmentImpl.setModifiedBy(getModifiedBy());
		employeeDepartmentImpl.setGroupId(getGroupId());
		employeeDepartmentImpl.setCreateDate(getCreateDate());
		employeeDepartmentImpl.setModifiedDate(getModifiedDate());
		employeeDepartmentImpl.setEmployeeDepartmentId(
			getEmployeeDepartmentId());
		employeeDepartmentImpl.setDepartmentMasterId(getDepartmentMasterId());
		employeeDepartmentImpl.setStatus(isStatus());
		employeeDepartmentImpl.setDateOfChange(getDateOfChange());
		employeeDepartmentImpl.setEmployeeId(getEmployeeId());

		employeeDepartmentImpl.resetOriginalValues();

		return employeeDepartmentImpl;
	}

	@Override
	public EmployeeDepartment cloneWithOriginalValues() {
		EmployeeDepartmentImpl employeeDepartmentImpl =
			new EmployeeDepartmentImpl();

		employeeDepartmentImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		employeeDepartmentImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		employeeDepartmentImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("createdBy"));
		employeeDepartmentImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modifiedBy"));
		employeeDepartmentImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		employeeDepartmentImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		employeeDepartmentImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		employeeDepartmentImpl.setEmployeeDepartmentId(
			this.<Long>getColumnOriginalValue("employeeDepartmentId"));
		employeeDepartmentImpl.setDepartmentMasterId(
			this.<Long>getColumnOriginalValue("departmentMasterId"));
		employeeDepartmentImpl.setStatus(
			this.<Boolean>getColumnOriginalValue("status"));
		employeeDepartmentImpl.setDateOfChange(
			this.<Date>getColumnOriginalValue("dateOfChange"));
		employeeDepartmentImpl.setEmployeeId(
			this.<Long>getColumnOriginalValue("employeeId"));

		return employeeDepartmentImpl;
	}

	@Override
	public int compareTo(EmployeeDepartment employeeDepartment) {
		long primaryKey = employeeDepartment.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof EmployeeDepartment)) {
			return false;
		}

		EmployeeDepartment employeeDepartment = (EmployeeDepartment)object;

		long primaryKey = employeeDepartment.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<EmployeeDepartment> toCacheModel() {
		EmployeeDepartmentCacheModel employeeDepartmentCacheModel =
			new EmployeeDepartmentCacheModel();

		employeeDepartmentCacheModel.uuid = getUuid();

		String uuid = employeeDepartmentCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			employeeDepartmentCacheModel.uuid = null;
		}

		employeeDepartmentCacheModel.companyId = getCompanyId();

		employeeDepartmentCacheModel.createdBy = getCreatedBy();

		employeeDepartmentCacheModel.modifiedBy = getModifiedBy();

		employeeDepartmentCacheModel.groupId = getGroupId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			employeeDepartmentCacheModel.createDate = createDate.getTime();
		}
		else {
			employeeDepartmentCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			employeeDepartmentCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			employeeDepartmentCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		employeeDepartmentCacheModel.employeeDepartmentId =
			getEmployeeDepartmentId();

		employeeDepartmentCacheModel.departmentMasterId =
			getDepartmentMasterId();

		employeeDepartmentCacheModel.status = isStatus();

		Date dateOfChange = getDateOfChange();

		if (dateOfChange != null) {
			employeeDepartmentCacheModel.dateOfChange = dateOfChange.getTime();
		}
		else {
			employeeDepartmentCacheModel.dateOfChange = Long.MIN_VALUE;
		}

		employeeDepartmentCacheModel.employeeId = getEmployeeId();

		return employeeDepartmentCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<EmployeeDepartment, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<EmployeeDepartment, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EmployeeDepartment, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(EmployeeDepartment)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, EmployeeDepartment>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					EmployeeDepartment.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _companyId;
	private long _createdBy;
	private long _modifiedBy;
	private long _groupId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _employeeDepartmentId;
	private long _departmentMasterId;
	private boolean _status;
	private Date _dateOfChange;
	private long _employeeId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<EmployeeDepartment, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((EmployeeDepartment)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createdBy", _createdBy);
		_columnOriginalValues.put("modifiedBy", _modifiedBy);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put(
			"employeeDepartmentId", _employeeDepartmentId);
		_columnOriginalValues.put("departmentMasterId", _departmentMasterId);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("dateOfChange", _dateOfChange);
		_columnOriginalValues.put("employeeId", _employeeId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("createdBy", 4L);

		columnBitmasks.put("modifiedBy", 8L);

		columnBitmasks.put("groupId", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("employeeDepartmentId", 128L);

		columnBitmasks.put("departmentMasterId", 256L);

		columnBitmasks.put("status", 512L);

		columnBitmasks.put("dateOfChange", 1024L);

		columnBitmasks.put("employeeId", 2048L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private EmployeeDepartment _escapedModel;

}