/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.model.impl;

import com.ax.hrms.model.EmployeeAddress;
import com.ax.hrms.model.EmployeeAddressModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the EmployeeAddress service. Represents a row in the &quot;ax_EmployeeAddress&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>EmployeeAddressModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EmployeeAddressImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmployeeAddressImpl
 * @generated
 */
@JSON(strict = true)
public class EmployeeAddressModelImpl
	extends BaseModelImpl<EmployeeAddress> implements EmployeeAddressModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a employee address model instance should use the <code>EmployeeAddress</code> interface instead.
	 */
	public static final String TABLE_NAME = "ax_EmployeeAddress";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"companyId", Types.BIGINT},
		{"createdBy", Types.BIGINT}, {"modifiedBy", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"employeeAddressId", Types.BIGINT},
		{"presentAddress", Types.BIGINT}, {"permanentAddress", Types.BIGINT},
		{"presentPermanentSame", Types.BOOLEAN}, {"status", Types.BOOLEAN},
		{"employeeId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("employeeAddressId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("presentAddress", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("permanentAddress", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("presentPermanentSame", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("status", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("employeeId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ax_EmployeeAddress (uuid_ VARCHAR(75) null,companyId LONG,createdBy LONG,modifiedBy LONG,groupId LONG,createDate DATE null,modifiedDate DATE null,employeeAddressId LONG not null primary key,presentAddress LONG,permanentAddress LONG,presentPermanentSame BOOLEAN,status BOOLEAN,employeeId LONG)";

	public static final String TABLE_SQL_DROP = "drop table ax_EmployeeAddress";

	public static final String ORDER_BY_JPQL =
		" ORDER BY employeeAddress.employeeAddressId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ax_EmployeeAddress.employeeAddressId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EMPLOYEEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EMPLOYEEADDRESSID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public EmployeeAddressModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _employeeAddressId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEmployeeAddressId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _employeeAddressId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return EmployeeAddress.class;
	}

	@Override
	public String getModelClassName() {
		return EmployeeAddress.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<EmployeeAddress, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<EmployeeAddress, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EmployeeAddress, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((EmployeeAddress)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<EmployeeAddress, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<EmployeeAddress, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(EmployeeAddress)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<EmployeeAddress, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<EmployeeAddress, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<EmployeeAddress, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<EmployeeAddress, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<EmployeeAddress, Object>>();

			attributeGetterFunctions.put("uuid", EmployeeAddress::getUuid);
			attributeGetterFunctions.put(
				"companyId", EmployeeAddress::getCompanyId);
			attributeGetterFunctions.put(
				"createdBy", EmployeeAddress::getCreatedBy);
			attributeGetterFunctions.put(
				"modifiedBy", EmployeeAddress::getModifiedBy);
			attributeGetterFunctions.put(
				"groupId", EmployeeAddress::getGroupId);
			attributeGetterFunctions.put(
				"createDate", EmployeeAddress::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", EmployeeAddress::getModifiedDate);
			attributeGetterFunctions.put(
				"employeeAddressId", EmployeeAddress::getEmployeeAddressId);
			attributeGetterFunctions.put(
				"presentAddress", EmployeeAddress::getPresentAddress);
			attributeGetterFunctions.put(
				"permanentAddress", EmployeeAddress::getPermanentAddress);
			attributeGetterFunctions.put(
				"presentPermanentSame",
				EmployeeAddress::getPresentPermanentSame);
			attributeGetterFunctions.put("status", EmployeeAddress::getStatus);
			attributeGetterFunctions.put(
				"employeeId", EmployeeAddress::getEmployeeId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<EmployeeAddress, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<EmployeeAddress, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<EmployeeAddress, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<EmployeeAddress, String>)EmployeeAddress::setUuid);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<EmployeeAddress, Long>)
					EmployeeAddress::setCompanyId);
			attributeSetterBiConsumers.put(
				"createdBy",
				(BiConsumer<EmployeeAddress, Long>)
					EmployeeAddress::setCreatedBy);
			attributeSetterBiConsumers.put(
				"modifiedBy",
				(BiConsumer<EmployeeAddress, Long>)
					EmployeeAddress::setModifiedBy);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<EmployeeAddress, Long>)EmployeeAddress::setGroupId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<EmployeeAddress, Date>)
					EmployeeAddress::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<EmployeeAddress, Date>)
					EmployeeAddress::setModifiedDate);
			attributeSetterBiConsumers.put(
				"employeeAddressId",
				(BiConsumer<EmployeeAddress, Long>)
					EmployeeAddress::setEmployeeAddressId);
			attributeSetterBiConsumers.put(
				"presentAddress",
				(BiConsumer<EmployeeAddress, Long>)
					EmployeeAddress::setPresentAddress);
			attributeSetterBiConsumers.put(
				"permanentAddress",
				(BiConsumer<EmployeeAddress, Long>)
					EmployeeAddress::setPermanentAddress);
			attributeSetterBiConsumers.put(
				"presentPermanentSame",
				(BiConsumer<EmployeeAddress, Boolean>)
					EmployeeAddress::setPresentPermanentSame);
			attributeSetterBiConsumers.put(
				"status",
				(BiConsumer<EmployeeAddress, Boolean>)
					EmployeeAddress::setStatus);
			attributeSetterBiConsumers.put(
				"employeeId",
				(BiConsumer<EmployeeAddress, Long>)
					EmployeeAddress::setEmployeeId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getEmployeeAddressId() {
		return _employeeAddressId;
	}

	@Override
	public void setEmployeeAddressId(long employeeAddressId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_employeeAddressId = employeeAddressId;
	}

	@JSON
	@Override
	public long getPresentAddress() {
		return _presentAddress;
	}

	@Override
	public void setPresentAddress(long presentAddress) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_presentAddress = presentAddress;
	}

	@JSON
	@Override
	public long getPermanentAddress() {
		return _permanentAddress;
	}

	@Override
	public void setPermanentAddress(long permanentAddress) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_permanentAddress = permanentAddress;
	}

	@JSON
	@Override
	public boolean getPresentPermanentSame() {
		return _presentPermanentSame;
	}

	@JSON
	@Override
	public boolean isPresentPermanentSame() {
		return _presentPermanentSame;
	}

	@Override
	public void setPresentPermanentSame(boolean presentPermanentSame) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_presentPermanentSame = presentPermanentSame;
	}

	@JSON
	@Override
	public boolean getStatus() {
		return _status;
	}

	@JSON
	@Override
	public boolean isStatus() {
		return _status;
	}

	@Override
	public void setStatus(boolean status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	@JSON
	@Override
	public long getEmployeeId() {
		return _employeeId;
	}

	@Override
	public void setEmployeeId(long employeeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_employeeId = employeeId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalEmployeeId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("employeeId"));
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(EmployeeAddress.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), EmployeeAddress.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public EmployeeAddress toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, EmployeeAddress>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EmployeeAddressImpl employeeAddressImpl = new EmployeeAddressImpl();

		employeeAddressImpl.setUuid(getUuid());
		employeeAddressImpl.setCompanyId(getCompanyId());
		employeeAddressImpl.setCreatedBy(getCreatedBy());
		employeeAddressImpl.setModifiedBy(getModifiedBy());
		employeeAddressImpl.setGroupId(getGroupId());
		employeeAddressImpl.setCreateDate(getCreateDate());
		employeeAddressImpl.setModifiedDate(getModifiedDate());
		employeeAddressImpl.setEmployeeAddressId(getEmployeeAddressId());
		employeeAddressImpl.setPresentAddress(getPresentAddress());
		employeeAddressImpl.setPermanentAddress(getPermanentAddress());
		employeeAddressImpl.setPresentPermanentSame(isPresentPermanentSame());
		employeeAddressImpl.setStatus(isStatus());
		employeeAddressImpl.setEmployeeId(getEmployeeId());

		employeeAddressImpl.resetOriginalValues();

		return employeeAddressImpl;
	}

	@Override
	public EmployeeAddress cloneWithOriginalValues() {
		EmployeeAddressImpl employeeAddressImpl = new EmployeeAddressImpl();

		employeeAddressImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		employeeAddressImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		employeeAddressImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("createdBy"));
		employeeAddressImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modifiedBy"));
		employeeAddressImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		employeeAddressImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		employeeAddressImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		employeeAddressImpl.setEmployeeAddressId(
			this.<Long>getColumnOriginalValue("employeeAddressId"));
		employeeAddressImpl.setPresentAddress(
			this.<Long>getColumnOriginalValue("presentAddress"));
		employeeAddressImpl.setPermanentAddress(
			this.<Long>getColumnOriginalValue("permanentAddress"));
		employeeAddressImpl.setPresentPermanentSame(
			this.<Boolean>getColumnOriginalValue("presentPermanentSame"));
		employeeAddressImpl.setStatus(
			this.<Boolean>getColumnOriginalValue("status"));
		employeeAddressImpl.setEmployeeId(
			this.<Long>getColumnOriginalValue("employeeId"));

		return employeeAddressImpl;
	}

	@Override
	public int compareTo(EmployeeAddress employeeAddress) {
		long primaryKey = employeeAddress.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof EmployeeAddress)) {
			return false;
		}

		EmployeeAddress employeeAddress = (EmployeeAddress)object;

		long primaryKey = employeeAddress.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<EmployeeAddress> toCacheModel() {
		EmployeeAddressCacheModel employeeAddressCacheModel =
			new EmployeeAddressCacheModel();

		employeeAddressCacheModel.uuid = getUuid();

		String uuid = employeeAddressCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			employeeAddressCacheModel.uuid = null;
		}

		employeeAddressCacheModel.companyId = getCompanyId();

		employeeAddressCacheModel.createdBy = getCreatedBy();

		employeeAddressCacheModel.modifiedBy = getModifiedBy();

		employeeAddressCacheModel.groupId = getGroupId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			employeeAddressCacheModel.createDate = createDate.getTime();
		}
		else {
			employeeAddressCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			employeeAddressCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			employeeAddressCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		employeeAddressCacheModel.employeeAddressId = getEmployeeAddressId();

		employeeAddressCacheModel.presentAddress = getPresentAddress();

		employeeAddressCacheModel.permanentAddress = getPermanentAddress();

		employeeAddressCacheModel.presentPermanentSame =
			isPresentPermanentSame();

		employeeAddressCacheModel.status = isStatus();

		employeeAddressCacheModel.employeeId = getEmployeeId();

		return employeeAddressCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<EmployeeAddress, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<EmployeeAddress, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EmployeeAddress, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((EmployeeAddress)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, EmployeeAddress>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					EmployeeAddress.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _companyId;
	private long _createdBy;
	private long _modifiedBy;
	private long _groupId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _employeeAddressId;
	private long _presentAddress;
	private long _permanentAddress;
	private boolean _presentPermanentSame;
	private boolean _status;
	private long _employeeId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<EmployeeAddress, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((EmployeeAddress)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createdBy", _createdBy);
		_columnOriginalValues.put("modifiedBy", _modifiedBy);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("employeeAddressId", _employeeAddressId);
		_columnOriginalValues.put("presentAddress", _presentAddress);
		_columnOriginalValues.put("permanentAddress", _permanentAddress);
		_columnOriginalValues.put(
			"presentPermanentSame", _presentPermanentSame);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("employeeId", _employeeId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("createdBy", 4L);

		columnBitmasks.put("modifiedBy", 8L);

		columnBitmasks.put("groupId", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("employeeAddressId", 128L);

		columnBitmasks.put("presentAddress", 256L);

		columnBitmasks.put("permanentAddress", 512L);

		columnBitmasks.put("presentPermanentSame", 1024L);

		columnBitmasks.put("status", 2048L);

		columnBitmasks.put("employeeId", 4096L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private EmployeeAddress _escapedModel;

}