/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.model.impl;

import com.ax.hrms.model.EmployeeDesignation;
import com.ax.hrms.model.EmployeeDesignationModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the EmployeeDesignation service. Represents a row in the &quot;ax_EmployeeDesignation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>EmployeeDesignationModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EmployeeDesignationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmployeeDesignationImpl
 * @generated
 */
@JSON(strict = true)
public class EmployeeDesignationModelImpl
	extends BaseModelImpl<EmployeeDesignation>
	implements EmployeeDesignationModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a employee designation model instance should use the <code>EmployeeDesignation</code> interface instead.
	 */
	public static final String TABLE_NAME = "ax_EmployeeDesignation";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"companyId", Types.BIGINT},
		{"createdBy", Types.BIGINT}, {"modifiedBy", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP},
		{"employeeDesignationId", Types.BIGINT},
		{"designationMasterId", Types.BIGINT}, {"status", Types.BOOLEAN},
		{"startDate", Types.TIMESTAMP}, {"endDate", Types.TIMESTAMP},
		{"employeeId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("employeeDesignationId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("designationMasterId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("status", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("startDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("endDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("employeeId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ax_EmployeeDesignation (uuid_ VARCHAR(75) null,companyId LONG,createdBy LONG,modifiedBy LONG,groupId LONG,createDate DATE null,modifiedDate DATE null,employeeDesignationId LONG not null primary key,designationMasterId LONG,status BOOLEAN,startDate DATE null,endDate DATE null,employeeId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table ax_EmployeeDesignation";

	public static final String ORDER_BY_JPQL =
		" ORDER BY employeeDesignation.employeeDesignationId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ax_EmployeeDesignation.employeeDesignationId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EMPLOYEEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EMPLOYEEDESIGNATIONID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public EmployeeDesignationModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _employeeDesignationId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEmployeeDesignationId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _employeeDesignationId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return EmployeeDesignation.class;
	}

	@Override
	public String getModelClassName() {
		return EmployeeDesignation.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<EmployeeDesignation, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<EmployeeDesignation, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EmployeeDesignation, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((EmployeeDesignation)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<EmployeeDesignation, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<EmployeeDesignation, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(EmployeeDesignation)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<EmployeeDesignation, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<EmployeeDesignation, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<EmployeeDesignation, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<EmployeeDesignation, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<EmployeeDesignation, Object>>();

			attributeGetterFunctions.put("uuid", EmployeeDesignation::getUuid);
			attributeGetterFunctions.put(
				"companyId", EmployeeDesignation::getCompanyId);
			attributeGetterFunctions.put(
				"createdBy", EmployeeDesignation::getCreatedBy);
			attributeGetterFunctions.put(
				"modifiedBy", EmployeeDesignation::getModifiedBy);
			attributeGetterFunctions.put(
				"groupId", EmployeeDesignation::getGroupId);
			attributeGetterFunctions.put(
				"createDate", EmployeeDesignation::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", EmployeeDesignation::getModifiedDate);
			attributeGetterFunctions.put(
				"employeeDesignationId",
				EmployeeDesignation::getEmployeeDesignationId);
			attributeGetterFunctions.put(
				"designationMasterId",
				EmployeeDesignation::getDesignationMasterId);
			attributeGetterFunctions.put(
				"status", EmployeeDesignation::getStatus);
			attributeGetterFunctions.put(
				"startDate", EmployeeDesignation::getStartDate);
			attributeGetterFunctions.put(
				"endDate", EmployeeDesignation::getEndDate);
			attributeGetterFunctions.put(
				"employeeId", EmployeeDesignation::getEmployeeId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<EmployeeDesignation, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<EmployeeDesignation, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<EmployeeDesignation, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<EmployeeDesignation, String>)
					EmployeeDesignation::setUuid);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<EmployeeDesignation, Long>)
					EmployeeDesignation::setCompanyId);
			attributeSetterBiConsumers.put(
				"createdBy",
				(BiConsumer<EmployeeDesignation, Long>)
					EmployeeDesignation::setCreatedBy);
			attributeSetterBiConsumers.put(
				"modifiedBy",
				(BiConsumer<EmployeeDesignation, Long>)
					EmployeeDesignation::setModifiedBy);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<EmployeeDesignation, Long>)
					EmployeeDesignation::setGroupId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<EmployeeDesignation, Date>)
					EmployeeDesignation::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<EmployeeDesignation, Date>)
					EmployeeDesignation::setModifiedDate);
			attributeSetterBiConsumers.put(
				"employeeDesignationId",
				(BiConsumer<EmployeeDesignation, Long>)
					EmployeeDesignation::setEmployeeDesignationId);
			attributeSetterBiConsumers.put(
				"designationMasterId",
				(BiConsumer<EmployeeDesignation, Long>)
					EmployeeDesignation::setDesignationMasterId);
			attributeSetterBiConsumers.put(
				"status",
				(BiConsumer<EmployeeDesignation, Boolean>)
					EmployeeDesignation::setStatus);
			attributeSetterBiConsumers.put(
				"startDate",
				(BiConsumer<EmployeeDesignation, Date>)
					EmployeeDesignation::setStartDate);
			attributeSetterBiConsumers.put(
				"endDate",
				(BiConsumer<EmployeeDesignation, Date>)
					EmployeeDesignation::setEndDate);
			attributeSetterBiConsumers.put(
				"employeeId",
				(BiConsumer<EmployeeDesignation, Long>)
					EmployeeDesignation::setEmployeeId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getEmployeeDesignationId() {
		return _employeeDesignationId;
	}

	@Override
	public void setEmployeeDesignationId(long employeeDesignationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_employeeDesignationId = employeeDesignationId;
	}

	@JSON
	@Override
	public long getDesignationMasterId() {
		return _designationMasterId;
	}

	@Override
	public void setDesignationMasterId(long designationMasterId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_designationMasterId = designationMasterId;
	}

	@JSON
	@Override
	public boolean getStatus() {
		return _status;
	}

	@JSON
	@Override
	public boolean isStatus() {
		return _status;
	}

	@Override
	public void setStatus(boolean status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	@JSON
	@Override
	public Date getStartDate() {
		return _startDate;
	}

	@Override
	public void setStartDate(Date startDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_startDate = startDate;
	}

	@JSON
	@Override
	public Date getEndDate() {
		return _endDate;
	}

	@Override
	public void setEndDate(Date endDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_endDate = endDate;
	}

	@JSON
	@Override
	public long getEmployeeId() {
		return _employeeId;
	}

	@Override
	public void setEmployeeId(long employeeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_employeeId = employeeId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalEmployeeId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("employeeId"));
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(EmployeeDesignation.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), EmployeeDesignation.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public EmployeeDesignation toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, EmployeeDesignation>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EmployeeDesignationImpl employeeDesignationImpl =
			new EmployeeDesignationImpl();

		employeeDesignationImpl.setUuid(getUuid());
		employeeDesignationImpl.setCompanyId(getCompanyId());
		employeeDesignationImpl.setCreatedBy(getCreatedBy());
		employeeDesignationImpl.setModifiedBy(getModifiedBy());
		employeeDesignationImpl.setGroupId(getGroupId());
		employeeDesignationImpl.setCreateDate(getCreateDate());
		employeeDesignationImpl.setModifiedDate(getModifiedDate());
		employeeDesignationImpl.setEmployeeDesignationId(
			getEmployeeDesignationId());
		employeeDesignationImpl.setDesignationMasterId(
			getDesignationMasterId());
		employeeDesignationImpl.setStatus(isStatus());
		employeeDesignationImpl.setStartDate(getStartDate());
		employeeDesignationImpl.setEndDate(getEndDate());
		employeeDesignationImpl.setEmployeeId(getEmployeeId());

		employeeDesignationImpl.resetOriginalValues();

		return employeeDesignationImpl;
	}

	@Override
	public EmployeeDesignation cloneWithOriginalValues() {
		EmployeeDesignationImpl employeeDesignationImpl =
			new EmployeeDesignationImpl();

		employeeDesignationImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		employeeDesignationImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		employeeDesignationImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("createdBy"));
		employeeDesignationImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modifiedBy"));
		employeeDesignationImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		employeeDesignationImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		employeeDesignationImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		employeeDesignationImpl.setEmployeeDesignationId(
			this.<Long>getColumnOriginalValue("employeeDesignationId"));
		employeeDesignationImpl.setDesignationMasterId(
			this.<Long>getColumnOriginalValue("designationMasterId"));
		employeeDesignationImpl.setStatus(
			this.<Boolean>getColumnOriginalValue("status"));
		employeeDesignationImpl.setStartDate(
			this.<Date>getColumnOriginalValue("startDate"));
		employeeDesignationImpl.setEndDate(
			this.<Date>getColumnOriginalValue("endDate"));
		employeeDesignationImpl.setEmployeeId(
			this.<Long>getColumnOriginalValue("employeeId"));

		return employeeDesignationImpl;
	}

	@Override
	public int compareTo(EmployeeDesignation employeeDesignation) {
		long primaryKey = employeeDesignation.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof EmployeeDesignation)) {
			return false;
		}

		EmployeeDesignation employeeDesignation = (EmployeeDesignation)object;

		long primaryKey = employeeDesignation.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<EmployeeDesignation> toCacheModel() {
		EmployeeDesignationCacheModel employeeDesignationCacheModel =
			new EmployeeDesignationCacheModel();

		employeeDesignationCacheModel.uuid = getUuid();

		String uuid = employeeDesignationCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			employeeDesignationCacheModel.uuid = null;
		}

		employeeDesignationCacheModel.companyId = getCompanyId();

		employeeDesignationCacheModel.createdBy = getCreatedBy();

		employeeDesignationCacheModel.modifiedBy = getModifiedBy();

		employeeDesignationCacheModel.groupId = getGroupId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			employeeDesignationCacheModel.createDate = createDate.getTime();
		}
		else {
			employeeDesignationCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			employeeDesignationCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			employeeDesignationCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		employeeDesignationCacheModel.employeeDesignationId =
			getEmployeeDesignationId();

		employeeDesignationCacheModel.designationMasterId =
			getDesignationMasterId();

		employeeDesignationCacheModel.status = isStatus();

		Date startDate = getStartDate();

		if (startDate != null) {
			employeeDesignationCacheModel.startDate = startDate.getTime();
		}
		else {
			employeeDesignationCacheModel.startDate = Long.MIN_VALUE;
		}

		Date endDate = getEndDate();

		if (endDate != null) {
			employeeDesignationCacheModel.endDate = endDate.getTime();
		}
		else {
			employeeDesignationCacheModel.endDate = Long.MIN_VALUE;
		}

		employeeDesignationCacheModel.employeeId = getEmployeeId();

		return employeeDesignationCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<EmployeeDesignation, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<EmployeeDesignation, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EmployeeDesignation, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(EmployeeDesignation)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, EmployeeDesignation>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					EmployeeDesignation.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _companyId;
	private long _createdBy;
	private long _modifiedBy;
	private long _groupId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _employeeDesignationId;
	private long _designationMasterId;
	private boolean _status;
	private Date _startDate;
	private Date _endDate;
	private long _employeeId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<EmployeeDesignation, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((EmployeeDesignation)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createdBy", _createdBy);
		_columnOriginalValues.put("modifiedBy", _modifiedBy);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put(
			"employeeDesignationId", _employeeDesignationId);
		_columnOriginalValues.put("designationMasterId", _designationMasterId);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("startDate", _startDate);
		_columnOriginalValues.put("endDate", _endDate);
		_columnOriginalValues.put("employeeId", _employeeId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("createdBy", 4L);

		columnBitmasks.put("modifiedBy", 8L);

		columnBitmasks.put("groupId", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("employeeDesignationId", 128L);

		columnBitmasks.put("designationMasterId", 256L);

		columnBitmasks.put("status", 512L);

		columnBitmasks.put("startDate", 1024L);

		columnBitmasks.put("endDate", 2048L);

		columnBitmasks.put("employeeId", 4096L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private EmployeeDesignation _escapedModel;

}