/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.model.impl;

import com.ax.hrms.model.EmployeeDocument;
import com.ax.hrms.model.EmployeeDocumentModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the EmployeeDocument service. Represents a row in the &quot;ax_EmployeeDocument&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>EmployeeDocumentModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EmployeeDocumentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmployeeDocumentImpl
 * @generated
 */
@JSON(strict = true)
public class EmployeeDocumentModelImpl
	extends BaseModelImpl<EmployeeDocument> implements EmployeeDocumentModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a employee document model instance should use the <code>EmployeeDocument</code> interface instead.
	 */
	public static final String TABLE_NAME = "ax_EmployeeDocument";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"companyId", Types.BIGINT},
		{"createdBy", Types.BIGINT}, {"modifiedBy", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"documentId", Types.BIGINT},
		{"documentTypeId", Types.BIGINT}, {"documentNumber", Types.VARCHAR},
		{"documentName", Types.VARCHAR}, {"documentMediaId", Types.BIGINT},
		{"documentStatus", Types.BOOLEAN}, {"employeeId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("documentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("documentTypeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("documentNumber", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("documentName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("documentMediaId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("documentStatus", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("employeeId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ax_EmployeeDocument (uuid_ VARCHAR(75) null,companyId LONG,createdBy LONG,modifiedBy LONG,groupId LONG,createDate DATE null,modifiedDate DATE null,documentId LONG not null primary key,documentTypeId LONG,documentNumber VARCHAR(75) null,documentName VARCHAR(75) null,documentMediaId LONG,documentStatus BOOLEAN,employeeId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table ax_EmployeeDocument";

	public static final String ORDER_BY_JPQL =
		" ORDER BY employeeDocument.documentId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ax_EmployeeDocument.documentId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DOCUMENTID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public EmployeeDocumentModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _documentId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setDocumentId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _documentId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return EmployeeDocument.class;
	}

	@Override
	public String getModelClassName() {
		return EmployeeDocument.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<EmployeeDocument, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<EmployeeDocument, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EmployeeDocument, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((EmployeeDocument)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<EmployeeDocument, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<EmployeeDocument, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(EmployeeDocument)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<EmployeeDocument, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<EmployeeDocument, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<EmployeeDocument, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<EmployeeDocument, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<EmployeeDocument, Object>>();

			attributeGetterFunctions.put("uuid", EmployeeDocument::getUuid);
			attributeGetterFunctions.put(
				"companyId", EmployeeDocument::getCompanyId);
			attributeGetterFunctions.put(
				"createdBy", EmployeeDocument::getCreatedBy);
			attributeGetterFunctions.put(
				"modifiedBy", EmployeeDocument::getModifiedBy);
			attributeGetterFunctions.put(
				"groupId", EmployeeDocument::getGroupId);
			attributeGetterFunctions.put(
				"createDate", EmployeeDocument::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", EmployeeDocument::getModifiedDate);
			attributeGetterFunctions.put(
				"documentId", EmployeeDocument::getDocumentId);
			attributeGetterFunctions.put(
				"documentTypeId", EmployeeDocument::getDocumentTypeId);
			attributeGetterFunctions.put(
				"documentNumber", EmployeeDocument::getDocumentNumber);
			attributeGetterFunctions.put(
				"documentName", EmployeeDocument::getDocumentName);
			attributeGetterFunctions.put(
				"documentMediaId", EmployeeDocument::getDocumentMediaId);
			attributeGetterFunctions.put(
				"documentStatus", EmployeeDocument::getDocumentStatus);
			attributeGetterFunctions.put(
				"employeeId", EmployeeDocument::getEmployeeId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<EmployeeDocument, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<EmployeeDocument, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<EmployeeDocument, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<EmployeeDocument, String>)
					EmployeeDocument::setUuid);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<EmployeeDocument, Long>)
					EmployeeDocument::setCompanyId);
			attributeSetterBiConsumers.put(
				"createdBy",
				(BiConsumer<EmployeeDocument, Long>)
					EmployeeDocument::setCreatedBy);
			attributeSetterBiConsumers.put(
				"modifiedBy",
				(BiConsumer<EmployeeDocument, Long>)
					EmployeeDocument::setModifiedBy);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<EmployeeDocument, Long>)
					EmployeeDocument::setGroupId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<EmployeeDocument, Date>)
					EmployeeDocument::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<EmployeeDocument, Date>)
					EmployeeDocument::setModifiedDate);
			attributeSetterBiConsumers.put(
				"documentId",
				(BiConsumer<EmployeeDocument, Long>)
					EmployeeDocument::setDocumentId);
			attributeSetterBiConsumers.put(
				"documentTypeId",
				(BiConsumer<EmployeeDocument, Long>)
					EmployeeDocument::setDocumentTypeId);
			attributeSetterBiConsumers.put(
				"documentNumber",
				(BiConsumer<EmployeeDocument, String>)
					EmployeeDocument::setDocumentNumber);
			attributeSetterBiConsumers.put(
				"documentName",
				(BiConsumer<EmployeeDocument, String>)
					EmployeeDocument::setDocumentName);
			attributeSetterBiConsumers.put(
				"documentMediaId",
				(BiConsumer<EmployeeDocument, Long>)
					EmployeeDocument::setDocumentMediaId);
			attributeSetterBiConsumers.put(
				"documentStatus",
				(BiConsumer<EmployeeDocument, Boolean>)
					EmployeeDocument::setDocumentStatus);
			attributeSetterBiConsumers.put(
				"employeeId",
				(BiConsumer<EmployeeDocument, Long>)
					EmployeeDocument::setEmployeeId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getDocumentId() {
		return _documentId;
	}

	@Override
	public void setDocumentId(long documentId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_documentId = documentId;
	}

	@JSON
	@Override
	public long getDocumentTypeId() {
		return _documentTypeId;
	}

	@Override
	public void setDocumentTypeId(long documentTypeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_documentTypeId = documentTypeId;
	}

	@JSON
	@Override
	public String getDocumentNumber() {
		if (_documentNumber == null) {
			return "";
		}
		else {
			return _documentNumber;
		}
	}

	@Override
	public void setDocumentNumber(String documentNumber) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_documentNumber = documentNumber;
	}

	@JSON
	@Override
	public String getDocumentName() {
		if (_documentName == null) {
			return "";
		}
		else {
			return _documentName;
		}
	}

	@Override
	public void setDocumentName(String documentName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_documentName = documentName;
	}

	@JSON
	@Override
	public long getDocumentMediaId() {
		return _documentMediaId;
	}

	@Override
	public void setDocumentMediaId(long documentMediaId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_documentMediaId = documentMediaId;
	}

	@JSON
	@Override
	public boolean getDocumentStatus() {
		return _documentStatus;
	}

	@JSON
	@Override
	public boolean isDocumentStatus() {
		return _documentStatus;
	}

	@Override
	public void setDocumentStatus(boolean documentStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_documentStatus = documentStatus;
	}

	@JSON
	@Override
	public long getEmployeeId() {
		return _employeeId;
	}

	@Override
	public void setEmployeeId(long employeeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_employeeId = employeeId;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(EmployeeDocument.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), EmployeeDocument.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public EmployeeDocument toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, EmployeeDocument>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EmployeeDocumentImpl employeeDocumentImpl = new EmployeeDocumentImpl();

		employeeDocumentImpl.setUuid(getUuid());
		employeeDocumentImpl.setCompanyId(getCompanyId());
		employeeDocumentImpl.setCreatedBy(getCreatedBy());
		employeeDocumentImpl.setModifiedBy(getModifiedBy());
		employeeDocumentImpl.setGroupId(getGroupId());
		employeeDocumentImpl.setCreateDate(getCreateDate());
		employeeDocumentImpl.setModifiedDate(getModifiedDate());
		employeeDocumentImpl.setDocumentId(getDocumentId());
		employeeDocumentImpl.setDocumentTypeId(getDocumentTypeId());
		employeeDocumentImpl.setDocumentNumber(getDocumentNumber());
		employeeDocumentImpl.setDocumentName(getDocumentName());
		employeeDocumentImpl.setDocumentMediaId(getDocumentMediaId());
		employeeDocumentImpl.setDocumentStatus(isDocumentStatus());
		employeeDocumentImpl.setEmployeeId(getEmployeeId());

		employeeDocumentImpl.resetOriginalValues();

		return employeeDocumentImpl;
	}

	@Override
	public EmployeeDocument cloneWithOriginalValues() {
		EmployeeDocumentImpl employeeDocumentImpl = new EmployeeDocumentImpl();

		employeeDocumentImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		employeeDocumentImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		employeeDocumentImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("createdBy"));
		employeeDocumentImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modifiedBy"));
		employeeDocumentImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		employeeDocumentImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		employeeDocumentImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		employeeDocumentImpl.setDocumentId(
			this.<Long>getColumnOriginalValue("documentId"));
		employeeDocumentImpl.setDocumentTypeId(
			this.<Long>getColumnOriginalValue("documentTypeId"));
		employeeDocumentImpl.setDocumentNumber(
			this.<String>getColumnOriginalValue("documentNumber"));
		employeeDocumentImpl.setDocumentName(
			this.<String>getColumnOriginalValue("documentName"));
		employeeDocumentImpl.setDocumentMediaId(
			this.<Long>getColumnOriginalValue("documentMediaId"));
		employeeDocumentImpl.setDocumentStatus(
			this.<Boolean>getColumnOriginalValue("documentStatus"));
		employeeDocumentImpl.setEmployeeId(
			this.<Long>getColumnOriginalValue("employeeId"));

		return employeeDocumentImpl;
	}

	@Override
	public int compareTo(EmployeeDocument employeeDocument) {
		long primaryKey = employeeDocument.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof EmployeeDocument)) {
			return false;
		}

		EmployeeDocument employeeDocument = (EmployeeDocument)object;

		long primaryKey = employeeDocument.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<EmployeeDocument> toCacheModel() {
		EmployeeDocumentCacheModel employeeDocumentCacheModel =
			new EmployeeDocumentCacheModel();

		employeeDocumentCacheModel.uuid = getUuid();

		String uuid = employeeDocumentCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			employeeDocumentCacheModel.uuid = null;
		}

		employeeDocumentCacheModel.companyId = getCompanyId();

		employeeDocumentCacheModel.createdBy = getCreatedBy();

		employeeDocumentCacheModel.modifiedBy = getModifiedBy();

		employeeDocumentCacheModel.groupId = getGroupId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			employeeDocumentCacheModel.createDate = createDate.getTime();
		}
		else {
			employeeDocumentCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			employeeDocumentCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			employeeDocumentCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		employeeDocumentCacheModel.documentId = getDocumentId();

		employeeDocumentCacheModel.documentTypeId = getDocumentTypeId();

		employeeDocumentCacheModel.documentNumber = getDocumentNumber();

		String documentNumber = employeeDocumentCacheModel.documentNumber;

		if ((documentNumber != null) && (documentNumber.length() == 0)) {
			employeeDocumentCacheModel.documentNumber = null;
		}

		employeeDocumentCacheModel.documentName = getDocumentName();

		String documentName = employeeDocumentCacheModel.documentName;

		if ((documentName != null) && (documentName.length() == 0)) {
			employeeDocumentCacheModel.documentName = null;
		}

		employeeDocumentCacheModel.documentMediaId = getDocumentMediaId();

		employeeDocumentCacheModel.documentStatus = isDocumentStatus();

		employeeDocumentCacheModel.employeeId = getEmployeeId();

		return employeeDocumentCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<EmployeeDocument, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<EmployeeDocument, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EmployeeDocument, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(EmployeeDocument)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, EmployeeDocument>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					EmployeeDocument.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _companyId;
	private long _createdBy;
	private long _modifiedBy;
	private long _groupId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _documentId;
	private long _documentTypeId;
	private String _documentNumber;
	private String _documentName;
	private long _documentMediaId;
	private boolean _documentStatus;
	private long _employeeId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<EmployeeDocument, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((EmployeeDocument)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createdBy", _createdBy);
		_columnOriginalValues.put("modifiedBy", _modifiedBy);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("documentId", _documentId);
		_columnOriginalValues.put("documentTypeId", _documentTypeId);
		_columnOriginalValues.put("documentNumber", _documentNumber);
		_columnOriginalValues.put("documentName", _documentName);
		_columnOriginalValues.put("documentMediaId", _documentMediaId);
		_columnOriginalValues.put("documentStatus", _documentStatus);
		_columnOriginalValues.put("employeeId", _employeeId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("createdBy", 4L);

		columnBitmasks.put("modifiedBy", 8L);

		columnBitmasks.put("groupId", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("documentId", 128L);

		columnBitmasks.put("documentTypeId", 256L);

		columnBitmasks.put("documentNumber", 512L);

		columnBitmasks.put("documentName", 1024L);

		columnBitmasks.put("documentMediaId", 2048L);

		columnBitmasks.put("documentStatus", 4096L);

		columnBitmasks.put("employeeId", 8192L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private EmployeeDocument _escapedModel;

}