/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.model.impl;

import com.ax.hrms.model.EmployeeEducation;
import com.ax.hrms.model.EmployeeEducationModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the EmployeeEducation service. Represents a row in the &quot;ax_EmployeeEducation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>EmployeeEducationModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EmployeeEducationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmployeeEducationImpl
 * @generated
 */
@JSON(strict = true)
public class EmployeeEducationModelImpl
	extends BaseModelImpl<EmployeeEducation> implements EmployeeEducationModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a employee education model instance should use the <code>EmployeeEducation</code> interface instead.
	 */
	public static final String TABLE_NAME = "ax_EmployeeEducation";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"companyId", Types.BIGINT},
		{"createdBy", Types.BIGINT}, {"modifiedBy", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"educationId", Types.BIGINT},
		{"levelId", Types.BIGINT}, {"institution", Types.VARCHAR},
		{"degree", Types.VARCHAR}, {"startDate", Types.TIMESTAMP},
		{"passingYear", Types.VARCHAR}, {"endDate", Types.TIMESTAMP},
		{"employeeId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("educationId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("levelId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("institution", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("degree", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("startDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("passingYear", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("endDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("employeeId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ax_EmployeeEducation (uuid_ VARCHAR(75) null,companyId LONG,createdBy LONG,modifiedBy LONG,groupId LONG,createDate DATE null,modifiedDate DATE null,educationId LONG not null primary key,levelId LONG,institution VARCHAR(75) null,degree VARCHAR(75) null,startDate DATE null,passingYear VARCHAR(75) null,endDate DATE null,employeeId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table ax_EmployeeEducation";

	public static final String ORDER_BY_JPQL =
		" ORDER BY employeeEducation.educationId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ax_EmployeeEducation.educationId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EMPLOYEEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EDUCATIONID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public EmployeeEducationModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _educationId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEducationId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _educationId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return EmployeeEducation.class;
	}

	@Override
	public String getModelClassName() {
		return EmployeeEducation.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<EmployeeEducation, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<EmployeeEducation, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EmployeeEducation, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((EmployeeEducation)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<EmployeeEducation, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<EmployeeEducation, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(EmployeeEducation)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<EmployeeEducation, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<EmployeeEducation, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<EmployeeEducation, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<EmployeeEducation, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<EmployeeEducation, Object>>();

			attributeGetterFunctions.put("uuid", EmployeeEducation::getUuid);
			attributeGetterFunctions.put(
				"companyId", EmployeeEducation::getCompanyId);
			attributeGetterFunctions.put(
				"createdBy", EmployeeEducation::getCreatedBy);
			attributeGetterFunctions.put(
				"modifiedBy", EmployeeEducation::getModifiedBy);
			attributeGetterFunctions.put(
				"groupId", EmployeeEducation::getGroupId);
			attributeGetterFunctions.put(
				"createDate", EmployeeEducation::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", EmployeeEducation::getModifiedDate);
			attributeGetterFunctions.put(
				"educationId", EmployeeEducation::getEducationId);
			attributeGetterFunctions.put(
				"levelId", EmployeeEducation::getLevelId);
			attributeGetterFunctions.put(
				"institution", EmployeeEducation::getInstitution);
			attributeGetterFunctions.put(
				"degree", EmployeeEducation::getDegree);
			attributeGetterFunctions.put(
				"startDate", EmployeeEducation::getStartDate);
			attributeGetterFunctions.put(
				"passingYear", EmployeeEducation::getPassingYear);
			attributeGetterFunctions.put(
				"endDate", EmployeeEducation::getEndDate);
			attributeGetterFunctions.put(
				"employeeId", EmployeeEducation::getEmployeeId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<EmployeeEducation, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<EmployeeEducation, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<EmployeeEducation, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<EmployeeEducation, String>)
					EmployeeEducation::setUuid);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<EmployeeEducation, Long>)
					EmployeeEducation::setCompanyId);
			attributeSetterBiConsumers.put(
				"createdBy",
				(BiConsumer<EmployeeEducation, Long>)
					EmployeeEducation::setCreatedBy);
			attributeSetterBiConsumers.put(
				"modifiedBy",
				(BiConsumer<EmployeeEducation, Long>)
					EmployeeEducation::setModifiedBy);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<EmployeeEducation, Long>)
					EmployeeEducation::setGroupId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<EmployeeEducation, Date>)
					EmployeeEducation::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<EmployeeEducation, Date>)
					EmployeeEducation::setModifiedDate);
			attributeSetterBiConsumers.put(
				"educationId",
				(BiConsumer<EmployeeEducation, Long>)
					EmployeeEducation::setEducationId);
			attributeSetterBiConsumers.put(
				"levelId",
				(BiConsumer<EmployeeEducation, Long>)
					EmployeeEducation::setLevelId);
			attributeSetterBiConsumers.put(
				"institution",
				(BiConsumer<EmployeeEducation, String>)
					EmployeeEducation::setInstitution);
			attributeSetterBiConsumers.put(
				"degree",
				(BiConsumer<EmployeeEducation, String>)
					EmployeeEducation::setDegree);
			attributeSetterBiConsumers.put(
				"startDate",
				(BiConsumer<EmployeeEducation, Date>)
					EmployeeEducation::setStartDate);
			attributeSetterBiConsumers.put(
				"passingYear",
				(BiConsumer<EmployeeEducation, String>)
					EmployeeEducation::setPassingYear);
			attributeSetterBiConsumers.put(
				"endDate",
				(BiConsumer<EmployeeEducation, Date>)
					EmployeeEducation::setEndDate);
			attributeSetterBiConsumers.put(
				"employeeId",
				(BiConsumer<EmployeeEducation, Long>)
					EmployeeEducation::setEmployeeId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getEducationId() {
		return _educationId;
	}

	@Override
	public void setEducationId(long educationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_educationId = educationId;
	}

	@JSON
	@Override
	public long getLevelId() {
		return _levelId;
	}

	@Override
	public void setLevelId(long levelId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_levelId = levelId;
	}

	@JSON
	@Override
	public String getInstitution() {
		if (_institution == null) {
			return "";
		}
		else {
			return _institution;
		}
	}

	@Override
	public void setInstitution(String institution) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_institution = institution;
	}

	@JSON
	@Override
	public String getDegree() {
		if (_degree == null) {
			return "";
		}
		else {
			return _degree;
		}
	}

	@Override
	public void setDegree(String degree) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_degree = degree;
	}

	@JSON
	@Override
	public Date getStartDate() {
		return _startDate;
	}

	@Override
	public void setStartDate(Date startDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_startDate = startDate;
	}

	@JSON
	@Override
	public String getPassingYear() {
		if (_passingYear == null) {
			return "";
		}
		else {
			return _passingYear;
		}
	}

	@Override
	public void setPassingYear(String passingYear) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_passingYear = passingYear;
	}

	@JSON
	@Override
	public Date getEndDate() {
		return _endDate;
	}

	@Override
	public void setEndDate(Date endDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_endDate = endDate;
	}

	@JSON
	@Override
	public long getEmployeeId() {
		return _employeeId;
	}

	@Override
	public void setEmployeeId(long employeeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_employeeId = employeeId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalEmployeeId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("employeeId"));
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(EmployeeEducation.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), EmployeeEducation.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public EmployeeEducation toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, EmployeeEducation>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EmployeeEducationImpl employeeEducationImpl =
			new EmployeeEducationImpl();

		employeeEducationImpl.setUuid(getUuid());
		employeeEducationImpl.setCompanyId(getCompanyId());
		employeeEducationImpl.setCreatedBy(getCreatedBy());
		employeeEducationImpl.setModifiedBy(getModifiedBy());
		employeeEducationImpl.setGroupId(getGroupId());
		employeeEducationImpl.setCreateDate(getCreateDate());
		employeeEducationImpl.setModifiedDate(getModifiedDate());
		employeeEducationImpl.setEducationId(getEducationId());
		employeeEducationImpl.setLevelId(getLevelId());
		employeeEducationImpl.setInstitution(getInstitution());
		employeeEducationImpl.setDegree(getDegree());
		employeeEducationImpl.setStartDate(getStartDate());
		employeeEducationImpl.setPassingYear(getPassingYear());
		employeeEducationImpl.setEndDate(getEndDate());
		employeeEducationImpl.setEmployeeId(getEmployeeId());

		employeeEducationImpl.resetOriginalValues();

		return employeeEducationImpl;
	}

	@Override
	public EmployeeEducation cloneWithOriginalValues() {
		EmployeeEducationImpl employeeEducationImpl =
			new EmployeeEducationImpl();

		employeeEducationImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		employeeEducationImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		employeeEducationImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("createdBy"));
		employeeEducationImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modifiedBy"));
		employeeEducationImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		employeeEducationImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		employeeEducationImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		employeeEducationImpl.setEducationId(
			this.<Long>getColumnOriginalValue("educationId"));
		employeeEducationImpl.setLevelId(
			this.<Long>getColumnOriginalValue("levelId"));
		employeeEducationImpl.setInstitution(
			this.<String>getColumnOriginalValue("institution"));
		employeeEducationImpl.setDegree(
			this.<String>getColumnOriginalValue("degree"));
		employeeEducationImpl.setStartDate(
			this.<Date>getColumnOriginalValue("startDate"));
		employeeEducationImpl.setPassingYear(
			this.<String>getColumnOriginalValue("passingYear"));
		employeeEducationImpl.setEndDate(
			this.<Date>getColumnOriginalValue("endDate"));
		employeeEducationImpl.setEmployeeId(
			this.<Long>getColumnOriginalValue("employeeId"));

		return employeeEducationImpl;
	}

	@Override
	public int compareTo(EmployeeEducation employeeEducation) {
		long primaryKey = employeeEducation.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof EmployeeEducation)) {
			return false;
		}

		EmployeeEducation employeeEducation = (EmployeeEducation)object;

		long primaryKey = employeeEducation.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<EmployeeEducation> toCacheModel() {
		EmployeeEducationCacheModel employeeEducationCacheModel =
			new EmployeeEducationCacheModel();

		employeeEducationCacheModel.uuid = getUuid();

		String uuid = employeeEducationCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			employeeEducationCacheModel.uuid = null;
		}

		employeeEducationCacheModel.companyId = getCompanyId();

		employeeEducationCacheModel.createdBy = getCreatedBy();

		employeeEducationCacheModel.modifiedBy = getModifiedBy();

		employeeEducationCacheModel.groupId = getGroupId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			employeeEducationCacheModel.createDate = createDate.getTime();
		}
		else {
			employeeEducationCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			employeeEducationCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			employeeEducationCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		employeeEducationCacheModel.educationId = getEducationId();

		employeeEducationCacheModel.levelId = getLevelId();

		employeeEducationCacheModel.institution = getInstitution();

		String institution = employeeEducationCacheModel.institution;

		if ((institution != null) && (institution.length() == 0)) {
			employeeEducationCacheModel.institution = null;
		}

		employeeEducationCacheModel.degree = getDegree();

		String degree = employeeEducationCacheModel.degree;

		if ((degree != null) && (degree.length() == 0)) {
			employeeEducationCacheModel.degree = null;
		}

		Date startDate = getStartDate();

		if (startDate != null) {
			employeeEducationCacheModel.startDate = startDate.getTime();
		}
		else {
			employeeEducationCacheModel.startDate = Long.MIN_VALUE;
		}

		employeeEducationCacheModel.passingYear = getPassingYear();

		String passingYear = employeeEducationCacheModel.passingYear;

		if ((passingYear != null) && (passingYear.length() == 0)) {
			employeeEducationCacheModel.passingYear = null;
		}

		Date endDate = getEndDate();

		if (endDate != null) {
			employeeEducationCacheModel.endDate = endDate.getTime();
		}
		else {
			employeeEducationCacheModel.endDate = Long.MIN_VALUE;
		}

		employeeEducationCacheModel.employeeId = getEmployeeId();

		return employeeEducationCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<EmployeeEducation, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<EmployeeEducation, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EmployeeEducation, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(EmployeeEducation)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, EmployeeEducation>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					EmployeeEducation.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _companyId;
	private long _createdBy;
	private long _modifiedBy;
	private long _groupId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _educationId;
	private long _levelId;
	private String _institution;
	private String _degree;
	private Date _startDate;
	private String _passingYear;
	private Date _endDate;
	private long _employeeId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<EmployeeEducation, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((EmployeeEducation)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createdBy", _createdBy);
		_columnOriginalValues.put("modifiedBy", _modifiedBy);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("educationId", _educationId);
		_columnOriginalValues.put("levelId", _levelId);
		_columnOriginalValues.put("institution", _institution);
		_columnOriginalValues.put("degree", _degree);
		_columnOriginalValues.put("startDate", _startDate);
		_columnOriginalValues.put("passingYear", _passingYear);
		_columnOriginalValues.put("endDate", _endDate);
		_columnOriginalValues.put("employeeId", _employeeId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("createdBy", 4L);

		columnBitmasks.put("modifiedBy", 8L);

		columnBitmasks.put("groupId", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("educationId", 128L);

		columnBitmasks.put("levelId", 256L);

		columnBitmasks.put("institution", 512L);

		columnBitmasks.put("degree", 1024L);

		columnBitmasks.put("startDate", 2048L);

		columnBitmasks.put("passingYear", 4096L);

		columnBitmasks.put("endDate", 8192L);

		columnBitmasks.put("employeeId", 16384L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private EmployeeEducation _escapedModel;

}