/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.model.impl;

import com.ax.hrms.model.EmployeeBankAccount;
import com.ax.hrms.model.EmployeeBankAccountModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the EmployeeBankAccount service. Represents a row in the &quot;ax_EmployeeBankAccount&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>EmployeeBankAccountModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EmployeeBankAccountImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmployeeBankAccountImpl
 * @generated
 */
@JSON(strict = true)
public class EmployeeBankAccountModelImpl
	extends BaseModelImpl<EmployeeBankAccount>
	implements EmployeeBankAccountModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a employee bank account model instance should use the <code>EmployeeBankAccount</code> interface instead.
	 */
	public static final String TABLE_NAME = "ax_EmployeeBankAccount";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"companyId", Types.BIGINT},
		{"createdBy", Types.BIGINT}, {"modifiedBy", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"bankAccountId", Types.BIGINT},
		{"accountNumber", Types.VARCHAR}, {"accountType", Types.VARCHAR},
		{"beneficiaryName", Types.VARCHAR}, {"bankName", Types.VARCHAR},
		{"status", Types.BOOLEAN}, {"ifscCode", Types.VARCHAR},
		{"bankBranch", Types.VARCHAR}, {"employeeId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("bankAccountId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("accountNumber", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("accountType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("beneficiaryName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("bankName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("status", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("ifscCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("bankBranch", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("employeeId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ax_EmployeeBankAccount (uuid_ VARCHAR(75) null,companyId LONG,createdBy LONG,modifiedBy LONG,groupId LONG,createDate DATE null,modifiedDate DATE null,bankAccountId LONG not null primary key,accountNumber VARCHAR(75) null,accountType VARCHAR(75) null,beneficiaryName VARCHAR(75) null,bankName VARCHAR(75) null,status BOOLEAN,ifscCode VARCHAR(75) null,bankBranch VARCHAR(75) null,employeeId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table ax_EmployeeBankAccount";

	public static final String ORDER_BY_JPQL =
		" ORDER BY employeeBankAccount.bankAccountId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ax_EmployeeBankAccount.bankAccountId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long BANKACCOUNTID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public EmployeeBankAccountModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _bankAccountId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setBankAccountId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _bankAccountId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return EmployeeBankAccount.class;
	}

	@Override
	public String getModelClassName() {
		return EmployeeBankAccount.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<EmployeeBankAccount, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<EmployeeBankAccount, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EmployeeBankAccount, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((EmployeeBankAccount)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<EmployeeBankAccount, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<EmployeeBankAccount, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(EmployeeBankAccount)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<EmployeeBankAccount, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<EmployeeBankAccount, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<EmployeeBankAccount, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<EmployeeBankAccount, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<EmployeeBankAccount, Object>>();

			attributeGetterFunctions.put("uuid", EmployeeBankAccount::getUuid);
			attributeGetterFunctions.put(
				"companyId", EmployeeBankAccount::getCompanyId);
			attributeGetterFunctions.put(
				"createdBy", EmployeeBankAccount::getCreatedBy);
			attributeGetterFunctions.put(
				"modifiedBy", EmployeeBankAccount::getModifiedBy);
			attributeGetterFunctions.put(
				"groupId", EmployeeBankAccount::getGroupId);
			attributeGetterFunctions.put(
				"createDate", EmployeeBankAccount::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", EmployeeBankAccount::getModifiedDate);
			attributeGetterFunctions.put(
				"bankAccountId", EmployeeBankAccount::getBankAccountId);
			attributeGetterFunctions.put(
				"accountNumber", EmployeeBankAccount::getAccountNumber);
			attributeGetterFunctions.put(
				"accountType", EmployeeBankAccount::getAccountType);
			attributeGetterFunctions.put(
				"beneficiaryName", EmployeeBankAccount::getBeneficiaryName);
			attributeGetterFunctions.put(
				"bankName", EmployeeBankAccount::getBankName);
			attributeGetterFunctions.put(
				"status", EmployeeBankAccount::getStatus);
			attributeGetterFunctions.put(
				"ifscCode", EmployeeBankAccount::getIfscCode);
			attributeGetterFunctions.put(
				"bankBranch", EmployeeBankAccount::getBankBranch);
			attributeGetterFunctions.put(
				"employeeId", EmployeeBankAccount::getEmployeeId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<EmployeeBankAccount, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<EmployeeBankAccount, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<EmployeeBankAccount, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<EmployeeBankAccount, String>)
					EmployeeBankAccount::setUuid);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<EmployeeBankAccount, Long>)
					EmployeeBankAccount::setCompanyId);
			attributeSetterBiConsumers.put(
				"createdBy",
				(BiConsumer<EmployeeBankAccount, Long>)
					EmployeeBankAccount::setCreatedBy);
			attributeSetterBiConsumers.put(
				"modifiedBy",
				(BiConsumer<EmployeeBankAccount, Long>)
					EmployeeBankAccount::setModifiedBy);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<EmployeeBankAccount, Long>)
					EmployeeBankAccount::setGroupId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<EmployeeBankAccount, Date>)
					EmployeeBankAccount::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<EmployeeBankAccount, Date>)
					EmployeeBankAccount::setModifiedDate);
			attributeSetterBiConsumers.put(
				"bankAccountId",
				(BiConsumer<EmployeeBankAccount, Long>)
					EmployeeBankAccount::setBankAccountId);
			attributeSetterBiConsumers.put(
				"accountNumber",
				(BiConsumer<EmployeeBankAccount, String>)
					EmployeeBankAccount::setAccountNumber);
			attributeSetterBiConsumers.put(
				"accountType",
				(BiConsumer<EmployeeBankAccount, String>)
					EmployeeBankAccount::setAccountType);
			attributeSetterBiConsumers.put(
				"beneficiaryName",
				(BiConsumer<EmployeeBankAccount, String>)
					EmployeeBankAccount::setBeneficiaryName);
			attributeSetterBiConsumers.put(
				"bankName",
				(BiConsumer<EmployeeBankAccount, String>)
					EmployeeBankAccount::setBankName);
			attributeSetterBiConsumers.put(
				"status",
				(BiConsumer<EmployeeBankAccount, Boolean>)
					EmployeeBankAccount::setStatus);
			attributeSetterBiConsumers.put(
				"ifscCode",
				(BiConsumer<EmployeeBankAccount, String>)
					EmployeeBankAccount::setIfscCode);
			attributeSetterBiConsumers.put(
				"bankBranch",
				(BiConsumer<EmployeeBankAccount, String>)
					EmployeeBankAccount::setBankBranch);
			attributeSetterBiConsumers.put(
				"employeeId",
				(BiConsumer<EmployeeBankAccount, Long>)
					EmployeeBankAccount::setEmployeeId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getBankAccountId() {
		return _bankAccountId;
	}

	@Override
	public void setBankAccountId(long bankAccountId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_bankAccountId = bankAccountId;
	}

	@JSON
	@Override
	public String getAccountNumber() {
		if (_accountNumber == null) {
			return "";
		}
		else {
			return _accountNumber;
		}
	}

	@Override
	public void setAccountNumber(String accountNumber) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_accountNumber = accountNumber;
	}

	@JSON
	@Override
	public String getAccountType() {
		if (_accountType == null) {
			return "";
		}
		else {
			return _accountType;
		}
	}

	@Override
	public void setAccountType(String accountType) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_accountType = accountType;
	}

	@JSON
	@Override
	public String getBeneficiaryName() {
		if (_beneficiaryName == null) {
			return "";
		}
		else {
			return _beneficiaryName;
		}
	}

	@Override
	public void setBeneficiaryName(String beneficiaryName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_beneficiaryName = beneficiaryName;
	}

	@JSON
	@Override
	public String getBankName() {
		if (_bankName == null) {
			return "";
		}
		else {
			return _bankName;
		}
	}

	@Override
	public void setBankName(String bankName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_bankName = bankName;
	}

	@JSON
	@Override
	public boolean getStatus() {
		return _status;
	}

	@JSON
	@Override
	public boolean isStatus() {
		return _status;
	}

	@Override
	public void setStatus(boolean status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	@JSON
	@Override
	public String getIfscCode() {
		if (_ifscCode == null) {
			return "";
		}
		else {
			return _ifscCode;
		}
	}

	@Override
	public void setIfscCode(String ifscCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ifscCode = ifscCode;
	}

	@JSON
	@Override
	public String getBankBranch() {
		if (_bankBranch == null) {
			return "";
		}
		else {
			return _bankBranch;
		}
	}

	@Override
	public void setBankBranch(String bankBranch) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_bankBranch = bankBranch;
	}

	@JSON
	@Override
	public long getEmployeeId() {
		return _employeeId;
	}

	@Override
	public void setEmployeeId(long employeeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_employeeId = employeeId;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(EmployeeBankAccount.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), EmployeeBankAccount.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public EmployeeBankAccount toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, EmployeeBankAccount>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EmployeeBankAccountImpl employeeBankAccountImpl =
			new EmployeeBankAccountImpl();

		employeeBankAccountImpl.setUuid(getUuid());
		employeeBankAccountImpl.setCompanyId(getCompanyId());
		employeeBankAccountImpl.setCreatedBy(getCreatedBy());
		employeeBankAccountImpl.setModifiedBy(getModifiedBy());
		employeeBankAccountImpl.setGroupId(getGroupId());
		employeeBankAccountImpl.setCreateDate(getCreateDate());
		employeeBankAccountImpl.setModifiedDate(getModifiedDate());
		employeeBankAccountImpl.setBankAccountId(getBankAccountId());
		employeeBankAccountImpl.setAccountNumber(getAccountNumber());
		employeeBankAccountImpl.setAccountType(getAccountType());
		employeeBankAccountImpl.setBeneficiaryName(getBeneficiaryName());
		employeeBankAccountImpl.setBankName(getBankName());
		employeeBankAccountImpl.setStatus(isStatus());
		employeeBankAccountImpl.setIfscCode(getIfscCode());
		employeeBankAccountImpl.setBankBranch(getBankBranch());
		employeeBankAccountImpl.setEmployeeId(getEmployeeId());

		employeeBankAccountImpl.resetOriginalValues();

		return employeeBankAccountImpl;
	}

	@Override
	public EmployeeBankAccount cloneWithOriginalValues() {
		EmployeeBankAccountImpl employeeBankAccountImpl =
			new EmployeeBankAccountImpl();

		employeeBankAccountImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		employeeBankAccountImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		employeeBankAccountImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("createdBy"));
		employeeBankAccountImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modifiedBy"));
		employeeBankAccountImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		employeeBankAccountImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		employeeBankAccountImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		employeeBankAccountImpl.setBankAccountId(
			this.<Long>getColumnOriginalValue("bankAccountId"));
		employeeBankAccountImpl.setAccountNumber(
			this.<String>getColumnOriginalValue("accountNumber"));
		employeeBankAccountImpl.setAccountType(
			this.<String>getColumnOriginalValue("accountType"));
		employeeBankAccountImpl.setBeneficiaryName(
			this.<String>getColumnOriginalValue("beneficiaryName"));
		employeeBankAccountImpl.setBankName(
			this.<String>getColumnOriginalValue("bankName"));
		employeeBankAccountImpl.setStatus(
			this.<Boolean>getColumnOriginalValue("status"));
		employeeBankAccountImpl.setIfscCode(
			this.<String>getColumnOriginalValue("ifscCode"));
		employeeBankAccountImpl.setBankBranch(
			this.<String>getColumnOriginalValue("bankBranch"));
		employeeBankAccountImpl.setEmployeeId(
			this.<Long>getColumnOriginalValue("employeeId"));

		return employeeBankAccountImpl;
	}

	@Override
	public int compareTo(EmployeeBankAccount employeeBankAccount) {
		long primaryKey = employeeBankAccount.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof EmployeeBankAccount)) {
			return false;
		}

		EmployeeBankAccount employeeBankAccount = (EmployeeBankAccount)object;

		long primaryKey = employeeBankAccount.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<EmployeeBankAccount> toCacheModel() {
		EmployeeBankAccountCacheModel employeeBankAccountCacheModel =
			new EmployeeBankAccountCacheModel();

		employeeBankAccountCacheModel.uuid = getUuid();

		String uuid = employeeBankAccountCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			employeeBankAccountCacheModel.uuid = null;
		}

		employeeBankAccountCacheModel.companyId = getCompanyId();

		employeeBankAccountCacheModel.createdBy = getCreatedBy();

		employeeBankAccountCacheModel.modifiedBy = getModifiedBy();

		employeeBankAccountCacheModel.groupId = getGroupId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			employeeBankAccountCacheModel.createDate = createDate.getTime();
		}
		else {
			employeeBankAccountCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			employeeBankAccountCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			employeeBankAccountCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		employeeBankAccountCacheModel.bankAccountId = getBankAccountId();

		employeeBankAccountCacheModel.accountNumber = getAccountNumber();

		String accountNumber = employeeBankAccountCacheModel.accountNumber;

		if ((accountNumber != null) && (accountNumber.length() == 0)) {
			employeeBankAccountCacheModel.accountNumber = null;
		}

		employeeBankAccountCacheModel.accountType = getAccountType();

		String accountType = employeeBankAccountCacheModel.accountType;

		if ((accountType != null) && (accountType.length() == 0)) {
			employeeBankAccountCacheModel.accountType = null;
		}

		employeeBankAccountCacheModel.beneficiaryName = getBeneficiaryName();

		String beneficiaryName = employeeBankAccountCacheModel.beneficiaryName;

		if ((beneficiaryName != null) && (beneficiaryName.length() == 0)) {
			employeeBankAccountCacheModel.beneficiaryName = null;
		}

		employeeBankAccountCacheModel.bankName = getBankName();

		String bankName = employeeBankAccountCacheModel.bankName;

		if ((bankName != null) && (bankName.length() == 0)) {
			employeeBankAccountCacheModel.bankName = null;
		}

		employeeBankAccountCacheModel.status = isStatus();

		employeeBankAccountCacheModel.ifscCode = getIfscCode();

		String ifscCode = employeeBankAccountCacheModel.ifscCode;

		if ((ifscCode != null) && (ifscCode.length() == 0)) {
			employeeBankAccountCacheModel.ifscCode = null;
		}

		employeeBankAccountCacheModel.bankBranch = getBankBranch();

		String bankBranch = employeeBankAccountCacheModel.bankBranch;

		if ((bankBranch != null) && (bankBranch.length() == 0)) {
			employeeBankAccountCacheModel.bankBranch = null;
		}

		employeeBankAccountCacheModel.employeeId = getEmployeeId();

		return employeeBankAccountCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<EmployeeBankAccount, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<EmployeeBankAccount, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EmployeeBankAccount, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(EmployeeBankAccount)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, EmployeeBankAccount>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					EmployeeBankAccount.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _companyId;
	private long _createdBy;
	private long _modifiedBy;
	private long _groupId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _bankAccountId;
	private String _accountNumber;
	private String _accountType;
	private String _beneficiaryName;
	private String _bankName;
	private boolean _status;
	private String _ifscCode;
	private String _bankBranch;
	private long _employeeId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<EmployeeBankAccount, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((EmployeeBankAccount)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createdBy", _createdBy);
		_columnOriginalValues.put("modifiedBy", _modifiedBy);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("bankAccountId", _bankAccountId);
		_columnOriginalValues.put("accountNumber", _accountNumber);
		_columnOriginalValues.put("accountType", _accountType);
		_columnOriginalValues.put("beneficiaryName", _beneficiaryName);
		_columnOriginalValues.put("bankName", _bankName);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("ifscCode", _ifscCode);
		_columnOriginalValues.put("bankBranch", _bankBranch);
		_columnOriginalValues.put("employeeId", _employeeId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("createdBy", 4L);

		columnBitmasks.put("modifiedBy", 8L);

		columnBitmasks.put("groupId", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("bankAccountId", 128L);

		columnBitmasks.put("accountNumber", 256L);

		columnBitmasks.put("accountType", 512L);

		columnBitmasks.put("beneficiaryName", 1024L);

		columnBitmasks.put("bankName", 2048L);

		columnBitmasks.put("status", 4096L);

		columnBitmasks.put("ifscCode", 8192L);

		columnBitmasks.put("bankBranch", 16384L);

		columnBitmasks.put("employeeId", 32768L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private EmployeeBankAccount _escapedModel;

}