/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.model.impl;

import com.ax.hrms.model.EmployeeUanEsic;
import com.ax.hrms.model.EmployeeUanEsicModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the EmployeeUanEsic service. Represents a row in the &quot;ax_EmployeeUanEsic&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>EmployeeUanEsicModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EmployeeUanEsicImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmployeeUanEsicImpl
 * @generated
 */
@JSON(strict = true)
public class EmployeeUanEsicModelImpl
	extends BaseModelImpl<EmployeeUanEsic> implements EmployeeUanEsicModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a employee uan esic model instance should use the <code>EmployeeUanEsic</code> interface instead.
	 */
	public static final String TABLE_NAME = "ax_EmployeeUanEsic";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"companyId", Types.BIGINT},
		{"createdBy", Types.BIGINT}, {"modifiedBy", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"uanEsicId", Types.BIGINT},
		{"uan", Types.VARCHAR}, {"esicNo", Types.VARCHAR},
		{"status", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("uanEsicId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("uan", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("esicNo", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("status", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ax_EmployeeUanEsic (uuid_ VARCHAR(75) null,companyId LONG,createdBy LONG,modifiedBy LONG,groupId LONG,createDate DATE null,modifiedDate DATE null,uanEsicId LONG not null primary key,uan VARCHAR(75) null,esicNo VARCHAR(75) null,status BOOLEAN)";

	public static final String TABLE_SQL_DROP = "drop table ax_EmployeeUanEsic";

	public static final String ORDER_BY_JPQL =
		" ORDER BY employeeUanEsic.uanEsicId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ax_EmployeeUanEsic.uanEsicId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UANESICID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public EmployeeUanEsicModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _uanEsicId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setUanEsicId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _uanEsicId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return EmployeeUanEsic.class;
	}

	@Override
	public String getModelClassName() {
		return EmployeeUanEsic.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<EmployeeUanEsic, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<EmployeeUanEsic, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EmployeeUanEsic, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((EmployeeUanEsic)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<EmployeeUanEsic, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<EmployeeUanEsic, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(EmployeeUanEsic)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<EmployeeUanEsic, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<EmployeeUanEsic, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<EmployeeUanEsic, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<EmployeeUanEsic, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<EmployeeUanEsic, Object>>();

			attributeGetterFunctions.put("uuid", EmployeeUanEsic::getUuid);
			attributeGetterFunctions.put(
				"companyId", EmployeeUanEsic::getCompanyId);
			attributeGetterFunctions.put(
				"createdBy", EmployeeUanEsic::getCreatedBy);
			attributeGetterFunctions.put(
				"modifiedBy", EmployeeUanEsic::getModifiedBy);
			attributeGetterFunctions.put(
				"groupId", EmployeeUanEsic::getGroupId);
			attributeGetterFunctions.put(
				"createDate", EmployeeUanEsic::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", EmployeeUanEsic::getModifiedDate);
			attributeGetterFunctions.put(
				"uanEsicId", EmployeeUanEsic::getUanEsicId);
			attributeGetterFunctions.put("uan", EmployeeUanEsic::getUan);
			attributeGetterFunctions.put("esicNo", EmployeeUanEsic::getEsicNo);
			attributeGetterFunctions.put("status", EmployeeUanEsic::getStatus);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<EmployeeUanEsic, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<EmployeeUanEsic, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<EmployeeUanEsic, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<EmployeeUanEsic, String>)EmployeeUanEsic::setUuid);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<EmployeeUanEsic, Long>)
					EmployeeUanEsic::setCompanyId);
			attributeSetterBiConsumers.put(
				"createdBy",
				(BiConsumer<EmployeeUanEsic, Long>)
					EmployeeUanEsic::setCreatedBy);
			attributeSetterBiConsumers.put(
				"modifiedBy",
				(BiConsumer<EmployeeUanEsic, Long>)
					EmployeeUanEsic::setModifiedBy);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<EmployeeUanEsic, Long>)EmployeeUanEsic::setGroupId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<EmployeeUanEsic, Date>)
					EmployeeUanEsic::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<EmployeeUanEsic, Date>)
					EmployeeUanEsic::setModifiedDate);
			attributeSetterBiConsumers.put(
				"uanEsicId",
				(BiConsumer<EmployeeUanEsic, Long>)
					EmployeeUanEsic::setUanEsicId);
			attributeSetterBiConsumers.put(
				"uan",
				(BiConsumer<EmployeeUanEsic, String>)EmployeeUanEsic::setUan);
			attributeSetterBiConsumers.put(
				"esicNo",
				(BiConsumer<EmployeeUanEsic, String>)
					EmployeeUanEsic::setEsicNo);
			attributeSetterBiConsumers.put(
				"status",
				(BiConsumer<EmployeeUanEsic, Boolean>)
					EmployeeUanEsic::setStatus);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getUanEsicId() {
		return _uanEsicId;
	}

	@Override
	public void setUanEsicId(long uanEsicId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uanEsicId = uanEsicId;
	}

	@JSON
	@Override
	public String getUan() {
		if (_uan == null) {
			return "";
		}
		else {
			return _uan;
		}
	}

	@Override
	public void setUan(String uan) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uan = uan;
	}

	@JSON
	@Override
	public String getEsicNo() {
		if (_esicNo == null) {
			return "";
		}
		else {
			return _esicNo;
		}
	}

	@Override
	public void setEsicNo(String esicNo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_esicNo = esicNo;
	}

	@JSON
	@Override
	public boolean getStatus() {
		return _status;
	}

	@JSON
	@Override
	public boolean isStatus() {
		return _status;
	}

	@Override
	public void setStatus(boolean status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(EmployeeUanEsic.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), EmployeeUanEsic.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public EmployeeUanEsic toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, EmployeeUanEsic>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EmployeeUanEsicImpl employeeUanEsicImpl = new EmployeeUanEsicImpl();

		employeeUanEsicImpl.setUuid(getUuid());
		employeeUanEsicImpl.setCompanyId(getCompanyId());
		employeeUanEsicImpl.setCreatedBy(getCreatedBy());
		employeeUanEsicImpl.setModifiedBy(getModifiedBy());
		employeeUanEsicImpl.setGroupId(getGroupId());
		employeeUanEsicImpl.setCreateDate(getCreateDate());
		employeeUanEsicImpl.setModifiedDate(getModifiedDate());
		employeeUanEsicImpl.setUanEsicId(getUanEsicId());
		employeeUanEsicImpl.setUan(getUan());
		employeeUanEsicImpl.setEsicNo(getEsicNo());
		employeeUanEsicImpl.setStatus(isStatus());

		employeeUanEsicImpl.resetOriginalValues();

		return employeeUanEsicImpl;
	}

	@Override
	public EmployeeUanEsic cloneWithOriginalValues() {
		EmployeeUanEsicImpl employeeUanEsicImpl = new EmployeeUanEsicImpl();

		employeeUanEsicImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		employeeUanEsicImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		employeeUanEsicImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("createdBy"));
		employeeUanEsicImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modifiedBy"));
		employeeUanEsicImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		employeeUanEsicImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		employeeUanEsicImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		employeeUanEsicImpl.setUanEsicId(
			this.<Long>getColumnOriginalValue("uanEsicId"));
		employeeUanEsicImpl.setUan(this.<String>getColumnOriginalValue("uan"));
		employeeUanEsicImpl.setEsicNo(
			this.<String>getColumnOriginalValue("esicNo"));
		employeeUanEsicImpl.setStatus(
			this.<Boolean>getColumnOriginalValue("status"));

		return employeeUanEsicImpl;
	}

	@Override
	public int compareTo(EmployeeUanEsic employeeUanEsic) {
		long primaryKey = employeeUanEsic.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof EmployeeUanEsic)) {
			return false;
		}

		EmployeeUanEsic employeeUanEsic = (EmployeeUanEsic)object;

		long primaryKey = employeeUanEsic.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<EmployeeUanEsic> toCacheModel() {
		EmployeeUanEsicCacheModel employeeUanEsicCacheModel =
			new EmployeeUanEsicCacheModel();

		employeeUanEsicCacheModel.uuid = getUuid();

		String uuid = employeeUanEsicCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			employeeUanEsicCacheModel.uuid = null;
		}

		employeeUanEsicCacheModel.companyId = getCompanyId();

		employeeUanEsicCacheModel.createdBy = getCreatedBy();

		employeeUanEsicCacheModel.modifiedBy = getModifiedBy();

		employeeUanEsicCacheModel.groupId = getGroupId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			employeeUanEsicCacheModel.createDate = createDate.getTime();
		}
		else {
			employeeUanEsicCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			employeeUanEsicCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			employeeUanEsicCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		employeeUanEsicCacheModel.uanEsicId = getUanEsicId();

		employeeUanEsicCacheModel.uan = getUan();

		String uan = employeeUanEsicCacheModel.uan;

		if ((uan != null) && (uan.length() == 0)) {
			employeeUanEsicCacheModel.uan = null;
		}

		employeeUanEsicCacheModel.esicNo = getEsicNo();

		String esicNo = employeeUanEsicCacheModel.esicNo;

		if ((esicNo != null) && (esicNo.length() == 0)) {
			employeeUanEsicCacheModel.esicNo = null;
		}

		employeeUanEsicCacheModel.status = isStatus();

		return employeeUanEsicCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<EmployeeUanEsic, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<EmployeeUanEsic, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EmployeeUanEsic, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((EmployeeUanEsic)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, EmployeeUanEsic>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					EmployeeUanEsic.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _companyId;
	private long _createdBy;
	private long _modifiedBy;
	private long _groupId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _uanEsicId;
	private String _uan;
	private String _esicNo;
	private boolean _status;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<EmployeeUanEsic, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((EmployeeUanEsic)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createdBy", _createdBy);
		_columnOriginalValues.put("modifiedBy", _modifiedBy);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("uanEsicId", _uanEsicId);
		_columnOriginalValues.put("uan", _uan);
		_columnOriginalValues.put("esicNo", _esicNo);
		_columnOriginalValues.put("status", _status);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("createdBy", 4L);

		columnBitmasks.put("modifiedBy", 8L);

		columnBitmasks.put("groupId", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("uanEsicId", 128L);

		columnBitmasks.put("uan", 256L);

		columnBitmasks.put("esicNo", 512L);

		columnBitmasks.put("status", 1024L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private EmployeeUanEsic _escapedModel;

}