/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.model.impl;

import com.ax.hrms.model.EmployeeAddress;
import com.ax.hrms.service.EmployeeAddressLocalServiceUtil;

/**
 * The extended model base implementation for the EmployeeAddress service. Represents a row in the &quot;ax_EmployeeAddress&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EmployeeAddressImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmployeeAddressImpl
 * @see EmployeeAddress
 * @generated
 */
public abstract class EmployeeAddressBaseImpl
	extends EmployeeAddressModelImpl implements EmployeeAddress {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a employee address model instance should use the <code>EmployeeAddress</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			EmployeeAddressLocalServiceUtil.addEmployeeAddress(this);
		}
		else {
			EmployeeAddressLocalServiceUtil.updateEmployeeAddress(this);
		}
	}

}