/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.model.impl;

import com.ax.hrms.model.EmployeeDetails;
import com.ax.hrms.model.EmployeeDetailsModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the EmployeeDetails service. Represents a row in the &quot;ax_EmployeeDetails&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>EmployeeDetailsModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EmployeeDetailsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmployeeDetailsImpl
 * @generated
 */
@JSON(strict = true)
public class EmployeeDetailsModelImpl
	extends BaseModelImpl<EmployeeDetails> implements EmployeeDetailsModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a employee details model instance should use the <code>EmployeeDetails</code> interface instead.
	 */
	public static final String TABLE_NAME = "ax_EmployeeDetails";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"companyId", Types.BIGINT},
		{"createdBy", Types.BIGINT}, {"modifiedBy", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"employeeId", Types.BIGINT},
		{"employeeCode", Types.VARCHAR}, {"lrUserId", Types.BIGINT},
		{"firstName", Types.VARCHAR}, {"lastName", Types.VARCHAR},
		{"officialEmail", Types.VARCHAR}, {"personalEmail", Types.VARCHAR},
		{"joiningDate", Types.TIMESTAMP}, {"leavingDate", Types.TIMESTAMP},
		{"mobileNo", Types.VARCHAR}, {"gender", Types.VARCHAR},
		{"fatherName", Types.VARCHAR}, {"dateOfBirth", Types.TIMESTAMP},
		{"maritalStatus", Types.BOOLEAN}, {"marriageDate", Types.TIMESTAMP},
		{"spouseName", Types.VARCHAR}, {"employeeAddressId", Types.BIGINT},
		{"skypeId", Types.VARCHAR}, {"nominneeId", Types.BIGINT},
		{"bankAccountId", Types.BIGINT}, {"uanEsicId", Types.BIGINT},
		{"probationStatusId", Types.BIGINT},
		{"isEmployeeOnboarded", Types.BOOLEAN},
		{"isExperienced", Types.BOOLEAN}, {"isProbationEnabled", Types.BOOLEAN},
		{"profilePicId", Types.BIGINT}, {"insuranceLink", Types.VARCHAR},
		{"isTerminated", Types.BOOLEAN}, {"appraisalDate", Types.TIMESTAMP},
		{"employeeType", Types.VARCHAR}, {"stipend", Types.DOUBLE}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("employeeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("employeeCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("lrUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("firstName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("lastName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("officialEmail", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("personalEmail", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("joiningDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("leavingDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("mobileNo", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("gender", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("fatherName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("dateOfBirth", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("maritalStatus", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("marriageDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("spouseName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("employeeAddressId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("skypeId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("nominneeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("bankAccountId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("uanEsicId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("probationStatusId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("isEmployeeOnboarded", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("isExperienced", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("isProbationEnabled", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("profilePicId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("insuranceLink", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("isTerminated", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("appraisalDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("employeeType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("stipend", Types.DOUBLE);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ax_EmployeeDetails (uuid_ VARCHAR(75) null,companyId LONG,createdBy LONG,modifiedBy LONG,groupId LONG,createDate DATE null,modifiedDate DATE null,employeeId LONG not null primary key,employeeCode VARCHAR(75) null,lrUserId LONG,firstName VARCHAR(75) null,lastName VARCHAR(75) null,officialEmail VARCHAR(75) null,personalEmail VARCHAR(75) null,joiningDate DATE null,leavingDate DATE null,mobileNo VARCHAR(75) null,gender VARCHAR(75) null,fatherName VARCHAR(75) null,dateOfBirth DATE null,maritalStatus BOOLEAN,marriageDate DATE null,spouseName VARCHAR(75) null,employeeAddressId LONG,skypeId VARCHAR(75) null,nominneeId LONG,bankAccountId LONG,uanEsicId LONG,probationStatusId LONG,isEmployeeOnboarded BOOLEAN,isExperienced BOOLEAN,isProbationEnabled BOOLEAN,profilePicId LONG,insuranceLink VARCHAR(1000) null,isTerminated BOOLEAN,appraisalDate DATE null,employeeType VARCHAR(75) null,stipend DOUBLE)";

	public static final String TABLE_SQL_DROP = "drop table ax_EmployeeDetails";

	public static final String ORDER_BY_JPQL =
		" ORDER BY employeeDetails.employeeId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ax_EmployeeDetails.employeeId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EMPLOYEEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FIRSTNAME_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ISTERMINATED_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LASTNAME_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LEAVINGDATE_COLUMN_BITMASK = 64L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LRUSERID_COLUMN_BITMASK = 128L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 256L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public EmployeeDetailsModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _employeeId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEmployeeId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _employeeId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return EmployeeDetails.class;
	}

	@Override
	public String getModelClassName() {
		return EmployeeDetails.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<EmployeeDetails, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<EmployeeDetails, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EmployeeDetails, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((EmployeeDetails)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<EmployeeDetails, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<EmployeeDetails, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(EmployeeDetails)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<EmployeeDetails, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<EmployeeDetails, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<EmployeeDetails, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<EmployeeDetails, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<EmployeeDetails, Object>>();

			attributeGetterFunctions.put("uuid", EmployeeDetails::getUuid);
			attributeGetterFunctions.put(
				"companyId", EmployeeDetails::getCompanyId);
			attributeGetterFunctions.put(
				"createdBy", EmployeeDetails::getCreatedBy);
			attributeGetterFunctions.put(
				"modifiedBy", EmployeeDetails::getModifiedBy);
			attributeGetterFunctions.put(
				"groupId", EmployeeDetails::getGroupId);
			attributeGetterFunctions.put(
				"createDate", EmployeeDetails::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", EmployeeDetails::getModifiedDate);
			attributeGetterFunctions.put(
				"employeeId", EmployeeDetails::getEmployeeId);
			attributeGetterFunctions.put(
				"employeeCode", EmployeeDetails::getEmployeeCode);
			attributeGetterFunctions.put(
				"lrUserId", EmployeeDetails::getLrUserId);
			attributeGetterFunctions.put(
				"firstName", EmployeeDetails::getFirstName);
			attributeGetterFunctions.put(
				"lastName", EmployeeDetails::getLastName);
			attributeGetterFunctions.put(
				"officialEmail", EmployeeDetails::getOfficialEmail);
			attributeGetterFunctions.put(
				"personalEmail", EmployeeDetails::getPersonalEmail);
			attributeGetterFunctions.put(
				"joiningDate", EmployeeDetails::getJoiningDate);
			attributeGetterFunctions.put(
				"leavingDate", EmployeeDetails::getLeavingDate);
			attributeGetterFunctions.put(
				"mobileNo", EmployeeDetails::getMobileNo);
			attributeGetterFunctions.put("gender", EmployeeDetails::getGender);
			attributeGetterFunctions.put(
				"fatherName", EmployeeDetails::getFatherName);
			attributeGetterFunctions.put(
				"dateOfBirth", EmployeeDetails::getDateOfBirth);
			attributeGetterFunctions.put(
				"maritalStatus", EmployeeDetails::getMaritalStatus);
			attributeGetterFunctions.put(
				"marriageDate", EmployeeDetails::getMarriageDate);
			attributeGetterFunctions.put(
				"spouseName", EmployeeDetails::getSpouseName);
			attributeGetterFunctions.put(
				"employeeAddressId", EmployeeDetails::getEmployeeAddressId);
			attributeGetterFunctions.put(
				"skypeId", EmployeeDetails::getSkypeId);
			attributeGetterFunctions.put(
				"nominneeId", EmployeeDetails::getNominneeId);
			attributeGetterFunctions.put(
				"bankAccountId", EmployeeDetails::getBankAccountId);
			attributeGetterFunctions.put(
				"uanEsicId", EmployeeDetails::getUanEsicId);
			attributeGetterFunctions.put(
				"probationStatusId", EmployeeDetails::getProbationStatusId);
			attributeGetterFunctions.put(
				"isEmployeeOnboarded", EmployeeDetails::getIsEmployeeOnboarded);
			attributeGetterFunctions.put(
				"isExperienced", EmployeeDetails::getIsExperienced);
			attributeGetterFunctions.put(
				"isProbationEnabled", EmployeeDetails::getIsProbationEnabled);
			attributeGetterFunctions.put(
				"profilePicId", EmployeeDetails::getProfilePicId);
			attributeGetterFunctions.put(
				"insuranceLink", EmployeeDetails::getInsuranceLink);
			attributeGetterFunctions.put(
				"isTerminated", EmployeeDetails::getIsTerminated);
			attributeGetterFunctions.put(
				"appraisalDate", EmployeeDetails::getAppraisalDate);
			attributeGetterFunctions.put(
				"employeeType", EmployeeDetails::getEmployeeType);
			attributeGetterFunctions.put(
				"stipend", EmployeeDetails::getStipend);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<EmployeeDetails, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<EmployeeDetails, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<EmployeeDetails, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<EmployeeDetails, String>)EmployeeDetails::setUuid);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<EmployeeDetails, Long>)
					EmployeeDetails::setCompanyId);
			attributeSetterBiConsumers.put(
				"createdBy",
				(BiConsumer<EmployeeDetails, Long>)
					EmployeeDetails::setCreatedBy);
			attributeSetterBiConsumers.put(
				"modifiedBy",
				(BiConsumer<EmployeeDetails, Long>)
					EmployeeDetails::setModifiedBy);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<EmployeeDetails, Long>)EmployeeDetails::setGroupId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<EmployeeDetails, Date>)
					EmployeeDetails::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<EmployeeDetails, Date>)
					EmployeeDetails::setModifiedDate);
			attributeSetterBiConsumers.put(
				"employeeId",
				(BiConsumer<EmployeeDetails, Long>)
					EmployeeDetails::setEmployeeId);
			attributeSetterBiConsumers.put(
				"employeeCode",
				(BiConsumer<EmployeeDetails, String>)
					EmployeeDetails::setEmployeeCode);
			attributeSetterBiConsumers.put(
				"lrUserId",
				(BiConsumer<EmployeeDetails, Long>)
					EmployeeDetails::setLrUserId);
			attributeSetterBiConsumers.put(
				"firstName",
				(BiConsumer<EmployeeDetails, String>)
					EmployeeDetails::setFirstName);
			attributeSetterBiConsumers.put(
				"lastName",
				(BiConsumer<EmployeeDetails, String>)
					EmployeeDetails::setLastName);
			attributeSetterBiConsumers.put(
				"officialEmail",
				(BiConsumer<EmployeeDetails, String>)
					EmployeeDetails::setOfficialEmail);
			attributeSetterBiConsumers.put(
				"personalEmail",
				(BiConsumer<EmployeeDetails, String>)
					EmployeeDetails::setPersonalEmail);
			attributeSetterBiConsumers.put(
				"joiningDate",
				(BiConsumer<EmployeeDetails, Date>)
					EmployeeDetails::setJoiningDate);
			attributeSetterBiConsumers.put(
				"leavingDate",
				(BiConsumer<EmployeeDetails, Date>)
					EmployeeDetails::setLeavingDate);
			attributeSetterBiConsumers.put(
				"mobileNo",
				(BiConsumer<EmployeeDetails, String>)
					EmployeeDetails::setMobileNo);
			attributeSetterBiConsumers.put(
				"gender",
				(BiConsumer<EmployeeDetails, String>)
					EmployeeDetails::setGender);
			attributeSetterBiConsumers.put(
				"fatherName",
				(BiConsumer<EmployeeDetails, String>)
					EmployeeDetails::setFatherName);
			attributeSetterBiConsumers.put(
				"dateOfBirth",
				(BiConsumer<EmployeeDetails, Date>)
					EmployeeDetails::setDateOfBirth);
			attributeSetterBiConsumers.put(
				"maritalStatus",
				(BiConsumer<EmployeeDetails, Boolean>)
					EmployeeDetails::setMaritalStatus);
			attributeSetterBiConsumers.put(
				"marriageDate",
				(BiConsumer<EmployeeDetails, Date>)
					EmployeeDetails::setMarriageDate);
			attributeSetterBiConsumers.put(
				"spouseName",
				(BiConsumer<EmployeeDetails, String>)
					EmployeeDetails::setSpouseName);
			attributeSetterBiConsumers.put(
				"employeeAddressId",
				(BiConsumer<EmployeeDetails, Long>)
					EmployeeDetails::setEmployeeAddressId);
			attributeSetterBiConsumers.put(
				"skypeId",
				(BiConsumer<EmployeeDetails, String>)
					EmployeeDetails::setSkypeId);
			attributeSetterBiConsumers.put(
				"nominneeId",
				(BiConsumer<EmployeeDetails, Long>)
					EmployeeDetails::setNominneeId);
			attributeSetterBiConsumers.put(
				"bankAccountId",
				(BiConsumer<EmployeeDetails, Long>)
					EmployeeDetails::setBankAccountId);
			attributeSetterBiConsumers.put(
				"uanEsicId",
				(BiConsumer<EmployeeDetails, Long>)
					EmployeeDetails::setUanEsicId);
			attributeSetterBiConsumers.put(
				"probationStatusId",
				(BiConsumer<EmployeeDetails, Long>)
					EmployeeDetails::setProbationStatusId);
			attributeSetterBiConsumers.put(
				"isEmployeeOnboarded",
				(BiConsumer<EmployeeDetails, Boolean>)
					EmployeeDetails::setIsEmployeeOnboarded);
			attributeSetterBiConsumers.put(
				"isExperienced",
				(BiConsumer<EmployeeDetails, Boolean>)
					EmployeeDetails::setIsExperienced);
			attributeSetterBiConsumers.put(
				"isProbationEnabled",
				(BiConsumer<EmployeeDetails, Boolean>)
					EmployeeDetails::setIsProbationEnabled);
			attributeSetterBiConsumers.put(
				"profilePicId",
				(BiConsumer<EmployeeDetails, Long>)
					EmployeeDetails::setProfilePicId);
			attributeSetterBiConsumers.put(
				"insuranceLink",
				(BiConsumer<EmployeeDetails, String>)
					EmployeeDetails::setInsuranceLink);
			attributeSetterBiConsumers.put(
				"isTerminated",
				(BiConsumer<EmployeeDetails, Boolean>)
					EmployeeDetails::setIsTerminated);
			attributeSetterBiConsumers.put(
				"appraisalDate",
				(BiConsumer<EmployeeDetails, Date>)
					EmployeeDetails::setAppraisalDate);
			attributeSetterBiConsumers.put(
				"employeeType",
				(BiConsumer<EmployeeDetails, String>)
					EmployeeDetails::setEmployeeType);
			attributeSetterBiConsumers.put(
				"stipend",
				(BiConsumer<EmployeeDetails, Double>)
					EmployeeDetails::setStipend);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getEmployeeId() {
		return _employeeId;
	}

	@Override
	public void setEmployeeId(long employeeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_employeeId = employeeId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalEmployeeId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("employeeId"));
	}

	@JSON
	@Override
	public String getEmployeeCode() {
		if (_employeeCode == null) {
			return "";
		}
		else {
			return _employeeCode;
		}
	}

	@Override
	public void setEmployeeCode(String employeeCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_employeeCode = employeeCode;
	}

	@JSON
	@Override
	public long getLrUserId() {
		return _lrUserId;
	}

	@Override
	public void setLrUserId(long lrUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_lrUserId = lrUserId;
	}

	@Override
	public String getLrUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getLrUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setLrUserUuid(String lrUserUuid) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalLrUserId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("lrUserId"));
	}

	@JSON
	@Override
	public String getFirstName() {
		if (_firstName == null) {
			return "";
		}
		else {
			return _firstName;
		}
	}

	@Override
	public void setFirstName(String firstName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_firstName = firstName;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalFirstName() {
		return getColumnOriginalValue("firstName");
	}

	@JSON
	@Override
	public String getLastName() {
		if (_lastName == null) {
			return "";
		}
		else {
			return _lastName;
		}
	}

	@Override
	public void setLastName(String lastName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_lastName = lastName;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalLastName() {
		return getColumnOriginalValue("lastName");
	}

	@JSON
	@Override
	public String getOfficialEmail() {
		if (_officialEmail == null) {
			return "";
		}
		else {
			return _officialEmail;
		}
	}

	@Override
	public void setOfficialEmail(String officialEmail) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_officialEmail = officialEmail;
	}

	@JSON
	@Override
	public String getPersonalEmail() {
		if (_personalEmail == null) {
			return "";
		}
		else {
			return _personalEmail;
		}
	}

	@Override
	public void setPersonalEmail(String personalEmail) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_personalEmail = personalEmail;
	}

	@JSON
	@Override
	public Date getJoiningDate() {
		return _joiningDate;
	}

	@Override
	public void setJoiningDate(Date joiningDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_joiningDate = joiningDate;
	}

	@JSON
	@Override
	public Date getLeavingDate() {
		return _leavingDate;
	}

	@Override
	public void setLeavingDate(Date leavingDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_leavingDate = leavingDate;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public Date getOriginalLeavingDate() {
		return getColumnOriginalValue("leavingDate");
	}

	@JSON
	@Override
	public String getMobileNo() {
		if (_mobileNo == null) {
			return "";
		}
		else {
			return _mobileNo;
		}
	}

	@Override
	public void setMobileNo(String mobileNo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mobileNo = mobileNo;
	}

	@JSON
	@Override
	public String getGender() {
		if (_gender == null) {
			return "";
		}
		else {
			return _gender;
		}
	}

	@Override
	public void setGender(String gender) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_gender = gender;
	}

	@JSON
	@Override
	public String getFatherName() {
		if (_fatherName == null) {
			return "";
		}
		else {
			return _fatherName;
		}
	}

	@Override
	public void setFatherName(String fatherName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fatherName = fatherName;
	}

	@JSON
	@Override
	public Date getDateOfBirth() {
		return _dateOfBirth;
	}

	@Override
	public void setDateOfBirth(Date dateOfBirth) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dateOfBirth = dateOfBirth;
	}

	@JSON
	@Override
	public boolean getMaritalStatus() {
		return _maritalStatus;
	}

	@JSON
	@Override
	public boolean isMaritalStatus() {
		return _maritalStatus;
	}

	@Override
	public void setMaritalStatus(boolean maritalStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_maritalStatus = maritalStatus;
	}

	@JSON
	@Override
	public Date getMarriageDate() {
		return _marriageDate;
	}

	@Override
	public void setMarriageDate(Date marriageDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_marriageDate = marriageDate;
	}

	@JSON
	@Override
	public String getSpouseName() {
		if (_spouseName == null) {
			return "";
		}
		else {
			return _spouseName;
		}
	}

	@Override
	public void setSpouseName(String spouseName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_spouseName = spouseName;
	}

	@JSON
	@Override
	public long getEmployeeAddressId() {
		return _employeeAddressId;
	}

	@Override
	public void setEmployeeAddressId(long employeeAddressId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_employeeAddressId = employeeAddressId;
	}

	@JSON
	@Override
	public String getSkypeId() {
		if (_skypeId == null) {
			return "";
		}
		else {
			return _skypeId;
		}
	}

	@Override
	public void setSkypeId(String skypeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_skypeId = skypeId;
	}

	@JSON
	@Override
	public long getNominneeId() {
		return _nominneeId;
	}

	@Override
	public void setNominneeId(long nominneeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nominneeId = nominneeId;
	}

	@JSON
	@Override
	public long getBankAccountId() {
		return _bankAccountId;
	}

	@Override
	public void setBankAccountId(long bankAccountId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_bankAccountId = bankAccountId;
	}

	@JSON
	@Override
	public long getUanEsicId() {
		return _uanEsicId;
	}

	@Override
	public void setUanEsicId(long uanEsicId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uanEsicId = uanEsicId;
	}

	@JSON
	@Override
	public long getProbationStatusId() {
		return _probationStatusId;
	}

	@Override
	public void setProbationStatusId(long probationStatusId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_probationStatusId = probationStatusId;
	}

	@JSON
	@Override
	public boolean getIsEmployeeOnboarded() {
		return _isEmployeeOnboarded;
	}

	@JSON
	@Override
	public boolean isIsEmployeeOnboarded() {
		return _isEmployeeOnboarded;
	}

	@Override
	public void setIsEmployeeOnboarded(boolean isEmployeeOnboarded) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_isEmployeeOnboarded = isEmployeeOnboarded;
	}

	@JSON
	@Override
	public boolean getIsExperienced() {
		return _isExperienced;
	}

	@JSON
	@Override
	public boolean isIsExperienced() {
		return _isExperienced;
	}

	@Override
	public void setIsExperienced(boolean isExperienced) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_isExperienced = isExperienced;
	}

	@JSON
	@Override
	public boolean getIsProbationEnabled() {
		return _isProbationEnabled;
	}

	@JSON
	@Override
	public boolean isIsProbationEnabled() {
		return _isProbationEnabled;
	}

	@Override
	public void setIsProbationEnabled(boolean isProbationEnabled) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_isProbationEnabled = isProbationEnabled;
	}

	@JSON
	@Override
	public long getProfilePicId() {
		return _profilePicId;
	}

	@Override
	public void setProfilePicId(long profilePicId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_profilePicId = profilePicId;
	}

	@JSON
	@Override
	public String getInsuranceLink() {
		if (_insuranceLink == null) {
			return "";
		}
		else {
			return _insuranceLink;
		}
	}

	@Override
	public void setInsuranceLink(String insuranceLink) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_insuranceLink = insuranceLink;
	}

	@JSON
	@Override
	public boolean getIsTerminated() {
		return _isTerminated;
	}

	@JSON
	@Override
	public boolean isIsTerminated() {
		return _isTerminated;
	}

	@Override
	public void setIsTerminated(boolean isTerminated) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_isTerminated = isTerminated;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public boolean getOriginalIsTerminated() {
		return GetterUtil.getBoolean(
			this.<Boolean>getColumnOriginalValue("isTerminated"));
	}

	@JSON
	@Override
	public Date getAppraisalDate() {
		return _appraisalDate;
	}

	@Override
	public void setAppraisalDate(Date appraisalDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_appraisalDate = appraisalDate;
	}

	@JSON
	@Override
	public String getEmployeeType() {
		if (_employeeType == null) {
			return "";
		}
		else {
			return _employeeType;
		}
	}

	@Override
	public void setEmployeeType(String employeeType) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_employeeType = employeeType;
	}

	@JSON
	@Override
	public double getStipend() {
		return _stipend;
	}

	@Override
	public void setStipend(double stipend) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_stipend = stipend;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(EmployeeDetails.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), EmployeeDetails.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public EmployeeDetails toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, EmployeeDetails>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EmployeeDetailsImpl employeeDetailsImpl = new EmployeeDetailsImpl();

		employeeDetailsImpl.setUuid(getUuid());
		employeeDetailsImpl.setCompanyId(getCompanyId());
		employeeDetailsImpl.setCreatedBy(getCreatedBy());
		employeeDetailsImpl.setModifiedBy(getModifiedBy());
		employeeDetailsImpl.setGroupId(getGroupId());
		employeeDetailsImpl.setCreateDate(getCreateDate());
		employeeDetailsImpl.setModifiedDate(getModifiedDate());
		employeeDetailsImpl.setEmployeeId(getEmployeeId());
		employeeDetailsImpl.setEmployeeCode(getEmployeeCode());
		employeeDetailsImpl.setLrUserId(getLrUserId());
		employeeDetailsImpl.setFirstName(getFirstName());
		employeeDetailsImpl.setLastName(getLastName());
		employeeDetailsImpl.setOfficialEmail(getOfficialEmail());
		employeeDetailsImpl.setPersonalEmail(getPersonalEmail());
		employeeDetailsImpl.setJoiningDate(getJoiningDate());
		employeeDetailsImpl.setLeavingDate(getLeavingDate());
		employeeDetailsImpl.setMobileNo(getMobileNo());
		employeeDetailsImpl.setGender(getGender());
		employeeDetailsImpl.setFatherName(getFatherName());
		employeeDetailsImpl.setDateOfBirth(getDateOfBirth());
		employeeDetailsImpl.setMaritalStatus(isMaritalStatus());
		employeeDetailsImpl.setMarriageDate(getMarriageDate());
		employeeDetailsImpl.setSpouseName(getSpouseName());
		employeeDetailsImpl.setEmployeeAddressId(getEmployeeAddressId());
		employeeDetailsImpl.setSkypeId(getSkypeId());
		employeeDetailsImpl.setNominneeId(getNominneeId());
		employeeDetailsImpl.setBankAccountId(getBankAccountId());
		employeeDetailsImpl.setUanEsicId(getUanEsicId());
		employeeDetailsImpl.setProbationStatusId(getProbationStatusId());
		employeeDetailsImpl.setIsEmployeeOnboarded(isIsEmployeeOnboarded());
		employeeDetailsImpl.setIsExperienced(isIsExperienced());
		employeeDetailsImpl.setIsProbationEnabled(isIsProbationEnabled());
		employeeDetailsImpl.setProfilePicId(getProfilePicId());
		employeeDetailsImpl.setInsuranceLink(getInsuranceLink());
		employeeDetailsImpl.setIsTerminated(isIsTerminated());
		employeeDetailsImpl.setAppraisalDate(getAppraisalDate());
		employeeDetailsImpl.setEmployeeType(getEmployeeType());
		employeeDetailsImpl.setStipend(getStipend());

		employeeDetailsImpl.resetOriginalValues();

		return employeeDetailsImpl;
	}

	@Override
	public EmployeeDetails cloneWithOriginalValues() {
		EmployeeDetailsImpl employeeDetailsImpl = new EmployeeDetailsImpl();

		employeeDetailsImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		employeeDetailsImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		employeeDetailsImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("createdBy"));
		employeeDetailsImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modifiedBy"));
		employeeDetailsImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		employeeDetailsImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		employeeDetailsImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		employeeDetailsImpl.setEmployeeId(
			this.<Long>getColumnOriginalValue("employeeId"));
		employeeDetailsImpl.setEmployeeCode(
			this.<String>getColumnOriginalValue("employeeCode"));
		employeeDetailsImpl.setLrUserId(
			this.<Long>getColumnOriginalValue("lrUserId"));
		employeeDetailsImpl.setFirstName(
			this.<String>getColumnOriginalValue("firstName"));
		employeeDetailsImpl.setLastName(
			this.<String>getColumnOriginalValue("lastName"));
		employeeDetailsImpl.setOfficialEmail(
			this.<String>getColumnOriginalValue("officialEmail"));
		employeeDetailsImpl.setPersonalEmail(
			this.<String>getColumnOriginalValue("personalEmail"));
		employeeDetailsImpl.setJoiningDate(
			this.<Date>getColumnOriginalValue("joiningDate"));
		employeeDetailsImpl.setLeavingDate(
			this.<Date>getColumnOriginalValue("leavingDate"));
		employeeDetailsImpl.setMobileNo(
			this.<String>getColumnOriginalValue("mobileNo"));
		employeeDetailsImpl.setGender(
			this.<String>getColumnOriginalValue("gender"));
		employeeDetailsImpl.setFatherName(
			this.<String>getColumnOriginalValue("fatherName"));
		employeeDetailsImpl.setDateOfBirth(
			this.<Date>getColumnOriginalValue("dateOfBirth"));
		employeeDetailsImpl.setMaritalStatus(
			this.<Boolean>getColumnOriginalValue("maritalStatus"));
		employeeDetailsImpl.setMarriageDate(
			this.<Date>getColumnOriginalValue("marriageDate"));
		employeeDetailsImpl.setSpouseName(
			this.<String>getColumnOriginalValue("spouseName"));
		employeeDetailsImpl.setEmployeeAddressId(
			this.<Long>getColumnOriginalValue("employeeAddressId"));
		employeeDetailsImpl.setSkypeId(
			this.<String>getColumnOriginalValue("skypeId"));
		employeeDetailsImpl.setNominneeId(
			this.<Long>getColumnOriginalValue("nominneeId"));
		employeeDetailsImpl.setBankAccountId(
			this.<Long>getColumnOriginalValue("bankAccountId"));
		employeeDetailsImpl.setUanEsicId(
			this.<Long>getColumnOriginalValue("uanEsicId"));
		employeeDetailsImpl.setProbationStatusId(
			this.<Long>getColumnOriginalValue("probationStatusId"));
		employeeDetailsImpl.setIsEmployeeOnboarded(
			this.<Boolean>getColumnOriginalValue("isEmployeeOnboarded"));
		employeeDetailsImpl.setIsExperienced(
			this.<Boolean>getColumnOriginalValue("isExperienced"));
		employeeDetailsImpl.setIsProbationEnabled(
			this.<Boolean>getColumnOriginalValue("isProbationEnabled"));
		employeeDetailsImpl.setProfilePicId(
			this.<Long>getColumnOriginalValue("profilePicId"));
		employeeDetailsImpl.setInsuranceLink(
			this.<String>getColumnOriginalValue("insuranceLink"));
		employeeDetailsImpl.setIsTerminated(
			this.<Boolean>getColumnOriginalValue("isTerminated"));
		employeeDetailsImpl.setAppraisalDate(
			this.<Date>getColumnOriginalValue("appraisalDate"));
		employeeDetailsImpl.setEmployeeType(
			this.<String>getColumnOriginalValue("employeeType"));
		employeeDetailsImpl.setStipend(
			this.<Double>getColumnOriginalValue("stipend"));

		return employeeDetailsImpl;
	}

	@Override
	public int compareTo(EmployeeDetails employeeDetails) {
		long primaryKey = employeeDetails.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof EmployeeDetails)) {
			return false;
		}

		EmployeeDetails employeeDetails = (EmployeeDetails)object;

		long primaryKey = employeeDetails.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<EmployeeDetails> toCacheModel() {
		EmployeeDetailsCacheModel employeeDetailsCacheModel =
			new EmployeeDetailsCacheModel();

		employeeDetailsCacheModel.uuid = getUuid();

		String uuid = employeeDetailsCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			employeeDetailsCacheModel.uuid = null;
		}

		employeeDetailsCacheModel.companyId = getCompanyId();

		employeeDetailsCacheModel.createdBy = getCreatedBy();

		employeeDetailsCacheModel.modifiedBy = getModifiedBy();

		employeeDetailsCacheModel.groupId = getGroupId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			employeeDetailsCacheModel.createDate = createDate.getTime();
		}
		else {
			employeeDetailsCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			employeeDetailsCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			employeeDetailsCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		employeeDetailsCacheModel.employeeId = getEmployeeId();

		employeeDetailsCacheModel.employeeCode = getEmployeeCode();

		String employeeCode = employeeDetailsCacheModel.employeeCode;

		if ((employeeCode != null) && (employeeCode.length() == 0)) {
			employeeDetailsCacheModel.employeeCode = null;
		}

		employeeDetailsCacheModel.lrUserId = getLrUserId();

		employeeDetailsCacheModel.firstName = getFirstName();

		String firstName = employeeDetailsCacheModel.firstName;

		if ((firstName != null) && (firstName.length() == 0)) {
			employeeDetailsCacheModel.firstName = null;
		}

		employeeDetailsCacheModel.lastName = getLastName();

		String lastName = employeeDetailsCacheModel.lastName;

		if ((lastName != null) && (lastName.length() == 0)) {
			employeeDetailsCacheModel.lastName = null;
		}

		employeeDetailsCacheModel.officialEmail = getOfficialEmail();

		String officialEmail = employeeDetailsCacheModel.officialEmail;

		if ((officialEmail != null) && (officialEmail.length() == 0)) {
			employeeDetailsCacheModel.officialEmail = null;
		}

		employeeDetailsCacheModel.personalEmail = getPersonalEmail();

		String personalEmail = employeeDetailsCacheModel.personalEmail;

		if ((personalEmail != null) && (personalEmail.length() == 0)) {
			employeeDetailsCacheModel.personalEmail = null;
		}

		Date joiningDate = getJoiningDate();

		if (joiningDate != null) {
			employeeDetailsCacheModel.joiningDate = joiningDate.getTime();
		}
		else {
			employeeDetailsCacheModel.joiningDate = Long.MIN_VALUE;
		}

		Date leavingDate = getLeavingDate();

		if (leavingDate != null) {
			employeeDetailsCacheModel.leavingDate = leavingDate.getTime();
		}
		else {
			employeeDetailsCacheModel.leavingDate = Long.MIN_VALUE;
		}

		employeeDetailsCacheModel.mobileNo = getMobileNo();

		String mobileNo = employeeDetailsCacheModel.mobileNo;

		if ((mobileNo != null) && (mobileNo.length() == 0)) {
			employeeDetailsCacheModel.mobileNo = null;
		}

		employeeDetailsCacheModel.gender = getGender();

		String gender = employeeDetailsCacheModel.gender;

		if ((gender != null) && (gender.length() == 0)) {
			employeeDetailsCacheModel.gender = null;
		}

		employeeDetailsCacheModel.fatherName = getFatherName();

		String fatherName = employeeDetailsCacheModel.fatherName;

		if ((fatherName != null) && (fatherName.length() == 0)) {
			employeeDetailsCacheModel.fatherName = null;
		}

		Date dateOfBirth = getDateOfBirth();

		if (dateOfBirth != null) {
			employeeDetailsCacheModel.dateOfBirth = dateOfBirth.getTime();
		}
		else {
			employeeDetailsCacheModel.dateOfBirth = Long.MIN_VALUE;
		}

		employeeDetailsCacheModel.maritalStatus = isMaritalStatus();

		Date marriageDate = getMarriageDate();

		if (marriageDate != null) {
			employeeDetailsCacheModel.marriageDate = marriageDate.getTime();
		}
		else {
			employeeDetailsCacheModel.marriageDate = Long.MIN_VALUE;
		}

		employeeDetailsCacheModel.spouseName = getSpouseName();

		String spouseName = employeeDetailsCacheModel.spouseName;

		if ((spouseName != null) && (spouseName.length() == 0)) {
			employeeDetailsCacheModel.spouseName = null;
		}

		employeeDetailsCacheModel.employeeAddressId = getEmployeeAddressId();

		employeeDetailsCacheModel.skypeId = getSkypeId();

		String skypeId = employeeDetailsCacheModel.skypeId;

		if ((skypeId != null) && (skypeId.length() == 0)) {
			employeeDetailsCacheModel.skypeId = null;
		}

		employeeDetailsCacheModel.nominneeId = getNominneeId();

		employeeDetailsCacheModel.bankAccountId = getBankAccountId();

		employeeDetailsCacheModel.uanEsicId = getUanEsicId();

		employeeDetailsCacheModel.probationStatusId = getProbationStatusId();

		employeeDetailsCacheModel.isEmployeeOnboarded = isIsEmployeeOnboarded();

		employeeDetailsCacheModel.isExperienced = isIsExperienced();

		employeeDetailsCacheModel.isProbationEnabled = isIsProbationEnabled();

		employeeDetailsCacheModel.profilePicId = getProfilePicId();

		employeeDetailsCacheModel.insuranceLink = getInsuranceLink();

		String insuranceLink = employeeDetailsCacheModel.insuranceLink;

		if ((insuranceLink != null) && (insuranceLink.length() == 0)) {
			employeeDetailsCacheModel.insuranceLink = null;
		}

		employeeDetailsCacheModel.isTerminated = isIsTerminated();

		Date appraisalDate = getAppraisalDate();

		if (appraisalDate != null) {
			employeeDetailsCacheModel.appraisalDate = appraisalDate.getTime();
		}
		else {
			employeeDetailsCacheModel.appraisalDate = Long.MIN_VALUE;
		}

		employeeDetailsCacheModel.employeeType = getEmployeeType();

		String employeeType = employeeDetailsCacheModel.employeeType;

		if ((employeeType != null) && (employeeType.length() == 0)) {
			employeeDetailsCacheModel.employeeType = null;
		}

		employeeDetailsCacheModel.stipend = getStipend();

		return employeeDetailsCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<EmployeeDetails, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<EmployeeDetails, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EmployeeDetails, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((EmployeeDetails)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, EmployeeDetails>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					EmployeeDetails.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _companyId;
	private long _createdBy;
	private long _modifiedBy;
	private long _groupId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _employeeId;
	private String _employeeCode;
	private long _lrUserId;
	private String _firstName;
	private String _lastName;
	private String _officialEmail;
	private String _personalEmail;
	private Date _joiningDate;
	private Date _leavingDate;
	private String _mobileNo;
	private String _gender;
	private String _fatherName;
	private Date _dateOfBirth;
	private boolean _maritalStatus;
	private Date _marriageDate;
	private String _spouseName;
	private long _employeeAddressId;
	private String _skypeId;
	private long _nominneeId;
	private long _bankAccountId;
	private long _uanEsicId;
	private long _probationStatusId;
	private boolean _isEmployeeOnboarded;
	private boolean _isExperienced;
	private boolean _isProbationEnabled;
	private long _profilePicId;
	private String _insuranceLink;
	private boolean _isTerminated;
	private Date _appraisalDate;
	private String _employeeType;
	private double _stipend;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<EmployeeDetails, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((EmployeeDetails)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createdBy", _createdBy);
		_columnOriginalValues.put("modifiedBy", _modifiedBy);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("employeeId", _employeeId);
		_columnOriginalValues.put("employeeCode", _employeeCode);
		_columnOriginalValues.put("lrUserId", _lrUserId);
		_columnOriginalValues.put("firstName", _firstName);
		_columnOriginalValues.put("lastName", _lastName);
		_columnOriginalValues.put("officialEmail", _officialEmail);
		_columnOriginalValues.put("personalEmail", _personalEmail);
		_columnOriginalValues.put("joiningDate", _joiningDate);
		_columnOriginalValues.put("leavingDate", _leavingDate);
		_columnOriginalValues.put("mobileNo", _mobileNo);
		_columnOriginalValues.put("gender", _gender);
		_columnOriginalValues.put("fatherName", _fatherName);
		_columnOriginalValues.put("dateOfBirth", _dateOfBirth);
		_columnOriginalValues.put("maritalStatus", _maritalStatus);
		_columnOriginalValues.put("marriageDate", _marriageDate);
		_columnOriginalValues.put("spouseName", _spouseName);
		_columnOriginalValues.put("employeeAddressId", _employeeAddressId);
		_columnOriginalValues.put("skypeId", _skypeId);
		_columnOriginalValues.put("nominneeId", _nominneeId);
		_columnOriginalValues.put("bankAccountId", _bankAccountId);
		_columnOriginalValues.put("uanEsicId", _uanEsicId);
		_columnOriginalValues.put("probationStatusId", _probationStatusId);
		_columnOriginalValues.put("isEmployeeOnboarded", _isEmployeeOnboarded);
		_columnOriginalValues.put("isExperienced", _isExperienced);
		_columnOriginalValues.put("isProbationEnabled", _isProbationEnabled);
		_columnOriginalValues.put("profilePicId", _profilePicId);
		_columnOriginalValues.put("insuranceLink", _insuranceLink);
		_columnOriginalValues.put("isTerminated", _isTerminated);
		_columnOriginalValues.put("appraisalDate", _appraisalDate);
		_columnOriginalValues.put("employeeType", _employeeType);
		_columnOriginalValues.put("stipend", _stipend);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("createdBy", 4L);

		columnBitmasks.put("modifiedBy", 8L);

		columnBitmasks.put("groupId", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("employeeId", 128L);

		columnBitmasks.put("employeeCode", 256L);

		columnBitmasks.put("lrUserId", 512L);

		columnBitmasks.put("firstName", 1024L);

		columnBitmasks.put("lastName", 2048L);

		columnBitmasks.put("officialEmail", 4096L);

		columnBitmasks.put("personalEmail", 8192L);

		columnBitmasks.put("joiningDate", 16384L);

		columnBitmasks.put("leavingDate", 32768L);

		columnBitmasks.put("mobileNo", 65536L);

		columnBitmasks.put("gender", 131072L);

		columnBitmasks.put("fatherName", 262144L);

		columnBitmasks.put("dateOfBirth", 524288L);

		columnBitmasks.put("maritalStatus", 1048576L);

		columnBitmasks.put("marriageDate", 2097152L);

		columnBitmasks.put("spouseName", 4194304L);

		columnBitmasks.put("employeeAddressId", 8388608L);

		columnBitmasks.put("skypeId", 16777216L);

		columnBitmasks.put("nominneeId", 33554432L);

		columnBitmasks.put("bankAccountId", 67108864L);

		columnBitmasks.put("uanEsicId", 134217728L);

		columnBitmasks.put("probationStatusId", 268435456L);

		columnBitmasks.put("isEmployeeOnboarded", 536870912L);

		columnBitmasks.put("isExperienced", 1073741824L);

		columnBitmasks.put("isProbationEnabled", 2147483648L);

		columnBitmasks.put("profilePicId", 4294967296L);

		columnBitmasks.put("insuranceLink", 8589934592L);

		columnBitmasks.put("isTerminated", 17179869184L);

		columnBitmasks.put("appraisalDate", 34359738368L);

		columnBitmasks.put("employeeType", 68719476736L);

		columnBitmasks.put("stipend", 137438953472L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private EmployeeDetails _escapedModel;

}