/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.model.impl;

import com.ax.hrms.model.EmployeeExperience;
import com.ax.hrms.model.EmployeeExperienceModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the EmployeeExperience service. Represents a row in the &quot;ax_EmployeeExperience&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>EmployeeExperienceModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EmployeeExperienceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmployeeExperienceImpl
 * @generated
 */
@JSON(strict = true)
public class EmployeeExperienceModelImpl
	extends BaseModelImpl<EmployeeExperience>
	implements EmployeeExperienceModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a employee experience model instance should use the <code>EmployeeExperience</code> interface instead.
	 */
	public static final String TABLE_NAME = "ax_EmployeeExperience";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"companyId", Types.BIGINT},
		{"createdBy", Types.BIGINT}, {"modifiedBy", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"experienceId", Types.BIGINT},
		{"companyName", Types.VARCHAR}, {"joiningDate", Types.TIMESTAMP},
		{"relievingDate", Types.TIMESTAMP},
		{"experienceCertificateMediaId", Types.BIGINT},
		{"employeeId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("experienceId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("joiningDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("relievingDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("experienceCertificateMediaId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("employeeId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ax_EmployeeExperience (uuid_ VARCHAR(75) null,companyId LONG,createdBy LONG,modifiedBy LONG,groupId LONG,createDate DATE null,modifiedDate DATE null,experienceId LONG not null primary key,companyName VARCHAR(75) null,joiningDate DATE null,relievingDate DATE null,experienceCertificateMediaId LONG,employeeId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table ax_EmployeeExperience";

	public static final String ORDER_BY_JPQL =
		" ORDER BY employeeExperience.experienceId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ax_EmployeeExperience.experienceId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EMPLOYEEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EXPERIENCEID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public EmployeeExperienceModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _experienceId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setExperienceId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _experienceId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return EmployeeExperience.class;
	}

	@Override
	public String getModelClassName() {
		return EmployeeExperience.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<EmployeeExperience, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<EmployeeExperience, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EmployeeExperience, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((EmployeeExperience)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<EmployeeExperience, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<EmployeeExperience, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(EmployeeExperience)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<EmployeeExperience, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<EmployeeExperience, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<EmployeeExperience, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<EmployeeExperience, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<EmployeeExperience, Object>>();

			attributeGetterFunctions.put("uuid", EmployeeExperience::getUuid);
			attributeGetterFunctions.put(
				"companyId", EmployeeExperience::getCompanyId);
			attributeGetterFunctions.put(
				"createdBy", EmployeeExperience::getCreatedBy);
			attributeGetterFunctions.put(
				"modifiedBy", EmployeeExperience::getModifiedBy);
			attributeGetterFunctions.put(
				"groupId", EmployeeExperience::getGroupId);
			attributeGetterFunctions.put(
				"createDate", EmployeeExperience::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", EmployeeExperience::getModifiedDate);
			attributeGetterFunctions.put(
				"experienceId", EmployeeExperience::getExperienceId);
			attributeGetterFunctions.put(
				"companyName", EmployeeExperience::getCompanyName);
			attributeGetterFunctions.put(
				"joiningDate", EmployeeExperience::getJoiningDate);
			attributeGetterFunctions.put(
				"relievingDate", EmployeeExperience::getRelievingDate);
			attributeGetterFunctions.put(
				"experienceCertificateMediaId",
				EmployeeExperience::getExperienceCertificateMediaId);
			attributeGetterFunctions.put(
				"employeeId", EmployeeExperience::getEmployeeId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<EmployeeExperience, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<EmployeeExperience, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<EmployeeExperience, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<EmployeeExperience, String>)
					EmployeeExperience::setUuid);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<EmployeeExperience, Long>)
					EmployeeExperience::setCompanyId);
			attributeSetterBiConsumers.put(
				"createdBy",
				(BiConsumer<EmployeeExperience, Long>)
					EmployeeExperience::setCreatedBy);
			attributeSetterBiConsumers.put(
				"modifiedBy",
				(BiConsumer<EmployeeExperience, Long>)
					EmployeeExperience::setModifiedBy);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<EmployeeExperience, Long>)
					EmployeeExperience::setGroupId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<EmployeeExperience, Date>)
					EmployeeExperience::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<EmployeeExperience, Date>)
					EmployeeExperience::setModifiedDate);
			attributeSetterBiConsumers.put(
				"experienceId",
				(BiConsumer<EmployeeExperience, Long>)
					EmployeeExperience::setExperienceId);
			attributeSetterBiConsumers.put(
				"companyName",
				(BiConsumer<EmployeeExperience, String>)
					EmployeeExperience::setCompanyName);
			attributeSetterBiConsumers.put(
				"joiningDate",
				(BiConsumer<EmployeeExperience, Date>)
					EmployeeExperience::setJoiningDate);
			attributeSetterBiConsumers.put(
				"relievingDate",
				(BiConsumer<EmployeeExperience, Date>)
					EmployeeExperience::setRelievingDate);
			attributeSetterBiConsumers.put(
				"experienceCertificateMediaId",
				(BiConsumer<EmployeeExperience, Long>)
					EmployeeExperience::setExperienceCertificateMediaId);
			attributeSetterBiConsumers.put(
				"employeeId",
				(BiConsumer<EmployeeExperience, Long>)
					EmployeeExperience::setEmployeeId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getExperienceId() {
		return _experienceId;
	}

	@Override
	public void setExperienceId(long experienceId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_experienceId = experienceId;
	}

	@JSON
	@Override
	public String getCompanyName() {
		if (_companyName == null) {
			return "";
		}
		else {
			return _companyName;
		}
	}

	@Override
	public void setCompanyName(String companyName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyName = companyName;
	}

	@JSON
	@Override
	public Date getJoiningDate() {
		return _joiningDate;
	}

	@Override
	public void setJoiningDate(Date joiningDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_joiningDate = joiningDate;
	}

	@JSON
	@Override
	public Date getRelievingDate() {
		return _relievingDate;
	}

	@Override
	public void setRelievingDate(Date relievingDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_relievingDate = relievingDate;
	}

	@JSON
	@Override
	public long getExperienceCertificateMediaId() {
		return _experienceCertificateMediaId;
	}

	@Override
	public void setExperienceCertificateMediaId(
		long experienceCertificateMediaId) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_experienceCertificateMediaId = experienceCertificateMediaId;
	}

	@JSON
	@Override
	public long getEmployeeId() {
		return _employeeId;
	}

	@Override
	public void setEmployeeId(long employeeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_employeeId = employeeId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalEmployeeId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("employeeId"));
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(EmployeeExperience.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), EmployeeExperience.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public EmployeeExperience toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, EmployeeExperience>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EmployeeExperienceImpl employeeExperienceImpl =
			new EmployeeExperienceImpl();

		employeeExperienceImpl.setUuid(getUuid());
		employeeExperienceImpl.setCompanyId(getCompanyId());
		employeeExperienceImpl.setCreatedBy(getCreatedBy());
		employeeExperienceImpl.setModifiedBy(getModifiedBy());
		employeeExperienceImpl.setGroupId(getGroupId());
		employeeExperienceImpl.setCreateDate(getCreateDate());
		employeeExperienceImpl.setModifiedDate(getModifiedDate());
		employeeExperienceImpl.setExperienceId(getExperienceId());
		employeeExperienceImpl.setCompanyName(getCompanyName());
		employeeExperienceImpl.setJoiningDate(getJoiningDate());
		employeeExperienceImpl.setRelievingDate(getRelievingDate());
		employeeExperienceImpl.setExperienceCertificateMediaId(
			getExperienceCertificateMediaId());
		employeeExperienceImpl.setEmployeeId(getEmployeeId());

		employeeExperienceImpl.resetOriginalValues();

		return employeeExperienceImpl;
	}

	@Override
	public EmployeeExperience cloneWithOriginalValues() {
		EmployeeExperienceImpl employeeExperienceImpl =
			new EmployeeExperienceImpl();

		employeeExperienceImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		employeeExperienceImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		employeeExperienceImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("createdBy"));
		employeeExperienceImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modifiedBy"));
		employeeExperienceImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		employeeExperienceImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		employeeExperienceImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		employeeExperienceImpl.setExperienceId(
			this.<Long>getColumnOriginalValue("experienceId"));
		employeeExperienceImpl.setCompanyName(
			this.<String>getColumnOriginalValue("companyName"));
		employeeExperienceImpl.setJoiningDate(
			this.<Date>getColumnOriginalValue("joiningDate"));
		employeeExperienceImpl.setRelievingDate(
			this.<Date>getColumnOriginalValue("relievingDate"));
		employeeExperienceImpl.setExperienceCertificateMediaId(
			this.<Long>getColumnOriginalValue("experienceCertificateMediaId"));
		employeeExperienceImpl.setEmployeeId(
			this.<Long>getColumnOriginalValue("employeeId"));

		return employeeExperienceImpl;
	}

	@Override
	public int compareTo(EmployeeExperience employeeExperience) {
		long primaryKey = employeeExperience.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof EmployeeExperience)) {
			return false;
		}

		EmployeeExperience employeeExperience = (EmployeeExperience)object;

		long primaryKey = employeeExperience.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<EmployeeExperience> toCacheModel() {
		EmployeeExperienceCacheModel employeeExperienceCacheModel =
			new EmployeeExperienceCacheModel();

		employeeExperienceCacheModel.uuid = getUuid();

		String uuid = employeeExperienceCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			employeeExperienceCacheModel.uuid = null;
		}

		employeeExperienceCacheModel.companyId = getCompanyId();

		employeeExperienceCacheModel.createdBy = getCreatedBy();

		employeeExperienceCacheModel.modifiedBy = getModifiedBy();

		employeeExperienceCacheModel.groupId = getGroupId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			employeeExperienceCacheModel.createDate = createDate.getTime();
		}
		else {
			employeeExperienceCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			employeeExperienceCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			employeeExperienceCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		employeeExperienceCacheModel.experienceId = getExperienceId();

		employeeExperienceCacheModel.companyName = getCompanyName();

		String companyName = employeeExperienceCacheModel.companyName;

		if ((companyName != null) && (companyName.length() == 0)) {
			employeeExperienceCacheModel.companyName = null;
		}

		Date joiningDate = getJoiningDate();

		if (joiningDate != null) {
			employeeExperienceCacheModel.joiningDate = joiningDate.getTime();
		}
		else {
			employeeExperienceCacheModel.joiningDate = Long.MIN_VALUE;
		}

		Date relievingDate = getRelievingDate();

		if (relievingDate != null) {
			employeeExperienceCacheModel.relievingDate =
				relievingDate.getTime();
		}
		else {
			employeeExperienceCacheModel.relievingDate = Long.MIN_VALUE;
		}

		employeeExperienceCacheModel.experienceCertificateMediaId =
			getExperienceCertificateMediaId();

		employeeExperienceCacheModel.employeeId = getEmployeeId();

		return employeeExperienceCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<EmployeeExperience, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<EmployeeExperience, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EmployeeExperience, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(EmployeeExperience)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, EmployeeExperience>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					EmployeeExperience.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _companyId;
	private long _createdBy;
	private long _modifiedBy;
	private long _groupId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _experienceId;
	private String _companyName;
	private Date _joiningDate;
	private Date _relievingDate;
	private long _experienceCertificateMediaId;
	private long _employeeId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<EmployeeExperience, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((EmployeeExperience)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createdBy", _createdBy);
		_columnOriginalValues.put("modifiedBy", _modifiedBy);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("experienceId", _experienceId);
		_columnOriginalValues.put("companyName", _companyName);
		_columnOriginalValues.put("joiningDate", _joiningDate);
		_columnOriginalValues.put("relievingDate", _relievingDate);
		_columnOriginalValues.put(
			"experienceCertificateMediaId", _experienceCertificateMediaId);
		_columnOriginalValues.put("employeeId", _employeeId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("createdBy", 4L);

		columnBitmasks.put("modifiedBy", 8L);

		columnBitmasks.put("groupId", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("experienceId", 128L);

		columnBitmasks.put("companyName", 256L);

		columnBitmasks.put("joiningDate", 512L);

		columnBitmasks.put("relievingDate", 1024L);

		columnBitmasks.put("experienceCertificateMediaId", 2048L);

		columnBitmasks.put("employeeId", 4096L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private EmployeeExperience _escapedModel;

}