/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.model.impl;

import com.ax.hrms.model.EmployeeSalary;
import com.ax.hrms.model.EmployeeSalaryModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the EmployeeSalary service. Represents a row in the &quot;ax_EmployeeSalary&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>EmployeeSalaryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EmployeeSalaryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmployeeSalaryImpl
 * @generated
 */
@JSON(strict = true)
public class EmployeeSalaryModelImpl
	extends BaseModelImpl<EmployeeSalary> implements EmployeeSalaryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a employee salary model instance should use the <code>EmployeeSalary</code> interface instead.
	 */
	public static final String TABLE_NAME = "ax_EmployeeSalary";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"companyId", Types.BIGINT},
		{"createdBy", Types.BIGINT}, {"modifiedBy", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"salaryId", Types.BIGINT},
		{"grossSalaryCtcPm", Types.DOUBLE}, {"grossSalaryCtcPa", Types.DOUBLE},
		{"employeeId", Types.BIGINT}, {"status", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("salaryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("grossSalaryCtcPm", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("grossSalaryCtcPa", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("employeeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("status", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ax_EmployeeSalary (uuid_ VARCHAR(75) null,companyId LONG,createdBy LONG,modifiedBy LONG,groupId LONG,createDate DATE null,modifiedDate DATE null,salaryId LONG not null primary key,grossSalaryCtcPm DOUBLE,grossSalaryCtcPa DOUBLE,employeeId LONG,status BOOLEAN)";

	public static final String TABLE_SQL_DROP = "drop table ax_EmployeeSalary";

	public static final String ORDER_BY_JPQL =
		" ORDER BY employeeSalary.salaryId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ax_EmployeeSalary.salaryId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EMPLOYEEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STATUS_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SALARYID_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public EmployeeSalaryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _salaryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSalaryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _salaryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return EmployeeSalary.class;
	}

	@Override
	public String getModelClassName() {
		return EmployeeSalary.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<EmployeeSalary, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<EmployeeSalary, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EmployeeSalary, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((EmployeeSalary)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<EmployeeSalary, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<EmployeeSalary, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(EmployeeSalary)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<EmployeeSalary, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<EmployeeSalary, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<EmployeeSalary, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<EmployeeSalary, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<EmployeeSalary, Object>>();

			attributeGetterFunctions.put("uuid", EmployeeSalary::getUuid);
			attributeGetterFunctions.put(
				"companyId", EmployeeSalary::getCompanyId);
			attributeGetterFunctions.put(
				"createdBy", EmployeeSalary::getCreatedBy);
			attributeGetterFunctions.put(
				"modifiedBy", EmployeeSalary::getModifiedBy);
			attributeGetterFunctions.put("groupId", EmployeeSalary::getGroupId);
			attributeGetterFunctions.put(
				"createDate", EmployeeSalary::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", EmployeeSalary::getModifiedDate);
			attributeGetterFunctions.put(
				"salaryId", EmployeeSalary::getSalaryId);
			attributeGetterFunctions.put(
				"grossSalaryCtcPm", EmployeeSalary::getGrossSalaryCtcPm);
			attributeGetterFunctions.put(
				"grossSalaryCtcPa", EmployeeSalary::getGrossSalaryCtcPa);
			attributeGetterFunctions.put(
				"employeeId", EmployeeSalary::getEmployeeId);
			attributeGetterFunctions.put("status", EmployeeSalary::getStatus);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<EmployeeSalary, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<EmployeeSalary, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<EmployeeSalary, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<EmployeeSalary, String>)EmployeeSalary::setUuid);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<EmployeeSalary, Long>)EmployeeSalary::setCompanyId);
			attributeSetterBiConsumers.put(
				"createdBy",
				(BiConsumer<EmployeeSalary, Long>)EmployeeSalary::setCreatedBy);
			attributeSetterBiConsumers.put(
				"modifiedBy",
				(BiConsumer<EmployeeSalary, Long>)
					EmployeeSalary::setModifiedBy);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<EmployeeSalary, Long>)EmployeeSalary::setGroupId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<EmployeeSalary, Date>)
					EmployeeSalary::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<EmployeeSalary, Date>)
					EmployeeSalary::setModifiedDate);
			attributeSetterBiConsumers.put(
				"salaryId",
				(BiConsumer<EmployeeSalary, Long>)EmployeeSalary::setSalaryId);
			attributeSetterBiConsumers.put(
				"grossSalaryCtcPm",
				(BiConsumer<EmployeeSalary, Double>)
					EmployeeSalary::setGrossSalaryCtcPm);
			attributeSetterBiConsumers.put(
				"grossSalaryCtcPa",
				(BiConsumer<EmployeeSalary, Double>)
					EmployeeSalary::setGrossSalaryCtcPa);
			attributeSetterBiConsumers.put(
				"employeeId",
				(BiConsumer<EmployeeSalary, Long>)
					EmployeeSalary::setEmployeeId);
			attributeSetterBiConsumers.put(
				"status",
				(BiConsumer<EmployeeSalary, Boolean>)EmployeeSalary::setStatus);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getSalaryId() {
		return _salaryId;
	}

	@Override
	public void setSalaryId(long salaryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_salaryId = salaryId;
	}

	@JSON
	@Override
	public double getGrossSalaryCtcPm() {
		return _grossSalaryCtcPm;
	}

	@Override
	public void setGrossSalaryCtcPm(double grossSalaryCtcPm) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_grossSalaryCtcPm = grossSalaryCtcPm;
	}

	@JSON
	@Override
	public double getGrossSalaryCtcPa() {
		return _grossSalaryCtcPa;
	}

	@Override
	public void setGrossSalaryCtcPa(double grossSalaryCtcPa) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_grossSalaryCtcPa = grossSalaryCtcPa;
	}

	@JSON
	@Override
	public long getEmployeeId() {
		return _employeeId;
	}

	@Override
	public void setEmployeeId(long employeeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_employeeId = employeeId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalEmployeeId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("employeeId"));
	}

	@JSON
	@Override
	public boolean getStatus() {
		return _status;
	}

	@JSON
	@Override
	public boolean isStatus() {
		return _status;
	}

	@Override
	public void setStatus(boolean status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public boolean getOriginalStatus() {
		return GetterUtil.getBoolean(
			this.<Boolean>getColumnOriginalValue("status"));
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(EmployeeSalary.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), EmployeeSalary.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public EmployeeSalary toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, EmployeeSalary>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EmployeeSalaryImpl employeeSalaryImpl = new EmployeeSalaryImpl();

		employeeSalaryImpl.setUuid(getUuid());
		employeeSalaryImpl.setCompanyId(getCompanyId());
		employeeSalaryImpl.setCreatedBy(getCreatedBy());
		employeeSalaryImpl.setModifiedBy(getModifiedBy());
		employeeSalaryImpl.setGroupId(getGroupId());
		employeeSalaryImpl.setCreateDate(getCreateDate());
		employeeSalaryImpl.setModifiedDate(getModifiedDate());
		employeeSalaryImpl.setSalaryId(getSalaryId());
		employeeSalaryImpl.setGrossSalaryCtcPm(getGrossSalaryCtcPm());
		employeeSalaryImpl.setGrossSalaryCtcPa(getGrossSalaryCtcPa());
		employeeSalaryImpl.setEmployeeId(getEmployeeId());
		employeeSalaryImpl.setStatus(isStatus());

		employeeSalaryImpl.resetOriginalValues();

		return employeeSalaryImpl;
	}

	@Override
	public EmployeeSalary cloneWithOriginalValues() {
		EmployeeSalaryImpl employeeSalaryImpl = new EmployeeSalaryImpl();

		employeeSalaryImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		employeeSalaryImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		employeeSalaryImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("createdBy"));
		employeeSalaryImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modifiedBy"));
		employeeSalaryImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		employeeSalaryImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		employeeSalaryImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		employeeSalaryImpl.setSalaryId(
			this.<Long>getColumnOriginalValue("salaryId"));
		employeeSalaryImpl.setGrossSalaryCtcPm(
			this.<Double>getColumnOriginalValue("grossSalaryCtcPm"));
		employeeSalaryImpl.setGrossSalaryCtcPa(
			this.<Double>getColumnOriginalValue("grossSalaryCtcPa"));
		employeeSalaryImpl.setEmployeeId(
			this.<Long>getColumnOriginalValue("employeeId"));
		employeeSalaryImpl.setStatus(
			this.<Boolean>getColumnOriginalValue("status"));

		return employeeSalaryImpl;
	}

	@Override
	public int compareTo(EmployeeSalary employeeSalary) {
		long primaryKey = employeeSalary.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof EmployeeSalary)) {
			return false;
		}

		EmployeeSalary employeeSalary = (EmployeeSalary)object;

		long primaryKey = employeeSalary.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<EmployeeSalary> toCacheModel() {
		EmployeeSalaryCacheModel employeeSalaryCacheModel =
			new EmployeeSalaryCacheModel();

		employeeSalaryCacheModel.uuid = getUuid();

		String uuid = employeeSalaryCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			employeeSalaryCacheModel.uuid = null;
		}

		employeeSalaryCacheModel.companyId = getCompanyId();

		employeeSalaryCacheModel.createdBy = getCreatedBy();

		employeeSalaryCacheModel.modifiedBy = getModifiedBy();

		employeeSalaryCacheModel.groupId = getGroupId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			employeeSalaryCacheModel.createDate = createDate.getTime();
		}
		else {
			employeeSalaryCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			employeeSalaryCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			employeeSalaryCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		employeeSalaryCacheModel.salaryId = getSalaryId();

		employeeSalaryCacheModel.grossSalaryCtcPm = getGrossSalaryCtcPm();

		employeeSalaryCacheModel.grossSalaryCtcPa = getGrossSalaryCtcPa();

		employeeSalaryCacheModel.employeeId = getEmployeeId();

		employeeSalaryCacheModel.status = isStatus();

		return employeeSalaryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<EmployeeSalary, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<EmployeeSalary, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EmployeeSalary, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((EmployeeSalary)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, EmployeeSalary>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					EmployeeSalary.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _companyId;
	private long _createdBy;
	private long _modifiedBy;
	private long _groupId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _salaryId;
	private double _grossSalaryCtcPm;
	private double _grossSalaryCtcPa;
	private long _employeeId;
	private boolean _status;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<EmployeeSalary, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((EmployeeSalary)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createdBy", _createdBy);
		_columnOriginalValues.put("modifiedBy", _modifiedBy);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("salaryId", _salaryId);
		_columnOriginalValues.put("grossSalaryCtcPm", _grossSalaryCtcPm);
		_columnOriginalValues.put("grossSalaryCtcPa", _grossSalaryCtcPa);
		_columnOriginalValues.put("employeeId", _employeeId);
		_columnOriginalValues.put("status", _status);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("createdBy", 4L);

		columnBitmasks.put("modifiedBy", 8L);

		columnBitmasks.put("groupId", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("salaryId", 128L);

		columnBitmasks.put("grossSalaryCtcPm", 256L);

		columnBitmasks.put("grossSalaryCtcPa", 512L);

		columnBitmasks.put("employeeId", 1024L);

		columnBitmasks.put("status", 2048L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private EmployeeSalary _escapedModel;

}