/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.model.impl;

import com.ax.hrms.model.EmployeeProbationDetails;
import com.ax.hrms.model.EmployeeProbationDetailsModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the EmployeeProbationDetails service. Represents a row in the &quot;ax_EmployeeProbationDetails&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>EmployeeProbationDetailsModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EmployeeProbationDetailsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmployeeProbationDetailsImpl
 * @generated
 */
@JSON(strict = true)
public class EmployeeProbationDetailsModelImpl
	extends BaseModelImpl<EmployeeProbationDetails>
	implements EmployeeProbationDetailsModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a employee probation details model instance should use the <code>EmployeeProbationDetails</code> interface instead.
	 */
	public static final String TABLE_NAME = "ax_EmployeeProbationDetails";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"companyId", Types.BIGINT},
		{"createdBy", Types.BIGINT}, {"modifiedBy", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"probationDetailId", Types.BIGINT},
		{"probationPeriod", Types.INTEGER},
		{"probationEndDate", Types.TIMESTAMP},
		{"probationStatusId", Types.BIGINT}, {"isExtended", Types.BOOLEAN},
		{"employeeId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("probationDetailId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("probationPeriod", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("probationEndDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("probationStatusId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("isExtended", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("employeeId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ax_EmployeeProbationDetails (uuid_ VARCHAR(75) null,companyId LONG,createdBy LONG,modifiedBy LONG,groupId LONG,createDate DATE null,modifiedDate DATE null,probationDetailId LONG not null primary key,probationPeriod INTEGER,probationEndDate DATE null,probationStatusId LONG,isExtended BOOLEAN,employeeId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table ax_EmployeeProbationDetails";

	public static final String ORDER_BY_JPQL =
		" ORDER BY employeeProbationDetails.probationDetailId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ax_EmployeeProbationDetails.probationDetailId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EMPLOYEEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PROBATIONDETAILID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public EmployeeProbationDetailsModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _probationDetailId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setProbationDetailId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _probationDetailId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return EmployeeProbationDetails.class;
	}

	@Override
	public String getModelClassName() {
		return EmployeeProbationDetails.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<EmployeeProbationDetails, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<EmployeeProbationDetails, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EmployeeProbationDetails, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((EmployeeProbationDetails)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<EmployeeProbationDetails, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<EmployeeProbationDetails, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(EmployeeProbationDetails)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<EmployeeProbationDetails, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<EmployeeProbationDetails, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map
			<String, Function<EmployeeProbationDetails, Object>>
				_attributeGetterFunctions;

		static {
			Map<String, Function<EmployeeProbationDetails, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<EmployeeProbationDetails, Object>>();

			attributeGetterFunctions.put(
				"uuid", EmployeeProbationDetails::getUuid);
			attributeGetterFunctions.put(
				"companyId", EmployeeProbationDetails::getCompanyId);
			attributeGetterFunctions.put(
				"createdBy", EmployeeProbationDetails::getCreatedBy);
			attributeGetterFunctions.put(
				"modifiedBy", EmployeeProbationDetails::getModifiedBy);
			attributeGetterFunctions.put(
				"groupId", EmployeeProbationDetails::getGroupId);
			attributeGetterFunctions.put(
				"createDate", EmployeeProbationDetails::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", EmployeeProbationDetails::getModifiedDate);
			attributeGetterFunctions.put(
				"probationDetailId",
				EmployeeProbationDetails::getProbationDetailId);
			attributeGetterFunctions.put(
				"probationPeriod",
				EmployeeProbationDetails::getProbationPeriod);
			attributeGetterFunctions.put(
				"probationEndDate",
				EmployeeProbationDetails::getProbationEndDate);
			attributeGetterFunctions.put(
				"probationStatusId",
				EmployeeProbationDetails::getProbationStatusId);
			attributeGetterFunctions.put(
				"isExtended", EmployeeProbationDetails::getIsExtended);
			attributeGetterFunctions.put(
				"employeeId", EmployeeProbationDetails::getEmployeeId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<EmployeeProbationDetails, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<EmployeeProbationDetails, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<EmployeeProbationDetails, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<EmployeeProbationDetails, String>)
					EmployeeProbationDetails::setUuid);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<EmployeeProbationDetails, Long>)
					EmployeeProbationDetails::setCompanyId);
			attributeSetterBiConsumers.put(
				"createdBy",
				(BiConsumer<EmployeeProbationDetails, Long>)
					EmployeeProbationDetails::setCreatedBy);
			attributeSetterBiConsumers.put(
				"modifiedBy",
				(BiConsumer<EmployeeProbationDetails, Long>)
					EmployeeProbationDetails::setModifiedBy);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<EmployeeProbationDetails, Long>)
					EmployeeProbationDetails::setGroupId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<EmployeeProbationDetails, Date>)
					EmployeeProbationDetails::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<EmployeeProbationDetails, Date>)
					EmployeeProbationDetails::setModifiedDate);
			attributeSetterBiConsumers.put(
				"probationDetailId",
				(BiConsumer<EmployeeProbationDetails, Long>)
					EmployeeProbationDetails::setProbationDetailId);
			attributeSetterBiConsumers.put(
				"probationPeriod",
				(BiConsumer<EmployeeProbationDetails, Integer>)
					EmployeeProbationDetails::setProbationPeriod);
			attributeSetterBiConsumers.put(
				"probationEndDate",
				(BiConsumer<EmployeeProbationDetails, Date>)
					EmployeeProbationDetails::setProbationEndDate);
			attributeSetterBiConsumers.put(
				"probationStatusId",
				(BiConsumer<EmployeeProbationDetails, Long>)
					EmployeeProbationDetails::setProbationStatusId);
			attributeSetterBiConsumers.put(
				"isExtended",
				(BiConsumer<EmployeeProbationDetails, Boolean>)
					EmployeeProbationDetails::setIsExtended);
			attributeSetterBiConsumers.put(
				"employeeId",
				(BiConsumer<EmployeeProbationDetails, Long>)
					EmployeeProbationDetails::setEmployeeId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getProbationDetailId() {
		return _probationDetailId;
	}

	@Override
	public void setProbationDetailId(long probationDetailId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_probationDetailId = probationDetailId;
	}

	@JSON
	@Override
	public int getProbationPeriod() {
		return _probationPeriod;
	}

	@Override
	public void setProbationPeriod(int probationPeriod) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_probationPeriod = probationPeriod;
	}

	@JSON
	@Override
	public Date getProbationEndDate() {
		return _probationEndDate;
	}

	@Override
	public void setProbationEndDate(Date probationEndDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_probationEndDate = probationEndDate;
	}

	@JSON
	@Override
	public long getProbationStatusId() {
		return _probationStatusId;
	}

	@Override
	public void setProbationStatusId(long probationStatusId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_probationStatusId = probationStatusId;
	}

	@JSON
	@Override
	public Boolean getIsExtended() {
		return _isExtended;
	}

	@Override
	public void setIsExtended(Boolean isExtended) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_isExtended = isExtended;
	}

	@JSON
	@Override
	public long getEmployeeId() {
		return _employeeId;
	}

	@Override
	public void setEmployeeId(long employeeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_employeeId = employeeId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalEmployeeId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("employeeId"));
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(
				EmployeeProbationDetails.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), EmployeeProbationDetails.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public EmployeeProbationDetails toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, EmployeeProbationDetails>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EmployeeProbationDetailsImpl employeeProbationDetailsImpl =
			new EmployeeProbationDetailsImpl();

		employeeProbationDetailsImpl.setUuid(getUuid());
		employeeProbationDetailsImpl.setCompanyId(getCompanyId());
		employeeProbationDetailsImpl.setCreatedBy(getCreatedBy());
		employeeProbationDetailsImpl.setModifiedBy(getModifiedBy());
		employeeProbationDetailsImpl.setGroupId(getGroupId());
		employeeProbationDetailsImpl.setCreateDate(getCreateDate());
		employeeProbationDetailsImpl.setModifiedDate(getModifiedDate());
		employeeProbationDetailsImpl.setProbationDetailId(
			getProbationDetailId());
		employeeProbationDetailsImpl.setProbationPeriod(getProbationPeriod());
		employeeProbationDetailsImpl.setProbationEndDate(getProbationEndDate());
		employeeProbationDetailsImpl.setProbationStatusId(
			getProbationStatusId());
		employeeProbationDetailsImpl.setIsExtended(getIsExtended());
		employeeProbationDetailsImpl.setEmployeeId(getEmployeeId());

		employeeProbationDetailsImpl.resetOriginalValues();

		return employeeProbationDetailsImpl;
	}

	@Override
	public EmployeeProbationDetails cloneWithOriginalValues() {
		EmployeeProbationDetailsImpl employeeProbationDetailsImpl =
			new EmployeeProbationDetailsImpl();

		employeeProbationDetailsImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		employeeProbationDetailsImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		employeeProbationDetailsImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("createdBy"));
		employeeProbationDetailsImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modifiedBy"));
		employeeProbationDetailsImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		employeeProbationDetailsImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		employeeProbationDetailsImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		employeeProbationDetailsImpl.setProbationDetailId(
			this.<Long>getColumnOriginalValue("probationDetailId"));
		employeeProbationDetailsImpl.setProbationPeriod(
			this.<Integer>getColumnOriginalValue("probationPeriod"));
		employeeProbationDetailsImpl.setProbationEndDate(
			this.<Date>getColumnOriginalValue("probationEndDate"));
		employeeProbationDetailsImpl.setProbationStatusId(
			this.<Long>getColumnOriginalValue("probationStatusId"));
		employeeProbationDetailsImpl.setIsExtended(
			this.<Boolean>getColumnOriginalValue("isExtended"));
		employeeProbationDetailsImpl.setEmployeeId(
			this.<Long>getColumnOriginalValue("employeeId"));

		return employeeProbationDetailsImpl;
	}

	@Override
	public int compareTo(EmployeeProbationDetails employeeProbationDetails) {
		long primaryKey = employeeProbationDetails.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof EmployeeProbationDetails)) {
			return false;
		}

		EmployeeProbationDetails employeeProbationDetails =
			(EmployeeProbationDetails)object;

		long primaryKey = employeeProbationDetails.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<EmployeeProbationDetails> toCacheModel() {
		EmployeeProbationDetailsCacheModel employeeProbationDetailsCacheModel =
			new EmployeeProbationDetailsCacheModel();

		employeeProbationDetailsCacheModel.uuid = getUuid();

		String uuid = employeeProbationDetailsCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			employeeProbationDetailsCacheModel.uuid = null;
		}

		employeeProbationDetailsCacheModel.companyId = getCompanyId();

		employeeProbationDetailsCacheModel.createdBy = getCreatedBy();

		employeeProbationDetailsCacheModel.modifiedBy = getModifiedBy();

		employeeProbationDetailsCacheModel.groupId = getGroupId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			employeeProbationDetailsCacheModel.createDate =
				createDate.getTime();
		}
		else {
			employeeProbationDetailsCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			employeeProbationDetailsCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			employeeProbationDetailsCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		employeeProbationDetailsCacheModel.probationDetailId =
			getProbationDetailId();

		employeeProbationDetailsCacheModel.probationPeriod =
			getProbationPeriod();

		Date probationEndDate = getProbationEndDate();

		if (probationEndDate != null) {
			employeeProbationDetailsCacheModel.probationEndDate =
				probationEndDate.getTime();
		}
		else {
			employeeProbationDetailsCacheModel.probationEndDate =
				Long.MIN_VALUE;
		}

		employeeProbationDetailsCacheModel.probationStatusId =
			getProbationStatusId();

		Boolean isExtended = getIsExtended();

		if (isExtended != null) {
			employeeProbationDetailsCacheModel.isExtended = isExtended;
		}

		employeeProbationDetailsCacheModel.employeeId = getEmployeeId();

		return employeeProbationDetailsCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<EmployeeProbationDetails, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<EmployeeProbationDetails, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EmployeeProbationDetails, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(EmployeeProbationDetails)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, EmployeeProbationDetails>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						EmployeeProbationDetails.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _companyId;
	private long _createdBy;
	private long _modifiedBy;
	private long _groupId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _probationDetailId;
	private int _probationPeriod;
	private Date _probationEndDate;
	private long _probationStatusId;
	private Boolean _isExtended;
	private long _employeeId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<EmployeeProbationDetails, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((EmployeeProbationDetails)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createdBy", _createdBy);
		_columnOriginalValues.put("modifiedBy", _modifiedBy);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("probationDetailId", _probationDetailId);
		_columnOriginalValues.put("probationPeriod", _probationPeriod);
		_columnOriginalValues.put("probationEndDate", _probationEndDate);
		_columnOriginalValues.put("probationStatusId", _probationStatusId);
		_columnOriginalValues.put("isExtended", _isExtended);
		_columnOriginalValues.put("employeeId", _employeeId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("createdBy", 4L);

		columnBitmasks.put("modifiedBy", 8L);

		columnBitmasks.put("groupId", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("probationDetailId", 128L);

		columnBitmasks.put("probationPeriod", 256L);

		columnBitmasks.put("probationEndDate", 512L);

		columnBitmasks.put("probationStatusId", 1024L);

		columnBitmasks.put("isExtended", 2048L);

		columnBitmasks.put("employeeId", 4096L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private EmployeeProbationDetails _escapedModel;

}