/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.model.impl;

import com.ax.hrms.model.EmployeeProbationDetails;
import com.ax.hrms.service.EmployeeProbationDetailsLocalServiceUtil;

/**
 * The extended model base implementation for the EmployeeProbationDetails service. Represents a row in the &quot;ax_EmployeeProbationDetails&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EmployeeProbationDetailsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmployeeProbationDetailsImpl
 * @see EmployeeProbationDetails
 * @generated
 */
public abstract class EmployeeProbationDetailsBaseImpl
	extends EmployeeProbationDetailsModelImpl
	implements EmployeeProbationDetails {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a employee probation details model instance should use the <code>EmployeeProbationDetails</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			EmployeeProbationDetailsLocalServiceUtil.
				addEmployeeProbationDetails(this);
		}
		else {
			EmployeeProbationDetailsLocalServiceUtil.
				updateEmployeeProbationDetails(this);
		}
	}

}