/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.model.impl;

import com.ax.hrms.model.EmployeeExperience;
import com.ax.hrms.service.EmployeeExperienceLocalServiceUtil;

/**
 * The extended model base implementation for the EmployeeExperience service. Represents a row in the &quot;ax_EmployeeExperience&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EmployeeExperienceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmployeeExperienceImpl
 * @see EmployeeExperience
 * @generated
 */
public abstract class EmployeeExperienceBaseImpl
	extends EmployeeExperienceModelImpl implements EmployeeExperience {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a employee experience model instance should use the <code>EmployeeExperience</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			EmployeeExperienceLocalServiceUtil.addEmployeeExperience(this);
		}
		else {
			EmployeeExperienceLocalServiceUtil.updateEmployeeExperience(this);
		}
	}

}