/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.model.impl;

import com.ax.hrms.model.EmployeeSalary;
import com.ax.hrms.service.EmployeeSalaryLocalServiceUtil;

/**
 * The extended model base implementation for the EmployeeSalary service. Represents a row in the &quot;ax_EmployeeSalary&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EmployeeSalaryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmployeeSalaryImpl
 * @see EmployeeSalary
 * @generated
 */
public abstract class EmployeeSalaryBaseImpl
	extends EmployeeSalaryModelImpl implements EmployeeSalary {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a employee salary model instance should use the <code>EmployeeSalary</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			EmployeeSalaryLocalServiceUtil.addEmployeeSalary(this);
		}
		else {
			EmployeeSalaryLocalServiceUtil.updateEmployeeSalary(this);
		}
	}

}