/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.model.impl;

import com.ax.hrms.model.EmployeeWish;
import com.ax.hrms.service.EmployeeWishLocalServiceUtil;

/**
 * The extended model base implementation for the EmployeeWish service. Represents a row in the &quot;ax_EmployeeWish&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EmployeeWishImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmployeeWishImpl
 * @see EmployeeWish
 * @generated
 */
public abstract class EmployeeWishBaseImpl
	extends EmployeeWishModelImpl implements EmployeeWish {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a employee wish model instance should use the <code>EmployeeWish</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			EmployeeWishLocalServiceUtil.addEmployeeWish(this);
		}
		else {
			EmployeeWishLocalServiceUtil.updateEmployeeWish(this);
		}
	}

}