/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.model.impl;

import com.ax.hrms.model.EmployeeOffBoarding;
import com.ax.hrms.model.EmployeeOffBoardingModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the EmployeeOffBoarding service. Represents a row in the &quot;ax_EmployeeOffBoarding&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>EmployeeOffBoardingModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EmployeeOffBoardingImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmployeeOffBoardingImpl
 * @generated
 */
@JSON(strict = true)
public class EmployeeOffBoardingModelImpl
	extends BaseModelImpl<EmployeeOffBoarding>
	implements EmployeeOffBoardingModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a employee off boarding model instance should use the <code>EmployeeOffBoarding</code> interface instead.
	 */
	public static final String TABLE_NAME = "ax_EmployeeOffBoarding";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"companyId", Types.BIGINT},
		{"createdBy", Types.BIGINT}, {"modifiedBy", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP},
		{"employeeOffBoardingId", Types.BIGINT}, {"kt", Types.BOOLEAN},
		{"assets", Types.BOOLEAN}, {"nda", Types.BOOLEAN},
		{"mailAndBiometrics", Types.BOOLEAN}, {"employeeId", Types.BIGINT},
		{"experienceLetterId", Types.BIGINT}, {"fullAndFinal", Types.VARCHAR},
		{"relievingLetterId", Types.BIGINT}, {"status", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("employeeOffBoardingId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("kt", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("assets", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("nda", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("mailAndBiometrics", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("employeeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("experienceLetterId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("fullAndFinal", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("relievingLetterId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("status", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ax_EmployeeOffBoarding (uuid_ VARCHAR(75) null,companyId LONG,createdBy LONG,modifiedBy LONG,groupId LONG,createDate DATE null,modifiedDate DATE null,employeeOffBoardingId LONG not null primary key,kt BOOLEAN,assets BOOLEAN,nda BOOLEAN,mailAndBiometrics BOOLEAN,employeeId LONG,experienceLetterId LONG,fullAndFinal VARCHAR(2000) null,relievingLetterId LONG,status BOOLEAN)";

	public static final String TABLE_SQL_DROP =
		"drop table ax_EmployeeOffBoarding";

	public static final String ORDER_BY_JPQL =
		" ORDER BY employeeOffBoarding.employeeOffBoardingId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ax_EmployeeOffBoarding.employeeOffBoardingId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EMPLOYEEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EMPLOYEEOFFBOARDINGID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public EmployeeOffBoardingModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _employeeOffBoardingId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEmployeeOffBoardingId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _employeeOffBoardingId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return EmployeeOffBoarding.class;
	}

	@Override
	public String getModelClassName() {
		return EmployeeOffBoarding.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<EmployeeOffBoarding, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<EmployeeOffBoarding, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EmployeeOffBoarding, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((EmployeeOffBoarding)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<EmployeeOffBoarding, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<EmployeeOffBoarding, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(EmployeeOffBoarding)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<EmployeeOffBoarding, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<EmployeeOffBoarding, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<EmployeeOffBoarding, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<EmployeeOffBoarding, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<EmployeeOffBoarding, Object>>();

			attributeGetterFunctions.put("uuid", EmployeeOffBoarding::getUuid);
			attributeGetterFunctions.put(
				"companyId", EmployeeOffBoarding::getCompanyId);
			attributeGetterFunctions.put(
				"createdBy", EmployeeOffBoarding::getCreatedBy);
			attributeGetterFunctions.put(
				"modifiedBy", EmployeeOffBoarding::getModifiedBy);
			attributeGetterFunctions.put(
				"groupId", EmployeeOffBoarding::getGroupId);
			attributeGetterFunctions.put(
				"createDate", EmployeeOffBoarding::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", EmployeeOffBoarding::getModifiedDate);
			attributeGetterFunctions.put(
				"employeeOffBoardingId",
				EmployeeOffBoarding::getEmployeeOffBoardingId);
			attributeGetterFunctions.put("kt", EmployeeOffBoarding::getKt);
			attributeGetterFunctions.put(
				"assets", EmployeeOffBoarding::getAssets);
			attributeGetterFunctions.put("nda", EmployeeOffBoarding::getNda);
			attributeGetterFunctions.put(
				"mailAndBiometrics", EmployeeOffBoarding::getMailAndBiometrics);
			attributeGetterFunctions.put(
				"employeeId", EmployeeOffBoarding::getEmployeeId);
			attributeGetterFunctions.put(
				"experienceLetterId",
				EmployeeOffBoarding::getExperienceLetterId);
			attributeGetterFunctions.put(
				"fullAndFinal", EmployeeOffBoarding::getFullAndFinal);
			attributeGetterFunctions.put(
				"relievingLetterId", EmployeeOffBoarding::getRelievingLetterId);
			attributeGetterFunctions.put(
				"status", EmployeeOffBoarding::getStatus);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<EmployeeOffBoarding, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<EmployeeOffBoarding, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<EmployeeOffBoarding, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<EmployeeOffBoarding, String>)
					EmployeeOffBoarding::setUuid);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<EmployeeOffBoarding, Long>)
					EmployeeOffBoarding::setCompanyId);
			attributeSetterBiConsumers.put(
				"createdBy",
				(BiConsumer<EmployeeOffBoarding, Long>)
					EmployeeOffBoarding::setCreatedBy);
			attributeSetterBiConsumers.put(
				"modifiedBy",
				(BiConsumer<EmployeeOffBoarding, Long>)
					EmployeeOffBoarding::setModifiedBy);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<EmployeeOffBoarding, Long>)
					EmployeeOffBoarding::setGroupId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<EmployeeOffBoarding, Date>)
					EmployeeOffBoarding::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<EmployeeOffBoarding, Date>)
					EmployeeOffBoarding::setModifiedDate);
			attributeSetterBiConsumers.put(
				"employeeOffBoardingId",
				(BiConsumer<EmployeeOffBoarding, Long>)
					EmployeeOffBoarding::setEmployeeOffBoardingId);
			attributeSetterBiConsumers.put(
				"kt",
				(BiConsumer<EmployeeOffBoarding, Boolean>)
					EmployeeOffBoarding::setKt);
			attributeSetterBiConsumers.put(
				"assets",
				(BiConsumer<EmployeeOffBoarding, Boolean>)
					EmployeeOffBoarding::setAssets);
			attributeSetterBiConsumers.put(
				"nda",
				(BiConsumer<EmployeeOffBoarding, Boolean>)
					EmployeeOffBoarding::setNda);
			attributeSetterBiConsumers.put(
				"mailAndBiometrics",
				(BiConsumer<EmployeeOffBoarding, Boolean>)
					EmployeeOffBoarding::setMailAndBiometrics);
			attributeSetterBiConsumers.put(
				"employeeId",
				(BiConsumer<EmployeeOffBoarding, Long>)
					EmployeeOffBoarding::setEmployeeId);
			attributeSetterBiConsumers.put(
				"experienceLetterId",
				(BiConsumer<EmployeeOffBoarding, Long>)
					EmployeeOffBoarding::setExperienceLetterId);
			attributeSetterBiConsumers.put(
				"fullAndFinal",
				(BiConsumer<EmployeeOffBoarding, String>)
					EmployeeOffBoarding::setFullAndFinal);
			attributeSetterBiConsumers.put(
				"relievingLetterId",
				(BiConsumer<EmployeeOffBoarding, Long>)
					EmployeeOffBoarding::setRelievingLetterId);
			attributeSetterBiConsumers.put(
				"status",
				(BiConsumer<EmployeeOffBoarding, Boolean>)
					EmployeeOffBoarding::setStatus);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getEmployeeOffBoardingId() {
		return _employeeOffBoardingId;
	}

	@Override
	public void setEmployeeOffBoardingId(long employeeOffBoardingId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_employeeOffBoardingId = employeeOffBoardingId;
	}

	@JSON
	@Override
	public boolean getKt() {
		return _kt;
	}

	@JSON
	@Override
	public boolean isKt() {
		return _kt;
	}

	@Override
	public void setKt(boolean kt) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_kt = kt;
	}

	@JSON
	@Override
	public boolean getAssets() {
		return _assets;
	}

	@JSON
	@Override
	public boolean isAssets() {
		return _assets;
	}

	@Override
	public void setAssets(boolean assets) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_assets = assets;
	}

	@JSON
	@Override
	public boolean getNda() {
		return _nda;
	}

	@JSON
	@Override
	public boolean isNda() {
		return _nda;
	}

	@Override
	public void setNda(boolean nda) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nda = nda;
	}

	@JSON
	@Override
	public boolean getMailAndBiometrics() {
		return _mailAndBiometrics;
	}

	@JSON
	@Override
	public boolean isMailAndBiometrics() {
		return _mailAndBiometrics;
	}

	@Override
	public void setMailAndBiometrics(boolean mailAndBiometrics) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mailAndBiometrics = mailAndBiometrics;
	}

	@JSON
	@Override
	public long getEmployeeId() {
		return _employeeId;
	}

	@Override
	public void setEmployeeId(long employeeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_employeeId = employeeId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalEmployeeId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("employeeId"));
	}

	@JSON
	@Override
	public long getExperienceLetterId() {
		return _experienceLetterId;
	}

	@Override
	public void setExperienceLetterId(long experienceLetterId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_experienceLetterId = experienceLetterId;
	}

	@JSON
	@Override
	public String getFullAndFinal() {
		if (_fullAndFinal == null) {
			return "";
		}
		else {
			return _fullAndFinal;
		}
	}

	@Override
	public void setFullAndFinal(String fullAndFinal) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fullAndFinal = fullAndFinal;
	}

	@JSON
	@Override
	public long getRelievingLetterId() {
		return _relievingLetterId;
	}

	@Override
	public void setRelievingLetterId(long relievingLetterId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_relievingLetterId = relievingLetterId;
	}

	@JSON
	@Override
	public boolean getStatus() {
		return _status;
	}

	@JSON
	@Override
	public boolean isStatus() {
		return _status;
	}

	@Override
	public void setStatus(boolean status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(EmployeeOffBoarding.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), EmployeeOffBoarding.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public EmployeeOffBoarding toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, EmployeeOffBoarding>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EmployeeOffBoardingImpl employeeOffBoardingImpl =
			new EmployeeOffBoardingImpl();

		employeeOffBoardingImpl.setUuid(getUuid());
		employeeOffBoardingImpl.setCompanyId(getCompanyId());
		employeeOffBoardingImpl.setCreatedBy(getCreatedBy());
		employeeOffBoardingImpl.setModifiedBy(getModifiedBy());
		employeeOffBoardingImpl.setGroupId(getGroupId());
		employeeOffBoardingImpl.setCreateDate(getCreateDate());
		employeeOffBoardingImpl.setModifiedDate(getModifiedDate());
		employeeOffBoardingImpl.setEmployeeOffBoardingId(
			getEmployeeOffBoardingId());
		employeeOffBoardingImpl.setKt(isKt());
		employeeOffBoardingImpl.setAssets(isAssets());
		employeeOffBoardingImpl.setNda(isNda());
		employeeOffBoardingImpl.setMailAndBiometrics(isMailAndBiometrics());
		employeeOffBoardingImpl.setEmployeeId(getEmployeeId());
		employeeOffBoardingImpl.setExperienceLetterId(getExperienceLetterId());
		employeeOffBoardingImpl.setFullAndFinal(getFullAndFinal());
		employeeOffBoardingImpl.setRelievingLetterId(getRelievingLetterId());
		employeeOffBoardingImpl.setStatus(isStatus());

		employeeOffBoardingImpl.resetOriginalValues();

		return employeeOffBoardingImpl;
	}

	@Override
	public EmployeeOffBoarding cloneWithOriginalValues() {
		EmployeeOffBoardingImpl employeeOffBoardingImpl =
			new EmployeeOffBoardingImpl();

		employeeOffBoardingImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		employeeOffBoardingImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		employeeOffBoardingImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("createdBy"));
		employeeOffBoardingImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modifiedBy"));
		employeeOffBoardingImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		employeeOffBoardingImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		employeeOffBoardingImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		employeeOffBoardingImpl.setEmployeeOffBoardingId(
			this.<Long>getColumnOriginalValue("employeeOffBoardingId"));
		employeeOffBoardingImpl.setKt(
			this.<Boolean>getColumnOriginalValue("kt"));
		employeeOffBoardingImpl.setAssets(
			this.<Boolean>getColumnOriginalValue("assets"));
		employeeOffBoardingImpl.setNda(
			this.<Boolean>getColumnOriginalValue("nda"));
		employeeOffBoardingImpl.setMailAndBiometrics(
			this.<Boolean>getColumnOriginalValue("mailAndBiometrics"));
		employeeOffBoardingImpl.setEmployeeId(
			this.<Long>getColumnOriginalValue("employeeId"));
		employeeOffBoardingImpl.setExperienceLetterId(
			this.<Long>getColumnOriginalValue("experienceLetterId"));
		employeeOffBoardingImpl.setFullAndFinal(
			this.<String>getColumnOriginalValue("fullAndFinal"));
		employeeOffBoardingImpl.setRelievingLetterId(
			this.<Long>getColumnOriginalValue("relievingLetterId"));
		employeeOffBoardingImpl.setStatus(
			this.<Boolean>getColumnOriginalValue("status"));

		return employeeOffBoardingImpl;
	}

	@Override
	public int compareTo(EmployeeOffBoarding employeeOffBoarding) {
		long primaryKey = employeeOffBoarding.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof EmployeeOffBoarding)) {
			return false;
		}

		EmployeeOffBoarding employeeOffBoarding = (EmployeeOffBoarding)object;

		long primaryKey = employeeOffBoarding.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<EmployeeOffBoarding> toCacheModel() {
		EmployeeOffBoardingCacheModel employeeOffBoardingCacheModel =
			new EmployeeOffBoardingCacheModel();

		employeeOffBoardingCacheModel.uuid = getUuid();

		String uuid = employeeOffBoardingCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			employeeOffBoardingCacheModel.uuid = null;
		}

		employeeOffBoardingCacheModel.companyId = getCompanyId();

		employeeOffBoardingCacheModel.createdBy = getCreatedBy();

		employeeOffBoardingCacheModel.modifiedBy = getModifiedBy();

		employeeOffBoardingCacheModel.groupId = getGroupId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			employeeOffBoardingCacheModel.createDate = createDate.getTime();
		}
		else {
			employeeOffBoardingCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			employeeOffBoardingCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			employeeOffBoardingCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		employeeOffBoardingCacheModel.employeeOffBoardingId =
			getEmployeeOffBoardingId();

		employeeOffBoardingCacheModel.kt = isKt();

		employeeOffBoardingCacheModel.assets = isAssets();

		employeeOffBoardingCacheModel.nda = isNda();

		employeeOffBoardingCacheModel.mailAndBiometrics = isMailAndBiometrics();

		employeeOffBoardingCacheModel.employeeId = getEmployeeId();

		employeeOffBoardingCacheModel.experienceLetterId =
			getExperienceLetterId();

		employeeOffBoardingCacheModel.fullAndFinal = getFullAndFinal();

		String fullAndFinal = employeeOffBoardingCacheModel.fullAndFinal;

		if ((fullAndFinal != null) && (fullAndFinal.length() == 0)) {
			employeeOffBoardingCacheModel.fullAndFinal = null;
		}

		employeeOffBoardingCacheModel.relievingLetterId =
			getRelievingLetterId();

		employeeOffBoardingCacheModel.status = isStatus();

		return employeeOffBoardingCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<EmployeeOffBoarding, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<EmployeeOffBoarding, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EmployeeOffBoarding, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(EmployeeOffBoarding)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, EmployeeOffBoarding>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					EmployeeOffBoarding.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _companyId;
	private long _createdBy;
	private long _modifiedBy;
	private long _groupId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _employeeOffBoardingId;
	private boolean _kt;
	private boolean _assets;
	private boolean _nda;
	private boolean _mailAndBiometrics;
	private long _employeeId;
	private long _experienceLetterId;
	private String _fullAndFinal;
	private long _relievingLetterId;
	private boolean _status;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<EmployeeOffBoarding, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((EmployeeOffBoarding)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createdBy", _createdBy);
		_columnOriginalValues.put("modifiedBy", _modifiedBy);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put(
			"employeeOffBoardingId", _employeeOffBoardingId);
		_columnOriginalValues.put("kt", _kt);
		_columnOriginalValues.put("assets", _assets);
		_columnOriginalValues.put("nda", _nda);
		_columnOriginalValues.put("mailAndBiometrics", _mailAndBiometrics);
		_columnOriginalValues.put("employeeId", _employeeId);
		_columnOriginalValues.put("experienceLetterId", _experienceLetterId);
		_columnOriginalValues.put("fullAndFinal", _fullAndFinal);
		_columnOriginalValues.put("relievingLetterId", _relievingLetterId);
		_columnOriginalValues.put("status", _status);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("createdBy", 4L);

		columnBitmasks.put("modifiedBy", 8L);

		columnBitmasks.put("groupId", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("employeeOffBoardingId", 128L);

		columnBitmasks.put("kt", 256L);

		columnBitmasks.put("assets", 512L);

		columnBitmasks.put("nda", 1024L);

		columnBitmasks.put("mailAndBiometrics", 2048L);

		columnBitmasks.put("employeeId", 4096L);

		columnBitmasks.put("experienceLetterId", 8192L);

		columnBitmasks.put("fullAndFinal", 16384L);

		columnBitmasks.put("relievingLetterId", 32768L);

		columnBitmasks.put("status", 65536L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private EmployeeOffBoarding _escapedModel;

}