/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.model.impl;

import com.ax.hrms.model.ExtendedProbationDetails;
import com.ax.hrms.model.ExtendedProbationDetailsModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ExtendedProbationDetails service. Represents a row in the &quot;ax_ExtendedProbationDetails&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ExtendedProbationDetailsModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ExtendedProbationDetailsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ExtendedProbationDetailsImpl
 * @generated
 */
@JSON(strict = true)
public class ExtendedProbationDetailsModelImpl
	extends BaseModelImpl<ExtendedProbationDetails>
	implements ExtendedProbationDetailsModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a extended probation details model instance should use the <code>ExtendedProbationDetails</code> interface instead.
	 */
	public static final String TABLE_NAME = "ax_ExtendedProbationDetails";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"companyId", Types.BIGINT},
		{"createdBy", Types.BIGINT}, {"modifiedBy", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP},
		{"extendedProbationDetailsId", Types.BIGINT},
		{"probationDetailId", Types.BIGINT}, {"extendDate", Types.TIMESTAMP},
		{"evalutionReview", Types.VARCHAR},
		{"extendedProbationPeriod", Types.INTEGER},
		{"extendedProbationEndDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("extendedProbationDetailsId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("probationDetailId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("extendDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("evalutionReview", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("extendedProbationPeriod", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("extendedProbationEndDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ax_ExtendedProbationDetails (uuid_ VARCHAR(75) null,companyId LONG,createdBy LONG,modifiedBy LONG,groupId LONG,createDate DATE null,modifiedDate DATE null,extendedProbationDetailsId LONG not null primary key,probationDetailId LONG,extendDate DATE null,evalutionReview VARCHAR(500) null,extendedProbationPeriod INTEGER,extendedProbationEndDate DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table ax_ExtendedProbationDetails";

	public static final String ORDER_BY_JPQL =
		" ORDER BY extendedProbationDetails.extendedProbationDetailsId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ax_ExtendedProbationDetails.extendedProbationDetailsId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EXTENDEDPROBATIONDETAILSID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ExtendedProbationDetailsModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _extendedProbationDetailsId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setExtendedProbationDetailsId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _extendedProbationDetailsId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ExtendedProbationDetails.class;
	}

	@Override
	public String getModelClassName() {
		return ExtendedProbationDetails.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ExtendedProbationDetails, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ExtendedProbationDetails, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ExtendedProbationDetails, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ExtendedProbationDetails)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ExtendedProbationDetails, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ExtendedProbationDetails, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ExtendedProbationDetails)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ExtendedProbationDetails, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ExtendedProbationDetails, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map
			<String, Function<ExtendedProbationDetails, Object>>
				_attributeGetterFunctions;

		static {
			Map<String, Function<ExtendedProbationDetails, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<ExtendedProbationDetails, Object>>();

			attributeGetterFunctions.put(
				"uuid", ExtendedProbationDetails::getUuid);
			attributeGetterFunctions.put(
				"companyId", ExtendedProbationDetails::getCompanyId);
			attributeGetterFunctions.put(
				"createdBy", ExtendedProbationDetails::getCreatedBy);
			attributeGetterFunctions.put(
				"modifiedBy", ExtendedProbationDetails::getModifiedBy);
			attributeGetterFunctions.put(
				"groupId", ExtendedProbationDetails::getGroupId);
			attributeGetterFunctions.put(
				"createDate", ExtendedProbationDetails::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", ExtendedProbationDetails::getModifiedDate);
			attributeGetterFunctions.put(
				"extendedProbationDetailsId",
				ExtendedProbationDetails::getExtendedProbationDetailsId);
			attributeGetterFunctions.put(
				"probationDetailId",
				ExtendedProbationDetails::getProbationDetailId);
			attributeGetterFunctions.put(
				"extendDate", ExtendedProbationDetails::getExtendDate);
			attributeGetterFunctions.put(
				"evalutionReview",
				ExtendedProbationDetails::getEvalutionReview);
			attributeGetterFunctions.put(
				"extendedProbationPeriod",
				ExtendedProbationDetails::getExtendedProbationPeriod);
			attributeGetterFunctions.put(
				"extendedProbationEndDate",
				ExtendedProbationDetails::getExtendedProbationEndDate);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<ExtendedProbationDetails, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<ExtendedProbationDetails, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<ExtendedProbationDetails, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<ExtendedProbationDetails, String>)
					ExtendedProbationDetails::setUuid);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<ExtendedProbationDetails, Long>)
					ExtendedProbationDetails::setCompanyId);
			attributeSetterBiConsumers.put(
				"createdBy",
				(BiConsumer<ExtendedProbationDetails, Long>)
					ExtendedProbationDetails::setCreatedBy);
			attributeSetterBiConsumers.put(
				"modifiedBy",
				(BiConsumer<ExtendedProbationDetails, Long>)
					ExtendedProbationDetails::setModifiedBy);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<ExtendedProbationDetails, Long>)
					ExtendedProbationDetails::setGroupId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<ExtendedProbationDetails, Date>)
					ExtendedProbationDetails::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<ExtendedProbationDetails, Date>)
					ExtendedProbationDetails::setModifiedDate);
			attributeSetterBiConsumers.put(
				"extendedProbationDetailsId",
				(BiConsumer<ExtendedProbationDetails, Long>)
					ExtendedProbationDetails::setExtendedProbationDetailsId);
			attributeSetterBiConsumers.put(
				"probationDetailId",
				(BiConsumer<ExtendedProbationDetails, Long>)
					ExtendedProbationDetails::setProbationDetailId);
			attributeSetterBiConsumers.put(
				"extendDate",
				(BiConsumer<ExtendedProbationDetails, Date>)
					ExtendedProbationDetails::setExtendDate);
			attributeSetterBiConsumers.put(
				"evalutionReview",
				(BiConsumer<ExtendedProbationDetails, String>)
					ExtendedProbationDetails::setEvalutionReview);
			attributeSetterBiConsumers.put(
				"extendedProbationPeriod",
				(BiConsumer<ExtendedProbationDetails, Integer>)
					ExtendedProbationDetails::setExtendedProbationPeriod);
			attributeSetterBiConsumers.put(
				"extendedProbationEndDate",
				(BiConsumer<ExtendedProbationDetails, Date>)
					ExtendedProbationDetails::setExtendedProbationEndDate);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getExtendedProbationDetailsId() {
		return _extendedProbationDetailsId;
	}

	@Override
	public void setExtendedProbationDetailsId(long extendedProbationDetailsId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_extendedProbationDetailsId = extendedProbationDetailsId;
	}

	@JSON
	@Override
	public long getProbationDetailId() {
		return _probationDetailId;
	}

	@Override
	public void setProbationDetailId(long probationDetailId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_probationDetailId = probationDetailId;
	}

	@JSON
	@Override
	public Date getExtendDate() {
		return _extendDate;
	}

	@Override
	public void setExtendDate(Date extendDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_extendDate = extendDate;
	}

	@JSON
	@Override
	public String getEvalutionReview() {
		if (_evalutionReview == null) {
			return "";
		}
		else {
			return _evalutionReview;
		}
	}

	@Override
	public void setEvalutionReview(String evalutionReview) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_evalutionReview = evalutionReview;
	}

	@JSON
	@Override
	public int getExtendedProbationPeriod() {
		return _extendedProbationPeriod;
	}

	@Override
	public void setExtendedProbationPeriod(int extendedProbationPeriod) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_extendedProbationPeriod = extendedProbationPeriod;
	}

	@JSON
	@Override
	public Date getExtendedProbationEndDate() {
		return _extendedProbationEndDate;
	}

	@Override
	public void setExtendedProbationEndDate(Date extendedProbationEndDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_extendedProbationEndDate = extendedProbationEndDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(
				ExtendedProbationDetails.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), ExtendedProbationDetails.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ExtendedProbationDetails toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ExtendedProbationDetails>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ExtendedProbationDetailsImpl extendedProbationDetailsImpl =
			new ExtendedProbationDetailsImpl();

		extendedProbationDetailsImpl.setUuid(getUuid());
		extendedProbationDetailsImpl.setCompanyId(getCompanyId());
		extendedProbationDetailsImpl.setCreatedBy(getCreatedBy());
		extendedProbationDetailsImpl.setModifiedBy(getModifiedBy());
		extendedProbationDetailsImpl.setGroupId(getGroupId());
		extendedProbationDetailsImpl.setCreateDate(getCreateDate());
		extendedProbationDetailsImpl.setModifiedDate(getModifiedDate());
		extendedProbationDetailsImpl.setExtendedProbationDetailsId(
			getExtendedProbationDetailsId());
		extendedProbationDetailsImpl.setProbationDetailId(
			getProbationDetailId());
		extendedProbationDetailsImpl.setExtendDate(getExtendDate());
		extendedProbationDetailsImpl.setEvalutionReview(getEvalutionReview());
		extendedProbationDetailsImpl.setExtendedProbationPeriod(
			getExtendedProbationPeriod());
		extendedProbationDetailsImpl.setExtendedProbationEndDate(
			getExtendedProbationEndDate());

		extendedProbationDetailsImpl.resetOriginalValues();

		return extendedProbationDetailsImpl;
	}

	@Override
	public ExtendedProbationDetails cloneWithOriginalValues() {
		ExtendedProbationDetailsImpl extendedProbationDetailsImpl =
			new ExtendedProbationDetailsImpl();

		extendedProbationDetailsImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		extendedProbationDetailsImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		extendedProbationDetailsImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("createdBy"));
		extendedProbationDetailsImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modifiedBy"));
		extendedProbationDetailsImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		extendedProbationDetailsImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		extendedProbationDetailsImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		extendedProbationDetailsImpl.setExtendedProbationDetailsId(
			this.<Long>getColumnOriginalValue("extendedProbationDetailsId"));
		extendedProbationDetailsImpl.setProbationDetailId(
			this.<Long>getColumnOriginalValue("probationDetailId"));
		extendedProbationDetailsImpl.setExtendDate(
			this.<Date>getColumnOriginalValue("extendDate"));
		extendedProbationDetailsImpl.setEvalutionReview(
			this.<String>getColumnOriginalValue("evalutionReview"));
		extendedProbationDetailsImpl.setExtendedProbationPeriod(
			this.<Integer>getColumnOriginalValue("extendedProbationPeriod"));
		extendedProbationDetailsImpl.setExtendedProbationEndDate(
			this.<Date>getColumnOriginalValue("extendedProbationEndDate"));

		return extendedProbationDetailsImpl;
	}

	@Override
	public int compareTo(ExtendedProbationDetails extendedProbationDetails) {
		long primaryKey = extendedProbationDetails.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ExtendedProbationDetails)) {
			return false;
		}

		ExtendedProbationDetails extendedProbationDetails =
			(ExtendedProbationDetails)object;

		long primaryKey = extendedProbationDetails.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ExtendedProbationDetails> toCacheModel() {
		ExtendedProbationDetailsCacheModel extendedProbationDetailsCacheModel =
			new ExtendedProbationDetailsCacheModel();

		extendedProbationDetailsCacheModel.uuid = getUuid();

		String uuid = extendedProbationDetailsCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			extendedProbationDetailsCacheModel.uuid = null;
		}

		extendedProbationDetailsCacheModel.companyId = getCompanyId();

		extendedProbationDetailsCacheModel.createdBy = getCreatedBy();

		extendedProbationDetailsCacheModel.modifiedBy = getModifiedBy();

		extendedProbationDetailsCacheModel.groupId = getGroupId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			extendedProbationDetailsCacheModel.createDate =
				createDate.getTime();
		}
		else {
			extendedProbationDetailsCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			extendedProbationDetailsCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			extendedProbationDetailsCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		extendedProbationDetailsCacheModel.extendedProbationDetailsId =
			getExtendedProbationDetailsId();

		extendedProbationDetailsCacheModel.probationDetailId =
			getProbationDetailId();

		Date extendDate = getExtendDate();

		if (extendDate != null) {
			extendedProbationDetailsCacheModel.extendDate =
				extendDate.getTime();
		}
		else {
			extendedProbationDetailsCacheModel.extendDate = Long.MIN_VALUE;
		}

		extendedProbationDetailsCacheModel.evalutionReview =
			getEvalutionReview();

		String evalutionReview =
			extendedProbationDetailsCacheModel.evalutionReview;

		if ((evalutionReview != null) && (evalutionReview.length() == 0)) {
			extendedProbationDetailsCacheModel.evalutionReview = null;
		}

		extendedProbationDetailsCacheModel.extendedProbationPeriod =
			getExtendedProbationPeriod();

		Date extendedProbationEndDate = getExtendedProbationEndDate();

		if (extendedProbationEndDate != null) {
			extendedProbationDetailsCacheModel.extendedProbationEndDate =
				extendedProbationEndDate.getTime();
		}
		else {
			extendedProbationDetailsCacheModel.extendedProbationEndDate =
				Long.MIN_VALUE;
		}

		return extendedProbationDetailsCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ExtendedProbationDetails, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ExtendedProbationDetails, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ExtendedProbationDetails, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(ExtendedProbationDetails)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, ExtendedProbationDetails>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						ExtendedProbationDetails.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _companyId;
	private long _createdBy;
	private long _modifiedBy;
	private long _groupId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _extendedProbationDetailsId;
	private long _probationDetailId;
	private Date _extendDate;
	private String _evalutionReview;
	private int _extendedProbationPeriod;
	private Date _extendedProbationEndDate;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<ExtendedProbationDetails, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ExtendedProbationDetails)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createdBy", _createdBy);
		_columnOriginalValues.put("modifiedBy", _modifiedBy);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put(
			"extendedProbationDetailsId", _extendedProbationDetailsId);
		_columnOriginalValues.put("probationDetailId", _probationDetailId);
		_columnOriginalValues.put("extendDate", _extendDate);
		_columnOriginalValues.put("evalutionReview", _evalutionReview);
		_columnOriginalValues.put(
			"extendedProbationPeriod", _extendedProbationPeriod);
		_columnOriginalValues.put(
			"extendedProbationEndDate", _extendedProbationEndDate);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("createdBy", 4L);

		columnBitmasks.put("modifiedBy", 8L);

		columnBitmasks.put("groupId", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("extendedProbationDetailsId", 128L);

		columnBitmasks.put("probationDetailId", 256L);

		columnBitmasks.put("extendDate", 512L);

		columnBitmasks.put("evalutionReview", 1024L);

		columnBitmasks.put("extendedProbationPeriod", 2048L);

		columnBitmasks.put("extendedProbationEndDate", 4096L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ExtendedProbationDetails _escapedModel;

}