/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.model.impl;

import com.ax.hrms.model.Holiday;
import com.ax.hrms.model.HolidayModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Holiday service. Represents a row in the &quot;ax_Holiday&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>HolidayModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link HolidayImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see HolidayImpl
 * @generated
 */
@JSON(strict = true)
public class HolidayModelImpl
	extends BaseModelImpl<Holiday> implements HolidayModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a holiday model instance should use the <code>Holiday</code> interface instead.
	 */
	public static final String TABLE_NAME = "ax_Holiday";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"companyId", Types.BIGINT},
		{"createdBy", Types.BIGINT}, {"modifiedBy", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"holidayId", Types.BIGINT},
		{"holidayName", Types.VARCHAR}, {"date_", Types.TIMESTAMP},
		{"description", Types.VARCHAR}, {"year", Types.INTEGER},
		{"isFloater", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("holidayId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("holidayName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("date_", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("year", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("isFloater", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ax_Holiday (uuid_ VARCHAR(75) null,companyId LONG,createdBy LONG,modifiedBy LONG,groupId LONG,createDate DATE null,modifiedDate DATE null,holidayId LONG not null primary key,holidayName VARCHAR(75) null,date_ DATE null,description VARCHAR(75) null,year INTEGER,isFloater BOOLEAN)";

	public static final String TABLE_SQL_DROP = "drop table ax_Holiday";

	public static final String ORDER_BY_JPQL =
		" ORDER BY holiday.holidayId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ax_Holiday.holidayId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DATE_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ISFLOATER_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long YEAR_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long HOLIDAYID_COLUMN_BITMASK = 64L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public HolidayModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _holidayId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setHolidayId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _holidayId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Holiday.class;
	}

	@Override
	public String getModelClassName() {
		return Holiday.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Holiday, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Holiday, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Holiday, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Holiday)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Holiday, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Holiday, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Holiday)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Holiday, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Holiday, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Holiday, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Holiday, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Holiday, Object>>();

			attributeGetterFunctions.put("uuid", Holiday::getUuid);
			attributeGetterFunctions.put("companyId", Holiday::getCompanyId);
			attributeGetterFunctions.put("createdBy", Holiday::getCreatedBy);
			attributeGetterFunctions.put("modifiedBy", Holiday::getModifiedBy);
			attributeGetterFunctions.put("groupId", Holiday::getGroupId);
			attributeGetterFunctions.put("createDate", Holiday::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", Holiday::getModifiedDate);
			attributeGetterFunctions.put("holidayId", Holiday::getHolidayId);
			attributeGetterFunctions.put(
				"holidayName", Holiday::getHolidayName);
			attributeGetterFunctions.put("date", Holiday::getDate);
			attributeGetterFunctions.put(
				"description", Holiday::getDescription);
			attributeGetterFunctions.put("year", Holiday::getYear);
			attributeGetterFunctions.put("isFloater", Holiday::getIsFloater);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Holiday, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Holiday, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Holiday, ?>>();

			attributeSetterBiConsumers.put(
				"uuid", (BiConsumer<Holiday, String>)Holiday::setUuid);
			attributeSetterBiConsumers.put(
				"companyId", (BiConsumer<Holiday, Long>)Holiday::setCompanyId);
			attributeSetterBiConsumers.put(
				"createdBy", (BiConsumer<Holiday, Long>)Holiday::setCreatedBy);
			attributeSetterBiConsumers.put(
				"modifiedBy",
				(BiConsumer<Holiday, Long>)Holiday::setModifiedBy);
			attributeSetterBiConsumers.put(
				"groupId", (BiConsumer<Holiday, Long>)Holiday::setGroupId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<Holiday, Date>)Holiday::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<Holiday, Date>)Holiday::setModifiedDate);
			attributeSetterBiConsumers.put(
				"holidayId", (BiConsumer<Holiday, Long>)Holiday::setHolidayId);
			attributeSetterBiConsumers.put(
				"holidayName",
				(BiConsumer<Holiday, String>)Holiday::setHolidayName);
			attributeSetterBiConsumers.put(
				"date", (BiConsumer<Holiday, Date>)Holiday::setDate);
			attributeSetterBiConsumers.put(
				"description",
				(BiConsumer<Holiday, String>)Holiday::setDescription);
			attributeSetterBiConsumers.put(
				"year", (BiConsumer<Holiday, Integer>)Holiday::setYear);
			attributeSetterBiConsumers.put(
				"isFloater",
				(BiConsumer<Holiday, Boolean>)Holiday::setIsFloater);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getHolidayId() {
		return _holidayId;
	}

	@Override
	public void setHolidayId(long holidayId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_holidayId = holidayId;
	}

	@JSON
	@Override
	public String getHolidayName() {
		if (_holidayName == null) {
			return "";
		}
		else {
			return _holidayName;
		}
	}

	@Override
	public void setHolidayName(String holidayName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_holidayName = holidayName;
	}

	@JSON
	@Override
	public Date getDate() {
		return _date;
	}

	@Override
	public void setDate(Date date) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_date = date;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public Date getOriginalDate() {
		return getColumnOriginalValue("date_");
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_description = description;
	}

	@JSON
	@Override
	public int getYear() {
		return _year;
	}

	@Override
	public void setYear(int year) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_year = year;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalYear() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("year"));
	}

	@JSON
	@Override
	public Boolean getIsFloater() {
		return _isFloater;
	}

	@Override
	public void setIsFloater(Boolean isFloater) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_isFloater = isFloater;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public Boolean getOriginalIsFloater() {
		return GetterUtil.getBoolean(
			this.<Boolean>getColumnOriginalValue("isFloater"));
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Holiday.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Holiday.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Holiday toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Holiday>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		HolidayImpl holidayImpl = new HolidayImpl();

		holidayImpl.setUuid(getUuid());
		holidayImpl.setCompanyId(getCompanyId());
		holidayImpl.setCreatedBy(getCreatedBy());
		holidayImpl.setModifiedBy(getModifiedBy());
		holidayImpl.setGroupId(getGroupId());
		holidayImpl.setCreateDate(getCreateDate());
		holidayImpl.setModifiedDate(getModifiedDate());
		holidayImpl.setHolidayId(getHolidayId());
		holidayImpl.setHolidayName(getHolidayName());
		holidayImpl.setDate(getDate());
		holidayImpl.setDescription(getDescription());
		holidayImpl.setYear(getYear());
		holidayImpl.setIsFloater(getIsFloater());

		holidayImpl.resetOriginalValues();

		return holidayImpl;
	}

	@Override
	public Holiday cloneWithOriginalValues() {
		HolidayImpl holidayImpl = new HolidayImpl();

		holidayImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		holidayImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		holidayImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("createdBy"));
		holidayImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modifiedBy"));
		holidayImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		holidayImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		holidayImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		holidayImpl.setHolidayId(
			this.<Long>getColumnOriginalValue("holidayId"));
		holidayImpl.setHolidayName(
			this.<String>getColumnOriginalValue("holidayName"));
		holidayImpl.setDate(this.<Date>getColumnOriginalValue("date_"));
		holidayImpl.setDescription(
			this.<String>getColumnOriginalValue("description"));
		holidayImpl.setYear(this.<Integer>getColumnOriginalValue("year"));
		holidayImpl.setIsFloater(
			this.<Boolean>getColumnOriginalValue("isFloater"));

		return holidayImpl;
	}

	@Override
	public int compareTo(Holiday holiday) {
		long primaryKey = holiday.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Holiday)) {
			return false;
		}

		Holiday holiday = (Holiday)object;

		long primaryKey = holiday.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Holiday> toCacheModel() {
		HolidayCacheModel holidayCacheModel = new HolidayCacheModel();

		holidayCacheModel.uuid = getUuid();

		String uuid = holidayCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			holidayCacheModel.uuid = null;
		}

		holidayCacheModel.companyId = getCompanyId();

		holidayCacheModel.createdBy = getCreatedBy();

		holidayCacheModel.modifiedBy = getModifiedBy();

		holidayCacheModel.groupId = getGroupId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			holidayCacheModel.createDate = createDate.getTime();
		}
		else {
			holidayCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			holidayCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			holidayCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		holidayCacheModel.holidayId = getHolidayId();

		holidayCacheModel.holidayName = getHolidayName();

		String holidayName = holidayCacheModel.holidayName;

		if ((holidayName != null) && (holidayName.length() == 0)) {
			holidayCacheModel.holidayName = null;
		}

		Date date = getDate();

		if (date != null) {
			holidayCacheModel.date = date.getTime();
		}
		else {
			holidayCacheModel.date = Long.MIN_VALUE;
		}

		holidayCacheModel.description = getDescription();

		String description = holidayCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			holidayCacheModel.description = null;
		}

		holidayCacheModel.year = getYear();

		Boolean isFloater = getIsFloater();

		if (isFloater != null) {
			holidayCacheModel.isFloater = isFloater;
		}

		return holidayCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Holiday, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Holiday, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Holiday, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Holiday)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Holiday>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Holiday.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _companyId;
	private long _createdBy;
	private long _modifiedBy;
	private long _groupId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _holidayId;
	private String _holidayName;
	private Date _date;
	private String _description;
	private int _year;
	private Boolean _isFloater;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Holiday, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Holiday)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createdBy", _createdBy);
		_columnOriginalValues.put("modifiedBy", _modifiedBy);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("holidayId", _holidayId);
		_columnOriginalValues.put("holidayName", _holidayName);
		_columnOriginalValues.put("date_", _date);
		_columnOriginalValues.put("description", _description);
		_columnOriginalValues.put("year", _year);
		_columnOriginalValues.put("isFloater", _isFloater);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");
		attributeNames.put("date_", "date");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("createdBy", 4L);

		columnBitmasks.put("modifiedBy", 8L);

		columnBitmasks.put("groupId", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("holidayId", 128L);

		columnBitmasks.put("holidayName", 256L);

		columnBitmasks.put("date_", 512L);

		columnBitmasks.put("description", 1024L);

		columnBitmasks.put("year", 2048L);

		columnBitmasks.put("isFloater", 4096L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Holiday _escapedModel;

}