/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.model.impl;

import com.ax.hrms.model.LeaveDayType;
import com.ax.hrms.model.LeaveDayTypeModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the LeaveDayType service. Represents a row in the &quot;ax_LeaveDayType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>LeaveDayTypeModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LeaveDayTypeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LeaveDayTypeImpl
 * @generated
 */
@JSON(strict = true)
public class LeaveDayTypeModelImpl
	extends BaseModelImpl<LeaveDayType> implements LeaveDayTypeModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a leave day type model instance should use the <code>LeaveDayType</code> interface instead.
	 */
	public static final String TABLE_NAME = "ax_LeaveDayType";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"companyId", Types.BIGINT},
		{"createdBy", Types.BIGINT}, {"modifiedBy", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"leaveDayTypeId", Types.BIGINT},
		{"leaveRequestId", Types.BIGINT}, {"leaveDate", Types.TIMESTAMP},
		{"isHalfDay", Types.BOOLEAN}, {"isFirstHalf", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("leaveDayTypeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("leaveRequestId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("leaveDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("isHalfDay", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("isFirstHalf", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ax_LeaveDayType (uuid_ VARCHAR(75) null,companyId LONG,createdBy LONG,modifiedBy LONG,groupId LONG,createDate DATE null,modifiedDate DATE null,leaveDayTypeId LONG not null primary key,leaveRequestId LONG,leaveDate DATE null,isHalfDay BOOLEAN,isFirstHalf BOOLEAN)";

	public static final String TABLE_SQL_DROP = "drop table ax_LeaveDayType";

	public static final String ORDER_BY_JPQL =
		" ORDER BY leaveDayType.leaveDayTypeId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ax_LeaveDayType.leaveDayTypeId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LEAVEREQUESTID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LEAVEDAYTYPEID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public LeaveDayTypeModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _leaveDayTypeId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLeaveDayTypeId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _leaveDayTypeId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return LeaveDayType.class;
	}

	@Override
	public String getModelClassName() {
		return LeaveDayType.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<LeaveDayType, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<LeaveDayType, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LeaveDayType, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((LeaveDayType)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<LeaveDayType, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<LeaveDayType, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(LeaveDayType)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<LeaveDayType, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<LeaveDayType, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<LeaveDayType, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<LeaveDayType, Object>>
				attributeGetterFunctions =
					new LinkedHashMap<String, Function<LeaveDayType, Object>>();

			attributeGetterFunctions.put("uuid", LeaveDayType::getUuid);
			attributeGetterFunctions.put(
				"companyId", LeaveDayType::getCompanyId);
			attributeGetterFunctions.put(
				"createdBy", LeaveDayType::getCreatedBy);
			attributeGetterFunctions.put(
				"modifiedBy", LeaveDayType::getModifiedBy);
			attributeGetterFunctions.put("groupId", LeaveDayType::getGroupId);
			attributeGetterFunctions.put(
				"createDate", LeaveDayType::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", LeaveDayType::getModifiedDate);
			attributeGetterFunctions.put(
				"leaveDayTypeId", LeaveDayType::getLeaveDayTypeId);
			attributeGetterFunctions.put(
				"leaveRequestId", LeaveDayType::getLeaveRequestId);
			attributeGetterFunctions.put(
				"leaveDate", LeaveDayType::getLeaveDate);
			attributeGetterFunctions.put(
				"isHalfDay", LeaveDayType::getIsHalfDay);
			attributeGetterFunctions.put(
				"isFirstHalf", LeaveDayType::getIsFirstHalf);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<LeaveDayType, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<LeaveDayType, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<LeaveDayType, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<LeaveDayType, String>)LeaveDayType::setUuid);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<LeaveDayType, Long>)LeaveDayType::setCompanyId);
			attributeSetterBiConsumers.put(
				"createdBy",
				(BiConsumer<LeaveDayType, Long>)LeaveDayType::setCreatedBy);
			attributeSetterBiConsumers.put(
				"modifiedBy",
				(BiConsumer<LeaveDayType, Long>)LeaveDayType::setModifiedBy);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<LeaveDayType, Long>)LeaveDayType::setGroupId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<LeaveDayType, Date>)LeaveDayType::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<LeaveDayType, Date>)LeaveDayType::setModifiedDate);
			attributeSetterBiConsumers.put(
				"leaveDayTypeId",
				(BiConsumer<LeaveDayType, Long>)
					LeaveDayType::setLeaveDayTypeId);
			attributeSetterBiConsumers.put(
				"leaveRequestId",
				(BiConsumer<LeaveDayType, Long>)
					LeaveDayType::setLeaveRequestId);
			attributeSetterBiConsumers.put(
				"leaveDate",
				(BiConsumer<LeaveDayType, Date>)LeaveDayType::setLeaveDate);
			attributeSetterBiConsumers.put(
				"isHalfDay",
				(BiConsumer<LeaveDayType, Boolean>)LeaveDayType::setIsHalfDay);
			attributeSetterBiConsumers.put(
				"isFirstHalf",
				(BiConsumer<LeaveDayType, Boolean>)
					LeaveDayType::setIsFirstHalf);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getLeaveDayTypeId() {
		return _leaveDayTypeId;
	}

	@Override
	public void setLeaveDayTypeId(long leaveDayTypeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_leaveDayTypeId = leaveDayTypeId;
	}

	@JSON
	@Override
	public long getLeaveRequestId() {
		return _leaveRequestId;
	}

	@Override
	public void setLeaveRequestId(long leaveRequestId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_leaveRequestId = leaveRequestId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalLeaveRequestId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("leaveRequestId"));
	}

	@JSON
	@Override
	public Date getLeaveDate() {
		return _leaveDate;
	}

	@Override
	public void setLeaveDate(Date leaveDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_leaveDate = leaveDate;
	}

	@JSON
	@Override
	public boolean getIsHalfDay() {
		return _isHalfDay;
	}

	@JSON
	@Override
	public boolean isIsHalfDay() {
		return _isHalfDay;
	}

	@Override
	public void setIsHalfDay(boolean isHalfDay) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_isHalfDay = isHalfDay;
	}

	@JSON
	@Override
	public boolean getIsFirstHalf() {
		return _isFirstHalf;
	}

	@JSON
	@Override
	public boolean isIsFirstHalf() {
		return _isFirstHalf;
	}

	@Override
	public void setIsFirstHalf(boolean isFirstHalf) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_isFirstHalf = isFirstHalf;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(LeaveDayType.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), LeaveDayType.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public LeaveDayType toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, LeaveDayType>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LeaveDayTypeImpl leaveDayTypeImpl = new LeaveDayTypeImpl();

		leaveDayTypeImpl.setUuid(getUuid());
		leaveDayTypeImpl.setCompanyId(getCompanyId());
		leaveDayTypeImpl.setCreatedBy(getCreatedBy());
		leaveDayTypeImpl.setModifiedBy(getModifiedBy());
		leaveDayTypeImpl.setGroupId(getGroupId());
		leaveDayTypeImpl.setCreateDate(getCreateDate());
		leaveDayTypeImpl.setModifiedDate(getModifiedDate());
		leaveDayTypeImpl.setLeaveDayTypeId(getLeaveDayTypeId());
		leaveDayTypeImpl.setLeaveRequestId(getLeaveRequestId());
		leaveDayTypeImpl.setLeaveDate(getLeaveDate());
		leaveDayTypeImpl.setIsHalfDay(isIsHalfDay());
		leaveDayTypeImpl.setIsFirstHalf(isIsFirstHalf());

		leaveDayTypeImpl.resetOriginalValues();

		return leaveDayTypeImpl;
	}

	@Override
	public LeaveDayType cloneWithOriginalValues() {
		LeaveDayTypeImpl leaveDayTypeImpl = new LeaveDayTypeImpl();

		leaveDayTypeImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		leaveDayTypeImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		leaveDayTypeImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("createdBy"));
		leaveDayTypeImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modifiedBy"));
		leaveDayTypeImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		leaveDayTypeImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		leaveDayTypeImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		leaveDayTypeImpl.setLeaveDayTypeId(
			this.<Long>getColumnOriginalValue("leaveDayTypeId"));
		leaveDayTypeImpl.setLeaveRequestId(
			this.<Long>getColumnOriginalValue("leaveRequestId"));
		leaveDayTypeImpl.setLeaveDate(
			this.<Date>getColumnOriginalValue("leaveDate"));
		leaveDayTypeImpl.setIsHalfDay(
			this.<Boolean>getColumnOriginalValue("isHalfDay"));
		leaveDayTypeImpl.setIsFirstHalf(
			this.<Boolean>getColumnOriginalValue("isFirstHalf"));

		return leaveDayTypeImpl;
	}

	@Override
	public int compareTo(LeaveDayType leaveDayType) {
		long primaryKey = leaveDayType.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof LeaveDayType)) {
			return false;
		}

		LeaveDayType leaveDayType = (LeaveDayType)object;

		long primaryKey = leaveDayType.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<LeaveDayType> toCacheModel() {
		LeaveDayTypeCacheModel leaveDayTypeCacheModel =
			new LeaveDayTypeCacheModel();

		leaveDayTypeCacheModel.uuid = getUuid();

		String uuid = leaveDayTypeCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			leaveDayTypeCacheModel.uuid = null;
		}

		leaveDayTypeCacheModel.companyId = getCompanyId();

		leaveDayTypeCacheModel.createdBy = getCreatedBy();

		leaveDayTypeCacheModel.modifiedBy = getModifiedBy();

		leaveDayTypeCacheModel.groupId = getGroupId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			leaveDayTypeCacheModel.createDate = createDate.getTime();
		}
		else {
			leaveDayTypeCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			leaveDayTypeCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			leaveDayTypeCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		leaveDayTypeCacheModel.leaveDayTypeId = getLeaveDayTypeId();

		leaveDayTypeCacheModel.leaveRequestId = getLeaveRequestId();

		Date leaveDate = getLeaveDate();

		if (leaveDate != null) {
			leaveDayTypeCacheModel.leaveDate = leaveDate.getTime();
		}
		else {
			leaveDayTypeCacheModel.leaveDate = Long.MIN_VALUE;
		}

		leaveDayTypeCacheModel.isHalfDay = isIsHalfDay();

		leaveDayTypeCacheModel.isFirstHalf = isIsFirstHalf();

		return leaveDayTypeCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<LeaveDayType, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<LeaveDayType, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LeaveDayType, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((LeaveDayType)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, LeaveDayType>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					LeaveDayType.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _companyId;
	private long _createdBy;
	private long _modifiedBy;
	private long _groupId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _leaveDayTypeId;
	private long _leaveRequestId;
	private Date _leaveDate;
	private boolean _isHalfDay;
	private boolean _isFirstHalf;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<LeaveDayType, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((LeaveDayType)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createdBy", _createdBy);
		_columnOriginalValues.put("modifiedBy", _modifiedBy);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("leaveDayTypeId", _leaveDayTypeId);
		_columnOriginalValues.put("leaveRequestId", _leaveRequestId);
		_columnOriginalValues.put("leaveDate", _leaveDate);
		_columnOriginalValues.put("isHalfDay", _isHalfDay);
		_columnOriginalValues.put("isFirstHalf", _isFirstHalf);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("createdBy", 4L);

		columnBitmasks.put("modifiedBy", 8L);

		columnBitmasks.put("groupId", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("leaveDayTypeId", 128L);

		columnBitmasks.put("leaveRequestId", 256L);

		columnBitmasks.put("leaveDate", 512L);

		columnBitmasks.put("isHalfDay", 1024L);

		columnBitmasks.put("isFirstHalf", 2048L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private LeaveDayType _escapedModel;

}