/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.model.impl;

import com.ax.hrms.model.LeaveBalance;
import com.ax.hrms.model.LeaveBalanceModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the LeaveBalance service. Represents a row in the &quot;ax_LeaveBalance&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>LeaveBalanceModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LeaveBalanceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LeaveBalanceImpl
 * @generated
 */
@JSON(strict = true)
public class LeaveBalanceModelImpl
	extends BaseModelImpl<LeaveBalance> implements LeaveBalanceModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a leave balance model instance should use the <code>LeaveBalance</code> interface instead.
	 */
	public static final String TABLE_NAME = "ax_LeaveBalance";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"companyId", Types.BIGINT},
		{"createdBy", Types.BIGINT}, {"modifiedBy", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"leaveBalanceId", Types.BIGINT},
		{"employeeId", Types.BIGINT}, {"leaveTypeMasterId", Types.BIGINT},
		{"year", Types.INTEGER}, {"noOfUsedLeaves", Types.DOUBLE},
		{"noOfRemainingLeaves", Types.DOUBLE}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("leaveBalanceId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("employeeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("leaveTypeMasterId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("year", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("noOfUsedLeaves", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("noOfRemainingLeaves", Types.DOUBLE);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ax_LeaveBalance (uuid_ VARCHAR(75) null,companyId LONG,createdBy LONG,modifiedBy LONG,groupId LONG,createDate DATE null,modifiedDate DATE null,leaveBalanceId LONG not null primary key,employeeId LONG,leaveTypeMasterId LONG,year INTEGER,noOfUsedLeaves DOUBLE,noOfRemainingLeaves DOUBLE)";

	public static final String TABLE_SQL_DROP = "drop table ax_LeaveBalance";

	public static final String ORDER_BY_JPQL =
		" ORDER BY leaveBalance.leaveBalanceId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ax_LeaveBalance.leaveBalanceId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EMPLOYEEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LEAVETYPEMASTERID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long YEAR_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LEAVEBALANCEID_COLUMN_BITMASK = 64L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public LeaveBalanceModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _leaveBalanceId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLeaveBalanceId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _leaveBalanceId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return LeaveBalance.class;
	}

	@Override
	public String getModelClassName() {
		return LeaveBalance.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<LeaveBalance, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<LeaveBalance, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LeaveBalance, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((LeaveBalance)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<LeaveBalance, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<LeaveBalance, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(LeaveBalance)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<LeaveBalance, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<LeaveBalance, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<LeaveBalance, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<LeaveBalance, Object>>
				attributeGetterFunctions =
					new LinkedHashMap<String, Function<LeaveBalance, Object>>();

			attributeGetterFunctions.put("uuid", LeaveBalance::getUuid);
			attributeGetterFunctions.put(
				"companyId", LeaveBalance::getCompanyId);
			attributeGetterFunctions.put(
				"createdBy", LeaveBalance::getCreatedBy);
			attributeGetterFunctions.put(
				"modifiedBy", LeaveBalance::getModifiedBy);
			attributeGetterFunctions.put("groupId", LeaveBalance::getGroupId);
			attributeGetterFunctions.put(
				"createDate", LeaveBalance::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", LeaveBalance::getModifiedDate);
			attributeGetterFunctions.put(
				"leaveBalanceId", LeaveBalance::getLeaveBalanceId);
			attributeGetterFunctions.put(
				"employeeId", LeaveBalance::getEmployeeId);
			attributeGetterFunctions.put(
				"leaveTypeMasterId", LeaveBalance::getLeaveTypeMasterId);
			attributeGetterFunctions.put("year", LeaveBalance::getYear);
			attributeGetterFunctions.put(
				"noOfUsedLeaves", LeaveBalance::getNoOfUsedLeaves);
			attributeGetterFunctions.put(
				"noOfRemainingLeaves", LeaveBalance::getNoOfRemainingLeaves);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<LeaveBalance, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<LeaveBalance, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<LeaveBalance, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<LeaveBalance, String>)LeaveBalance::setUuid);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<LeaveBalance, Long>)LeaveBalance::setCompanyId);
			attributeSetterBiConsumers.put(
				"createdBy",
				(BiConsumer<LeaveBalance, Long>)LeaveBalance::setCreatedBy);
			attributeSetterBiConsumers.put(
				"modifiedBy",
				(BiConsumer<LeaveBalance, Long>)LeaveBalance::setModifiedBy);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<LeaveBalance, Long>)LeaveBalance::setGroupId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<LeaveBalance, Date>)LeaveBalance::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<LeaveBalance, Date>)LeaveBalance::setModifiedDate);
			attributeSetterBiConsumers.put(
				"leaveBalanceId",
				(BiConsumer<LeaveBalance, Long>)
					LeaveBalance::setLeaveBalanceId);
			attributeSetterBiConsumers.put(
				"employeeId",
				(BiConsumer<LeaveBalance, Long>)LeaveBalance::setEmployeeId);
			attributeSetterBiConsumers.put(
				"leaveTypeMasterId",
				(BiConsumer<LeaveBalance, Long>)
					LeaveBalance::setLeaveTypeMasterId);
			attributeSetterBiConsumers.put(
				"year",
				(BiConsumer<LeaveBalance, Integer>)LeaveBalance::setYear);
			attributeSetterBiConsumers.put(
				"noOfUsedLeaves",
				(BiConsumer<LeaveBalance, Double>)
					LeaveBalance::setNoOfUsedLeaves);
			attributeSetterBiConsumers.put(
				"noOfRemainingLeaves",
				(BiConsumer<LeaveBalance, Double>)
					LeaveBalance::setNoOfRemainingLeaves);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getLeaveBalanceId() {
		return _leaveBalanceId;
	}

	@Override
	public void setLeaveBalanceId(long leaveBalanceId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_leaveBalanceId = leaveBalanceId;
	}

	@JSON
	@Override
	public long getEmployeeId() {
		return _employeeId;
	}

	@Override
	public void setEmployeeId(long employeeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_employeeId = employeeId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalEmployeeId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("employeeId"));
	}

	@JSON
	@Override
	public long getLeaveTypeMasterId() {
		return _leaveTypeMasterId;
	}

	@Override
	public void setLeaveTypeMasterId(long leaveTypeMasterId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_leaveTypeMasterId = leaveTypeMasterId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalLeaveTypeMasterId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("leaveTypeMasterId"));
	}

	@JSON
	@Override
	public int getYear() {
		return _year;
	}

	@Override
	public void setYear(int year) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_year = year;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalYear() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("year"));
	}

	@JSON
	@Override
	public double getNoOfUsedLeaves() {
		return _noOfUsedLeaves;
	}

	@Override
	public void setNoOfUsedLeaves(double noOfUsedLeaves) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_noOfUsedLeaves = noOfUsedLeaves;
	}

	@JSON
	@Override
	public double getNoOfRemainingLeaves() {
		return _noOfRemainingLeaves;
	}

	@Override
	public void setNoOfRemainingLeaves(double noOfRemainingLeaves) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_noOfRemainingLeaves = noOfRemainingLeaves;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(LeaveBalance.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), LeaveBalance.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public LeaveBalance toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, LeaveBalance>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LeaveBalanceImpl leaveBalanceImpl = new LeaveBalanceImpl();

		leaveBalanceImpl.setUuid(getUuid());
		leaveBalanceImpl.setCompanyId(getCompanyId());
		leaveBalanceImpl.setCreatedBy(getCreatedBy());
		leaveBalanceImpl.setModifiedBy(getModifiedBy());
		leaveBalanceImpl.setGroupId(getGroupId());
		leaveBalanceImpl.setCreateDate(getCreateDate());
		leaveBalanceImpl.setModifiedDate(getModifiedDate());
		leaveBalanceImpl.setLeaveBalanceId(getLeaveBalanceId());
		leaveBalanceImpl.setEmployeeId(getEmployeeId());
		leaveBalanceImpl.setLeaveTypeMasterId(getLeaveTypeMasterId());
		leaveBalanceImpl.setYear(getYear());
		leaveBalanceImpl.setNoOfUsedLeaves(getNoOfUsedLeaves());
		leaveBalanceImpl.setNoOfRemainingLeaves(getNoOfRemainingLeaves());

		leaveBalanceImpl.resetOriginalValues();

		return leaveBalanceImpl;
	}

	@Override
	public LeaveBalance cloneWithOriginalValues() {
		LeaveBalanceImpl leaveBalanceImpl = new LeaveBalanceImpl();

		leaveBalanceImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		leaveBalanceImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		leaveBalanceImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("createdBy"));
		leaveBalanceImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modifiedBy"));
		leaveBalanceImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		leaveBalanceImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		leaveBalanceImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		leaveBalanceImpl.setLeaveBalanceId(
			this.<Long>getColumnOriginalValue("leaveBalanceId"));
		leaveBalanceImpl.setEmployeeId(
			this.<Long>getColumnOriginalValue("employeeId"));
		leaveBalanceImpl.setLeaveTypeMasterId(
			this.<Long>getColumnOriginalValue("leaveTypeMasterId"));
		leaveBalanceImpl.setYear(this.<Integer>getColumnOriginalValue("year"));
		leaveBalanceImpl.setNoOfUsedLeaves(
			this.<Double>getColumnOriginalValue("noOfUsedLeaves"));
		leaveBalanceImpl.setNoOfRemainingLeaves(
			this.<Double>getColumnOriginalValue("noOfRemainingLeaves"));

		return leaveBalanceImpl;
	}

	@Override
	public int compareTo(LeaveBalance leaveBalance) {
		long primaryKey = leaveBalance.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof LeaveBalance)) {
			return false;
		}

		LeaveBalance leaveBalance = (LeaveBalance)object;

		long primaryKey = leaveBalance.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<LeaveBalance> toCacheModel() {
		LeaveBalanceCacheModel leaveBalanceCacheModel =
			new LeaveBalanceCacheModel();

		leaveBalanceCacheModel.uuid = getUuid();

		String uuid = leaveBalanceCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			leaveBalanceCacheModel.uuid = null;
		}

		leaveBalanceCacheModel.companyId = getCompanyId();

		leaveBalanceCacheModel.createdBy = getCreatedBy();

		leaveBalanceCacheModel.modifiedBy = getModifiedBy();

		leaveBalanceCacheModel.groupId = getGroupId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			leaveBalanceCacheModel.createDate = createDate.getTime();
		}
		else {
			leaveBalanceCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			leaveBalanceCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			leaveBalanceCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		leaveBalanceCacheModel.leaveBalanceId = getLeaveBalanceId();

		leaveBalanceCacheModel.employeeId = getEmployeeId();

		leaveBalanceCacheModel.leaveTypeMasterId = getLeaveTypeMasterId();

		leaveBalanceCacheModel.year = getYear();

		leaveBalanceCacheModel.noOfUsedLeaves = getNoOfUsedLeaves();

		leaveBalanceCacheModel.noOfRemainingLeaves = getNoOfRemainingLeaves();

		return leaveBalanceCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<LeaveBalance, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<LeaveBalance, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LeaveBalance, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((LeaveBalance)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, LeaveBalance>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					LeaveBalance.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _companyId;
	private long _createdBy;
	private long _modifiedBy;
	private long _groupId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _leaveBalanceId;
	private long _employeeId;
	private long _leaveTypeMasterId;
	private int _year;
	private double _noOfUsedLeaves;
	private double _noOfRemainingLeaves;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<LeaveBalance, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((LeaveBalance)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createdBy", _createdBy);
		_columnOriginalValues.put("modifiedBy", _modifiedBy);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("leaveBalanceId", _leaveBalanceId);
		_columnOriginalValues.put("employeeId", _employeeId);
		_columnOriginalValues.put("leaveTypeMasterId", _leaveTypeMasterId);
		_columnOriginalValues.put("year", _year);
		_columnOriginalValues.put("noOfUsedLeaves", _noOfUsedLeaves);
		_columnOriginalValues.put("noOfRemainingLeaves", _noOfRemainingLeaves);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("createdBy", 4L);

		columnBitmasks.put("modifiedBy", 8L);

		columnBitmasks.put("groupId", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("leaveBalanceId", 128L);

		columnBitmasks.put("employeeId", 256L);

		columnBitmasks.put("leaveTypeMasterId", 512L);

		columnBitmasks.put("year", 1024L);

		columnBitmasks.put("noOfUsedLeaves", 2048L);

		columnBitmasks.put("noOfRemainingLeaves", 4096L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private LeaveBalance _escapedModel;

}