/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.model.impl;

import com.ax.hrms.model.LeaveInformToTeamDetail;
import com.ax.hrms.model.LeaveInformToTeamDetailModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the LeaveInformToTeamDetail service. Represents a row in the &quot;ax_LeaveInformToTeamDetail&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>LeaveInformToTeamDetailModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LeaveInformToTeamDetailImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LeaveInformToTeamDetailImpl
 * @generated
 */
@JSON(strict = true)
public class LeaveInformToTeamDetailModelImpl
	extends BaseModelImpl<LeaveInformToTeamDetail>
	implements LeaveInformToTeamDetailModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a leave inform to team detail model instance should use the <code>LeaveInformToTeamDetail</code> interface instead.
	 */
	public static final String TABLE_NAME = "ax_LeaveInformToTeamDetail";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"companyId", Types.BIGINT},
		{"createdBy", Types.BIGINT}, {"modifiedBy", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"leaveInformId", Types.BIGINT},
		{"leaveRequestId", Types.BIGINT}, {"employeeId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("leaveInformId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("leaveRequestId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("employeeId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ax_LeaveInformToTeamDetail (uuid_ VARCHAR(75) null,companyId LONG,createdBy LONG,modifiedBy LONG,groupId LONG,createDate DATE null,modifiedDate DATE null,leaveInformId LONG not null primary key,leaveRequestId LONG,employeeId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table ax_LeaveInformToTeamDetail";

	public static final String ORDER_BY_JPQL =
		" ORDER BY leaveInformToTeamDetail.leaveInformId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ax_LeaveInformToTeamDetail.leaveInformId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LEAVEREQUESTID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LEAVEINFORMID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public LeaveInformToTeamDetailModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _leaveInformId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLeaveInformId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _leaveInformId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return LeaveInformToTeamDetail.class;
	}

	@Override
	public String getModelClassName() {
		return LeaveInformToTeamDetail.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<LeaveInformToTeamDetail, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<LeaveInformToTeamDetail, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LeaveInformToTeamDetail, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((LeaveInformToTeamDetail)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<LeaveInformToTeamDetail, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<LeaveInformToTeamDetail, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(LeaveInformToTeamDetail)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<LeaveInformToTeamDetail, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<LeaveInformToTeamDetail, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map
			<String, Function<LeaveInformToTeamDetail, Object>>
				_attributeGetterFunctions;

		static {
			Map<String, Function<LeaveInformToTeamDetail, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<LeaveInformToTeamDetail, Object>>();

			attributeGetterFunctions.put(
				"uuid", LeaveInformToTeamDetail::getUuid);
			attributeGetterFunctions.put(
				"companyId", LeaveInformToTeamDetail::getCompanyId);
			attributeGetterFunctions.put(
				"createdBy", LeaveInformToTeamDetail::getCreatedBy);
			attributeGetterFunctions.put(
				"modifiedBy", LeaveInformToTeamDetail::getModifiedBy);
			attributeGetterFunctions.put(
				"groupId", LeaveInformToTeamDetail::getGroupId);
			attributeGetterFunctions.put(
				"createDate", LeaveInformToTeamDetail::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", LeaveInformToTeamDetail::getModifiedDate);
			attributeGetterFunctions.put(
				"leaveInformId", LeaveInformToTeamDetail::getLeaveInformId);
			attributeGetterFunctions.put(
				"leaveRequestId", LeaveInformToTeamDetail::getLeaveRequestId);
			attributeGetterFunctions.put(
				"employeeId", LeaveInformToTeamDetail::getEmployeeId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<LeaveInformToTeamDetail, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<LeaveInformToTeamDetail, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<LeaveInformToTeamDetail, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<LeaveInformToTeamDetail, String>)
					LeaveInformToTeamDetail::setUuid);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<LeaveInformToTeamDetail, Long>)
					LeaveInformToTeamDetail::setCompanyId);
			attributeSetterBiConsumers.put(
				"createdBy",
				(BiConsumer<LeaveInformToTeamDetail, Long>)
					LeaveInformToTeamDetail::setCreatedBy);
			attributeSetterBiConsumers.put(
				"modifiedBy",
				(BiConsumer<LeaveInformToTeamDetail, Long>)
					LeaveInformToTeamDetail::setModifiedBy);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<LeaveInformToTeamDetail, Long>)
					LeaveInformToTeamDetail::setGroupId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<LeaveInformToTeamDetail, Date>)
					LeaveInformToTeamDetail::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<LeaveInformToTeamDetail, Date>)
					LeaveInformToTeamDetail::setModifiedDate);
			attributeSetterBiConsumers.put(
				"leaveInformId",
				(BiConsumer<LeaveInformToTeamDetail, Long>)
					LeaveInformToTeamDetail::setLeaveInformId);
			attributeSetterBiConsumers.put(
				"leaveRequestId",
				(BiConsumer<LeaveInformToTeamDetail, Long>)
					LeaveInformToTeamDetail::setLeaveRequestId);
			attributeSetterBiConsumers.put(
				"employeeId",
				(BiConsumer<LeaveInformToTeamDetail, Long>)
					LeaveInformToTeamDetail::setEmployeeId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getLeaveInformId() {
		return _leaveInformId;
	}

	@Override
	public void setLeaveInformId(long leaveInformId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_leaveInformId = leaveInformId;
	}

	@JSON
	@Override
	public long getLeaveRequestId() {
		return _leaveRequestId;
	}

	@Override
	public void setLeaveRequestId(long leaveRequestId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_leaveRequestId = leaveRequestId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalLeaveRequestId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("leaveRequestId"));
	}

	@JSON
	@Override
	public long getEmployeeId() {
		return _employeeId;
	}

	@Override
	public void setEmployeeId(long employeeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_employeeId = employeeId;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(LeaveInformToTeamDetail.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), LeaveInformToTeamDetail.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public LeaveInformToTeamDetail toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, LeaveInformToTeamDetail>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LeaveInformToTeamDetailImpl leaveInformToTeamDetailImpl =
			new LeaveInformToTeamDetailImpl();

		leaveInformToTeamDetailImpl.setUuid(getUuid());
		leaveInformToTeamDetailImpl.setCompanyId(getCompanyId());
		leaveInformToTeamDetailImpl.setCreatedBy(getCreatedBy());
		leaveInformToTeamDetailImpl.setModifiedBy(getModifiedBy());
		leaveInformToTeamDetailImpl.setGroupId(getGroupId());
		leaveInformToTeamDetailImpl.setCreateDate(getCreateDate());
		leaveInformToTeamDetailImpl.setModifiedDate(getModifiedDate());
		leaveInformToTeamDetailImpl.setLeaveInformId(getLeaveInformId());
		leaveInformToTeamDetailImpl.setLeaveRequestId(getLeaveRequestId());
		leaveInformToTeamDetailImpl.setEmployeeId(getEmployeeId());

		leaveInformToTeamDetailImpl.resetOriginalValues();

		return leaveInformToTeamDetailImpl;
	}

	@Override
	public LeaveInformToTeamDetail cloneWithOriginalValues() {
		LeaveInformToTeamDetailImpl leaveInformToTeamDetailImpl =
			new LeaveInformToTeamDetailImpl();

		leaveInformToTeamDetailImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		leaveInformToTeamDetailImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		leaveInformToTeamDetailImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("createdBy"));
		leaveInformToTeamDetailImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modifiedBy"));
		leaveInformToTeamDetailImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		leaveInformToTeamDetailImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		leaveInformToTeamDetailImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		leaveInformToTeamDetailImpl.setLeaveInformId(
			this.<Long>getColumnOriginalValue("leaveInformId"));
		leaveInformToTeamDetailImpl.setLeaveRequestId(
			this.<Long>getColumnOriginalValue("leaveRequestId"));
		leaveInformToTeamDetailImpl.setEmployeeId(
			this.<Long>getColumnOriginalValue("employeeId"));

		return leaveInformToTeamDetailImpl;
	}

	@Override
	public int compareTo(LeaveInformToTeamDetail leaveInformToTeamDetail) {
		long primaryKey = leaveInformToTeamDetail.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof LeaveInformToTeamDetail)) {
			return false;
		}

		LeaveInformToTeamDetail leaveInformToTeamDetail =
			(LeaveInformToTeamDetail)object;

		long primaryKey = leaveInformToTeamDetail.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<LeaveInformToTeamDetail> toCacheModel() {
		LeaveInformToTeamDetailCacheModel leaveInformToTeamDetailCacheModel =
			new LeaveInformToTeamDetailCacheModel();

		leaveInformToTeamDetailCacheModel.uuid = getUuid();

		String uuid = leaveInformToTeamDetailCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			leaveInformToTeamDetailCacheModel.uuid = null;
		}

		leaveInformToTeamDetailCacheModel.companyId = getCompanyId();

		leaveInformToTeamDetailCacheModel.createdBy = getCreatedBy();

		leaveInformToTeamDetailCacheModel.modifiedBy = getModifiedBy();

		leaveInformToTeamDetailCacheModel.groupId = getGroupId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			leaveInformToTeamDetailCacheModel.createDate = createDate.getTime();
		}
		else {
			leaveInformToTeamDetailCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			leaveInformToTeamDetailCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			leaveInformToTeamDetailCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		leaveInformToTeamDetailCacheModel.leaveInformId = getLeaveInformId();

		leaveInformToTeamDetailCacheModel.leaveRequestId = getLeaveRequestId();

		leaveInformToTeamDetailCacheModel.employeeId = getEmployeeId();

		return leaveInformToTeamDetailCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<LeaveInformToTeamDetail, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<LeaveInformToTeamDetail, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LeaveInformToTeamDetail, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(LeaveInformToTeamDetail)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, LeaveInformToTeamDetail>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						LeaveInformToTeamDetail.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _companyId;
	private long _createdBy;
	private long _modifiedBy;
	private long _groupId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _leaveInformId;
	private long _leaveRequestId;
	private long _employeeId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<LeaveInformToTeamDetail, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((LeaveInformToTeamDetail)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createdBy", _createdBy);
		_columnOriginalValues.put("modifiedBy", _modifiedBy);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("leaveInformId", _leaveInformId);
		_columnOriginalValues.put("leaveRequestId", _leaveRequestId);
		_columnOriginalValues.put("employeeId", _employeeId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("createdBy", 4L);

		columnBitmasks.put("modifiedBy", 8L);

		columnBitmasks.put("groupId", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("leaveInformId", 128L);

		columnBitmasks.put("leaveRequestId", 256L);

		columnBitmasks.put("employeeId", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private LeaveInformToTeamDetail _escapedModel;

}