/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.model.impl;

import com.ax.hrms.model.LeaveRequest;
import com.ax.hrms.model.LeaveRequestModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the LeaveRequest service. Represents a row in the &quot;ax_LeaveRequest&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>LeaveRequestModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LeaveRequestImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LeaveRequestImpl
 * @generated
 */
@JSON(strict = true)
public class LeaveRequestModelImpl
	extends BaseModelImpl<LeaveRequest> implements LeaveRequestModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a leave request model instance should use the <code>LeaveRequest</code> interface instead.
	 */
	public static final String TABLE_NAME = "ax_LeaveRequest";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"companyId", Types.BIGINT},
		{"createdBy", Types.BIGINT}, {"modifiedBy", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"leaveRequestId", Types.BIGINT},
		{"employeeId", Types.BIGINT}, {"leaveTypeMasterId", Types.BIGINT},
		{"startDateTime", Types.TIMESTAMP}, {"endDateTime", Types.TIMESTAMP},
		{"reason", Types.VARCHAR},
		{"leaveCompensatoryStatusMasterId", Types.BIGINT},
		{"hrApprovalId", Types.BIGINT}, {"managerApprovalId", Types.BIGINT},
		{"dateOfRequest", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("leaveRequestId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("employeeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("leaveTypeMasterId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("startDateTime", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("endDateTime", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("reason", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("leaveCompensatoryStatusMasterId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("hrApprovalId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("managerApprovalId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("dateOfRequest", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ax_LeaveRequest (uuid_ VARCHAR(75) null,companyId LONG,createdBy LONG,modifiedBy LONG,groupId LONG,createDate DATE null,modifiedDate DATE null,leaveRequestId LONG not null primary key,employeeId LONG,leaveTypeMasterId LONG,startDateTime DATE null,endDateTime DATE null,reason VARCHAR(250) null,leaveCompensatoryStatusMasterId LONG,hrApprovalId LONG,managerApprovalId LONG,dateOfRequest DATE null)";

	public static final String TABLE_SQL_DROP = "drop table ax_LeaveRequest";

	public static final String ORDER_BY_JPQL =
		" ORDER BY leaveRequest.dateOfRequest DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ax_LeaveRequest.dateOfRequest DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EMPLOYEEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LEAVEREQUESTID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DATEOFREQUEST_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public LeaveRequestModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _leaveRequestId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLeaveRequestId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _leaveRequestId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return LeaveRequest.class;
	}

	@Override
	public String getModelClassName() {
		return LeaveRequest.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<LeaveRequest, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<LeaveRequest, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LeaveRequest, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((LeaveRequest)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<LeaveRequest, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<LeaveRequest, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(LeaveRequest)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<LeaveRequest, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<LeaveRequest, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<LeaveRequest, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<LeaveRequest, Object>>
				attributeGetterFunctions =
					new LinkedHashMap<String, Function<LeaveRequest, Object>>();

			attributeGetterFunctions.put("uuid", LeaveRequest::getUuid);
			attributeGetterFunctions.put(
				"companyId", LeaveRequest::getCompanyId);
			attributeGetterFunctions.put(
				"createdBy", LeaveRequest::getCreatedBy);
			attributeGetterFunctions.put(
				"modifiedBy", LeaveRequest::getModifiedBy);
			attributeGetterFunctions.put("groupId", LeaveRequest::getGroupId);
			attributeGetterFunctions.put(
				"createDate", LeaveRequest::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", LeaveRequest::getModifiedDate);
			attributeGetterFunctions.put(
				"leaveRequestId", LeaveRequest::getLeaveRequestId);
			attributeGetterFunctions.put(
				"employeeId", LeaveRequest::getEmployeeId);
			attributeGetterFunctions.put(
				"leaveTypeMasterId", LeaveRequest::getLeaveTypeMasterId);
			attributeGetterFunctions.put(
				"startDateTime", LeaveRequest::getStartDateTime);
			attributeGetterFunctions.put(
				"endDateTime", LeaveRequest::getEndDateTime);
			attributeGetterFunctions.put("reason", LeaveRequest::getReason);
			attributeGetterFunctions.put(
				"leaveCompensatoryStatusMasterId",
				LeaveRequest::getLeaveCompensatoryStatusMasterId);
			attributeGetterFunctions.put(
				"hrApprovalId", LeaveRequest::getHrApprovalId);
			attributeGetterFunctions.put(
				"managerApprovalId", LeaveRequest::getManagerApprovalId);
			attributeGetterFunctions.put(
				"dateOfRequest", LeaveRequest::getDateOfRequest);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<LeaveRequest, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<LeaveRequest, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<LeaveRequest, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<LeaveRequest, String>)LeaveRequest::setUuid);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<LeaveRequest, Long>)LeaveRequest::setCompanyId);
			attributeSetterBiConsumers.put(
				"createdBy",
				(BiConsumer<LeaveRequest, Long>)LeaveRequest::setCreatedBy);
			attributeSetterBiConsumers.put(
				"modifiedBy",
				(BiConsumer<LeaveRequest, Long>)LeaveRequest::setModifiedBy);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<LeaveRequest, Long>)LeaveRequest::setGroupId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<LeaveRequest, Date>)LeaveRequest::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<LeaveRequest, Date>)LeaveRequest::setModifiedDate);
			attributeSetterBiConsumers.put(
				"leaveRequestId",
				(BiConsumer<LeaveRequest, Long>)
					LeaveRequest::setLeaveRequestId);
			attributeSetterBiConsumers.put(
				"employeeId",
				(BiConsumer<LeaveRequest, Long>)LeaveRequest::setEmployeeId);
			attributeSetterBiConsumers.put(
				"leaveTypeMasterId",
				(BiConsumer<LeaveRequest, Long>)
					LeaveRequest::setLeaveTypeMasterId);
			attributeSetterBiConsumers.put(
				"startDateTime",
				(BiConsumer<LeaveRequest, Date>)LeaveRequest::setStartDateTime);
			attributeSetterBiConsumers.put(
				"endDateTime",
				(BiConsumer<LeaveRequest, Date>)LeaveRequest::setEndDateTime);
			attributeSetterBiConsumers.put(
				"reason",
				(BiConsumer<LeaveRequest, String>)LeaveRequest::setReason);
			attributeSetterBiConsumers.put(
				"leaveCompensatoryStatusMasterId",
				(BiConsumer<LeaveRequest, Long>)
					LeaveRequest::setLeaveCompensatoryStatusMasterId);
			attributeSetterBiConsumers.put(
				"hrApprovalId",
				(BiConsumer<LeaveRequest, Long>)LeaveRequest::setHrApprovalId);
			attributeSetterBiConsumers.put(
				"managerApprovalId",
				(BiConsumer<LeaveRequest, Long>)
					LeaveRequest::setManagerApprovalId);
			attributeSetterBiConsumers.put(
				"dateOfRequest",
				(BiConsumer<LeaveRequest, Date>)LeaveRequest::setDateOfRequest);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getLeaveRequestId() {
		return _leaveRequestId;
	}

	@Override
	public void setLeaveRequestId(long leaveRequestId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_leaveRequestId = leaveRequestId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalLeaveRequestId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("leaveRequestId"));
	}

	@JSON
	@Override
	public long getEmployeeId() {
		return _employeeId;
	}

	@Override
	public void setEmployeeId(long employeeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_employeeId = employeeId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalEmployeeId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("employeeId"));
	}

	@JSON
	@Override
	public long getLeaveTypeMasterId() {
		return _leaveTypeMasterId;
	}

	@Override
	public void setLeaveTypeMasterId(long leaveTypeMasterId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_leaveTypeMasterId = leaveTypeMasterId;
	}

	@JSON
	@Override
	public Date getStartDateTime() {
		return _startDateTime;
	}

	@Override
	public void setStartDateTime(Date startDateTime) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_startDateTime = startDateTime;
	}

	@JSON
	@Override
	public Date getEndDateTime() {
		return _endDateTime;
	}

	@Override
	public void setEndDateTime(Date endDateTime) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_endDateTime = endDateTime;
	}

	@JSON
	@Override
	public String getReason() {
		if (_reason == null) {
			return "";
		}
		else {
			return _reason;
		}
	}

	@Override
	public void setReason(String reason) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_reason = reason;
	}

	@JSON
	@Override
	public long getLeaveCompensatoryStatusMasterId() {
		return _leaveCompensatoryStatusMasterId;
	}

	@Override
	public void setLeaveCompensatoryStatusMasterId(
		long leaveCompensatoryStatusMasterId) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_leaveCompensatoryStatusMasterId = leaveCompensatoryStatusMasterId;
	}

	@JSON
	@Override
	public long getHrApprovalId() {
		return _hrApprovalId;
	}

	@Override
	public void setHrApprovalId(long hrApprovalId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_hrApprovalId = hrApprovalId;
	}

	@JSON
	@Override
	public long getManagerApprovalId() {
		return _managerApprovalId;
	}

	@Override
	public void setManagerApprovalId(long managerApprovalId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_managerApprovalId = managerApprovalId;
	}

	@JSON
	@Override
	public Date getDateOfRequest() {
		return _dateOfRequest;
	}

	@Override
	public void setDateOfRequest(Date dateOfRequest) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dateOfRequest = dateOfRequest;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(LeaveRequest.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), LeaveRequest.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public LeaveRequest toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, LeaveRequest>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LeaveRequestImpl leaveRequestImpl = new LeaveRequestImpl();

		leaveRequestImpl.setUuid(getUuid());
		leaveRequestImpl.setCompanyId(getCompanyId());
		leaveRequestImpl.setCreatedBy(getCreatedBy());
		leaveRequestImpl.setModifiedBy(getModifiedBy());
		leaveRequestImpl.setGroupId(getGroupId());
		leaveRequestImpl.setCreateDate(getCreateDate());
		leaveRequestImpl.setModifiedDate(getModifiedDate());
		leaveRequestImpl.setLeaveRequestId(getLeaveRequestId());
		leaveRequestImpl.setEmployeeId(getEmployeeId());
		leaveRequestImpl.setLeaveTypeMasterId(getLeaveTypeMasterId());
		leaveRequestImpl.setStartDateTime(getStartDateTime());
		leaveRequestImpl.setEndDateTime(getEndDateTime());
		leaveRequestImpl.setReason(getReason());
		leaveRequestImpl.setLeaveCompensatoryStatusMasterId(
			getLeaveCompensatoryStatusMasterId());
		leaveRequestImpl.setHrApprovalId(getHrApprovalId());
		leaveRequestImpl.setManagerApprovalId(getManagerApprovalId());
		leaveRequestImpl.setDateOfRequest(getDateOfRequest());

		leaveRequestImpl.resetOriginalValues();

		return leaveRequestImpl;
	}

	@Override
	public LeaveRequest cloneWithOriginalValues() {
		LeaveRequestImpl leaveRequestImpl = new LeaveRequestImpl();

		leaveRequestImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		leaveRequestImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		leaveRequestImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("createdBy"));
		leaveRequestImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modifiedBy"));
		leaveRequestImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		leaveRequestImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		leaveRequestImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		leaveRequestImpl.setLeaveRequestId(
			this.<Long>getColumnOriginalValue("leaveRequestId"));
		leaveRequestImpl.setEmployeeId(
			this.<Long>getColumnOriginalValue("employeeId"));
		leaveRequestImpl.setLeaveTypeMasterId(
			this.<Long>getColumnOriginalValue("leaveTypeMasterId"));
		leaveRequestImpl.setStartDateTime(
			this.<Date>getColumnOriginalValue("startDateTime"));
		leaveRequestImpl.setEndDateTime(
			this.<Date>getColumnOriginalValue("endDateTime"));
		leaveRequestImpl.setReason(
			this.<String>getColumnOriginalValue("reason"));
		leaveRequestImpl.setLeaveCompensatoryStatusMasterId(
			this.<Long>getColumnOriginalValue(
				"leaveCompensatoryStatusMasterId"));
		leaveRequestImpl.setHrApprovalId(
			this.<Long>getColumnOriginalValue("hrApprovalId"));
		leaveRequestImpl.setManagerApprovalId(
			this.<Long>getColumnOriginalValue("managerApprovalId"));
		leaveRequestImpl.setDateOfRequest(
			this.<Date>getColumnOriginalValue("dateOfRequest"));

		return leaveRequestImpl;
	}

	@Override
	public int compareTo(LeaveRequest leaveRequest) {
		int value = 0;

		value = DateUtil.compareTo(
			getDateOfRequest(), leaveRequest.getDateOfRequest());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof LeaveRequest)) {
			return false;
		}

		LeaveRequest leaveRequest = (LeaveRequest)object;

		long primaryKey = leaveRequest.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<LeaveRequest> toCacheModel() {
		LeaveRequestCacheModel leaveRequestCacheModel =
			new LeaveRequestCacheModel();

		leaveRequestCacheModel.uuid = getUuid();

		String uuid = leaveRequestCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			leaveRequestCacheModel.uuid = null;
		}

		leaveRequestCacheModel.companyId = getCompanyId();

		leaveRequestCacheModel.createdBy = getCreatedBy();

		leaveRequestCacheModel.modifiedBy = getModifiedBy();

		leaveRequestCacheModel.groupId = getGroupId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			leaveRequestCacheModel.createDate = createDate.getTime();
		}
		else {
			leaveRequestCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			leaveRequestCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			leaveRequestCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		leaveRequestCacheModel.leaveRequestId = getLeaveRequestId();

		leaveRequestCacheModel.employeeId = getEmployeeId();

		leaveRequestCacheModel.leaveTypeMasterId = getLeaveTypeMasterId();

		Date startDateTime = getStartDateTime();

		if (startDateTime != null) {
			leaveRequestCacheModel.startDateTime = startDateTime.getTime();
		}
		else {
			leaveRequestCacheModel.startDateTime = Long.MIN_VALUE;
		}

		Date endDateTime = getEndDateTime();

		if (endDateTime != null) {
			leaveRequestCacheModel.endDateTime = endDateTime.getTime();
		}
		else {
			leaveRequestCacheModel.endDateTime = Long.MIN_VALUE;
		}

		leaveRequestCacheModel.reason = getReason();

		String reason = leaveRequestCacheModel.reason;

		if ((reason != null) && (reason.length() == 0)) {
			leaveRequestCacheModel.reason = null;
		}

		leaveRequestCacheModel.leaveCompensatoryStatusMasterId =
			getLeaveCompensatoryStatusMasterId();

		leaveRequestCacheModel.hrApprovalId = getHrApprovalId();

		leaveRequestCacheModel.managerApprovalId = getManagerApprovalId();

		Date dateOfRequest = getDateOfRequest();

		if (dateOfRequest != null) {
			leaveRequestCacheModel.dateOfRequest = dateOfRequest.getTime();
		}
		else {
			leaveRequestCacheModel.dateOfRequest = Long.MIN_VALUE;
		}

		return leaveRequestCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<LeaveRequest, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<LeaveRequest, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LeaveRequest, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((LeaveRequest)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, LeaveRequest>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					LeaveRequest.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _companyId;
	private long _createdBy;
	private long _modifiedBy;
	private long _groupId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _leaveRequestId;
	private long _employeeId;
	private long _leaveTypeMasterId;
	private Date _startDateTime;
	private Date _endDateTime;
	private String _reason;
	private long _leaveCompensatoryStatusMasterId;
	private long _hrApprovalId;
	private long _managerApprovalId;
	private Date _dateOfRequest;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<LeaveRequest, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((LeaveRequest)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createdBy", _createdBy);
		_columnOriginalValues.put("modifiedBy", _modifiedBy);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("leaveRequestId", _leaveRequestId);
		_columnOriginalValues.put("employeeId", _employeeId);
		_columnOriginalValues.put("leaveTypeMasterId", _leaveTypeMasterId);
		_columnOriginalValues.put("startDateTime", _startDateTime);
		_columnOriginalValues.put("endDateTime", _endDateTime);
		_columnOriginalValues.put("reason", _reason);
		_columnOriginalValues.put(
			"leaveCompensatoryStatusMasterId",
			_leaveCompensatoryStatusMasterId);
		_columnOriginalValues.put("hrApprovalId", _hrApprovalId);
		_columnOriginalValues.put("managerApprovalId", _managerApprovalId);
		_columnOriginalValues.put("dateOfRequest", _dateOfRequest);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("createdBy", 4L);

		columnBitmasks.put("modifiedBy", 8L);

		columnBitmasks.put("groupId", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("leaveRequestId", 128L);

		columnBitmasks.put("employeeId", 256L);

		columnBitmasks.put("leaveTypeMasterId", 512L);

		columnBitmasks.put("startDateTime", 1024L);

		columnBitmasks.put("endDateTime", 2048L);

		columnBitmasks.put("reason", 4096L);

		columnBitmasks.put("leaveCompensatoryStatusMasterId", 8192L);

		columnBitmasks.put("hrApprovalId", 16384L);

		columnBitmasks.put("managerApprovalId", 32768L);

		columnBitmasks.put("dateOfRequest", 65536L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private LeaveRequest _escapedModel;

}