/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.model.impl;

import com.ax.hrms.model.LeaveDayType;
import com.ax.hrms.service.LeaveDayTypeLocalServiceUtil;

/**
 * The extended model base implementation for the LeaveDayType service. Represents a row in the &quot;ax_LeaveDayType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LeaveDayTypeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LeaveDayTypeImpl
 * @see LeaveDayType
 * @generated
 */
public abstract class LeaveDayTypeBaseImpl
	extends LeaveDayTypeModelImpl implements LeaveDayType {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a leave day type model instance should use the <code>LeaveDayType</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			LeaveDayTypeLocalServiceUtil.addLeaveDayType(this);
		}
		else {
			LeaveDayTypeLocalServiceUtil.updateLeaveDayType(this);
		}
	}

}