/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.model.impl;

import com.ax.hrms.model.LeaveBalanceHistory;
import com.ax.hrms.model.LeaveBalanceHistoryModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the LeaveBalanceHistory service. Represents a row in the &quot;ax_LeaveBalanceHistory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>LeaveBalanceHistoryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LeaveBalanceHistoryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LeaveBalanceHistoryImpl
 * @generated
 */
@JSON(strict = true)
public class LeaveBalanceHistoryModelImpl
	extends BaseModelImpl<LeaveBalanceHistory>
	implements LeaveBalanceHistoryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a leave balance history model instance should use the <code>LeaveBalanceHistory</code> interface instead.
	 */
	public static final String TABLE_NAME = "ax_LeaveBalanceHistory";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"companyId", Types.BIGINT},
		{"createdBy", Types.BIGINT}, {"modifiedBy", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP},
		{"leaveBalanceHistoryId", Types.BIGINT},
		{"leaveBalanceId", Types.BIGINT}, {"employeeId", Types.BIGINT},
		{"leaveTypeMasterId", Types.BIGINT}, {"year", Types.INTEGER},
		{"noOfUsedLeaves", Types.DOUBLE}, {"noOfRemainingLeaves", Types.DOUBLE}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("leaveBalanceHistoryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("leaveBalanceId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("employeeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("leaveTypeMasterId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("year", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("noOfUsedLeaves", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("noOfRemainingLeaves", Types.DOUBLE);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ax_LeaveBalanceHistory (uuid_ VARCHAR(75) null,companyId LONG,createdBy LONG,modifiedBy LONG,groupId LONG,createDate DATE null,modifiedDate DATE null,leaveBalanceHistoryId LONG not null primary key,leaveBalanceId LONG,employeeId LONG,leaveTypeMasterId LONG,year INTEGER,noOfUsedLeaves DOUBLE,noOfRemainingLeaves DOUBLE)";

	public static final String TABLE_SQL_DROP =
		"drop table ax_LeaveBalanceHistory";

	public static final String ORDER_BY_JPQL =
		" ORDER BY leaveBalanceHistory.leaveBalanceHistoryId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ax_LeaveBalanceHistory.leaveBalanceHistoryId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EMPLOYEEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long YEAR_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LEAVEBALANCEHISTORYID_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public LeaveBalanceHistoryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _leaveBalanceHistoryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLeaveBalanceHistoryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _leaveBalanceHistoryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return LeaveBalanceHistory.class;
	}

	@Override
	public String getModelClassName() {
		return LeaveBalanceHistory.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<LeaveBalanceHistory, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<LeaveBalanceHistory, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LeaveBalanceHistory, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((LeaveBalanceHistory)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<LeaveBalanceHistory, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<LeaveBalanceHistory, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(LeaveBalanceHistory)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<LeaveBalanceHistory, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<LeaveBalanceHistory, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<LeaveBalanceHistory, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<LeaveBalanceHistory, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<LeaveBalanceHistory, Object>>();

			attributeGetterFunctions.put("uuid", LeaveBalanceHistory::getUuid);
			attributeGetterFunctions.put(
				"companyId", LeaveBalanceHistory::getCompanyId);
			attributeGetterFunctions.put(
				"createdBy", LeaveBalanceHistory::getCreatedBy);
			attributeGetterFunctions.put(
				"modifiedBy", LeaveBalanceHistory::getModifiedBy);
			attributeGetterFunctions.put(
				"groupId", LeaveBalanceHistory::getGroupId);
			attributeGetterFunctions.put(
				"createDate", LeaveBalanceHistory::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", LeaveBalanceHistory::getModifiedDate);
			attributeGetterFunctions.put(
				"leaveBalanceHistoryId",
				LeaveBalanceHistory::getLeaveBalanceHistoryId);
			attributeGetterFunctions.put(
				"leaveBalanceId", LeaveBalanceHistory::getLeaveBalanceId);
			attributeGetterFunctions.put(
				"employeeId", LeaveBalanceHistory::getEmployeeId);
			attributeGetterFunctions.put(
				"leaveTypeMasterId", LeaveBalanceHistory::getLeaveTypeMasterId);
			attributeGetterFunctions.put("year", LeaveBalanceHistory::getYear);
			attributeGetterFunctions.put(
				"noOfUsedLeaves", LeaveBalanceHistory::getNoOfUsedLeaves);
			attributeGetterFunctions.put(
				"noOfRemainingLeaves",
				LeaveBalanceHistory::getNoOfRemainingLeaves);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<LeaveBalanceHistory, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<LeaveBalanceHistory, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<LeaveBalanceHistory, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<LeaveBalanceHistory, String>)
					LeaveBalanceHistory::setUuid);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<LeaveBalanceHistory, Long>)
					LeaveBalanceHistory::setCompanyId);
			attributeSetterBiConsumers.put(
				"createdBy",
				(BiConsumer<LeaveBalanceHistory, Long>)
					LeaveBalanceHistory::setCreatedBy);
			attributeSetterBiConsumers.put(
				"modifiedBy",
				(BiConsumer<LeaveBalanceHistory, Long>)
					LeaveBalanceHistory::setModifiedBy);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<LeaveBalanceHistory, Long>)
					LeaveBalanceHistory::setGroupId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<LeaveBalanceHistory, Date>)
					LeaveBalanceHistory::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<LeaveBalanceHistory, Date>)
					LeaveBalanceHistory::setModifiedDate);
			attributeSetterBiConsumers.put(
				"leaveBalanceHistoryId",
				(BiConsumer<LeaveBalanceHistory, Long>)
					LeaveBalanceHistory::setLeaveBalanceHistoryId);
			attributeSetterBiConsumers.put(
				"leaveBalanceId",
				(BiConsumer<LeaveBalanceHistory, Long>)
					LeaveBalanceHistory::setLeaveBalanceId);
			attributeSetterBiConsumers.put(
				"employeeId",
				(BiConsumer<LeaveBalanceHistory, Long>)
					LeaveBalanceHistory::setEmployeeId);
			attributeSetterBiConsumers.put(
				"leaveTypeMasterId",
				(BiConsumer<LeaveBalanceHistory, Long>)
					LeaveBalanceHistory::setLeaveTypeMasterId);
			attributeSetterBiConsumers.put(
				"year",
				(BiConsumer<LeaveBalanceHistory, Integer>)
					LeaveBalanceHistory::setYear);
			attributeSetterBiConsumers.put(
				"noOfUsedLeaves",
				(BiConsumer<LeaveBalanceHistory, Double>)
					LeaveBalanceHistory::setNoOfUsedLeaves);
			attributeSetterBiConsumers.put(
				"noOfRemainingLeaves",
				(BiConsumer<LeaveBalanceHistory, Double>)
					LeaveBalanceHistory::setNoOfRemainingLeaves);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getLeaveBalanceHistoryId() {
		return _leaveBalanceHistoryId;
	}

	@Override
	public void setLeaveBalanceHistoryId(long leaveBalanceHistoryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_leaveBalanceHistoryId = leaveBalanceHistoryId;
	}

	@JSON
	@Override
	public long getLeaveBalanceId() {
		return _leaveBalanceId;
	}

	@Override
	public void setLeaveBalanceId(long leaveBalanceId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_leaveBalanceId = leaveBalanceId;
	}

	@JSON
	@Override
	public long getEmployeeId() {
		return _employeeId;
	}

	@Override
	public void setEmployeeId(long employeeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_employeeId = employeeId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalEmployeeId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("employeeId"));
	}

	@JSON
	@Override
	public long getLeaveTypeMasterId() {
		return _leaveTypeMasterId;
	}

	@Override
	public void setLeaveTypeMasterId(long leaveTypeMasterId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_leaveTypeMasterId = leaveTypeMasterId;
	}

	@JSON
	@Override
	public int getYear() {
		return _year;
	}

	@Override
	public void setYear(int year) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_year = year;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalYear() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("year"));
	}

	@JSON
	@Override
	public double getNoOfUsedLeaves() {
		return _noOfUsedLeaves;
	}

	@Override
	public void setNoOfUsedLeaves(double noOfUsedLeaves) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_noOfUsedLeaves = noOfUsedLeaves;
	}

	@JSON
	@Override
	public double getNoOfRemainingLeaves() {
		return _noOfRemainingLeaves;
	}

	@Override
	public void setNoOfRemainingLeaves(double noOfRemainingLeaves) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_noOfRemainingLeaves = noOfRemainingLeaves;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(LeaveBalanceHistory.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), LeaveBalanceHistory.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public LeaveBalanceHistory toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, LeaveBalanceHistory>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LeaveBalanceHistoryImpl leaveBalanceHistoryImpl =
			new LeaveBalanceHistoryImpl();

		leaveBalanceHistoryImpl.setUuid(getUuid());
		leaveBalanceHistoryImpl.setCompanyId(getCompanyId());
		leaveBalanceHistoryImpl.setCreatedBy(getCreatedBy());
		leaveBalanceHistoryImpl.setModifiedBy(getModifiedBy());
		leaveBalanceHistoryImpl.setGroupId(getGroupId());
		leaveBalanceHistoryImpl.setCreateDate(getCreateDate());
		leaveBalanceHistoryImpl.setModifiedDate(getModifiedDate());
		leaveBalanceHistoryImpl.setLeaveBalanceHistoryId(
			getLeaveBalanceHistoryId());
		leaveBalanceHistoryImpl.setLeaveBalanceId(getLeaveBalanceId());
		leaveBalanceHistoryImpl.setEmployeeId(getEmployeeId());
		leaveBalanceHistoryImpl.setLeaveTypeMasterId(getLeaveTypeMasterId());
		leaveBalanceHistoryImpl.setYear(getYear());
		leaveBalanceHistoryImpl.setNoOfUsedLeaves(getNoOfUsedLeaves());
		leaveBalanceHistoryImpl.setNoOfRemainingLeaves(
			getNoOfRemainingLeaves());

		leaveBalanceHistoryImpl.resetOriginalValues();

		return leaveBalanceHistoryImpl;
	}

	@Override
	public LeaveBalanceHistory cloneWithOriginalValues() {
		LeaveBalanceHistoryImpl leaveBalanceHistoryImpl =
			new LeaveBalanceHistoryImpl();

		leaveBalanceHistoryImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		leaveBalanceHistoryImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		leaveBalanceHistoryImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("createdBy"));
		leaveBalanceHistoryImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modifiedBy"));
		leaveBalanceHistoryImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		leaveBalanceHistoryImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		leaveBalanceHistoryImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		leaveBalanceHistoryImpl.setLeaveBalanceHistoryId(
			this.<Long>getColumnOriginalValue("leaveBalanceHistoryId"));
		leaveBalanceHistoryImpl.setLeaveBalanceId(
			this.<Long>getColumnOriginalValue("leaveBalanceId"));
		leaveBalanceHistoryImpl.setEmployeeId(
			this.<Long>getColumnOriginalValue("employeeId"));
		leaveBalanceHistoryImpl.setLeaveTypeMasterId(
			this.<Long>getColumnOriginalValue("leaveTypeMasterId"));
		leaveBalanceHistoryImpl.setYear(
			this.<Integer>getColumnOriginalValue("year"));
		leaveBalanceHistoryImpl.setNoOfUsedLeaves(
			this.<Double>getColumnOriginalValue("noOfUsedLeaves"));
		leaveBalanceHistoryImpl.setNoOfRemainingLeaves(
			this.<Double>getColumnOriginalValue("noOfRemainingLeaves"));

		return leaveBalanceHistoryImpl;
	}

	@Override
	public int compareTo(LeaveBalanceHistory leaveBalanceHistory) {
		long primaryKey = leaveBalanceHistory.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof LeaveBalanceHistory)) {
			return false;
		}

		LeaveBalanceHistory leaveBalanceHistory = (LeaveBalanceHistory)object;

		long primaryKey = leaveBalanceHistory.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<LeaveBalanceHistory> toCacheModel() {
		LeaveBalanceHistoryCacheModel leaveBalanceHistoryCacheModel =
			new LeaveBalanceHistoryCacheModel();

		leaveBalanceHistoryCacheModel.uuid = getUuid();

		String uuid = leaveBalanceHistoryCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			leaveBalanceHistoryCacheModel.uuid = null;
		}

		leaveBalanceHistoryCacheModel.companyId = getCompanyId();

		leaveBalanceHistoryCacheModel.createdBy = getCreatedBy();

		leaveBalanceHistoryCacheModel.modifiedBy = getModifiedBy();

		leaveBalanceHistoryCacheModel.groupId = getGroupId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			leaveBalanceHistoryCacheModel.createDate = createDate.getTime();
		}
		else {
			leaveBalanceHistoryCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			leaveBalanceHistoryCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			leaveBalanceHistoryCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		leaveBalanceHistoryCacheModel.leaveBalanceHistoryId =
			getLeaveBalanceHistoryId();

		leaveBalanceHistoryCacheModel.leaveBalanceId = getLeaveBalanceId();

		leaveBalanceHistoryCacheModel.employeeId = getEmployeeId();

		leaveBalanceHistoryCacheModel.leaveTypeMasterId =
			getLeaveTypeMasterId();

		leaveBalanceHistoryCacheModel.year = getYear();

		leaveBalanceHistoryCacheModel.noOfUsedLeaves = getNoOfUsedLeaves();

		leaveBalanceHistoryCacheModel.noOfRemainingLeaves =
			getNoOfRemainingLeaves();

		return leaveBalanceHistoryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<LeaveBalanceHistory, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<LeaveBalanceHistory, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LeaveBalanceHistory, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(LeaveBalanceHistory)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, LeaveBalanceHistory>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					LeaveBalanceHistory.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _companyId;
	private long _createdBy;
	private long _modifiedBy;
	private long _groupId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _leaveBalanceHistoryId;
	private long _leaveBalanceId;
	private long _employeeId;
	private long _leaveTypeMasterId;
	private int _year;
	private double _noOfUsedLeaves;
	private double _noOfRemainingLeaves;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<LeaveBalanceHistory, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((LeaveBalanceHistory)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createdBy", _createdBy);
		_columnOriginalValues.put("modifiedBy", _modifiedBy);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put(
			"leaveBalanceHistoryId", _leaveBalanceHistoryId);
		_columnOriginalValues.put("leaveBalanceId", _leaveBalanceId);
		_columnOriginalValues.put("employeeId", _employeeId);
		_columnOriginalValues.put("leaveTypeMasterId", _leaveTypeMasterId);
		_columnOriginalValues.put("year", _year);
		_columnOriginalValues.put("noOfUsedLeaves", _noOfUsedLeaves);
		_columnOriginalValues.put("noOfRemainingLeaves", _noOfRemainingLeaves);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("createdBy", 4L);

		columnBitmasks.put("modifiedBy", 8L);

		columnBitmasks.put("groupId", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("leaveBalanceHistoryId", 128L);

		columnBitmasks.put("leaveBalanceId", 256L);

		columnBitmasks.put("employeeId", 512L);

		columnBitmasks.put("leaveTypeMasterId", 1024L);

		columnBitmasks.put("year", 2048L);

		columnBitmasks.put("noOfUsedLeaves", 4096L);

		columnBitmasks.put("noOfRemainingLeaves", 8192L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private LeaveBalanceHistory _escapedModel;

}