/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.model.impl;

import com.ax.hrms.model.Nominee;
import com.ax.hrms.service.NomineeLocalServiceUtil;

/**
 * The extended model base implementation for the Nominee service. Represents a row in the &quot;ax_Nominee&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link NomineeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see NomineeImpl
 * @see Nominee
 * @generated
 */
public abstract class NomineeBaseImpl
	extends NomineeModelImpl implements Nominee {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a nominee model instance should use the <code>Nominee</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			NomineeLocalServiceUtil.addNominee(this);
		}
		else {
			NomineeLocalServiceUtil.updateNominee(this);
		}
	}

}