/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.model.impl;

import com.ax.hrms.model.Nominee;
import com.ax.hrms.model.NomineeModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Nominee service. Represents a row in the &quot;ax_Nominee&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>NomineeModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link NomineeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see NomineeImpl
 * @generated
 */
@JSON(strict = true)
public class NomineeModelImpl
	extends BaseModelImpl<Nominee> implements NomineeModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a nominee model instance should use the <code>Nominee</code> interface instead.
	 */
	public static final String TABLE_NAME = "ax_Nominee";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"companyId", Types.BIGINT},
		{"createdBy", Types.BIGINT}, {"modifiedBy", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"nomineeId", Types.BIGINT},
		{"nomineeFirstName", Types.VARCHAR}, {"nomineeLastName", Types.VARCHAR},
		{"nomineeContact", Types.VARCHAR}, {"nomineeAddress", Types.BIGINT},
		{"relationshipWithNominee", Types.VARCHAR},
		{"nomineeDob", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("nomineeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("nomineeFirstName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("nomineeLastName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("nomineeContact", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("nomineeAddress", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("relationshipWithNominee", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("nomineeDob", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ax_Nominee (uuid_ VARCHAR(75) null,companyId LONG,createdBy LONG,modifiedBy LONG,groupId LONG,createDate DATE null,modifiedDate DATE null,nomineeId LONG not null primary key,nomineeFirstName VARCHAR(75) null,nomineeLastName VARCHAR(75) null,nomineeContact VARCHAR(75) null,nomineeAddress LONG,relationshipWithNominee VARCHAR(75) null,nomineeDob DATE null)";

	public static final String TABLE_SQL_DROP = "drop table ax_Nominee";

	public static final String ORDER_BY_JPQL =
		" ORDER BY nominee.nomineeId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ax_Nominee.nomineeId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NOMINEEID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public NomineeModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _nomineeId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setNomineeId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _nomineeId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Nominee.class;
	}

	@Override
	public String getModelClassName() {
		return Nominee.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Nominee, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Nominee, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Nominee, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Nominee)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Nominee, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Nominee, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Nominee)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Nominee, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Nominee, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Nominee, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Nominee, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Nominee, Object>>();

			attributeGetterFunctions.put("uuid", Nominee::getUuid);
			attributeGetterFunctions.put("companyId", Nominee::getCompanyId);
			attributeGetterFunctions.put("createdBy", Nominee::getCreatedBy);
			attributeGetterFunctions.put("modifiedBy", Nominee::getModifiedBy);
			attributeGetterFunctions.put("groupId", Nominee::getGroupId);
			attributeGetterFunctions.put("createDate", Nominee::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", Nominee::getModifiedDate);
			attributeGetterFunctions.put("nomineeId", Nominee::getNomineeId);
			attributeGetterFunctions.put(
				"nomineeFirstName", Nominee::getNomineeFirstName);
			attributeGetterFunctions.put(
				"nomineeLastName", Nominee::getNomineeLastName);
			attributeGetterFunctions.put(
				"nomineeContact", Nominee::getNomineeContact);
			attributeGetterFunctions.put(
				"nomineeAddress", Nominee::getNomineeAddress);
			attributeGetterFunctions.put(
				"relationshipWithNominee", Nominee::getRelationshipWithNominee);
			attributeGetterFunctions.put("nomineeDob", Nominee::getNomineeDob);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Nominee, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Nominee, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Nominee, ?>>();

			attributeSetterBiConsumers.put(
				"uuid", (BiConsumer<Nominee, String>)Nominee::setUuid);
			attributeSetterBiConsumers.put(
				"companyId", (BiConsumer<Nominee, Long>)Nominee::setCompanyId);
			attributeSetterBiConsumers.put(
				"createdBy", (BiConsumer<Nominee, Long>)Nominee::setCreatedBy);
			attributeSetterBiConsumers.put(
				"modifiedBy",
				(BiConsumer<Nominee, Long>)Nominee::setModifiedBy);
			attributeSetterBiConsumers.put(
				"groupId", (BiConsumer<Nominee, Long>)Nominee::setGroupId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<Nominee, Date>)Nominee::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<Nominee, Date>)Nominee::setModifiedDate);
			attributeSetterBiConsumers.put(
				"nomineeId", (BiConsumer<Nominee, Long>)Nominee::setNomineeId);
			attributeSetterBiConsumers.put(
				"nomineeFirstName",
				(BiConsumer<Nominee, String>)Nominee::setNomineeFirstName);
			attributeSetterBiConsumers.put(
				"nomineeLastName",
				(BiConsumer<Nominee, String>)Nominee::setNomineeLastName);
			attributeSetterBiConsumers.put(
				"nomineeContact",
				(BiConsumer<Nominee, String>)Nominee::setNomineeContact);
			attributeSetterBiConsumers.put(
				"nomineeAddress",
				(BiConsumer<Nominee, Long>)Nominee::setNomineeAddress);
			attributeSetterBiConsumers.put(
				"relationshipWithNominee",
				(BiConsumer<Nominee, String>)
					Nominee::setRelationshipWithNominee);
			attributeSetterBiConsumers.put(
				"nomineeDob",
				(BiConsumer<Nominee, Date>)Nominee::setNomineeDob);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getNomineeId() {
		return _nomineeId;
	}

	@Override
	public void setNomineeId(long nomineeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nomineeId = nomineeId;
	}

	@JSON
	@Override
	public String getNomineeFirstName() {
		if (_nomineeFirstName == null) {
			return "";
		}
		else {
			return _nomineeFirstName;
		}
	}

	@Override
	public void setNomineeFirstName(String nomineeFirstName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nomineeFirstName = nomineeFirstName;
	}

	@JSON
	@Override
	public String getNomineeLastName() {
		if (_nomineeLastName == null) {
			return "";
		}
		else {
			return _nomineeLastName;
		}
	}

	@Override
	public void setNomineeLastName(String nomineeLastName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nomineeLastName = nomineeLastName;
	}

	@JSON
	@Override
	public String getNomineeContact() {
		if (_nomineeContact == null) {
			return "";
		}
		else {
			return _nomineeContact;
		}
	}

	@Override
	public void setNomineeContact(String nomineeContact) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nomineeContact = nomineeContact;
	}

	@JSON
	@Override
	public long getNomineeAddress() {
		return _nomineeAddress;
	}

	@Override
	public void setNomineeAddress(long nomineeAddress) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nomineeAddress = nomineeAddress;
	}

	@JSON
	@Override
	public String getRelationshipWithNominee() {
		if (_relationshipWithNominee == null) {
			return "";
		}
		else {
			return _relationshipWithNominee;
		}
	}

	@Override
	public void setRelationshipWithNominee(String relationshipWithNominee) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_relationshipWithNominee = relationshipWithNominee;
	}

	@JSON
	@Override
	public Date getNomineeDob() {
		return _nomineeDob;
	}

	@Override
	public void setNomineeDob(Date nomineeDob) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nomineeDob = nomineeDob;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Nominee.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Nominee.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Nominee toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Nominee>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		NomineeImpl nomineeImpl = new NomineeImpl();

		nomineeImpl.setUuid(getUuid());
		nomineeImpl.setCompanyId(getCompanyId());
		nomineeImpl.setCreatedBy(getCreatedBy());
		nomineeImpl.setModifiedBy(getModifiedBy());
		nomineeImpl.setGroupId(getGroupId());
		nomineeImpl.setCreateDate(getCreateDate());
		nomineeImpl.setModifiedDate(getModifiedDate());
		nomineeImpl.setNomineeId(getNomineeId());
		nomineeImpl.setNomineeFirstName(getNomineeFirstName());
		nomineeImpl.setNomineeLastName(getNomineeLastName());
		nomineeImpl.setNomineeContact(getNomineeContact());
		nomineeImpl.setNomineeAddress(getNomineeAddress());
		nomineeImpl.setRelationshipWithNominee(getRelationshipWithNominee());
		nomineeImpl.setNomineeDob(getNomineeDob());

		nomineeImpl.resetOriginalValues();

		return nomineeImpl;
	}

	@Override
	public Nominee cloneWithOriginalValues() {
		NomineeImpl nomineeImpl = new NomineeImpl();

		nomineeImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		nomineeImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		nomineeImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("createdBy"));
		nomineeImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modifiedBy"));
		nomineeImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		nomineeImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		nomineeImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		nomineeImpl.setNomineeId(
			this.<Long>getColumnOriginalValue("nomineeId"));
		nomineeImpl.setNomineeFirstName(
			this.<String>getColumnOriginalValue("nomineeFirstName"));
		nomineeImpl.setNomineeLastName(
			this.<String>getColumnOriginalValue("nomineeLastName"));
		nomineeImpl.setNomineeContact(
			this.<String>getColumnOriginalValue("nomineeContact"));
		nomineeImpl.setNomineeAddress(
			this.<Long>getColumnOriginalValue("nomineeAddress"));
		nomineeImpl.setRelationshipWithNominee(
			this.<String>getColumnOriginalValue("relationshipWithNominee"));
		nomineeImpl.setNomineeDob(
			this.<Date>getColumnOriginalValue("nomineeDob"));

		return nomineeImpl;
	}

	@Override
	public int compareTo(Nominee nominee) {
		long primaryKey = nominee.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Nominee)) {
			return false;
		}

		Nominee nominee = (Nominee)object;

		long primaryKey = nominee.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Nominee> toCacheModel() {
		NomineeCacheModel nomineeCacheModel = new NomineeCacheModel();

		nomineeCacheModel.uuid = getUuid();

		String uuid = nomineeCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			nomineeCacheModel.uuid = null;
		}

		nomineeCacheModel.companyId = getCompanyId();

		nomineeCacheModel.createdBy = getCreatedBy();

		nomineeCacheModel.modifiedBy = getModifiedBy();

		nomineeCacheModel.groupId = getGroupId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			nomineeCacheModel.createDate = createDate.getTime();
		}
		else {
			nomineeCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			nomineeCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			nomineeCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		nomineeCacheModel.nomineeId = getNomineeId();

		nomineeCacheModel.nomineeFirstName = getNomineeFirstName();

		String nomineeFirstName = nomineeCacheModel.nomineeFirstName;

		if ((nomineeFirstName != null) && (nomineeFirstName.length() == 0)) {
			nomineeCacheModel.nomineeFirstName = null;
		}

		nomineeCacheModel.nomineeLastName = getNomineeLastName();

		String nomineeLastName = nomineeCacheModel.nomineeLastName;

		if ((nomineeLastName != null) && (nomineeLastName.length() == 0)) {
			nomineeCacheModel.nomineeLastName = null;
		}

		nomineeCacheModel.nomineeContact = getNomineeContact();

		String nomineeContact = nomineeCacheModel.nomineeContact;

		if ((nomineeContact != null) && (nomineeContact.length() == 0)) {
			nomineeCacheModel.nomineeContact = null;
		}

		nomineeCacheModel.nomineeAddress = getNomineeAddress();

		nomineeCacheModel.relationshipWithNominee =
			getRelationshipWithNominee();

		String relationshipWithNominee =
			nomineeCacheModel.relationshipWithNominee;

		if ((relationshipWithNominee != null) &&
			(relationshipWithNominee.length() == 0)) {

			nomineeCacheModel.relationshipWithNominee = null;
		}

		Date nomineeDob = getNomineeDob();

		if (nomineeDob != null) {
			nomineeCacheModel.nomineeDob = nomineeDob.getTime();
		}
		else {
			nomineeCacheModel.nomineeDob = Long.MIN_VALUE;
		}

		return nomineeCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Nominee, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Nominee, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Nominee, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Nominee)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Nominee>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Nominee.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _companyId;
	private long _createdBy;
	private long _modifiedBy;
	private long _groupId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _nomineeId;
	private String _nomineeFirstName;
	private String _nomineeLastName;
	private String _nomineeContact;
	private long _nomineeAddress;
	private String _relationshipWithNominee;
	private Date _nomineeDob;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Nominee, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Nominee)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createdBy", _createdBy);
		_columnOriginalValues.put("modifiedBy", _modifiedBy);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("nomineeId", _nomineeId);
		_columnOriginalValues.put("nomineeFirstName", _nomineeFirstName);
		_columnOriginalValues.put("nomineeLastName", _nomineeLastName);
		_columnOriginalValues.put("nomineeContact", _nomineeContact);
		_columnOriginalValues.put("nomineeAddress", _nomineeAddress);
		_columnOriginalValues.put(
			"relationshipWithNominee", _relationshipWithNominee);
		_columnOriginalValues.put("nomineeDob", _nomineeDob);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("createdBy", 4L);

		columnBitmasks.put("modifiedBy", 8L);

		columnBitmasks.put("groupId", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("nomineeId", 128L);

		columnBitmasks.put("nomineeFirstName", 256L);

		columnBitmasks.put("nomineeLastName", 512L);

		columnBitmasks.put("nomineeContact", 1024L);

		columnBitmasks.put("nomineeAddress", 2048L);

		columnBitmasks.put("relationshipWithNominee", 4096L);

		columnBitmasks.put("nomineeDob", 8192L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Nominee _escapedModel;

}