/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.model.impl;

import com.ax.hrms.model.PipProgram;
import com.ax.hrms.model.PipProgramModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the PipProgram service. Represents a row in the &quot;ax_PipProgram&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>PipProgramModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PipProgramImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PipProgramImpl
 * @generated
 */
@JSON(strict = true)
public class PipProgramModelImpl
	extends BaseModelImpl<PipProgram> implements PipProgramModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a pip program model instance should use the <code>PipProgram</code> interface instead.
	 */
	public static final String TABLE_NAME = "ax_PipProgram";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"companyId", Types.BIGINT},
		{"createdBy", Types.BIGINT}, {"modifiedBy", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"pipProgramId", Types.BIGINT},
		{"employeeId", Types.BIGINT}, {"startDate", Types.TIMESTAMP},
		{"endDate", Types.TIMESTAMP}, {"numberOfMonths", Types.INTEGER},
		{"improvementAreas", Types.VARCHAR}, {"meetingDate", Types.TIMESTAMP},
		{"status", Types.VARCHAR}, {"isExtended", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("pipProgramId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("employeeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("startDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("endDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("numberOfMonths", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("improvementAreas", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("meetingDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("isExtended", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ax_PipProgram (uuid_ VARCHAR(75) null,companyId LONG,createdBy LONG,modifiedBy LONG,groupId LONG,createDate DATE null,modifiedDate DATE null,pipProgramId LONG not null primary key,employeeId LONG,startDate DATE null,endDate DATE null,numberOfMonths INTEGER,improvementAreas VARCHAR(2000) null,meetingDate DATE null,status VARCHAR(75) null,isExtended BOOLEAN)";

	public static final String TABLE_SQL_DROP = "drop table ax_PipProgram";

	public static final String ORDER_BY_JPQL =
		" ORDER BY pipProgram.pipProgramId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ax_PipProgram.pipProgramId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PIPPROGRAMID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public PipProgramModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _pipProgramId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPipProgramId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _pipProgramId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return PipProgram.class;
	}

	@Override
	public String getModelClassName() {
		return PipProgram.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<PipProgram, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<PipProgram, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PipProgram, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((PipProgram)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<PipProgram, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<PipProgram, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(PipProgram)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<PipProgram, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<PipProgram, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<PipProgram, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<PipProgram, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<PipProgram, Object>>();

			attributeGetterFunctions.put("uuid", PipProgram::getUuid);
			attributeGetterFunctions.put("companyId", PipProgram::getCompanyId);
			attributeGetterFunctions.put("createdBy", PipProgram::getCreatedBy);
			attributeGetterFunctions.put(
				"modifiedBy", PipProgram::getModifiedBy);
			attributeGetterFunctions.put("groupId", PipProgram::getGroupId);
			attributeGetterFunctions.put(
				"createDate", PipProgram::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", PipProgram::getModifiedDate);
			attributeGetterFunctions.put(
				"pipProgramId", PipProgram::getPipProgramId);
			attributeGetterFunctions.put(
				"employeeId", PipProgram::getEmployeeId);
			attributeGetterFunctions.put("startDate", PipProgram::getStartDate);
			attributeGetterFunctions.put("endDate", PipProgram::getEndDate);
			attributeGetterFunctions.put(
				"numberOfMonths", PipProgram::getNumberOfMonths);
			attributeGetterFunctions.put(
				"improvementAreas", PipProgram::getImprovementAreas);
			attributeGetterFunctions.put(
				"meetingDate", PipProgram::getMeetingDate);
			attributeGetterFunctions.put("status", PipProgram::getStatus);
			attributeGetterFunctions.put(
				"isExtended", PipProgram::getIsExtended);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<PipProgram, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<PipProgram, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<PipProgram, ?>>();

			attributeSetterBiConsumers.put(
				"uuid", (BiConsumer<PipProgram, String>)PipProgram::setUuid);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<PipProgram, Long>)PipProgram::setCompanyId);
			attributeSetterBiConsumers.put(
				"createdBy",
				(BiConsumer<PipProgram, Long>)PipProgram::setCreatedBy);
			attributeSetterBiConsumers.put(
				"modifiedBy",
				(BiConsumer<PipProgram, Long>)PipProgram::setModifiedBy);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<PipProgram, Long>)PipProgram::setGroupId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<PipProgram, Date>)PipProgram::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<PipProgram, Date>)PipProgram::setModifiedDate);
			attributeSetterBiConsumers.put(
				"pipProgramId",
				(BiConsumer<PipProgram, Long>)PipProgram::setPipProgramId);
			attributeSetterBiConsumers.put(
				"employeeId",
				(BiConsumer<PipProgram, Long>)PipProgram::setEmployeeId);
			attributeSetterBiConsumers.put(
				"startDate",
				(BiConsumer<PipProgram, Date>)PipProgram::setStartDate);
			attributeSetterBiConsumers.put(
				"endDate",
				(BiConsumer<PipProgram, Date>)PipProgram::setEndDate);
			attributeSetterBiConsumers.put(
				"numberOfMonths",
				(BiConsumer<PipProgram, Integer>)PipProgram::setNumberOfMonths);
			attributeSetterBiConsumers.put(
				"improvementAreas",
				(BiConsumer<PipProgram, String>)
					PipProgram::setImprovementAreas);
			attributeSetterBiConsumers.put(
				"meetingDate",
				(BiConsumer<PipProgram, Date>)PipProgram::setMeetingDate);
			attributeSetterBiConsumers.put(
				"status",
				(BiConsumer<PipProgram, String>)PipProgram::setStatus);
			attributeSetterBiConsumers.put(
				"isExtended",
				(BiConsumer<PipProgram, Boolean>)PipProgram::setIsExtended);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getPipProgramId() {
		return _pipProgramId;
	}

	@Override
	public void setPipProgramId(long pipProgramId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_pipProgramId = pipProgramId;
	}

	@JSON
	@Override
	public long getEmployeeId() {
		return _employeeId;
	}

	@Override
	public void setEmployeeId(long employeeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_employeeId = employeeId;
	}

	@JSON
	@Override
	public Date getStartDate() {
		return _startDate;
	}

	@Override
	public void setStartDate(Date startDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_startDate = startDate;
	}

	@JSON
	@Override
	public Date getEndDate() {
		return _endDate;
	}

	@Override
	public void setEndDate(Date endDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_endDate = endDate;
	}

	@JSON
	@Override
	public int getNumberOfMonths() {
		return _numberOfMonths;
	}

	@Override
	public void setNumberOfMonths(int numberOfMonths) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_numberOfMonths = numberOfMonths;
	}

	@JSON
	@Override
	public String getImprovementAreas() {
		if (_improvementAreas == null) {
			return "";
		}
		else {
			return _improvementAreas;
		}
	}

	@Override
	public void setImprovementAreas(String improvementAreas) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_improvementAreas = improvementAreas;
	}

	@JSON
	@Override
	public Date getMeetingDate() {
		return _meetingDate;
	}

	@Override
	public void setMeetingDate(Date meetingDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_meetingDate = meetingDate;
	}

	@JSON
	@Override
	public String getStatus() {
		if (_status == null) {
			return "";
		}
		else {
			return _status;
		}
	}

	@Override
	public void setStatus(String status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	@JSON
	@Override
	public boolean getIsExtended() {
		return _isExtended;
	}

	@JSON
	@Override
	public boolean isIsExtended() {
		return _isExtended;
	}

	@Override
	public void setIsExtended(boolean isExtended) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_isExtended = isExtended;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(PipProgram.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), PipProgram.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public PipProgram toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, PipProgram>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PipProgramImpl pipProgramImpl = new PipProgramImpl();

		pipProgramImpl.setUuid(getUuid());
		pipProgramImpl.setCompanyId(getCompanyId());
		pipProgramImpl.setCreatedBy(getCreatedBy());
		pipProgramImpl.setModifiedBy(getModifiedBy());
		pipProgramImpl.setGroupId(getGroupId());
		pipProgramImpl.setCreateDate(getCreateDate());
		pipProgramImpl.setModifiedDate(getModifiedDate());
		pipProgramImpl.setPipProgramId(getPipProgramId());
		pipProgramImpl.setEmployeeId(getEmployeeId());
		pipProgramImpl.setStartDate(getStartDate());
		pipProgramImpl.setEndDate(getEndDate());
		pipProgramImpl.setNumberOfMonths(getNumberOfMonths());
		pipProgramImpl.setImprovementAreas(getImprovementAreas());
		pipProgramImpl.setMeetingDate(getMeetingDate());
		pipProgramImpl.setStatus(getStatus());
		pipProgramImpl.setIsExtended(isIsExtended());

		pipProgramImpl.resetOriginalValues();

		return pipProgramImpl;
	}

	@Override
	public PipProgram cloneWithOriginalValues() {
		PipProgramImpl pipProgramImpl = new PipProgramImpl();

		pipProgramImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		pipProgramImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		pipProgramImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("createdBy"));
		pipProgramImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modifiedBy"));
		pipProgramImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		pipProgramImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		pipProgramImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		pipProgramImpl.setPipProgramId(
			this.<Long>getColumnOriginalValue("pipProgramId"));
		pipProgramImpl.setEmployeeId(
			this.<Long>getColumnOriginalValue("employeeId"));
		pipProgramImpl.setStartDate(
			this.<Date>getColumnOriginalValue("startDate"));
		pipProgramImpl.setEndDate(this.<Date>getColumnOriginalValue("endDate"));
		pipProgramImpl.setNumberOfMonths(
			this.<Integer>getColumnOriginalValue("numberOfMonths"));
		pipProgramImpl.setImprovementAreas(
			this.<String>getColumnOriginalValue("improvementAreas"));
		pipProgramImpl.setMeetingDate(
			this.<Date>getColumnOriginalValue("meetingDate"));
		pipProgramImpl.setStatus(this.<String>getColumnOriginalValue("status"));
		pipProgramImpl.setIsExtended(
			this.<Boolean>getColumnOriginalValue("isExtended"));

		return pipProgramImpl;
	}

	@Override
	public int compareTo(PipProgram pipProgram) {
		long primaryKey = pipProgram.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof PipProgram)) {
			return false;
		}

		PipProgram pipProgram = (PipProgram)object;

		long primaryKey = pipProgram.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<PipProgram> toCacheModel() {
		PipProgramCacheModel pipProgramCacheModel = new PipProgramCacheModel();

		pipProgramCacheModel.uuid = getUuid();

		String uuid = pipProgramCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			pipProgramCacheModel.uuid = null;
		}

		pipProgramCacheModel.companyId = getCompanyId();

		pipProgramCacheModel.createdBy = getCreatedBy();

		pipProgramCacheModel.modifiedBy = getModifiedBy();

		pipProgramCacheModel.groupId = getGroupId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			pipProgramCacheModel.createDate = createDate.getTime();
		}
		else {
			pipProgramCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			pipProgramCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			pipProgramCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		pipProgramCacheModel.pipProgramId = getPipProgramId();

		pipProgramCacheModel.employeeId = getEmployeeId();

		Date startDate = getStartDate();

		if (startDate != null) {
			pipProgramCacheModel.startDate = startDate.getTime();
		}
		else {
			pipProgramCacheModel.startDate = Long.MIN_VALUE;
		}

		Date endDate = getEndDate();

		if (endDate != null) {
			pipProgramCacheModel.endDate = endDate.getTime();
		}
		else {
			pipProgramCacheModel.endDate = Long.MIN_VALUE;
		}

		pipProgramCacheModel.numberOfMonths = getNumberOfMonths();

		pipProgramCacheModel.improvementAreas = getImprovementAreas();

		String improvementAreas = pipProgramCacheModel.improvementAreas;

		if ((improvementAreas != null) && (improvementAreas.length() == 0)) {
			pipProgramCacheModel.improvementAreas = null;
		}

		Date meetingDate = getMeetingDate();

		if (meetingDate != null) {
			pipProgramCacheModel.meetingDate = meetingDate.getTime();
		}
		else {
			pipProgramCacheModel.meetingDate = Long.MIN_VALUE;
		}

		pipProgramCacheModel.status = getStatus();

		String status = pipProgramCacheModel.status;

		if ((status != null) && (status.length() == 0)) {
			pipProgramCacheModel.status = null;
		}

		pipProgramCacheModel.isExtended = isIsExtended();

		return pipProgramCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<PipProgram, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<PipProgram, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PipProgram, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((PipProgram)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, PipProgram>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					PipProgram.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _companyId;
	private long _createdBy;
	private long _modifiedBy;
	private long _groupId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _pipProgramId;
	private long _employeeId;
	private Date _startDate;
	private Date _endDate;
	private int _numberOfMonths;
	private String _improvementAreas;
	private Date _meetingDate;
	private String _status;
	private boolean _isExtended;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<PipProgram, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((PipProgram)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createdBy", _createdBy);
		_columnOriginalValues.put("modifiedBy", _modifiedBy);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("pipProgramId", _pipProgramId);
		_columnOriginalValues.put("employeeId", _employeeId);
		_columnOriginalValues.put("startDate", _startDate);
		_columnOriginalValues.put("endDate", _endDate);
		_columnOriginalValues.put("numberOfMonths", _numberOfMonths);
		_columnOriginalValues.put("improvementAreas", _improvementAreas);
		_columnOriginalValues.put("meetingDate", _meetingDate);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("isExtended", _isExtended);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("createdBy", 4L);

		columnBitmasks.put("modifiedBy", 8L);

		columnBitmasks.put("groupId", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("pipProgramId", 128L);

		columnBitmasks.put("employeeId", 256L);

		columnBitmasks.put("startDate", 512L);

		columnBitmasks.put("endDate", 1024L);

		columnBitmasks.put("numberOfMonths", 2048L);

		columnBitmasks.put("improvementAreas", 4096L);

		columnBitmasks.put("meetingDate", 8192L);

		columnBitmasks.put("status", 16384L);

		columnBitmasks.put("isExtended", 32768L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private PipProgram _escapedModel;

}