/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.model.impl;

import com.ax.hrms.model.Policy;
import com.ax.hrms.model.PolicyModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Policy service. Represents a row in the &quot;ax_Policy&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>PolicyModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PolicyImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PolicyImpl
 * @generated
 */
@JSON(strict = true)
public class PolicyModelImpl
	extends BaseModelImpl<Policy> implements PolicyModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a policy model instance should use the <code>Policy</code> interface instead.
	 */
	public static final String TABLE_NAME = "ax_Policy";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"companyId", Types.BIGINT},
		{"createdBy", Types.BIGINT}, {"modifiedBy", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"policyId", Types.BIGINT},
		{"policyName", Types.VARCHAR}, {"policyDescription", Types.VARCHAR},
		{"year", Types.INTEGER}, {"status", Types.BOOLEAN},
		{"policyTypeId", Types.BIGINT}, {"policyDocumentId", Types.BIGINT},
		{"applicableDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("policyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("policyName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("policyDescription", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("year", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("status", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("policyTypeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("policyDocumentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("applicableDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ax_Policy (uuid_ VARCHAR(75) null,companyId LONG,createdBy LONG,modifiedBy LONG,groupId LONG,createDate DATE null,modifiedDate DATE null,policyId LONG not null primary key,policyName VARCHAR(75) null,policyDescription VARCHAR(75) null,year INTEGER,status BOOLEAN,policyTypeId LONG,policyDocumentId LONG,applicableDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table ax_Policy";

	public static final String ORDER_BY_JPQL =
		" ORDER BY policy.applicableDate ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ax_Policy.applicableDate ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long POLICYTYPEID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long YEAR_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long APPLICABLEDATE_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public PolicyModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _policyId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPolicyId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _policyId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Policy.class;
	}

	@Override
	public String getModelClassName() {
		return Policy.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Policy, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Policy, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Policy, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Policy)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Policy, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Policy, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Policy)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Policy, Object>> getAttributeGetterFunctions() {
		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Policy, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Policy, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Policy, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Policy, Object>>();

			attributeGetterFunctions.put("uuid", Policy::getUuid);
			attributeGetterFunctions.put("companyId", Policy::getCompanyId);
			attributeGetterFunctions.put("createdBy", Policy::getCreatedBy);
			attributeGetterFunctions.put("modifiedBy", Policy::getModifiedBy);
			attributeGetterFunctions.put("groupId", Policy::getGroupId);
			attributeGetterFunctions.put("createDate", Policy::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", Policy::getModifiedDate);
			attributeGetterFunctions.put("policyId", Policy::getPolicyId);
			attributeGetterFunctions.put("policyName", Policy::getPolicyName);
			attributeGetterFunctions.put(
				"policyDescription", Policy::getPolicyDescription);
			attributeGetterFunctions.put("year", Policy::getYear);
			attributeGetterFunctions.put("status", Policy::getStatus);
			attributeGetterFunctions.put(
				"policyTypeId", Policy::getPolicyTypeId);
			attributeGetterFunctions.put(
				"policyDocumentId", Policy::getPolicyDocumentId);
			attributeGetterFunctions.put(
				"applicableDate", Policy::getApplicableDate);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Policy, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Policy, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Policy, ?>>();

			attributeSetterBiConsumers.put(
				"uuid", (BiConsumer<Policy, String>)Policy::setUuid);
			attributeSetterBiConsumers.put(
				"companyId", (BiConsumer<Policy, Long>)Policy::setCompanyId);
			attributeSetterBiConsumers.put(
				"createdBy", (BiConsumer<Policy, Long>)Policy::setCreatedBy);
			attributeSetterBiConsumers.put(
				"modifiedBy", (BiConsumer<Policy, Long>)Policy::setModifiedBy);
			attributeSetterBiConsumers.put(
				"groupId", (BiConsumer<Policy, Long>)Policy::setGroupId);
			attributeSetterBiConsumers.put(
				"createDate", (BiConsumer<Policy, Date>)Policy::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<Policy, Date>)Policy::setModifiedDate);
			attributeSetterBiConsumers.put(
				"policyId", (BiConsumer<Policy, Long>)Policy::setPolicyId);
			attributeSetterBiConsumers.put(
				"policyName",
				(BiConsumer<Policy, String>)Policy::setPolicyName);
			attributeSetterBiConsumers.put(
				"policyDescription",
				(BiConsumer<Policy, String>)Policy::setPolicyDescription);
			attributeSetterBiConsumers.put(
				"year", (BiConsumer<Policy, Integer>)Policy::setYear);
			attributeSetterBiConsumers.put(
				"status", (BiConsumer<Policy, Boolean>)Policy::setStatus);
			attributeSetterBiConsumers.put(
				"policyTypeId",
				(BiConsumer<Policy, Long>)Policy::setPolicyTypeId);
			attributeSetterBiConsumers.put(
				"policyDocumentId",
				(BiConsumer<Policy, Long>)Policy::setPolicyDocumentId);
			attributeSetterBiConsumers.put(
				"applicableDate",
				(BiConsumer<Policy, Date>)Policy::setApplicableDate);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getPolicyId() {
		return _policyId;
	}

	@Override
	public void setPolicyId(long policyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_policyId = policyId;
	}

	@JSON
	@Override
	public String getPolicyName() {
		if (_policyName == null) {
			return "";
		}
		else {
			return _policyName;
		}
	}

	@Override
	public void setPolicyName(String policyName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_policyName = policyName;
	}

	@JSON
	@Override
	public String getPolicyDescription() {
		if (_policyDescription == null) {
			return "";
		}
		else {
			return _policyDescription;
		}
	}

	@Override
	public void setPolicyDescription(String policyDescription) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_policyDescription = policyDescription;
	}

	@JSON
	@Override
	public int getYear() {
		return _year;
	}

	@Override
	public void setYear(int year) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_year = year;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalYear() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("year"));
	}

	@JSON
	@Override
	public Boolean getStatus() {
		return _status;
	}

	@Override
	public void setStatus(Boolean status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	@JSON
	@Override
	public long getPolicyTypeId() {
		return _policyTypeId;
	}

	@Override
	public void setPolicyTypeId(long policyTypeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_policyTypeId = policyTypeId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalPolicyTypeId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("policyTypeId"));
	}

	@JSON
	@Override
	public long getPolicyDocumentId() {
		return _policyDocumentId;
	}

	@Override
	public void setPolicyDocumentId(long policyDocumentId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_policyDocumentId = policyDocumentId;
	}

	@JSON
	@Override
	public Date getApplicableDate() {
		return _applicableDate;
	}

	@Override
	public void setApplicableDate(Date applicableDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_applicableDate = applicableDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Policy.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Policy.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Policy toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Policy>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PolicyImpl policyImpl = new PolicyImpl();

		policyImpl.setUuid(getUuid());
		policyImpl.setCompanyId(getCompanyId());
		policyImpl.setCreatedBy(getCreatedBy());
		policyImpl.setModifiedBy(getModifiedBy());
		policyImpl.setGroupId(getGroupId());
		policyImpl.setCreateDate(getCreateDate());
		policyImpl.setModifiedDate(getModifiedDate());
		policyImpl.setPolicyId(getPolicyId());
		policyImpl.setPolicyName(getPolicyName());
		policyImpl.setPolicyDescription(getPolicyDescription());
		policyImpl.setYear(getYear());
		policyImpl.setStatus(getStatus());
		policyImpl.setPolicyTypeId(getPolicyTypeId());
		policyImpl.setPolicyDocumentId(getPolicyDocumentId());
		policyImpl.setApplicableDate(getApplicableDate());

		policyImpl.resetOriginalValues();

		return policyImpl;
	}

	@Override
	public Policy cloneWithOriginalValues() {
		PolicyImpl policyImpl = new PolicyImpl();

		policyImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		policyImpl.setCompanyId(this.<Long>getColumnOriginalValue("companyId"));
		policyImpl.setCreatedBy(this.<Long>getColumnOriginalValue("createdBy"));
		policyImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modifiedBy"));
		policyImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		policyImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		policyImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		policyImpl.setPolicyId(this.<Long>getColumnOriginalValue("policyId"));
		policyImpl.setPolicyName(
			this.<String>getColumnOriginalValue("policyName"));
		policyImpl.setPolicyDescription(
			this.<String>getColumnOriginalValue("policyDescription"));
		policyImpl.setYear(this.<Integer>getColumnOriginalValue("year"));
		policyImpl.setStatus(this.<Boolean>getColumnOriginalValue("status"));
		policyImpl.setPolicyTypeId(
			this.<Long>getColumnOriginalValue("policyTypeId"));
		policyImpl.setPolicyDocumentId(
			this.<Long>getColumnOriginalValue("policyDocumentId"));
		policyImpl.setApplicableDate(
			this.<Date>getColumnOriginalValue("applicableDate"));

		return policyImpl;
	}

	@Override
	public int compareTo(Policy policy) {
		int value = 0;

		value = DateUtil.compareTo(
			getApplicableDate(), policy.getApplicableDate());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Policy)) {
			return false;
		}

		Policy policy = (Policy)object;

		long primaryKey = policy.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Policy> toCacheModel() {
		PolicyCacheModel policyCacheModel = new PolicyCacheModel();

		policyCacheModel.uuid = getUuid();

		String uuid = policyCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			policyCacheModel.uuid = null;
		}

		policyCacheModel.companyId = getCompanyId();

		policyCacheModel.createdBy = getCreatedBy();

		policyCacheModel.modifiedBy = getModifiedBy();

		policyCacheModel.groupId = getGroupId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			policyCacheModel.createDate = createDate.getTime();
		}
		else {
			policyCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			policyCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			policyCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		policyCacheModel.policyId = getPolicyId();

		policyCacheModel.policyName = getPolicyName();

		String policyName = policyCacheModel.policyName;

		if ((policyName != null) && (policyName.length() == 0)) {
			policyCacheModel.policyName = null;
		}

		policyCacheModel.policyDescription = getPolicyDescription();

		String policyDescription = policyCacheModel.policyDescription;

		if ((policyDescription != null) && (policyDescription.length() == 0)) {
			policyCacheModel.policyDescription = null;
		}

		policyCacheModel.year = getYear();

		Boolean status = getStatus();

		if (status != null) {
			policyCacheModel.status = status;
		}

		policyCacheModel.policyTypeId = getPolicyTypeId();

		policyCacheModel.policyDocumentId = getPolicyDocumentId();

		Date applicableDate = getApplicableDate();

		if (applicableDate != null) {
			policyCacheModel.applicableDate = applicableDate.getTime();
		}
		else {
			policyCacheModel.applicableDate = Long.MIN_VALUE;
		}

		return policyCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Policy, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Policy, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Policy, Object> attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Policy)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Policy>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Policy.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _companyId;
	private long _createdBy;
	private long _modifiedBy;
	private long _groupId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _policyId;
	private String _policyName;
	private String _policyDescription;
	private int _year;
	private Boolean _status;
	private long _policyTypeId;
	private long _policyDocumentId;
	private Date _applicableDate;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Policy, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Policy)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createdBy", _createdBy);
		_columnOriginalValues.put("modifiedBy", _modifiedBy);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("policyId", _policyId);
		_columnOriginalValues.put("policyName", _policyName);
		_columnOriginalValues.put("policyDescription", _policyDescription);
		_columnOriginalValues.put("year", _year);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("policyTypeId", _policyTypeId);
		_columnOriginalValues.put("policyDocumentId", _policyDocumentId);
		_columnOriginalValues.put("applicableDate", _applicableDate);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("createdBy", 4L);

		columnBitmasks.put("modifiedBy", 8L);

		columnBitmasks.put("groupId", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("policyId", 128L);

		columnBitmasks.put("policyName", 256L);

		columnBitmasks.put("policyDescription", 512L);

		columnBitmasks.put("year", 1024L);

		columnBitmasks.put("status", 2048L);

		columnBitmasks.put("policyTypeId", 4096L);

		columnBitmasks.put("policyDocumentId", 8192L);

		columnBitmasks.put("applicableDate", 16384L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Policy _escapedModel;

}