/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.model.impl;

import com.ax.hrms.model.ProjectHistory;
import com.ax.hrms.model.ProjectHistoryModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ProjectHistory service. Represents a row in the &quot;ax_ProjectHistory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ProjectHistoryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ProjectHistoryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProjectHistoryImpl
 * @generated
 */
@JSON(strict = true)
public class ProjectHistoryModelImpl
	extends BaseModelImpl<ProjectHistory> implements ProjectHistoryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a project history model instance should use the <code>ProjectHistory</code> interface instead.
	 */
	public static final String TABLE_NAME = "ax_ProjectHistory";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"companyId", Types.BIGINT},
		{"createdBy", Types.BIGINT}, {"modifiedBy", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"projectHistoryId", Types.BIGINT},
		{"projectId", Types.BIGINT},
		{"projectTaskStatusMasterId", Types.BIGINT},
		{"managerId", Types.BIGINT}, {"startDate", Types.TIMESTAMP},
		{"isBillble", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("projectHistoryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("projectId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("projectTaskStatusMasterId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("managerId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("startDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("isBillble", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ax_ProjectHistory (uuid_ VARCHAR(75) null,companyId LONG,createdBy LONG,modifiedBy LONG,groupId LONG,createDate DATE null,modifiedDate DATE null,projectHistoryId LONG not null primary key,projectId LONG,projectTaskStatusMasterId LONG,managerId LONG,startDate DATE null,isBillble BOOLEAN)";

	public static final String TABLE_SQL_DROP = "drop table ax_ProjectHistory";

	public static final String ORDER_BY_JPQL =
		" ORDER BY projectHistory.projectHistoryId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ax_ProjectHistory.projectHistoryId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long MANAGERID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PROJECTID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PROJECTHISTORYID_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ProjectHistoryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _projectHistoryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setProjectHistoryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _projectHistoryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ProjectHistory.class;
	}

	@Override
	public String getModelClassName() {
		return ProjectHistory.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ProjectHistory, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ProjectHistory, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ProjectHistory, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ProjectHistory)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ProjectHistory, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ProjectHistory, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ProjectHistory)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ProjectHistory, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ProjectHistory, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<ProjectHistory, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<ProjectHistory, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<ProjectHistory, Object>>();

			attributeGetterFunctions.put("uuid", ProjectHistory::getUuid);
			attributeGetterFunctions.put(
				"companyId", ProjectHistory::getCompanyId);
			attributeGetterFunctions.put(
				"createdBy", ProjectHistory::getCreatedBy);
			attributeGetterFunctions.put(
				"modifiedBy", ProjectHistory::getModifiedBy);
			attributeGetterFunctions.put("groupId", ProjectHistory::getGroupId);
			attributeGetterFunctions.put(
				"createDate", ProjectHistory::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", ProjectHistory::getModifiedDate);
			attributeGetterFunctions.put(
				"projectHistoryId", ProjectHistory::getProjectHistoryId);
			attributeGetterFunctions.put(
				"projectId", ProjectHistory::getProjectId);
			attributeGetterFunctions.put(
				"projectTaskStatusMasterId",
				ProjectHistory::getProjectTaskStatusMasterId);
			attributeGetterFunctions.put(
				"managerId", ProjectHistory::getManagerId);
			attributeGetterFunctions.put(
				"startDate", ProjectHistory::getStartDate);
			attributeGetterFunctions.put(
				"isBillble", ProjectHistory::getIsBillble);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<ProjectHistory, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<ProjectHistory, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<ProjectHistory, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<ProjectHistory, String>)ProjectHistory::setUuid);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<ProjectHistory, Long>)ProjectHistory::setCompanyId);
			attributeSetterBiConsumers.put(
				"createdBy",
				(BiConsumer<ProjectHistory, Long>)ProjectHistory::setCreatedBy);
			attributeSetterBiConsumers.put(
				"modifiedBy",
				(BiConsumer<ProjectHistory, Long>)
					ProjectHistory::setModifiedBy);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<ProjectHistory, Long>)ProjectHistory::setGroupId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<ProjectHistory, Date>)
					ProjectHistory::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<ProjectHistory, Date>)
					ProjectHistory::setModifiedDate);
			attributeSetterBiConsumers.put(
				"projectHistoryId",
				(BiConsumer<ProjectHistory, Long>)
					ProjectHistory::setProjectHistoryId);
			attributeSetterBiConsumers.put(
				"projectId",
				(BiConsumer<ProjectHistory, Long>)ProjectHistory::setProjectId);
			attributeSetterBiConsumers.put(
				"projectTaskStatusMasterId",
				(BiConsumer<ProjectHistory, Long>)
					ProjectHistory::setProjectTaskStatusMasterId);
			attributeSetterBiConsumers.put(
				"managerId",
				(BiConsumer<ProjectHistory, Long>)ProjectHistory::setManagerId);
			attributeSetterBiConsumers.put(
				"startDate",
				(BiConsumer<ProjectHistory, Date>)ProjectHistory::setStartDate);
			attributeSetterBiConsumers.put(
				"isBillble",
				(BiConsumer<ProjectHistory, Boolean>)
					ProjectHistory::setIsBillble);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getProjectHistoryId() {
		return _projectHistoryId;
	}

	@Override
	public void setProjectHistoryId(long projectHistoryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_projectHistoryId = projectHistoryId;
	}

	@JSON
	@Override
	public long getProjectId() {
		return _projectId;
	}

	@Override
	public void setProjectId(long projectId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_projectId = projectId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalProjectId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("projectId"));
	}

	@JSON
	@Override
	public long getProjectTaskStatusMasterId() {
		return _projectTaskStatusMasterId;
	}

	@Override
	public void setProjectTaskStatusMasterId(long projectTaskStatusMasterId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_projectTaskStatusMasterId = projectTaskStatusMasterId;
	}

	@JSON
	@Override
	public long getManagerId() {
		return _managerId;
	}

	@Override
	public void setManagerId(long managerId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_managerId = managerId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalManagerId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("managerId"));
	}

	@JSON
	@Override
	public Date getStartDate() {
		return _startDate;
	}

	@Override
	public void setStartDate(Date startDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_startDate = startDate;
	}

	@JSON
	@Override
	public boolean getIsBillble() {
		return _isBillble;
	}

	@JSON
	@Override
	public boolean isIsBillble() {
		return _isBillble;
	}

	@Override
	public void setIsBillble(boolean isBillble) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_isBillble = isBillble;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(ProjectHistory.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), ProjectHistory.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ProjectHistory toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ProjectHistory>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ProjectHistoryImpl projectHistoryImpl = new ProjectHistoryImpl();

		projectHistoryImpl.setUuid(getUuid());
		projectHistoryImpl.setCompanyId(getCompanyId());
		projectHistoryImpl.setCreatedBy(getCreatedBy());
		projectHistoryImpl.setModifiedBy(getModifiedBy());
		projectHistoryImpl.setGroupId(getGroupId());
		projectHistoryImpl.setCreateDate(getCreateDate());
		projectHistoryImpl.setModifiedDate(getModifiedDate());
		projectHistoryImpl.setProjectHistoryId(getProjectHistoryId());
		projectHistoryImpl.setProjectId(getProjectId());
		projectHistoryImpl.setProjectTaskStatusMasterId(
			getProjectTaskStatusMasterId());
		projectHistoryImpl.setManagerId(getManagerId());
		projectHistoryImpl.setStartDate(getStartDate());
		projectHistoryImpl.setIsBillble(isIsBillble());

		projectHistoryImpl.resetOriginalValues();

		return projectHistoryImpl;
	}

	@Override
	public ProjectHistory cloneWithOriginalValues() {
		ProjectHistoryImpl projectHistoryImpl = new ProjectHistoryImpl();

		projectHistoryImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		projectHistoryImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		projectHistoryImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("createdBy"));
		projectHistoryImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modifiedBy"));
		projectHistoryImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		projectHistoryImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		projectHistoryImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		projectHistoryImpl.setProjectHistoryId(
			this.<Long>getColumnOriginalValue("projectHistoryId"));
		projectHistoryImpl.setProjectId(
			this.<Long>getColumnOriginalValue("projectId"));
		projectHistoryImpl.setProjectTaskStatusMasterId(
			this.<Long>getColumnOriginalValue("projectTaskStatusMasterId"));
		projectHistoryImpl.setManagerId(
			this.<Long>getColumnOriginalValue("managerId"));
		projectHistoryImpl.setStartDate(
			this.<Date>getColumnOriginalValue("startDate"));
		projectHistoryImpl.setIsBillble(
			this.<Boolean>getColumnOriginalValue("isBillble"));

		return projectHistoryImpl;
	}

	@Override
	public int compareTo(ProjectHistory projectHistory) {
		long primaryKey = projectHistory.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ProjectHistory)) {
			return false;
		}

		ProjectHistory projectHistory = (ProjectHistory)object;

		long primaryKey = projectHistory.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ProjectHistory> toCacheModel() {
		ProjectHistoryCacheModel projectHistoryCacheModel =
			new ProjectHistoryCacheModel();

		projectHistoryCacheModel.uuid = getUuid();

		String uuid = projectHistoryCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			projectHistoryCacheModel.uuid = null;
		}

		projectHistoryCacheModel.companyId = getCompanyId();

		projectHistoryCacheModel.createdBy = getCreatedBy();

		projectHistoryCacheModel.modifiedBy = getModifiedBy();

		projectHistoryCacheModel.groupId = getGroupId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			projectHistoryCacheModel.createDate = createDate.getTime();
		}
		else {
			projectHistoryCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			projectHistoryCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			projectHistoryCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		projectHistoryCacheModel.projectHistoryId = getProjectHistoryId();

		projectHistoryCacheModel.projectId = getProjectId();

		projectHistoryCacheModel.projectTaskStatusMasterId =
			getProjectTaskStatusMasterId();

		projectHistoryCacheModel.managerId = getManagerId();

		Date startDate = getStartDate();

		if (startDate != null) {
			projectHistoryCacheModel.startDate = startDate.getTime();
		}
		else {
			projectHistoryCacheModel.startDate = Long.MIN_VALUE;
		}

		projectHistoryCacheModel.isBillble = isIsBillble();

		return projectHistoryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ProjectHistory, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ProjectHistory, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ProjectHistory, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((ProjectHistory)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ProjectHistory>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					ProjectHistory.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _companyId;
	private long _createdBy;
	private long _modifiedBy;
	private long _groupId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _projectHistoryId;
	private long _projectId;
	private long _projectTaskStatusMasterId;
	private long _managerId;
	private Date _startDate;
	private boolean _isBillble;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<ProjectHistory, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ProjectHistory)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createdBy", _createdBy);
		_columnOriginalValues.put("modifiedBy", _modifiedBy);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("projectHistoryId", _projectHistoryId);
		_columnOriginalValues.put("projectId", _projectId);
		_columnOriginalValues.put(
			"projectTaskStatusMasterId", _projectTaskStatusMasterId);
		_columnOriginalValues.put("managerId", _managerId);
		_columnOriginalValues.put("startDate", _startDate);
		_columnOriginalValues.put("isBillble", _isBillble);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("createdBy", 4L);

		columnBitmasks.put("modifiedBy", 8L);

		columnBitmasks.put("groupId", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("projectHistoryId", 128L);

		columnBitmasks.put("projectId", 256L);

		columnBitmasks.put("projectTaskStatusMasterId", 512L);

		columnBitmasks.put("managerId", 1024L);

		columnBitmasks.put("startDate", 2048L);

		columnBitmasks.put("isBillble", 4096L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ProjectHistory _escapedModel;

}