/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.model.impl;

import com.ax.hrms.model.ProjectEmployeeDetails;
import com.ax.hrms.model.ProjectEmployeeDetailsModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ProjectEmployeeDetails service. Represents a row in the &quot;ax_ProjectEmployeeDetails&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ProjectEmployeeDetailsModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ProjectEmployeeDetailsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProjectEmployeeDetailsImpl
 * @generated
 */
@JSON(strict = true)
public class ProjectEmployeeDetailsModelImpl
	extends BaseModelImpl<ProjectEmployeeDetails>
	implements ProjectEmployeeDetailsModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a project employee details model instance should use the <code>ProjectEmployeeDetails</code> interface instead.
	 */
	public static final String TABLE_NAME = "ax_ProjectEmployeeDetails";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"companyId", Types.BIGINT},
		{"createdBy", Types.BIGINT}, {"modifiedBy", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP},
		{"projectEmployeeDetailsId", Types.BIGINT}, {"projectId", Types.BIGINT},
		{"employeeId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("projectEmployeeDetailsId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("projectId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("employeeId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ax_ProjectEmployeeDetails (uuid_ VARCHAR(75) null,companyId LONG,createdBy LONG,modifiedBy LONG,groupId LONG,createDate DATE null,modifiedDate DATE null,projectEmployeeDetailsId LONG not null primary key,projectId LONG,employeeId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table ax_ProjectEmployeeDetails";

	public static final String ORDER_BY_JPQL =
		" ORDER BY projectEmployeeDetails.projectEmployeeDetailsId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ax_ProjectEmployeeDetails.projectEmployeeDetailsId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EMPLOYEEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PROJECTID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PROJECTEMPLOYEEDETAILSID_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ProjectEmployeeDetailsModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _projectEmployeeDetailsId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setProjectEmployeeDetailsId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _projectEmployeeDetailsId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ProjectEmployeeDetails.class;
	}

	@Override
	public String getModelClassName() {
		return ProjectEmployeeDetails.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ProjectEmployeeDetails, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ProjectEmployeeDetails, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ProjectEmployeeDetails, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ProjectEmployeeDetails)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ProjectEmployeeDetails, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ProjectEmployeeDetails, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ProjectEmployeeDetails)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ProjectEmployeeDetails, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ProjectEmployeeDetails, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map
			<String, Function<ProjectEmployeeDetails, Object>>
				_attributeGetterFunctions;

		static {
			Map<String, Function<ProjectEmployeeDetails, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<ProjectEmployeeDetails, Object>>();

			attributeGetterFunctions.put(
				"uuid", ProjectEmployeeDetails::getUuid);
			attributeGetterFunctions.put(
				"companyId", ProjectEmployeeDetails::getCompanyId);
			attributeGetterFunctions.put(
				"createdBy", ProjectEmployeeDetails::getCreatedBy);
			attributeGetterFunctions.put(
				"modifiedBy", ProjectEmployeeDetails::getModifiedBy);
			attributeGetterFunctions.put(
				"groupId", ProjectEmployeeDetails::getGroupId);
			attributeGetterFunctions.put(
				"createDate", ProjectEmployeeDetails::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", ProjectEmployeeDetails::getModifiedDate);
			attributeGetterFunctions.put(
				"projectEmployeeDetailsId",
				ProjectEmployeeDetails::getProjectEmployeeDetailsId);
			attributeGetterFunctions.put(
				"projectId", ProjectEmployeeDetails::getProjectId);
			attributeGetterFunctions.put(
				"employeeId", ProjectEmployeeDetails::getEmployeeId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<ProjectEmployeeDetails, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<ProjectEmployeeDetails, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<ProjectEmployeeDetails, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<ProjectEmployeeDetails, String>)
					ProjectEmployeeDetails::setUuid);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<ProjectEmployeeDetails, Long>)
					ProjectEmployeeDetails::setCompanyId);
			attributeSetterBiConsumers.put(
				"createdBy",
				(BiConsumer<ProjectEmployeeDetails, Long>)
					ProjectEmployeeDetails::setCreatedBy);
			attributeSetterBiConsumers.put(
				"modifiedBy",
				(BiConsumer<ProjectEmployeeDetails, Long>)
					ProjectEmployeeDetails::setModifiedBy);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<ProjectEmployeeDetails, Long>)
					ProjectEmployeeDetails::setGroupId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<ProjectEmployeeDetails, Date>)
					ProjectEmployeeDetails::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<ProjectEmployeeDetails, Date>)
					ProjectEmployeeDetails::setModifiedDate);
			attributeSetterBiConsumers.put(
				"projectEmployeeDetailsId",
				(BiConsumer<ProjectEmployeeDetails, Long>)
					ProjectEmployeeDetails::setProjectEmployeeDetailsId);
			attributeSetterBiConsumers.put(
				"projectId",
				(BiConsumer<ProjectEmployeeDetails, Long>)
					ProjectEmployeeDetails::setProjectId);
			attributeSetterBiConsumers.put(
				"employeeId",
				(BiConsumer<ProjectEmployeeDetails, Long>)
					ProjectEmployeeDetails::setEmployeeId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getProjectEmployeeDetailsId() {
		return _projectEmployeeDetailsId;
	}

	@Override
	public void setProjectEmployeeDetailsId(long projectEmployeeDetailsId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_projectEmployeeDetailsId = projectEmployeeDetailsId;
	}

	@JSON
	@Override
	public long getProjectId() {
		return _projectId;
	}

	@Override
	public void setProjectId(long projectId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_projectId = projectId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalProjectId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("projectId"));
	}

	@JSON
	@Override
	public long getEmployeeId() {
		return _employeeId;
	}

	@Override
	public void setEmployeeId(long employeeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_employeeId = employeeId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalEmployeeId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("employeeId"));
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(ProjectEmployeeDetails.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), ProjectEmployeeDetails.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ProjectEmployeeDetails toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ProjectEmployeeDetails>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ProjectEmployeeDetailsImpl projectEmployeeDetailsImpl =
			new ProjectEmployeeDetailsImpl();

		projectEmployeeDetailsImpl.setUuid(getUuid());
		projectEmployeeDetailsImpl.setCompanyId(getCompanyId());
		projectEmployeeDetailsImpl.setCreatedBy(getCreatedBy());
		projectEmployeeDetailsImpl.setModifiedBy(getModifiedBy());
		projectEmployeeDetailsImpl.setGroupId(getGroupId());
		projectEmployeeDetailsImpl.setCreateDate(getCreateDate());
		projectEmployeeDetailsImpl.setModifiedDate(getModifiedDate());
		projectEmployeeDetailsImpl.setProjectEmployeeDetailsId(
			getProjectEmployeeDetailsId());
		projectEmployeeDetailsImpl.setProjectId(getProjectId());
		projectEmployeeDetailsImpl.setEmployeeId(getEmployeeId());

		projectEmployeeDetailsImpl.resetOriginalValues();

		return projectEmployeeDetailsImpl;
	}

	@Override
	public ProjectEmployeeDetails cloneWithOriginalValues() {
		ProjectEmployeeDetailsImpl projectEmployeeDetailsImpl =
			new ProjectEmployeeDetailsImpl();

		projectEmployeeDetailsImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		projectEmployeeDetailsImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		projectEmployeeDetailsImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("createdBy"));
		projectEmployeeDetailsImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modifiedBy"));
		projectEmployeeDetailsImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		projectEmployeeDetailsImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		projectEmployeeDetailsImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		projectEmployeeDetailsImpl.setProjectEmployeeDetailsId(
			this.<Long>getColumnOriginalValue("projectEmployeeDetailsId"));
		projectEmployeeDetailsImpl.setProjectId(
			this.<Long>getColumnOriginalValue("projectId"));
		projectEmployeeDetailsImpl.setEmployeeId(
			this.<Long>getColumnOriginalValue("employeeId"));

		return projectEmployeeDetailsImpl;
	}

	@Override
	public int compareTo(ProjectEmployeeDetails projectEmployeeDetails) {
		long primaryKey = projectEmployeeDetails.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ProjectEmployeeDetails)) {
			return false;
		}

		ProjectEmployeeDetails projectEmployeeDetails =
			(ProjectEmployeeDetails)object;

		long primaryKey = projectEmployeeDetails.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ProjectEmployeeDetails> toCacheModel() {
		ProjectEmployeeDetailsCacheModel projectEmployeeDetailsCacheModel =
			new ProjectEmployeeDetailsCacheModel();

		projectEmployeeDetailsCacheModel.uuid = getUuid();

		String uuid = projectEmployeeDetailsCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			projectEmployeeDetailsCacheModel.uuid = null;
		}

		projectEmployeeDetailsCacheModel.companyId = getCompanyId();

		projectEmployeeDetailsCacheModel.createdBy = getCreatedBy();

		projectEmployeeDetailsCacheModel.modifiedBy = getModifiedBy();

		projectEmployeeDetailsCacheModel.groupId = getGroupId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			projectEmployeeDetailsCacheModel.createDate = createDate.getTime();
		}
		else {
			projectEmployeeDetailsCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			projectEmployeeDetailsCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			projectEmployeeDetailsCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		projectEmployeeDetailsCacheModel.projectEmployeeDetailsId =
			getProjectEmployeeDetailsId();

		projectEmployeeDetailsCacheModel.projectId = getProjectId();

		projectEmployeeDetailsCacheModel.employeeId = getEmployeeId();

		return projectEmployeeDetailsCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ProjectEmployeeDetails, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ProjectEmployeeDetails, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ProjectEmployeeDetails, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(ProjectEmployeeDetails)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ProjectEmployeeDetails>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					ProjectEmployeeDetails.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _companyId;
	private long _createdBy;
	private long _modifiedBy;
	private long _groupId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _projectEmployeeDetailsId;
	private long _projectId;
	private long _employeeId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<ProjectEmployeeDetails, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ProjectEmployeeDetails)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createdBy", _createdBy);
		_columnOriginalValues.put("modifiedBy", _modifiedBy);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put(
			"projectEmployeeDetailsId", _projectEmployeeDetailsId);
		_columnOriginalValues.put("projectId", _projectId);
		_columnOriginalValues.put("employeeId", _employeeId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("createdBy", 4L);

		columnBitmasks.put("modifiedBy", 8L);

		columnBitmasks.put("groupId", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("projectEmployeeDetailsId", 128L);

		columnBitmasks.put("projectId", 256L);

		columnBitmasks.put("employeeId", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ProjectEmployeeDetails _escapedModel;

}