/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.model.impl;

import com.ax.hrms.model.RolePolicies;
import com.ax.hrms.service.RolePoliciesLocalServiceUtil;

/**
 * The extended model base implementation for the RolePolicies service. Represents a row in the &quot;ax_RolePolicies&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RolePoliciesImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RolePoliciesImpl
 * @see RolePolicies
 * @generated
 */
public abstract class RolePoliciesBaseImpl
	extends RolePoliciesModelImpl implements RolePolicies {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a role policies model instance should use the <code>RolePolicies</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			RolePoliciesLocalServiceUtil.addRolePolicies(this);
		}
		else {
			RolePoliciesLocalServiceUtil.updateRolePolicies(this);
		}
	}

}