/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.model.impl;

import com.ax.hrms.model.TaskReview;
import com.ax.hrms.model.TaskReviewModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the TaskReview service. Represents a row in the &quot;ax_TaskReview&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>TaskReviewModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TaskReviewImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TaskReviewImpl
 * @generated
 */
@JSON(strict = true)
public class TaskReviewModelImpl
	extends BaseModelImpl<TaskReview> implements TaskReviewModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a task review model instance should use the <code>TaskReview</code> interface instead.
	 */
	public static final String TABLE_NAME = "ax_TaskReview";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"companyId", Types.BIGINT},
		{"createdBy", Types.BIGINT}, {"modifiedBy", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"taskReviewId", Types.BIGINT},
		{"taskId", Types.BIGINT}, {"reviewerId", Types.BIGINT},
		{"review", Types.VARCHAR}, {"dateOfReview", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("taskReviewId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("taskId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("reviewerId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("review", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("dateOfReview", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ax_TaskReview (uuid_ VARCHAR(75) null,companyId LONG,createdBy LONG,modifiedBy LONG,groupId LONG,createDate DATE null,modifiedDate DATE null,taskReviewId LONG not null primary key,taskId LONG,reviewerId LONG,review TEXT null,dateOfReview DATE null)";

	public static final String TABLE_SQL_DROP = "drop table ax_TaskReview";

	public static final String ORDER_BY_JPQL =
		" ORDER BY taskReview.taskReviewId DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ax_TaskReview.taskReviewId DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long REVIEWERID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TASKID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TASKREVIEWID_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public TaskReviewModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _taskReviewId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTaskReviewId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _taskReviewId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TaskReview.class;
	}

	@Override
	public String getModelClassName() {
		return TaskReview.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<TaskReview, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<TaskReview, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TaskReview, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((TaskReview)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<TaskReview, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<TaskReview, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(TaskReview)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<TaskReview, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<TaskReview, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<TaskReview, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<TaskReview, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<TaskReview, Object>>();

			attributeGetterFunctions.put("uuid", TaskReview::getUuid);
			attributeGetterFunctions.put("companyId", TaskReview::getCompanyId);
			attributeGetterFunctions.put("createdBy", TaskReview::getCreatedBy);
			attributeGetterFunctions.put(
				"modifiedBy", TaskReview::getModifiedBy);
			attributeGetterFunctions.put("groupId", TaskReview::getGroupId);
			attributeGetterFunctions.put(
				"createDate", TaskReview::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", TaskReview::getModifiedDate);
			attributeGetterFunctions.put(
				"taskReviewId", TaskReview::getTaskReviewId);
			attributeGetterFunctions.put("taskId", TaskReview::getTaskId);
			attributeGetterFunctions.put(
				"reviewerId", TaskReview::getReviewerId);
			attributeGetterFunctions.put("review", TaskReview::getReview);
			attributeGetterFunctions.put(
				"dateOfReview", TaskReview::getDateOfReview);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<TaskReview, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<TaskReview, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<TaskReview, ?>>();

			attributeSetterBiConsumers.put(
				"uuid", (BiConsumer<TaskReview, String>)TaskReview::setUuid);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<TaskReview, Long>)TaskReview::setCompanyId);
			attributeSetterBiConsumers.put(
				"createdBy",
				(BiConsumer<TaskReview, Long>)TaskReview::setCreatedBy);
			attributeSetterBiConsumers.put(
				"modifiedBy",
				(BiConsumer<TaskReview, Long>)TaskReview::setModifiedBy);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<TaskReview, Long>)TaskReview::setGroupId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<TaskReview, Date>)TaskReview::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<TaskReview, Date>)TaskReview::setModifiedDate);
			attributeSetterBiConsumers.put(
				"taskReviewId",
				(BiConsumer<TaskReview, Long>)TaskReview::setTaskReviewId);
			attributeSetterBiConsumers.put(
				"taskId", (BiConsumer<TaskReview, Long>)TaskReview::setTaskId);
			attributeSetterBiConsumers.put(
				"reviewerId",
				(BiConsumer<TaskReview, Long>)TaskReview::setReviewerId);
			attributeSetterBiConsumers.put(
				"review",
				(BiConsumer<TaskReview, String>)TaskReview::setReview);
			attributeSetterBiConsumers.put(
				"dateOfReview",
				(BiConsumer<TaskReview, Date>)TaskReview::setDateOfReview);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getTaskReviewId() {
		return _taskReviewId;
	}

	@Override
	public void setTaskReviewId(long taskReviewId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_taskReviewId = taskReviewId;
	}

	@JSON
	@Override
	public long getTaskId() {
		return _taskId;
	}

	@Override
	public void setTaskId(long taskId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_taskId = taskId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalTaskId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("taskId"));
	}

	@JSON
	@Override
	public long getReviewerId() {
		return _reviewerId;
	}

	@Override
	public void setReviewerId(long reviewerId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_reviewerId = reviewerId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalReviewerId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("reviewerId"));
	}

	@JSON
	@Override
	public String getReview() {
		if (_review == null) {
			return "";
		}
		else {
			return _review;
		}
	}

	@Override
	public void setReview(String review) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_review = review;
	}

	@JSON
	@Override
	public Date getDateOfReview() {
		return _dateOfReview;
	}

	@Override
	public void setDateOfReview(Date dateOfReview) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dateOfReview = dateOfReview;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(TaskReview.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), TaskReview.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TaskReview toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, TaskReview>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TaskReviewImpl taskReviewImpl = new TaskReviewImpl();

		taskReviewImpl.setUuid(getUuid());
		taskReviewImpl.setCompanyId(getCompanyId());
		taskReviewImpl.setCreatedBy(getCreatedBy());
		taskReviewImpl.setModifiedBy(getModifiedBy());
		taskReviewImpl.setGroupId(getGroupId());
		taskReviewImpl.setCreateDate(getCreateDate());
		taskReviewImpl.setModifiedDate(getModifiedDate());
		taskReviewImpl.setTaskReviewId(getTaskReviewId());
		taskReviewImpl.setTaskId(getTaskId());
		taskReviewImpl.setReviewerId(getReviewerId());
		taskReviewImpl.setReview(getReview());
		taskReviewImpl.setDateOfReview(getDateOfReview());

		taskReviewImpl.resetOriginalValues();

		return taskReviewImpl;
	}

	@Override
	public TaskReview cloneWithOriginalValues() {
		TaskReviewImpl taskReviewImpl = new TaskReviewImpl();

		taskReviewImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		taskReviewImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		taskReviewImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("createdBy"));
		taskReviewImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modifiedBy"));
		taskReviewImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		taskReviewImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		taskReviewImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		taskReviewImpl.setTaskReviewId(
			this.<Long>getColumnOriginalValue("taskReviewId"));
		taskReviewImpl.setTaskId(this.<Long>getColumnOriginalValue("taskId"));
		taskReviewImpl.setReviewerId(
			this.<Long>getColumnOriginalValue("reviewerId"));
		taskReviewImpl.setReview(this.<String>getColumnOriginalValue("review"));
		taskReviewImpl.setDateOfReview(
			this.<Date>getColumnOriginalValue("dateOfReview"));

		return taskReviewImpl;
	}

	@Override
	public int compareTo(TaskReview taskReview) {
		int value = 0;

		if (getTaskReviewId() < taskReview.getTaskReviewId()) {
			value = -1;
		}
		else if (getTaskReviewId() > taskReview.getTaskReviewId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof TaskReview)) {
			return false;
		}

		TaskReview taskReview = (TaskReview)object;

		long primaryKey = taskReview.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<TaskReview> toCacheModel() {
		TaskReviewCacheModel taskReviewCacheModel = new TaskReviewCacheModel();

		taskReviewCacheModel.uuid = getUuid();

		String uuid = taskReviewCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			taskReviewCacheModel.uuid = null;
		}

		taskReviewCacheModel.companyId = getCompanyId();

		taskReviewCacheModel.createdBy = getCreatedBy();

		taskReviewCacheModel.modifiedBy = getModifiedBy();

		taskReviewCacheModel.groupId = getGroupId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			taskReviewCacheModel.createDate = createDate.getTime();
		}
		else {
			taskReviewCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			taskReviewCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			taskReviewCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		taskReviewCacheModel.taskReviewId = getTaskReviewId();

		taskReviewCacheModel.taskId = getTaskId();

		taskReviewCacheModel.reviewerId = getReviewerId();

		taskReviewCacheModel.review = getReview();

		String review = taskReviewCacheModel.review;

		if ((review != null) && (review.length() == 0)) {
			taskReviewCacheModel.review = null;
		}

		Date dateOfReview = getDateOfReview();

		if (dateOfReview != null) {
			taskReviewCacheModel.dateOfReview = dateOfReview.getTime();
		}
		else {
			taskReviewCacheModel.dateOfReview = Long.MIN_VALUE;
		}

		return taskReviewCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<TaskReview, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<TaskReview, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TaskReview, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((TaskReview)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, TaskReview>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					TaskReview.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _companyId;
	private long _createdBy;
	private long _modifiedBy;
	private long _groupId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _taskReviewId;
	private long _taskId;
	private long _reviewerId;
	private String _review;
	private Date _dateOfReview;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<TaskReview, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((TaskReview)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createdBy", _createdBy);
		_columnOriginalValues.put("modifiedBy", _modifiedBy);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("taskReviewId", _taskReviewId);
		_columnOriginalValues.put("taskId", _taskId);
		_columnOriginalValues.put("reviewerId", _reviewerId);
		_columnOriginalValues.put("review", _review);
		_columnOriginalValues.put("dateOfReview", _dateOfReview);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("createdBy", 4L);

		columnBitmasks.put("modifiedBy", 8L);

		columnBitmasks.put("groupId", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("taskReviewId", 128L);

		columnBitmasks.put("taskId", 256L);

		columnBitmasks.put("reviewerId", 512L);

		columnBitmasks.put("review", 1024L);

		columnBitmasks.put("dateOfReview", 2048L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private TaskReview _escapedModel;

}