/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.model.impl;

import com.ax.hrms.model.TimeTracker;
import com.ax.hrms.service.TimeTrackerLocalServiceUtil;

/**
 * The extended model base implementation for the TimeTracker service. Represents a row in the &quot;ax_TimeTracker&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TimeTrackerImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TimeTrackerImpl
 * @see TimeTracker
 * @generated
 */
public abstract class TimeTrackerBaseImpl
	extends TimeTrackerModelImpl implements TimeTracker {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a time tracker model instance should use the <code>TimeTracker</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			TimeTrackerLocalServiceUtil.addTimeTracker(this);
		}
		else {
			TimeTrackerLocalServiceUtil.updateTimeTracker(this);
		}
	}

}