/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.model.impl;

import com.ax.hrms.model.UpcomingProbationEmployee;
import com.ax.hrms.model.UpcomingProbationEmployeeModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the UpcomingProbationEmployee service. Represents a row in the &quot;ax_UpcomingProbationEmployee&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>UpcomingProbationEmployeeModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link UpcomingProbationEmployeeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UpcomingProbationEmployeeImpl
 * @generated
 */
@JSON(strict = true)
public class UpcomingProbationEmployeeModelImpl
	extends BaseModelImpl<UpcomingProbationEmployee>
	implements UpcomingProbationEmployeeModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a upcoming probation employee model instance should use the <code>UpcomingProbationEmployee</code> interface instead.
	 */
	public static final String TABLE_NAME = "ax_UpcomingProbationEmployee";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"companyId", Types.BIGINT},
		{"createdBy", Types.BIGINT}, {"modifiedBy", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP},
		{"upcomingProbationEmployeeId", Types.BIGINT},
		{"probationDetailId", Types.BIGINT}, {"month", Types.INTEGER},
		{"year", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("upcomingProbationEmployeeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("probationDetailId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("month", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("year", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ax_UpcomingProbationEmployee (uuid_ VARCHAR(75) null,companyId LONG,createdBy LONG,modifiedBy LONG,groupId LONG,createDate DATE null,modifiedDate DATE null,upcomingProbationEmployeeId LONG not null primary key,probationDetailId LONG,month INTEGER,year INTEGER)";

	public static final String TABLE_SQL_DROP =
		"drop table ax_UpcomingProbationEmployee";

	public static final String ORDER_BY_JPQL =
		" ORDER BY upcomingProbationEmployee.upcomingProbationEmployeeId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ax_UpcomingProbationEmployee.upcomingProbationEmployeeId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long MONTH_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long YEAR_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UPCOMINGPROBATIONEMPLOYEEID_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public UpcomingProbationEmployeeModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _upcomingProbationEmployeeId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setUpcomingProbationEmployeeId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _upcomingProbationEmployeeId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return UpcomingProbationEmployee.class;
	}

	@Override
	public String getModelClassName() {
		return UpcomingProbationEmployee.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<UpcomingProbationEmployee, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<UpcomingProbationEmployee, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<UpcomingProbationEmployee, Object>
				attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((UpcomingProbationEmployee)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<UpcomingProbationEmployee, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<UpcomingProbationEmployee, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(UpcomingProbationEmployee)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<UpcomingProbationEmployee, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<UpcomingProbationEmployee, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map
			<String, Function<UpcomingProbationEmployee, Object>>
				_attributeGetterFunctions;

		static {
			Map<String, Function<UpcomingProbationEmployee, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<UpcomingProbationEmployee, Object>>();

			attributeGetterFunctions.put(
				"uuid", UpcomingProbationEmployee::getUuid);
			attributeGetterFunctions.put(
				"companyId", UpcomingProbationEmployee::getCompanyId);
			attributeGetterFunctions.put(
				"createdBy", UpcomingProbationEmployee::getCreatedBy);
			attributeGetterFunctions.put(
				"modifiedBy", UpcomingProbationEmployee::getModifiedBy);
			attributeGetterFunctions.put(
				"groupId", UpcomingProbationEmployee::getGroupId);
			attributeGetterFunctions.put(
				"createDate", UpcomingProbationEmployee::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", UpcomingProbationEmployee::getModifiedDate);
			attributeGetterFunctions.put(
				"upcomingProbationEmployeeId",
				UpcomingProbationEmployee::getUpcomingProbationEmployeeId);
			attributeGetterFunctions.put(
				"probationDetailId",
				UpcomingProbationEmployee::getProbationDetailId);
			attributeGetterFunctions.put(
				"month", UpcomingProbationEmployee::getMonth);
			attributeGetterFunctions.put(
				"year", UpcomingProbationEmployee::getYear);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<UpcomingProbationEmployee, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<UpcomingProbationEmployee, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<UpcomingProbationEmployee, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<UpcomingProbationEmployee, String>)
					UpcomingProbationEmployee::setUuid);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<UpcomingProbationEmployee, Long>)
					UpcomingProbationEmployee::setCompanyId);
			attributeSetterBiConsumers.put(
				"createdBy",
				(BiConsumer<UpcomingProbationEmployee, Long>)
					UpcomingProbationEmployee::setCreatedBy);
			attributeSetterBiConsumers.put(
				"modifiedBy",
				(BiConsumer<UpcomingProbationEmployee, Long>)
					UpcomingProbationEmployee::setModifiedBy);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<UpcomingProbationEmployee, Long>)
					UpcomingProbationEmployee::setGroupId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<UpcomingProbationEmployee, Date>)
					UpcomingProbationEmployee::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<UpcomingProbationEmployee, Date>)
					UpcomingProbationEmployee::setModifiedDate);
			attributeSetterBiConsumers.put(
				"upcomingProbationEmployeeId",
				(BiConsumer<UpcomingProbationEmployee, Long>)
					UpcomingProbationEmployee::setUpcomingProbationEmployeeId);
			attributeSetterBiConsumers.put(
				"probationDetailId",
				(BiConsumer<UpcomingProbationEmployee, Long>)
					UpcomingProbationEmployee::setProbationDetailId);
			attributeSetterBiConsumers.put(
				"month",
				(BiConsumer<UpcomingProbationEmployee, Integer>)
					UpcomingProbationEmployee::setMonth);
			attributeSetterBiConsumers.put(
				"year",
				(BiConsumer<UpcomingProbationEmployee, Integer>)
					UpcomingProbationEmployee::setYear);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getUpcomingProbationEmployeeId() {
		return _upcomingProbationEmployeeId;
	}

	@Override
	public void setUpcomingProbationEmployeeId(
		long upcomingProbationEmployeeId) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_upcomingProbationEmployeeId = upcomingProbationEmployeeId;
	}

	@JSON
	@Override
	public long getProbationDetailId() {
		return _probationDetailId;
	}

	@Override
	public void setProbationDetailId(long probationDetailId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_probationDetailId = probationDetailId;
	}

	@JSON
	@Override
	public int getMonth() {
		return _month;
	}

	@Override
	public void setMonth(int month) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_month = month;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalMonth() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("month"));
	}

	@JSON
	@Override
	public int getYear() {
		return _year;
	}

	@Override
	public void setYear(int year) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_year = year;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalYear() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("year"));
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(
				UpcomingProbationEmployee.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), UpcomingProbationEmployee.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public UpcomingProbationEmployee toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, UpcomingProbationEmployee>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		UpcomingProbationEmployeeImpl upcomingProbationEmployeeImpl =
			new UpcomingProbationEmployeeImpl();

		upcomingProbationEmployeeImpl.setUuid(getUuid());
		upcomingProbationEmployeeImpl.setCompanyId(getCompanyId());
		upcomingProbationEmployeeImpl.setCreatedBy(getCreatedBy());
		upcomingProbationEmployeeImpl.setModifiedBy(getModifiedBy());
		upcomingProbationEmployeeImpl.setGroupId(getGroupId());
		upcomingProbationEmployeeImpl.setCreateDate(getCreateDate());
		upcomingProbationEmployeeImpl.setModifiedDate(getModifiedDate());
		upcomingProbationEmployeeImpl.setUpcomingProbationEmployeeId(
			getUpcomingProbationEmployeeId());
		upcomingProbationEmployeeImpl.setProbationDetailId(
			getProbationDetailId());
		upcomingProbationEmployeeImpl.setMonth(getMonth());
		upcomingProbationEmployeeImpl.setYear(getYear());

		upcomingProbationEmployeeImpl.resetOriginalValues();

		return upcomingProbationEmployeeImpl;
	}

	@Override
	public UpcomingProbationEmployee cloneWithOriginalValues() {
		UpcomingProbationEmployeeImpl upcomingProbationEmployeeImpl =
			new UpcomingProbationEmployeeImpl();

		upcomingProbationEmployeeImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		upcomingProbationEmployeeImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		upcomingProbationEmployeeImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("createdBy"));
		upcomingProbationEmployeeImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modifiedBy"));
		upcomingProbationEmployeeImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		upcomingProbationEmployeeImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		upcomingProbationEmployeeImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		upcomingProbationEmployeeImpl.setUpcomingProbationEmployeeId(
			this.<Long>getColumnOriginalValue("upcomingProbationEmployeeId"));
		upcomingProbationEmployeeImpl.setProbationDetailId(
			this.<Long>getColumnOriginalValue("probationDetailId"));
		upcomingProbationEmployeeImpl.setMonth(
			this.<Integer>getColumnOriginalValue("month"));
		upcomingProbationEmployeeImpl.setYear(
			this.<Integer>getColumnOriginalValue("year"));

		return upcomingProbationEmployeeImpl;
	}

	@Override
	public int compareTo(UpcomingProbationEmployee upcomingProbationEmployee) {
		long primaryKey = upcomingProbationEmployee.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof UpcomingProbationEmployee)) {
			return false;
		}

		UpcomingProbationEmployee upcomingProbationEmployee =
			(UpcomingProbationEmployee)object;

		long primaryKey = upcomingProbationEmployee.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<UpcomingProbationEmployee> toCacheModel() {
		UpcomingProbationEmployeeCacheModel
			upcomingProbationEmployeeCacheModel =
				new UpcomingProbationEmployeeCacheModel();

		upcomingProbationEmployeeCacheModel.uuid = getUuid();

		String uuid = upcomingProbationEmployeeCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			upcomingProbationEmployeeCacheModel.uuid = null;
		}

		upcomingProbationEmployeeCacheModel.companyId = getCompanyId();

		upcomingProbationEmployeeCacheModel.createdBy = getCreatedBy();

		upcomingProbationEmployeeCacheModel.modifiedBy = getModifiedBy();

		upcomingProbationEmployeeCacheModel.groupId = getGroupId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			upcomingProbationEmployeeCacheModel.createDate =
				createDate.getTime();
		}
		else {
			upcomingProbationEmployeeCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			upcomingProbationEmployeeCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			upcomingProbationEmployeeCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		upcomingProbationEmployeeCacheModel.upcomingProbationEmployeeId =
			getUpcomingProbationEmployeeId();

		upcomingProbationEmployeeCacheModel.probationDetailId =
			getProbationDetailId();

		upcomingProbationEmployeeCacheModel.month = getMonth();

		upcomingProbationEmployeeCacheModel.year = getYear();

		return upcomingProbationEmployeeCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<UpcomingProbationEmployee, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<UpcomingProbationEmployee, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<UpcomingProbationEmployee, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(UpcomingProbationEmployee)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, UpcomingProbationEmployee>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						UpcomingProbationEmployee.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _companyId;
	private long _createdBy;
	private long _modifiedBy;
	private long _groupId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _upcomingProbationEmployeeId;
	private long _probationDetailId;
	private int _month;
	private int _year;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<UpcomingProbationEmployee, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((UpcomingProbationEmployee)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createdBy", _createdBy);
		_columnOriginalValues.put("modifiedBy", _modifiedBy);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put(
			"upcomingProbationEmployeeId", _upcomingProbationEmployeeId);
		_columnOriginalValues.put("probationDetailId", _probationDetailId);
		_columnOriginalValues.put("month", _month);
		_columnOriginalValues.put("year", _year);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("createdBy", 4L);

		columnBitmasks.put("modifiedBy", 8L);

		columnBitmasks.put("groupId", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("upcomingProbationEmployeeId", 128L);

		columnBitmasks.put("probationDetailId", 256L);

		columnBitmasks.put("month", 512L);

		columnBitmasks.put("year", 1024L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private UpcomingProbationEmployee _escapedModel;

}