/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.model.impl;

import com.ax.hrms.model.WorkFromHomeDayType;
import com.ax.hrms.model.WorkFromHomeDayTypeModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the WorkFromHomeDayType service. Represents a row in the &quot;ax_WorkFromHomeDayType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>WorkFromHomeDayTypeModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link WorkFromHomeDayTypeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see WorkFromHomeDayTypeImpl
 * @generated
 */
@JSON(strict = true)
public class WorkFromHomeDayTypeModelImpl
	extends BaseModelImpl<WorkFromHomeDayType>
	implements WorkFromHomeDayTypeModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a work from home day type model instance should use the <code>WorkFromHomeDayType</code> interface instead.
	 */
	public static final String TABLE_NAME = "ax_WorkFromHomeDayType";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"companyId", Types.BIGINT},
		{"createdBy", Types.BIGINT}, {"modifiedBy", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP},
		{"workFromHomeDayTypeId", Types.BIGINT},
		{"workFromHomeRequestId", Types.BIGINT},
		{"workFromHomeDate", Types.TIMESTAMP}, {"isHalfDay", Types.BOOLEAN},
		{"isFirstHalf", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("workFromHomeDayTypeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("workFromHomeRequestId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("workFromHomeDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("isHalfDay", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("isFirstHalf", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ax_WorkFromHomeDayType (uuid_ VARCHAR(75) null,companyId LONG,createdBy LONG,modifiedBy LONG,groupId LONG,createDate DATE null,modifiedDate DATE null,workFromHomeDayTypeId LONG not null primary key,workFromHomeRequestId LONG,workFromHomeDate DATE null,isHalfDay BOOLEAN,isFirstHalf BOOLEAN)";

	public static final String TABLE_SQL_DROP =
		"drop table ax_WorkFromHomeDayType";

	public static final String ORDER_BY_JPQL =
		" ORDER BY workFromHomeDayType.workFromHomeDayTypeId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ax_WorkFromHomeDayType.workFromHomeDayTypeId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long WORKFROMHOMEDATE_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long WORKFROMHOMEREQUESTID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long WORKFROMHOMEDAYTYPEID_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public WorkFromHomeDayTypeModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _workFromHomeDayTypeId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setWorkFromHomeDayTypeId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _workFromHomeDayTypeId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return WorkFromHomeDayType.class;
	}

	@Override
	public String getModelClassName() {
		return WorkFromHomeDayType.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<WorkFromHomeDayType, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<WorkFromHomeDayType, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<WorkFromHomeDayType, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((WorkFromHomeDayType)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<WorkFromHomeDayType, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<WorkFromHomeDayType, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(WorkFromHomeDayType)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<WorkFromHomeDayType, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<WorkFromHomeDayType, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<WorkFromHomeDayType, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<WorkFromHomeDayType, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<WorkFromHomeDayType, Object>>();

			attributeGetterFunctions.put("uuid", WorkFromHomeDayType::getUuid);
			attributeGetterFunctions.put(
				"companyId", WorkFromHomeDayType::getCompanyId);
			attributeGetterFunctions.put(
				"createdBy", WorkFromHomeDayType::getCreatedBy);
			attributeGetterFunctions.put(
				"modifiedBy", WorkFromHomeDayType::getModifiedBy);
			attributeGetterFunctions.put(
				"groupId", WorkFromHomeDayType::getGroupId);
			attributeGetterFunctions.put(
				"createDate", WorkFromHomeDayType::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", WorkFromHomeDayType::getModifiedDate);
			attributeGetterFunctions.put(
				"workFromHomeDayTypeId",
				WorkFromHomeDayType::getWorkFromHomeDayTypeId);
			attributeGetterFunctions.put(
				"workFromHomeRequestId",
				WorkFromHomeDayType::getWorkFromHomeRequestId);
			attributeGetterFunctions.put(
				"workFromHomeDate", WorkFromHomeDayType::getWorkFromHomeDate);
			attributeGetterFunctions.put(
				"isHalfDay", WorkFromHomeDayType::getIsHalfDay);
			attributeGetterFunctions.put(
				"isFirstHalf", WorkFromHomeDayType::getIsFirstHalf);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<WorkFromHomeDayType, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<WorkFromHomeDayType, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<WorkFromHomeDayType, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<WorkFromHomeDayType, String>)
					WorkFromHomeDayType::setUuid);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<WorkFromHomeDayType, Long>)
					WorkFromHomeDayType::setCompanyId);
			attributeSetterBiConsumers.put(
				"createdBy",
				(BiConsumer<WorkFromHomeDayType, Long>)
					WorkFromHomeDayType::setCreatedBy);
			attributeSetterBiConsumers.put(
				"modifiedBy",
				(BiConsumer<WorkFromHomeDayType, Long>)
					WorkFromHomeDayType::setModifiedBy);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<WorkFromHomeDayType, Long>)
					WorkFromHomeDayType::setGroupId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<WorkFromHomeDayType, Date>)
					WorkFromHomeDayType::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<WorkFromHomeDayType, Date>)
					WorkFromHomeDayType::setModifiedDate);
			attributeSetterBiConsumers.put(
				"workFromHomeDayTypeId",
				(BiConsumer<WorkFromHomeDayType, Long>)
					WorkFromHomeDayType::setWorkFromHomeDayTypeId);
			attributeSetterBiConsumers.put(
				"workFromHomeRequestId",
				(BiConsumer<WorkFromHomeDayType, Long>)
					WorkFromHomeDayType::setWorkFromHomeRequestId);
			attributeSetterBiConsumers.put(
				"workFromHomeDate",
				(BiConsumer<WorkFromHomeDayType, Date>)
					WorkFromHomeDayType::setWorkFromHomeDate);
			attributeSetterBiConsumers.put(
				"isHalfDay",
				(BiConsumer<WorkFromHomeDayType, Boolean>)
					WorkFromHomeDayType::setIsHalfDay);
			attributeSetterBiConsumers.put(
				"isFirstHalf",
				(BiConsumer<WorkFromHomeDayType, Boolean>)
					WorkFromHomeDayType::setIsFirstHalf);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getWorkFromHomeDayTypeId() {
		return _workFromHomeDayTypeId;
	}

	@Override
	public void setWorkFromHomeDayTypeId(long workFromHomeDayTypeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_workFromHomeDayTypeId = workFromHomeDayTypeId;
	}

	@JSON
	@Override
	public long getWorkFromHomeRequestId() {
		return _workFromHomeRequestId;
	}

	@Override
	public void setWorkFromHomeRequestId(long workFromHomeRequestId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_workFromHomeRequestId = workFromHomeRequestId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalWorkFromHomeRequestId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("workFromHomeRequestId"));
	}

	@JSON
	@Override
	public Date getWorkFromHomeDate() {
		return _workFromHomeDate;
	}

	@Override
	public void setWorkFromHomeDate(Date workFromHomeDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_workFromHomeDate = workFromHomeDate;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public Date getOriginalWorkFromHomeDate() {
		return getColumnOriginalValue("workFromHomeDate");
	}

	@JSON
	@Override
	public boolean getIsHalfDay() {
		return _isHalfDay;
	}

	@JSON
	@Override
	public boolean isIsHalfDay() {
		return _isHalfDay;
	}

	@Override
	public void setIsHalfDay(boolean isHalfDay) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_isHalfDay = isHalfDay;
	}

	@JSON
	@Override
	public boolean getIsFirstHalf() {
		return _isFirstHalf;
	}

	@JSON
	@Override
	public boolean isIsFirstHalf() {
		return _isFirstHalf;
	}

	@Override
	public void setIsFirstHalf(boolean isFirstHalf) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_isFirstHalf = isFirstHalf;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(WorkFromHomeDayType.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), WorkFromHomeDayType.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public WorkFromHomeDayType toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, WorkFromHomeDayType>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		WorkFromHomeDayTypeImpl workFromHomeDayTypeImpl =
			new WorkFromHomeDayTypeImpl();

		workFromHomeDayTypeImpl.setUuid(getUuid());
		workFromHomeDayTypeImpl.setCompanyId(getCompanyId());
		workFromHomeDayTypeImpl.setCreatedBy(getCreatedBy());
		workFromHomeDayTypeImpl.setModifiedBy(getModifiedBy());
		workFromHomeDayTypeImpl.setGroupId(getGroupId());
		workFromHomeDayTypeImpl.setCreateDate(getCreateDate());
		workFromHomeDayTypeImpl.setModifiedDate(getModifiedDate());
		workFromHomeDayTypeImpl.setWorkFromHomeDayTypeId(
			getWorkFromHomeDayTypeId());
		workFromHomeDayTypeImpl.setWorkFromHomeRequestId(
			getWorkFromHomeRequestId());
		workFromHomeDayTypeImpl.setWorkFromHomeDate(getWorkFromHomeDate());
		workFromHomeDayTypeImpl.setIsHalfDay(isIsHalfDay());
		workFromHomeDayTypeImpl.setIsFirstHalf(isIsFirstHalf());

		workFromHomeDayTypeImpl.resetOriginalValues();

		return workFromHomeDayTypeImpl;
	}

	@Override
	public WorkFromHomeDayType cloneWithOriginalValues() {
		WorkFromHomeDayTypeImpl workFromHomeDayTypeImpl =
			new WorkFromHomeDayTypeImpl();

		workFromHomeDayTypeImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		workFromHomeDayTypeImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		workFromHomeDayTypeImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("createdBy"));
		workFromHomeDayTypeImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modifiedBy"));
		workFromHomeDayTypeImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		workFromHomeDayTypeImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		workFromHomeDayTypeImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		workFromHomeDayTypeImpl.setWorkFromHomeDayTypeId(
			this.<Long>getColumnOriginalValue("workFromHomeDayTypeId"));
		workFromHomeDayTypeImpl.setWorkFromHomeRequestId(
			this.<Long>getColumnOriginalValue("workFromHomeRequestId"));
		workFromHomeDayTypeImpl.setWorkFromHomeDate(
			this.<Date>getColumnOriginalValue("workFromHomeDate"));
		workFromHomeDayTypeImpl.setIsHalfDay(
			this.<Boolean>getColumnOriginalValue("isHalfDay"));
		workFromHomeDayTypeImpl.setIsFirstHalf(
			this.<Boolean>getColumnOriginalValue("isFirstHalf"));

		return workFromHomeDayTypeImpl;
	}

	@Override
	public int compareTo(WorkFromHomeDayType workFromHomeDayType) {
		long primaryKey = workFromHomeDayType.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof WorkFromHomeDayType)) {
			return false;
		}

		WorkFromHomeDayType workFromHomeDayType = (WorkFromHomeDayType)object;

		long primaryKey = workFromHomeDayType.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<WorkFromHomeDayType> toCacheModel() {
		WorkFromHomeDayTypeCacheModel workFromHomeDayTypeCacheModel =
			new WorkFromHomeDayTypeCacheModel();

		workFromHomeDayTypeCacheModel.uuid = getUuid();

		String uuid = workFromHomeDayTypeCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			workFromHomeDayTypeCacheModel.uuid = null;
		}

		workFromHomeDayTypeCacheModel.companyId = getCompanyId();

		workFromHomeDayTypeCacheModel.createdBy = getCreatedBy();

		workFromHomeDayTypeCacheModel.modifiedBy = getModifiedBy();

		workFromHomeDayTypeCacheModel.groupId = getGroupId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			workFromHomeDayTypeCacheModel.createDate = createDate.getTime();
		}
		else {
			workFromHomeDayTypeCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			workFromHomeDayTypeCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			workFromHomeDayTypeCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		workFromHomeDayTypeCacheModel.workFromHomeDayTypeId =
			getWorkFromHomeDayTypeId();

		workFromHomeDayTypeCacheModel.workFromHomeRequestId =
			getWorkFromHomeRequestId();

		Date workFromHomeDate = getWorkFromHomeDate();

		if (workFromHomeDate != null) {
			workFromHomeDayTypeCacheModel.workFromHomeDate =
				workFromHomeDate.getTime();
		}
		else {
			workFromHomeDayTypeCacheModel.workFromHomeDate = Long.MIN_VALUE;
		}

		workFromHomeDayTypeCacheModel.isHalfDay = isIsHalfDay();

		workFromHomeDayTypeCacheModel.isFirstHalf = isIsFirstHalf();

		return workFromHomeDayTypeCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<WorkFromHomeDayType, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<WorkFromHomeDayType, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<WorkFromHomeDayType, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(WorkFromHomeDayType)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, WorkFromHomeDayType>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					WorkFromHomeDayType.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _companyId;
	private long _createdBy;
	private long _modifiedBy;
	private long _groupId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _workFromHomeDayTypeId;
	private long _workFromHomeRequestId;
	private Date _workFromHomeDate;
	private boolean _isHalfDay;
	private boolean _isFirstHalf;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<WorkFromHomeDayType, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((WorkFromHomeDayType)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createdBy", _createdBy);
		_columnOriginalValues.put("modifiedBy", _modifiedBy);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put(
			"workFromHomeDayTypeId", _workFromHomeDayTypeId);
		_columnOriginalValues.put(
			"workFromHomeRequestId", _workFromHomeRequestId);
		_columnOriginalValues.put("workFromHomeDate", _workFromHomeDate);
		_columnOriginalValues.put("isHalfDay", _isHalfDay);
		_columnOriginalValues.put("isFirstHalf", _isFirstHalf);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("createdBy", 4L);

		columnBitmasks.put("modifiedBy", 8L);

		columnBitmasks.put("groupId", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("workFromHomeDayTypeId", 128L);

		columnBitmasks.put("workFromHomeRequestId", 256L);

		columnBitmasks.put("workFromHomeDate", 512L);

		columnBitmasks.put("isHalfDay", 1024L);

		columnBitmasks.put("isFirstHalf", 2048L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private WorkFromHomeDayType _escapedModel;

}