/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.model.impl;

import com.ax.hrms.model.WorkFromHome;
import com.ax.hrms.model.WorkFromHomeModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the WorkFromHome service. Represents a row in the &quot;ax_WorkFromHome&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>WorkFromHomeModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link WorkFromHomeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see WorkFromHomeImpl
 * @generated
 */
@JSON(strict = true)
public class WorkFromHomeModelImpl
	extends BaseModelImpl<WorkFromHome> implements WorkFromHomeModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a work from home model instance should use the <code>WorkFromHome</code> interface instead.
	 */
	public static final String TABLE_NAME = "ax_WorkFromHome";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"companyId", Types.BIGINT},
		{"createdBy", Types.BIGINT}, {"modifiedBy", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP},
		{"workFromHomeRequestId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"teamMailId", Types.VARCHAR}, {"status", Types.VARCHAR},
		{"reason", Types.VARCHAR}, {"requestDate", Types.TIMESTAMP},
		{"startDate", Types.TIMESTAMP}, {"endDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("workFromHomeRequestId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("teamMailId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("status", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("reason", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("requestDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("startDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("endDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ax_WorkFromHome (uuid_ VARCHAR(75) null,companyId LONG,createdBy LONG,modifiedBy LONG,groupId LONG,createDate DATE null,modifiedDate DATE null,workFromHomeRequestId LONG not null primary key,userId LONG,teamMailId VARCHAR(75) null,status VARCHAR(75) null,reason VARCHAR(75) null,requestDate DATE null,startDate DATE null,endDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table ax_WorkFromHome";

	public static final String ORDER_BY_JPQL =
		" ORDER BY workFromHome.workFromHomeRequestId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ax_WorkFromHome.workFromHomeRequestId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ENDDATE_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STARTDATE_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STATUS_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long USERID_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 64L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long WORKFROMHOMEREQUESTID_COLUMN_BITMASK = 128L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public WorkFromHomeModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _workFromHomeRequestId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setWorkFromHomeRequestId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _workFromHomeRequestId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return WorkFromHome.class;
	}

	@Override
	public String getModelClassName() {
		return WorkFromHome.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<WorkFromHome, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<WorkFromHome, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<WorkFromHome, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((WorkFromHome)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<WorkFromHome, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<WorkFromHome, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(WorkFromHome)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<WorkFromHome, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<WorkFromHome, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<WorkFromHome, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<WorkFromHome, Object>>
				attributeGetterFunctions =
					new LinkedHashMap<String, Function<WorkFromHome, Object>>();

			attributeGetterFunctions.put("uuid", WorkFromHome::getUuid);
			attributeGetterFunctions.put(
				"companyId", WorkFromHome::getCompanyId);
			attributeGetterFunctions.put(
				"createdBy", WorkFromHome::getCreatedBy);
			attributeGetterFunctions.put(
				"modifiedBy", WorkFromHome::getModifiedBy);
			attributeGetterFunctions.put("groupId", WorkFromHome::getGroupId);
			attributeGetterFunctions.put(
				"createDate", WorkFromHome::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", WorkFromHome::getModifiedDate);
			attributeGetterFunctions.put(
				"workFromHomeRequestId",
				WorkFromHome::getWorkFromHomeRequestId);
			attributeGetterFunctions.put("userId", WorkFromHome::getUserId);
			attributeGetterFunctions.put(
				"teamMailId", WorkFromHome::getTeamMailId);
			attributeGetterFunctions.put("status", WorkFromHome::getStatus);
			attributeGetterFunctions.put("reason", WorkFromHome::getReason);
			attributeGetterFunctions.put(
				"requestDate", WorkFromHome::getRequestDate);
			attributeGetterFunctions.put(
				"startDate", WorkFromHome::getStartDate);
			attributeGetterFunctions.put("endDate", WorkFromHome::getEndDate);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<WorkFromHome, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<WorkFromHome, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<WorkFromHome, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<WorkFromHome, String>)WorkFromHome::setUuid);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<WorkFromHome, Long>)WorkFromHome::setCompanyId);
			attributeSetterBiConsumers.put(
				"createdBy",
				(BiConsumer<WorkFromHome, Long>)WorkFromHome::setCreatedBy);
			attributeSetterBiConsumers.put(
				"modifiedBy",
				(BiConsumer<WorkFromHome, Long>)WorkFromHome::setModifiedBy);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<WorkFromHome, Long>)WorkFromHome::setGroupId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<WorkFromHome, Date>)WorkFromHome::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<WorkFromHome, Date>)WorkFromHome::setModifiedDate);
			attributeSetterBiConsumers.put(
				"workFromHomeRequestId",
				(BiConsumer<WorkFromHome, Long>)
					WorkFromHome::setWorkFromHomeRequestId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<WorkFromHome, Long>)WorkFromHome::setUserId);
			attributeSetterBiConsumers.put(
				"teamMailId",
				(BiConsumer<WorkFromHome, String>)WorkFromHome::setTeamMailId);
			attributeSetterBiConsumers.put(
				"status",
				(BiConsumer<WorkFromHome, String>)WorkFromHome::setStatus);
			attributeSetterBiConsumers.put(
				"reason",
				(BiConsumer<WorkFromHome, String>)WorkFromHome::setReason);
			attributeSetterBiConsumers.put(
				"requestDate",
				(BiConsumer<WorkFromHome, Date>)WorkFromHome::setRequestDate);
			attributeSetterBiConsumers.put(
				"startDate",
				(BiConsumer<WorkFromHome, Date>)WorkFromHome::setStartDate);
			attributeSetterBiConsumers.put(
				"endDate",
				(BiConsumer<WorkFromHome, Date>)WorkFromHome::setEndDate);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getWorkFromHomeRequestId() {
		return _workFromHomeRequestId;
	}

	@Override
	public void setWorkFromHomeRequestId(long workFromHomeRequestId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_workFromHomeRequestId = workFromHomeRequestId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalUserId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("userId"));
	}

	@JSON
	@Override
	public String getTeamMailId() {
		if (_teamMailId == null) {
			return "";
		}
		else {
			return _teamMailId;
		}
	}

	@Override
	public void setTeamMailId(String teamMailId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_teamMailId = teamMailId;
	}

	@JSON
	@Override
	public String getStatus() {
		if (_status == null) {
			return "";
		}
		else {
			return _status;
		}
	}

	@Override
	public void setStatus(String status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalStatus() {
		return getColumnOriginalValue("status");
	}

	@JSON
	@Override
	public String getReason() {
		if (_reason == null) {
			return "";
		}
		else {
			return _reason;
		}
	}

	@Override
	public void setReason(String reason) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_reason = reason;
	}

	@JSON
	@Override
	public Date getRequestDate() {
		return _requestDate;
	}

	@Override
	public void setRequestDate(Date requestDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_requestDate = requestDate;
	}

	@JSON
	@Override
	public Date getStartDate() {
		return _startDate;
	}

	@Override
	public void setStartDate(Date startDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_startDate = startDate;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public Date getOriginalStartDate() {
		return getColumnOriginalValue("startDate");
	}

	@JSON
	@Override
	public Date getEndDate() {
		return _endDate;
	}

	@Override
	public void setEndDate(Date endDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_endDate = endDate;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public Date getOriginalEndDate() {
		return getColumnOriginalValue("endDate");
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(WorkFromHome.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), WorkFromHome.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public WorkFromHome toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, WorkFromHome>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		WorkFromHomeImpl workFromHomeImpl = new WorkFromHomeImpl();

		workFromHomeImpl.setUuid(getUuid());
		workFromHomeImpl.setCompanyId(getCompanyId());
		workFromHomeImpl.setCreatedBy(getCreatedBy());
		workFromHomeImpl.setModifiedBy(getModifiedBy());
		workFromHomeImpl.setGroupId(getGroupId());
		workFromHomeImpl.setCreateDate(getCreateDate());
		workFromHomeImpl.setModifiedDate(getModifiedDate());
		workFromHomeImpl.setWorkFromHomeRequestId(getWorkFromHomeRequestId());
		workFromHomeImpl.setUserId(getUserId());
		workFromHomeImpl.setTeamMailId(getTeamMailId());
		workFromHomeImpl.setStatus(getStatus());
		workFromHomeImpl.setReason(getReason());
		workFromHomeImpl.setRequestDate(getRequestDate());
		workFromHomeImpl.setStartDate(getStartDate());
		workFromHomeImpl.setEndDate(getEndDate());

		workFromHomeImpl.resetOriginalValues();

		return workFromHomeImpl;
	}

	@Override
	public WorkFromHome cloneWithOriginalValues() {
		WorkFromHomeImpl workFromHomeImpl = new WorkFromHomeImpl();

		workFromHomeImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		workFromHomeImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		workFromHomeImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("createdBy"));
		workFromHomeImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modifiedBy"));
		workFromHomeImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		workFromHomeImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		workFromHomeImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		workFromHomeImpl.setWorkFromHomeRequestId(
			this.<Long>getColumnOriginalValue("workFromHomeRequestId"));
		workFromHomeImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		workFromHomeImpl.setTeamMailId(
			this.<String>getColumnOriginalValue("teamMailId"));
		workFromHomeImpl.setStatus(
			this.<String>getColumnOriginalValue("status"));
		workFromHomeImpl.setReason(
			this.<String>getColumnOriginalValue("reason"));
		workFromHomeImpl.setRequestDate(
			this.<Date>getColumnOriginalValue("requestDate"));
		workFromHomeImpl.setStartDate(
			this.<Date>getColumnOriginalValue("startDate"));
		workFromHomeImpl.setEndDate(
			this.<Date>getColumnOriginalValue("endDate"));

		return workFromHomeImpl;
	}

	@Override
	public int compareTo(WorkFromHome workFromHome) {
		long primaryKey = workFromHome.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof WorkFromHome)) {
			return false;
		}

		WorkFromHome workFromHome = (WorkFromHome)object;

		long primaryKey = workFromHome.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<WorkFromHome> toCacheModel() {
		WorkFromHomeCacheModel workFromHomeCacheModel =
			new WorkFromHomeCacheModel();

		workFromHomeCacheModel.uuid = getUuid();

		String uuid = workFromHomeCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			workFromHomeCacheModel.uuid = null;
		}

		workFromHomeCacheModel.companyId = getCompanyId();

		workFromHomeCacheModel.createdBy = getCreatedBy();

		workFromHomeCacheModel.modifiedBy = getModifiedBy();

		workFromHomeCacheModel.groupId = getGroupId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			workFromHomeCacheModel.createDate = createDate.getTime();
		}
		else {
			workFromHomeCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			workFromHomeCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			workFromHomeCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		workFromHomeCacheModel.workFromHomeRequestId =
			getWorkFromHomeRequestId();

		workFromHomeCacheModel.userId = getUserId();

		workFromHomeCacheModel.teamMailId = getTeamMailId();

		String teamMailId = workFromHomeCacheModel.teamMailId;

		if ((teamMailId != null) && (teamMailId.length() == 0)) {
			workFromHomeCacheModel.teamMailId = null;
		}

		workFromHomeCacheModel.status = getStatus();

		String status = workFromHomeCacheModel.status;

		if ((status != null) && (status.length() == 0)) {
			workFromHomeCacheModel.status = null;
		}

		workFromHomeCacheModel.reason = getReason();

		String reason = workFromHomeCacheModel.reason;

		if ((reason != null) && (reason.length() == 0)) {
			workFromHomeCacheModel.reason = null;
		}

		Date requestDate = getRequestDate();

		if (requestDate != null) {
			workFromHomeCacheModel.requestDate = requestDate.getTime();
		}
		else {
			workFromHomeCacheModel.requestDate = Long.MIN_VALUE;
		}

		Date startDate = getStartDate();

		if (startDate != null) {
			workFromHomeCacheModel.startDate = startDate.getTime();
		}
		else {
			workFromHomeCacheModel.startDate = Long.MIN_VALUE;
		}

		Date endDate = getEndDate();

		if (endDate != null) {
			workFromHomeCacheModel.endDate = endDate.getTime();
		}
		else {
			workFromHomeCacheModel.endDate = Long.MIN_VALUE;
		}

		return workFromHomeCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<WorkFromHome, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<WorkFromHome, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<WorkFromHome, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((WorkFromHome)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, WorkFromHome>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					WorkFromHome.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _companyId;
	private long _createdBy;
	private long _modifiedBy;
	private long _groupId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _workFromHomeRequestId;
	private long _userId;
	private String _teamMailId;
	private String _status;
	private String _reason;
	private Date _requestDate;
	private Date _startDate;
	private Date _endDate;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<WorkFromHome, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((WorkFromHome)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createdBy", _createdBy);
		_columnOriginalValues.put("modifiedBy", _modifiedBy);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put(
			"workFromHomeRequestId", _workFromHomeRequestId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("teamMailId", _teamMailId);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("reason", _reason);
		_columnOriginalValues.put("requestDate", _requestDate);
		_columnOriginalValues.put("startDate", _startDate);
		_columnOriginalValues.put("endDate", _endDate);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("createdBy", 4L);

		columnBitmasks.put("modifiedBy", 8L);

		columnBitmasks.put("groupId", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("workFromHomeRequestId", 128L);

		columnBitmasks.put("userId", 256L);

		columnBitmasks.put("teamMailId", 512L);

		columnBitmasks.put("status", 1024L);

		columnBitmasks.put("reason", 2048L);

		columnBitmasks.put("requestDate", 4096L);

		columnBitmasks.put("startDate", 8192L);

		columnBitmasks.put("endDate", 16384L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private WorkFromHome _escapedModel;

}