/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ax.hrms.model.impl;

import com.ax.hrms.model.WorkFromHomeRequest;
import com.ax.hrms.model.WorkFromHomeRequestModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the WorkFromHomeRequest service. Represents a row in the &quot;ax_WorkFromHomeRequest&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>WorkFromHomeRequestModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link WorkFromHomeRequestImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see WorkFromHomeRequestImpl
 * @generated
 */
@JSON(strict = true)
public class WorkFromHomeRequestModelImpl
	extends BaseModelImpl<WorkFromHomeRequest>
	implements WorkFromHomeRequestModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a work from home request model instance should use the <code>WorkFromHomeRequest</code> interface instead.
	 */
	public static final String TABLE_NAME = "ax_WorkFromHomeRequest";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"companyId", Types.BIGINT},
		{"createdBy", Types.BIGINT}, {"modifiedBy", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP},
		{"workFromHomeRequestId", Types.BIGINT}, {"employeeId", Types.BIGINT},
		{"reviewerId", Types.BIGINT}, {"teamMailId", Types.VARCHAR},
		{"status", Types.BIGINT}, {"reason", Types.VARCHAR},
		{"requestDate", Types.TIMESTAMP}, {"startDate", Types.TIMESTAMP},
		{"endDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("workFromHomeRequestId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("employeeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("reviewerId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("teamMailId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("status", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("reason", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("requestDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("startDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("endDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ax_WorkFromHomeRequest (uuid_ VARCHAR(75) null,companyId LONG,createdBy LONG,modifiedBy LONG,groupId LONG,createDate DATE null,modifiedDate DATE null,workFromHomeRequestId LONG not null primary key,employeeId LONG,reviewerId LONG,teamMailId VARCHAR(2000) null,status LONG,reason VARCHAR(2000) null,requestDate DATE null,startDate DATE null,endDate DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table ax_WorkFromHomeRequest";

	public static final String ORDER_BY_JPQL =
		" ORDER BY workFromHomeRequest.createDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ax_WorkFromHomeRequest.createDate DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EMPLOYEEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ENDDATE_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STARTDATE_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STATUS_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 64L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CREATEDATE_COLUMN_BITMASK = 128L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public WorkFromHomeRequestModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _workFromHomeRequestId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setWorkFromHomeRequestId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _workFromHomeRequestId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return WorkFromHomeRequest.class;
	}

	@Override
	public String getModelClassName() {
		return WorkFromHomeRequest.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<WorkFromHomeRequest, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<WorkFromHomeRequest, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<WorkFromHomeRequest, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((WorkFromHomeRequest)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<WorkFromHomeRequest, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<WorkFromHomeRequest, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(WorkFromHomeRequest)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<WorkFromHomeRequest, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<WorkFromHomeRequest, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<WorkFromHomeRequest, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<WorkFromHomeRequest, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<WorkFromHomeRequest, Object>>();

			attributeGetterFunctions.put("uuid", WorkFromHomeRequest::getUuid);
			attributeGetterFunctions.put(
				"companyId", WorkFromHomeRequest::getCompanyId);
			attributeGetterFunctions.put(
				"createdBy", WorkFromHomeRequest::getCreatedBy);
			attributeGetterFunctions.put(
				"modifiedBy", WorkFromHomeRequest::getModifiedBy);
			attributeGetterFunctions.put(
				"groupId", WorkFromHomeRequest::getGroupId);
			attributeGetterFunctions.put(
				"createDate", WorkFromHomeRequest::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", WorkFromHomeRequest::getModifiedDate);
			attributeGetterFunctions.put(
				"workFromHomeRequestId",
				WorkFromHomeRequest::getWorkFromHomeRequestId);
			attributeGetterFunctions.put(
				"employeeId", WorkFromHomeRequest::getEmployeeId);
			attributeGetterFunctions.put(
				"reviewerId", WorkFromHomeRequest::getReviewerId);
			attributeGetterFunctions.put(
				"teamMailId", WorkFromHomeRequest::getTeamMailId);
			attributeGetterFunctions.put(
				"status", WorkFromHomeRequest::getStatus);
			attributeGetterFunctions.put(
				"reason", WorkFromHomeRequest::getReason);
			attributeGetterFunctions.put(
				"requestDate", WorkFromHomeRequest::getRequestDate);
			attributeGetterFunctions.put(
				"startDate", WorkFromHomeRequest::getStartDate);
			attributeGetterFunctions.put(
				"endDate", WorkFromHomeRequest::getEndDate);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<WorkFromHomeRequest, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<WorkFromHomeRequest, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<WorkFromHomeRequest, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<WorkFromHomeRequest, String>)
					WorkFromHomeRequest::setUuid);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<WorkFromHomeRequest, Long>)
					WorkFromHomeRequest::setCompanyId);
			attributeSetterBiConsumers.put(
				"createdBy",
				(BiConsumer<WorkFromHomeRequest, Long>)
					WorkFromHomeRequest::setCreatedBy);
			attributeSetterBiConsumers.put(
				"modifiedBy",
				(BiConsumer<WorkFromHomeRequest, Long>)
					WorkFromHomeRequest::setModifiedBy);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<WorkFromHomeRequest, Long>)
					WorkFromHomeRequest::setGroupId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<WorkFromHomeRequest, Date>)
					WorkFromHomeRequest::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<WorkFromHomeRequest, Date>)
					WorkFromHomeRequest::setModifiedDate);
			attributeSetterBiConsumers.put(
				"workFromHomeRequestId",
				(BiConsumer<WorkFromHomeRequest, Long>)
					WorkFromHomeRequest::setWorkFromHomeRequestId);
			attributeSetterBiConsumers.put(
				"employeeId",
				(BiConsumer<WorkFromHomeRequest, Long>)
					WorkFromHomeRequest::setEmployeeId);
			attributeSetterBiConsumers.put(
				"reviewerId",
				(BiConsumer<WorkFromHomeRequest, Long>)
					WorkFromHomeRequest::setReviewerId);
			attributeSetterBiConsumers.put(
				"teamMailId",
				(BiConsumer<WorkFromHomeRequest, String>)
					WorkFromHomeRequest::setTeamMailId);
			attributeSetterBiConsumers.put(
				"status",
				(BiConsumer<WorkFromHomeRequest, Long>)
					WorkFromHomeRequest::setStatus);
			attributeSetterBiConsumers.put(
				"reason",
				(BiConsumer<WorkFromHomeRequest, String>)
					WorkFromHomeRequest::setReason);
			attributeSetterBiConsumers.put(
				"requestDate",
				(BiConsumer<WorkFromHomeRequest, Date>)
					WorkFromHomeRequest::setRequestDate);
			attributeSetterBiConsumers.put(
				"startDate",
				(BiConsumer<WorkFromHomeRequest, Date>)
					WorkFromHomeRequest::setStartDate);
			attributeSetterBiConsumers.put(
				"endDate",
				(BiConsumer<WorkFromHomeRequest, Date>)
					WorkFromHomeRequest::setEndDate);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@JSON
	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getWorkFromHomeRequestId() {
		return _workFromHomeRequestId;
	}

	@Override
	public void setWorkFromHomeRequestId(long workFromHomeRequestId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_workFromHomeRequestId = workFromHomeRequestId;
	}

	@JSON
	@Override
	public long getEmployeeId() {
		return _employeeId;
	}

	@Override
	public void setEmployeeId(long employeeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_employeeId = employeeId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalEmployeeId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("employeeId"));
	}

	@JSON
	@Override
	public long getReviewerId() {
		return _reviewerId;
	}

	@Override
	public void setReviewerId(long reviewerId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_reviewerId = reviewerId;
	}

	@JSON
	@Override
	public String getTeamMailId() {
		if (_teamMailId == null) {
			return "";
		}
		else {
			return _teamMailId;
		}
	}

	@Override
	public void setTeamMailId(String teamMailId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_teamMailId = teamMailId;
	}

	@JSON
	@Override
	public long getStatus() {
		return _status;
	}

	@Override
	public void setStatus(long status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalStatus() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("status"));
	}

	@JSON
	@Override
	public String getReason() {
		if (_reason == null) {
			return "";
		}
		else {
			return _reason;
		}
	}

	@Override
	public void setReason(String reason) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_reason = reason;
	}

	@JSON
	@Override
	public Date getRequestDate() {
		return _requestDate;
	}

	@Override
	public void setRequestDate(Date requestDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_requestDate = requestDate;
	}

	@JSON
	@Override
	public Date getStartDate() {
		return _startDate;
	}

	@Override
	public void setStartDate(Date startDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_startDate = startDate;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public Date getOriginalStartDate() {
		return getColumnOriginalValue("startDate");
	}

	@JSON
	@Override
	public Date getEndDate() {
		return _endDate;
	}

	@Override
	public void setEndDate(Date endDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_endDate = endDate;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public Date getOriginalEndDate() {
		return getColumnOriginalValue("endDate");
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(WorkFromHomeRequest.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), WorkFromHomeRequest.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public WorkFromHomeRequest toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, WorkFromHomeRequest>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		WorkFromHomeRequestImpl workFromHomeRequestImpl =
			new WorkFromHomeRequestImpl();

		workFromHomeRequestImpl.setUuid(getUuid());
		workFromHomeRequestImpl.setCompanyId(getCompanyId());
		workFromHomeRequestImpl.setCreatedBy(getCreatedBy());
		workFromHomeRequestImpl.setModifiedBy(getModifiedBy());
		workFromHomeRequestImpl.setGroupId(getGroupId());
		workFromHomeRequestImpl.setCreateDate(getCreateDate());
		workFromHomeRequestImpl.setModifiedDate(getModifiedDate());
		workFromHomeRequestImpl.setWorkFromHomeRequestId(
			getWorkFromHomeRequestId());
		workFromHomeRequestImpl.setEmployeeId(getEmployeeId());
		workFromHomeRequestImpl.setReviewerId(getReviewerId());
		workFromHomeRequestImpl.setTeamMailId(getTeamMailId());
		workFromHomeRequestImpl.setStatus(getStatus());
		workFromHomeRequestImpl.setReason(getReason());
		workFromHomeRequestImpl.setRequestDate(getRequestDate());
		workFromHomeRequestImpl.setStartDate(getStartDate());
		workFromHomeRequestImpl.setEndDate(getEndDate());

		workFromHomeRequestImpl.resetOriginalValues();

		return workFromHomeRequestImpl;
	}

	@Override
	public WorkFromHomeRequest cloneWithOriginalValues() {
		WorkFromHomeRequestImpl workFromHomeRequestImpl =
			new WorkFromHomeRequestImpl();

		workFromHomeRequestImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		workFromHomeRequestImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		workFromHomeRequestImpl.setCreatedBy(
			this.<Long>getColumnOriginalValue("createdBy"));
		workFromHomeRequestImpl.setModifiedBy(
			this.<Long>getColumnOriginalValue("modifiedBy"));
		workFromHomeRequestImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		workFromHomeRequestImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		workFromHomeRequestImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		workFromHomeRequestImpl.setWorkFromHomeRequestId(
			this.<Long>getColumnOriginalValue("workFromHomeRequestId"));
		workFromHomeRequestImpl.setEmployeeId(
			this.<Long>getColumnOriginalValue("employeeId"));
		workFromHomeRequestImpl.setReviewerId(
			this.<Long>getColumnOriginalValue("reviewerId"));
		workFromHomeRequestImpl.setTeamMailId(
			this.<String>getColumnOriginalValue("teamMailId"));
		workFromHomeRequestImpl.setStatus(
			this.<Long>getColumnOriginalValue("status"));
		workFromHomeRequestImpl.setReason(
			this.<String>getColumnOriginalValue("reason"));
		workFromHomeRequestImpl.setRequestDate(
			this.<Date>getColumnOriginalValue("requestDate"));
		workFromHomeRequestImpl.setStartDate(
			this.<Date>getColumnOriginalValue("startDate"));
		workFromHomeRequestImpl.setEndDate(
			this.<Date>getColumnOriginalValue("endDate"));

		return workFromHomeRequestImpl;
	}

	@Override
	public int compareTo(WorkFromHomeRequest workFromHomeRequest) {
		int value = 0;

		value = DateUtil.compareTo(
			getCreateDate(), workFromHomeRequest.getCreateDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof WorkFromHomeRequest)) {
			return false;
		}

		WorkFromHomeRequest workFromHomeRequest = (WorkFromHomeRequest)object;

		long primaryKey = workFromHomeRequest.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<WorkFromHomeRequest> toCacheModel() {
		WorkFromHomeRequestCacheModel workFromHomeRequestCacheModel =
			new WorkFromHomeRequestCacheModel();

		workFromHomeRequestCacheModel.uuid = getUuid();

		String uuid = workFromHomeRequestCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			workFromHomeRequestCacheModel.uuid = null;
		}

		workFromHomeRequestCacheModel.companyId = getCompanyId();

		workFromHomeRequestCacheModel.createdBy = getCreatedBy();

		workFromHomeRequestCacheModel.modifiedBy = getModifiedBy();

		workFromHomeRequestCacheModel.groupId = getGroupId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			workFromHomeRequestCacheModel.createDate = createDate.getTime();
		}
		else {
			workFromHomeRequestCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			workFromHomeRequestCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			workFromHomeRequestCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		workFromHomeRequestCacheModel.workFromHomeRequestId =
			getWorkFromHomeRequestId();

		workFromHomeRequestCacheModel.employeeId = getEmployeeId();

		workFromHomeRequestCacheModel.reviewerId = getReviewerId();

		workFromHomeRequestCacheModel.teamMailId = getTeamMailId();

		String teamMailId = workFromHomeRequestCacheModel.teamMailId;

		if ((teamMailId != null) && (teamMailId.length() == 0)) {
			workFromHomeRequestCacheModel.teamMailId = null;
		}

		workFromHomeRequestCacheModel.status = getStatus();

		workFromHomeRequestCacheModel.reason = getReason();

		String reason = workFromHomeRequestCacheModel.reason;

		if ((reason != null) && (reason.length() == 0)) {
			workFromHomeRequestCacheModel.reason = null;
		}

		Date requestDate = getRequestDate();

		if (requestDate != null) {
			workFromHomeRequestCacheModel.requestDate = requestDate.getTime();
		}
		else {
			workFromHomeRequestCacheModel.requestDate = Long.MIN_VALUE;
		}

		Date startDate = getStartDate();

		if (startDate != null) {
			workFromHomeRequestCacheModel.startDate = startDate.getTime();
		}
		else {
			workFromHomeRequestCacheModel.startDate = Long.MIN_VALUE;
		}

		Date endDate = getEndDate();

		if (endDate != null) {
			workFromHomeRequestCacheModel.endDate = endDate.getTime();
		}
		else {
			workFromHomeRequestCacheModel.endDate = Long.MIN_VALUE;
		}

		return workFromHomeRequestCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<WorkFromHomeRequest, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<WorkFromHomeRequest, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<WorkFromHomeRequest, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(WorkFromHomeRequest)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, WorkFromHomeRequest>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					WorkFromHomeRequest.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _companyId;
	private long _createdBy;
	private long _modifiedBy;
	private long _groupId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _workFromHomeRequestId;
	private long _employeeId;
	private long _reviewerId;
	private String _teamMailId;
	private long _status;
	private String _reason;
	private Date _requestDate;
	private Date _startDate;
	private Date _endDate;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<WorkFromHomeRequest, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((WorkFromHomeRequest)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createdBy", _createdBy);
		_columnOriginalValues.put("modifiedBy", _modifiedBy);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put(
			"workFromHomeRequestId", _workFromHomeRequestId);
		_columnOriginalValues.put("employeeId", _employeeId);
		_columnOriginalValues.put("reviewerId", _reviewerId);
		_columnOriginalValues.put("teamMailId", _teamMailId);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("reason", _reason);
		_columnOriginalValues.put("requestDate", _requestDate);
		_columnOriginalValues.put("startDate", _startDate);
		_columnOriginalValues.put("endDate", _endDate);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("createdBy", 4L);

		columnBitmasks.put("modifiedBy", 8L);

		columnBitmasks.put("groupId", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("workFromHomeRequestId", 128L);

		columnBitmasks.put("employeeId", 256L);

		columnBitmasks.put("reviewerId", 512L);

		columnBitmasks.put("teamMailId", 1024L);

		columnBitmasks.put("status", 2048L);

		columnBitmasks.put("reason", 4096L);

		columnBitmasks.put("requestDate", 8192L);

		columnBitmasks.put("startDate", 16384L);

		columnBitmasks.put("endDate", 32768L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private WorkFromHomeRequest _escapedModel;

}